table CG_PeriodSelection
	lineageTag: dba42b4b-ba38-47f1-a418-c2087a0813a0

	calculationGroup

		calculationItem PTD = ```
				
				    CALCULATE(
				        SELECTEDMEASURE(),
				        FILTER(
				            VALUES( Dim_Date[P_Year] ),
				            VALUE( Dim_Date[P_Year] ) = VALUE( [LastSelectedYear_P] )
				        ),
				        FILTER(
				            VALUES( Dim_Date[P_MonthFull] ),
				            VALUE( Dim_Date[P_MonthFull] ) = VALUE( [LastSelectedMonth_P] )
				        ),
				        FILTER( VALUES( Dim_Date[Date] ), Dim_Date[Date] <= [LastSelectedDate] )
				    )
				
				```

		calculationItem YTD = ```
				
				IF (
				    CONTAINSSTRING ( SELECTEDMEASURENAME (), "Inventory" )
				    || CONTAINSSTRING ( SELECTEDMEASURENAME (), "DSO" )
				    || CONTAINSSTRING ( SELECTEDMEASURENAME (), "DPO" )
				    || CONTAINSSTRING ( SELECTEDMEASURENAME (), "DIO" ),
				    CALCULATE ( 
				        SELECTEDMEASURE (),
				        CG_PeriodSelection[Period] = "PTD" 
				    ),
				
				    CALCULATE (
				        SELECTEDMEASURE (),
				        FILTER ( VALUES ( Dim_Date[P_Year] ), Dim_Date[P_Year] = [LastSelectedYear_P] ),
				        FILTER ( VALUES ( Dim_Date[Date] ), Dim_Date[Date] <= [LastSelectedDate] )
				    )
				    
				)
				```

	measure DownTrendIcon = ```
			
			// "data:image/svg+xml;utf8,
			// <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'>
			//   <path d='M3,7l5.79,5.79a1,1,0,0,0,1.42,0l2.58-2.58a1,1,0,0,1,1.42,0L21,17'
			//         style='fill: none; stroke: red; stroke-linecap: round; stroke-linejoin: round; stroke-width: 2;' />
			//   <polyline points='17 17 21 17 21 13'
			//             style='fill: none; stroke: red; stroke-linecap: round; stroke-linejoin: round; stroke-width: 2;' />
			// </svg>"
			var PositiveIcon=UNICHAR(129137) 
			VAR NegativeIcon=UNICHAR(129139)
			VAR per = [Red Count (Last Closed)]
			// var _sign=IF(per >=0 ,"+","")
			RETURN IF([Red Count (Last Closed)]>0, NegativeIcon & " " & [Red Count (Last Closed)], BLANK())
			```
		lineageTag: 6c09a6db-18f5-47b3-a0ab-8d253e8b02ef

	measure TextColorGreencount = "#09a80e"
		lineageTag: 839953fd-c60a-47fb-a44b-5c28a3ca249e

	measure TextColorRedCount = "#ef0808"
		lineageTag: 522b27ce-a4ba-4252-a8b5-930ab906bf02

	measure UpTrendIcon = ```
			
			// "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'><path d='M3,17l5.79-5.79a1,1,0,0,1,1.42,0l2.58,2.58a1,1,0,0,0,1.42,0L21,7' style='fill: none; stroke: green; stroke-linecap: round; stroke-linejoin: round; stroke-width: 2;' /><polyline points='17 7 21 7 21 11' style='fill: none; stroke: green; stroke-linecap: round; stroke-linejoin: round; stroke-width: 2;' /></svg>"
			var PositiveIcon=UNICHAR(129137) 
			VAR NegativeIcon=UNICHAR(9660)
			VAR per = [Green Count (Visible)]
			// var _sign=IF(per >=0 ,"+","")
			RETURN IF([Green Count (Visible)]>0,  PositiveIcon & " " & [Green Count (Visible)], BLANK())
			
			```
		lineageTag: de349d72-f512-442e-b420-248bf751887a

	column Period
		dataType: string
		lineageTag: c4668b98-e4be-4a69-b234-d065042b837e
		summarizeBy: none
		sourceColumn: Name
		sortByColumn: Ordinal

		annotation SummarizationSetBy = Automatic

	column Ordinal
		dataType: int64
		formatString: 0
		lineageTag: 1b5a798d-6084-47cd-bae5-fda4cdc6ec1d
		summarizeBy: sum
		sourceColumn: Ordinal

		annotation SummarizationSetBy = Automatic

