table 'Distribution CSCA'
	lineageTag: 886fc3a1-1d66-49ae-8d74-9ea0aa1e6816

	measure 'ASTM # of incidents' = SUM('Distribution CSCA'[ASTM - # of Incidents])
		formatString: 0
		lineageTag: c35ed44e-211a-4968-8ec9-bd0f47d3c161

	measure 'ASTM Rate' = SUM('Distribution CSCA'[ASTM - Rate])
		formatString: 0
		lineageTag: f1b965fe-ad3f-423f-9d1d-54cfc13151bf

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Carrier On-Time Del Perf' = SUM('Distribution CSCA'[Carrier On-Time Delivery Performance])
		lineageTag: 3a7058f4-aef3-43c0-b4dc-27f552bf7c4f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cost/CWT LTL' = SELECTEDVALUE ('Distribution CSCA'[Cost / CWT LTL] )
		lineageTag: f1bfbcfc-d528-42ce-be83-de4a109d3c5b

	measure 'Cost/CWT TL' = SELECTEDVALUE('Distribution CSCA'[Cost / CWT TL])
		lineageTag: bd2f0aae-ac07-48bd-89eb-3dadd6ed33c8

	measure 'Customer Service (inclusive of Gap Orders)' = sum('Distribution CSCA'[Customer Service (inclusive of Gap Orders) * CSCA Total])
		lineageTag: bbbce16d-05c1-4a16-9c4a-64c765de3121

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cycle Count Accuracy%' = SUM('Distribution CSCA'[Cycle Count Accuracy %])
		lineageTag: c63ce0e3-bc33-4356-91bc-47c63e7a2c14

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Delivery of ABP Spend-Distribution' = SELECTEDVALUE('Distribution CSCA'[Delivery of ABP Spend - Distribution])
		lineageTag: 7fe4d97f-b833-4bbf-8366-088345c852b5

	measure 'Delivery of ABP Spend-Transportation' = SELECTEDVALUE('Distribution CSCA'[Delivery of ABP Spend - Transportation])
		lineageTag: 7c10c19d-3c5e-48ce-999d-471b8012427a

	measure 'Distribution Labor Staff%' = SUM('Distribution CSCA'[Distribution Labor Staff %])
		lineageTag: 88f10e0a-9580-428a-bdde-bbede87c5e39

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Drive completion in rates' = SUm('Distribution CSCA'[Drive completion in rates in function of 12 week "Connect with Core Behavior" learning program assignment])
		lineageTag: 97e80444-6f04-4320-843c-0d63908ac9c3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'GOOD Catch% Closure Rate' = SUM('Distribution CSCA'[GOOD Catch % Closure Rate])
		formatString: 0
		lineageTag: 930476bb-1d25-4200-84b3-58f22197b7c5

	measure 'Involuntary Turnove' = SUM('Distribution CSCA'[Involuntary Turnover])
		lineageTag: a63bd626-811f-4582-8a84-a2fd997d105c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'No Critical or Major observations - Regulatory Agency' = SUM('Distribution CSCA'[No Critical or Major observations as a result of a Regulatory Agency ])
		formatString: 0
		lineageTag: 779f9124-993d-4085-b368-a1db77f74e40

	measure Picks/Hour = SUM('Distribution CSCA'[Picks / Hour])
		formatString: 0
		lineageTag: 480d98be-fa40-40f0-ba9d-4b454d61f06c

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'SIF & pSIF Focus' = SUM('Distribution CSCA'[SIF & pSIF Focus at our Sites - Action Closure Rate on Time])
		lineageTag: 163ec71b-9eed-41d6-a42f-027ce14aac28

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Distribution Center Capacity%' = SUM('Distribution CSCA'[Total Distribution Center Capacity %])
		lineageTag: 0244ccff-aab5-46e9-b8c5-a101bb6d41a7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Voluntary Turnover(No Retirement)' = SUM('Distribution CSCA'[Voluntary Turnover (No Retirement)])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c091a964-bb39-416b-b474-e1ac9984eb1e

	measure Cost_CWT_LTL_Num = ```
			
			MAXX (
			    VALUES ( 'Distribution CSCA'[Month] ),
			    VAR rawVal = MAX ( 'Distribution CSCA'[Cost / CWT LTL] )
			    VAR cleaned =
			        SUBSTITUTE (
			            SUBSTITUTE ( SUBSTITUTE ( rawVal, "$", "" ), "M", "" ),
			            "/ CWT", ""
			        )
			    RETURN IF ( ISNUMBER ( VALUE ( cleaned ) ), VALUE ( cleaned ) )
			)
			
			```
		lineageTag: 55c79340-825f-4703-9e83-9194fec84ecc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Cost_CWT_TL_Num = ```
			
			MAXX (
			    VALUES ( 'Distribution CSCA'[Month] ),
			    VAR rawVal = MAX ( 'Distribution CSCA'[Cost / CWT TL] )
			    VAR cleaned =
			        SUBSTITUTE (
			            SUBSTITUTE (
			                SUBSTITUTE ( rawVal, "$", "" ),
			                "/ CWT", ""
			            ),
			            " ", ""
			        )
			    RETURN
			        IF ( ISNUMBER ( VALUE ( cleaned ) ), VALUE ( cleaned ) )
			)
			
			```
		lineageTag: b925eb25-74d8-403b-80b8-7c1dcb495007

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ABP_Spend_Transportation_Num = ```
			
			MAXX (
			    VALUES ( 'Distribution CSCA'[Month] ),
			    VAR rawVal = MAX ( 'Distribution CSCA'[Delivery of ABP Spend - Transportation] )
			    VAR cleaned =
			        SUBSTITUTE (
			            SUBSTITUTE (
			                SUBSTITUTE ( rawVal, "$", "" ),
			                "M", ""
			            ),
			            " ", ""
			        )
			    RETURN
			        IF ( ISNUMBER ( VALUE ( cleaned ) ), VALUE ( cleaned ) )
			)
			
			```
		lineageTag: 0fdeed16-4d48-4649-90b1-48e519dce144

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ABP_Spend_Distribution_Num = ```
			
			MAXX (
			    VALUES ( 'Distribution CSCA'[Month] ),
			    VAR rawVal = MAX ( 'Distribution CSCA'[Delivery of ABP Spend - Distribution] )
			    VAR cleaned =
			        SUBSTITUTE (
			            SUBSTITUTE (
			                SUBSTITUTE ( rawVal, "$", "" ),
			                "M", ""
			            ),
			            " ", ""
			        )
			    RETURN
			        IF ( ISNUMBER ( VALUE ( cleaned ) ), VALUE ( cleaned ) )
			)
			
			```
		lineageTag: a9c1c198-dbfe-4d81-861b-cce7cf410efa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Month
		dataType: string
		lineageTag: d7fb06bb-322c-4225-8241-5128cde6dd05
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: 'Month Number'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'ASTM - Rate'
		dataType: double
		lineageTag: 752140a6-8d2b-4169-9ad4-d957453e0653
		summarizeBy: sum
		sourceColumn: ASTM - Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ASTM - # of Incidents'
		dataType: int64
		formatString: 0
		lineageTag: 96880017-edda-4b55-92c4-494aa81916a3
		summarizeBy: sum
		sourceColumn: ASTM - # of Incidents

		annotation SummarizationSetBy = Automatic

	column 'SIF & pSIF Focus at our Sites - Action Closure Rate on Time'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5aecf3ac-a827-46c0-a692-99fad329aa2a
		summarizeBy: sum
		sourceColumn: SIF & pSIF Focus at our Sites - Action Closure Rate on Time

		annotation SummarizationSetBy = Automatic

	column 'GOOD Catch % Closure Rate'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 35244c35-7e58-40ca-9e74-890992faace2
		summarizeBy: sum
		sourceColumn: GOOD Catch % Closure Rate

		annotation SummarizationSetBy = Automatic

	column 'No Critical or Major observations as a result of a Regulatory Agency '
		dataType: string
		lineageTag: 60fef84f-0af6-4d0c-8141-4a8c37001658
		summarizeBy: none
		sourceColumn: "No Critical or Major observations as a result of a Regulatory Agency "

		annotation SummarizationSetBy = Automatic

	column 'Cycle Count Accuracy %'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e64b6ce9-ab57-429f-97f0-99a6bf2375f4
		summarizeBy: sum
		sourceColumn: Cycle Count Accuracy %

		annotation SummarizationSetBy = Automatic

	column 'Total Distribution Center Capacity %'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 955f6511-1009-42d2-bae4-1d568cdcf9b8
		summarizeBy: sum
		sourceColumn: Total Distribution Center Capacity %

		annotation SummarizationSetBy = Automatic

	column 'Schedule Attainment - Shipments / Picks On Time - This metric needs to be developed'
		dataType: string
		lineageTag: 905251e1-fe18-4e74-bd69-055501058ada
		summarizeBy: none
		sourceColumn: Schedule Attainment - Shipments / Picks On Time - This metric needs to be developed

		annotation SummarizationSetBy = Automatic

	column 'Customer Service (inclusive of Gap Orders) * CSCA Total'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 7f16a4b3-3af4-45c8-8c35-6955417aa4ad
		summarizeBy: sum
		sourceColumn: Customer Service (inclusive of Gap Orders) * CSCA Total

		annotation SummarizationSetBy = Automatic

	column 'Carrier On-Time Delivery Performance'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a929a444-5231-4e35-bf32-9564917cf4ae
		summarizeBy: sum
		sourceColumn: Carrier On-Time Delivery Performance

		annotation SummarizationSetBy = Automatic

	column 'Delivery of ABP Spend - Transportation'
		dataType: string
		lineageTag: 993b4ae1-a2a1-45e4-920e-cbd428fdc328
		summarizeBy: none
		sourceColumn: Delivery of ABP Spend - Transportation

		annotation SummarizationSetBy = Automatic

	column 'Delivery of ABP Spend - Distribution'
		dataType: string
		lineageTag: afcb5114-16c8-4efd-96f5-bbdf9c07a5b4
		summarizeBy: none
		sourceColumn: Delivery of ABP Spend - Distribution

		annotation SummarizationSetBy = Automatic

	column 'Picks / Hour'
		dataType: double
		lineageTag: 3c3d826a-69d1-4607-9f45-a5beb1f878b1
		summarizeBy: sum
		sourceColumn: Picks / Hour

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cost / CWT LTL'
		dataType: string
		lineageTag: b6fe5f5c-7b74-47d2-9fbd-95e3c6afbc6f
		summarizeBy: none
		sourceColumn: Cost / CWT LTL

		annotation SummarizationSetBy = Automatic

	column 'Cost / CWT TL'
		dataType: string
		lineageTag: 94b41095-7d73-487c-962e-f798af3370a8
		summarizeBy: none
		sourceColumn: Cost / CWT TL

		annotation SummarizationSetBy = Automatic

	column 'Glint Survey Results - Identify 2 or 3 Key Areas of Improvement / Response Rate from May 2025 Survey '
		dataType: string
		lineageTag: 1dff5937-644c-4ec8-8e32-7e872f3b6bf3
		summarizeBy: none
		sourceColumn: "Glint Survey Results - Identify 2 or 3 Key Areas of Improvement / Response Rate from May 2025 Survey "

		annotation SummarizationSetBy = Automatic

	column 'Voluntary Turnover (No Retirement)'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 81006b58-c305-43fd-b5d5-5d77d342124f
		summarizeBy: sum
		sourceColumn: Voluntary Turnover (No Retirement)

		annotation SummarizationSetBy = Automatic

	column 'Involuntary Turnover'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a7bf39a9-f300-49c9-8678-e52ff0323440
		summarizeBy: sum
		sourceColumn: Involuntary Turnover

		annotation SummarizationSetBy = Automatic

	column 'Distribution Labor Staff %'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 84f8b075-107f-430b-a030-4414a0d59438
		summarizeBy: sum
		sourceColumn: Distribution Labor Staff %

		annotation SummarizationSetBy = Automatic

	column 'PWS vs clearly defined Plan and Criteria - Must haves:  DMS - Tier 1 & Tier 2 Meetings with Agendas, Visual Management at All DCs, 5S, Preventative Maintenance'
		dataType: string
		lineageTag: c0738d47-beea-47d6-8282-dc4422bb1fbd
		summarizeBy: none
		sourceColumn: PWS vs clearly defined Plan and Criteria - Must haves:  DMS - Tier 1 & Tier 2 Meetings with Agendas, Visual Management at All DCs, 5S, Preventative Maintenance

		annotation SummarizationSetBy = Automatic

	column 'Drive completion in rates in function of 12 week "Connect with Core Behavior" learning program assignment'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b7a7bf82-40e7-4d91-bf21-c8438814684e
		summarizeBy: sum
		sourceColumn: Drive completion in rates in function of 12 week "Connect with Core Behavior" learning program assignment

		annotation SummarizationSetBy = Automatic

	column 'Month Number'
		dataType: string
		lineageTag: 0ff8f84d-b87a-4179-bd59-4e3ef3840ac0
		summarizeBy: none
		sourceColumn: Month Number

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: string
		lineageTag: a9aa160a-a091-4e26-9a71-191318f6e902
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	partition 'Distribution CSCA' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://perrigo.sharepoint.com/sites/O365GRP_CSCAPSLT-OverallGeneral/Shared%20Documents/Master%20Plans/2025CSCA%20Scorecard.xlsx")),
				    Distribution_sheet = Source{[Item="Distribution",Kind="Sheet"]}[Data],
				    #"Removed Top Rows" = Table.Skip(Distribution_sheet, 3),
				    #"Removed Bottom Rows" = Table.RemoveLastN(#"Removed Top Rows", 21),
				    #"Removed Other Columns" = Table.SelectColumns(#"Removed Bottom Rows", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column17"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"Column1", type text}, {"Column2", type text}, {"Column3", type any}, {"Column4", type any}, {"Column5", type any}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column17", type any}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Column1", type text}, {"Column2", type text}, {"2024", type any}, {"Target", type any}, {"Jan", type any}, {"Feb", type any}, {"Mar", type any}, {"Apr", type any}, {"May", type any}, {"Jun", type any}, {"Jul", type any}, {"YTD", type number}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Column2", "KPI"}, {"Column1", "Category"}}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Renamed Columns", {"Category", "KPI"}, "Attribute", "Value"),
				    #"Removed Columns" = Table.RemoveColumns(#"Unpivoted Other Columns",{"Category"}),
				    #"Pivoted Column" = Table.Pivot(#"Removed Columns", List.Distinct(#"Removed Columns"[KPI]), "KPI", "Value"),
				    #"Split Column by Delimiter" = Table.SplitColumn(Table.TransformColumnTypes(#"Pivoted Column", {{"ASTM - Rate & # of Incidents", type text}}, "en-IN"), "ASTM - Rate & # of Incidents", Splitter.SplitTextByDelimiter("/", QuoteStyle.None), {"ASTM - Rate & # of Incidents.1", "ASTM - Rate & # of Incidents.2"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"ASTM - Rate & # of Incidents.1", type number}, {"ASTM - Rate & # of Incidents.2", Int64.Type}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type2",{{"ASTM - Rate & # of Incidents.1", "ASTM - Rate"}, {"ASTM - Rate & # of Incidents.2", "ASTM - # of Incidents"}, {"Attribute", "Month"}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns1",{{"SIF & pSIF Focus at our Sites - Action Closure Rate on Time", Percentage.Type}, {"GOOD Catch % Closure Rate", Percentage.Type}, {"Cycle Count Accuracy %", Percentage.Type}, {"Total Distribution Center Capacity %", Percentage.Type}, {"Customer Service (inclusive of Gap Orders) * CSCA Total", Percentage.Type}, {"Carrier On-Time Delivery Performance", Percentage.Type}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type3","3.6 Picks / Hour",3.6,Replacer.ReplaceValue,{"Picks / Hour"}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Replaced Value",{{"Voluntary Turnover (No Retirement)", Percentage.Type}, {"Involuntary Turnover", Percentage.Type}, {"Distribution Labor Staff %", Percentage.Type}, {"Drive completion in rates in function of 12 week ""Connect with Core Behavior"" learning program assignment", Percentage.Type}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type4",{"Capital Projects", "4 Forklift Batteries @ HDC", "Amazon Cage @ High Point & Electrical for Opportunity Charging", "Massage Therapy / Conference Space @ IDC 1", "Forklift Batteries / Opportunity Charging @ ALC", "Opportunity Battery Chargers @ IDC 1", "ALC Concrete Repairs in Truck Docks", "Fire Suppression @ HDC", "Cameras & Computers for Trucks - $1,800 / Camera, $1,000 / Computer", "ALC Signage", "Forklift Monitoring Systems - Impact Monitoring, Cameras"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Removed Columns1", "Month Number", each if [Month] = "Jan" then 1 else if [Month] = "Feb" then 2 else if [Month] = "Mar" then 3 else if [Month] = "Apr" then 4 else if [Month] = "May" then 5 else if [Month] = "Jun" then 6 else if [Month] = "Jul" then 7 else if [Month] = "Aug" then 8 else if [Month] = "Sep" then 9 else if [Month] = "Oct" then 10 else if [Month] = "Nov" then 11 else if [Month] = "Dec" then 12 else null),
				    #"Added Conditional Column1" = Table.AddColumn(#"Added Conditional Column", "Period", each if [Month] = "Jan" then "P1 2025" else if [Month] = "Feb" then "P2 2025" else if [Month] = "Mar" then "P3 2025" else if [Month] = "Apr" then "P4 2025" else if [Month] = "May" then "P5 2025" else if [Month] = "Jun" then "P6 2025" else if [Month] = "Jul" then "P7 2025" else if [Month] = "Aug" then "P8 2025" else if [Month] = "Sep" then "P9 2025" else if [Month] = "Oct" then "P10 2025" else if [Month] = "Nov" then "P11 2025" else if [Month] = "Dec" then "P12 2025" else null),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Added Conditional Column1", {{"Drive completion in rates in function of 12 week ""Connect with Core Behavior"" learning program assignment", 0}})
				in
				    #"Replaced Errors"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

