table Fact_BS
	lineageTag: 42a6c082-a7fc-4f31-81b9-81d1f0ebe352

	measure 'Accounts Payable Avg L4M' = ```
			VAR _LastMonth = VALUE(MAX(Dim_DateSlicer[P_YearPeriod Seq]))
			VAR _FirstMonth = _LastMonth - 3
			RETURN 
			    AVERAGEX(
			        SUMMARIZE(
			            FILTER(
			                Dim_Date,
			                Dim_Date[P_YearPeriod Seq] >= _FirstMonth && Dim_Date[P_YearPeriod Seq] <= _LastMonth
			            ),
			            Dim_Date[P_YearPeriod]
			        ),
			        [Sum Accounts Payable]
			    )
			```
		lineageTag: 6c9e537f-2cbb-4adf-8bfe-3b629f3b6b86

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Accounts Receivable Avg L4M' =
			
			VAR _LastMonth = MAX( Dim_DateSlicer[P_YearPeriod Seq] )
			VAR _FirstMonth = _LastMonth - 3
			RETURN
			    AVERAGEX(
			        SUMMARIZE(
			            FILTER(
			               all( Dim_Date),
			                Dim_Date[P_YearPeriod Seq] >= _FirstMonth && Dim_Date[P_YearPeriod Seq] <= _LastMonth
			            ),
			            Dim_Date[P_YearPeriod]
			        ),
			        [Sum Accounts Receivable]
			    )
		lineageTag: 7a979186-6e5c-4c90-830f-0fdab37969e3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sum Accounts Payable' = SUM(Fact_BS[Accounts Payable])
		lineageTag: 5565125f-eeb0-47f6-bc48-035d6c607ee7

	measure 'Sum Accounts Receivable' = SUM(Fact_BS[Accounts Receivable])
		lineageTag: e45e1e9b-a5a6-46f2-b4e7-e493c065b6d2

	column Date
		dataType: dateTime
		formatString: General Date
		lineageTag: e4ac614d-6186-481b-ba83-43b02b368d7c
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column 'Profit Center'
		dataType: string
		lineageTag: 2af927fb-0efc-469d-80d2-7f1c7190db75
		summarizeBy: none
		sourceColumn: Profit Center

		annotation SummarizationSetBy = Automatic

	column 'Accounts Payable'
		dataType: double
		lineageTag: a5c52c25-ab4d-4caa-9373-a3ad24ed72c3
		summarizeBy: sum
		sourceColumn: Accounts Payable

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Accounts Receivable'
		dataType: double
		lineageTag: 82a8d8a6-443d-4feb-bb46-515a985cf0cb
		summarizeBy: sum
		sourceColumn: Accounts Receivable

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_BS = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Fact_BS = AnalysisServices.Database("powerbi://api.powerbi.com/v1.0/myorg/CSCI%20Supply%20Chain", "CSCI Supply Chain Model", [Query="/* START QUERY BUILDER */#(lf)DEFINE#(lf)MEASURE Fact_BS_AR_AP[Accounts Payable] = CALCULATE([Accounts Payable Base], 'Dim_Reporting Currency'[Currency] = ""USD"")#(lf)MEASURE Fact_BS_AR_AP[Accounts Receivable] = CALCULATE([Accounts Receivable Base], 'Dim_Reporting Currency'[Currency] = ""USD"")#(lf)EVALUATE#(lf)SUMMARIZECOLUMNS(#(lf)    Fact_BS_AR_AP[Date],#(lf)    Fact_BS_AR_AP[Profit Center],#(lf)    ""Accounts Payable"", [Accounts Payable],#(lf)    ""Accounts Receivable"", [Accounts Receivable]#(lf))#(lf)ORDER BY #(lf)    Fact_BS_AR_AP[Date] ASC,#(lf)    Fact_BS_AR_AP[Profit Center] ASC#(lf)/* END QUERY BUILDER */", Implementation="2.0"]),
				    #"Renamed Columns" = Table.RenameColumns(Fact_BS,{{"Fact_BS_AR_AP[Date]", "Date"}, {"Fact_BS_AR_AP[Profit Center]", "Profit Center"}, {"[Accounts Payable]", "Accounts Payable"}, {"[Accounts Receivable]", "Accounts Receivable"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Accounts Payable", type number}, {"Accounts Receivable", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

