table Fact_CFIN_Inventory
	lineageTag: 93ad0ccd-cbdd-4975-bde9-11c391c93454

	column 'Profit Center'
		dataType: string
		lineageTag: e2a5de58-1be0-4ef2-b5b5-2fbbe8452c80
		summarizeBy: none
		sourceColumn: Profit Center

		annotation SummarizationSetBy = Automatic

	column 'Account Number'
		dataType: string
		lineageTag: 15e71991-c9df-497f-8418-13aa96eed299
		summarizeBy: none
		sourceColumn: Account Number

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 4a72050b-d54f-4ac9-b778-338c205d64c0
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 26d77b2c-6403-4c51-97da-ce33ba743e56
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column YearPeriod
		dataType: string
		lineageTag: 32859c61-49cd-40c0-bc33-24b1387a46ac
		summarizeBy: none
		sourceColumn: YearPeriod

		annotation SummarizationSetBy = Automatic

	column 'Sum Amount CFIN Base'
		dataType: double
		lineageTag: dd9ffdf9-df77-4811-985b-45e7264beb94
		summarizeBy: sum
		sourceColumn: Sum Amount CFIN Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'CFIN Amount Excl Inventory Reserves'
		dataType: double
		lineageTag: 1e288652-4908-4b2c-a5c3-b6a0e731819f
		summarizeBy: sum
		sourceColumn: CFIN Amount Excl Inventory Reserves

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Material Number'
		dataType: string
		lineageTag: f9e76d79-201b-4e52-a4b6-351ebf464b3e
		summarizeBy: none
		sourceColumn: Material Number

		annotation SummarizationSetBy = Automatic

	column 'Sum Amount CFIN Base_APN'
		dataType: double
		lineageTag: 356ba678-cdc5-4df0-a626-bbdd53a1e766
		summarizeBy: sum
		sourceColumn: Sum Amount CFIN Base_APN

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'CFIN Amount Excl Inventory Reserves_APN'
		dataType: double
		lineageTag: 304dc198-6d39-42bd-976d-2e8051b6f012
		summarizeBy: sum
		sourceColumn: CFIN Amount Excl Inventory Reserves_APN

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sum Amount CFIN Base_AFX'
		dataType: double
		lineageTag: 517b4003-0a16-4fcc-b6b1-4aa72ac056e7
		summarizeBy: sum
		sourceColumn: Sum Amount CFIN Base_AFX

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'CFIN Amount Excl Inventory Reserves_AFX'
		dataType: double
		lineageTag: f3fb72bf-71d2-4b9a-9c7c-4de2a26a575a
		summarizeBy: sum
		sourceColumn: CFIN Amount Excl Inventory Reserves_AFX

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_CFIN_Inventory = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Fact_CFIN_Inventory = AnalysisServices.Database("powerbi://api.powerbi.com/v1.0/myorg/Global%20Supply%20Chain", "BW - Inventory - Dataset", [Query="/* START QUERY BUILDER */#(lf)DEFINE#(lf)#(lf)-- Base Reserves Measure (no exchange rate)#(lf)MEASURE Fact_CFIN_Inventory[CFIN Inventory Breakdown - Reserves RAW] =#(lf)CALCULATE(#(lf)    [Sum_Report_Currency_CFIN],#(lf)    Dim_GL_Account_Hierarchy[Inventory Breakdown Category] = ""Reserves""#(lf))#(lf)#(lf)-- ACT01 (default names)#(lf)MEASURE Fact_CFIN_Inventory[Sum Amount CFIN Base] = #(lf)CALCULATE(#(lf)    [Sum_Report_Currency_CFIN],#(lf)    REMOVEFILTERS(Dim_ComparableFilter[Comparable Version]),#(lf)    Dim_ComparableFilter[Exchange Rate Financial] = ""ACT01"",#(lf)    KEEPFILTERS(Dim_ReportCurrency[To-currency] = ""USD"")#(lf))#(lf)#(lf)MEASURE Fact_CFIN_Inventory[CFIN Amount Excl Inventory Reserves] = #(lf)    [Sum Amount CFIN Base] - #(lf)    CALCULATE(#(lf)        [CFIN Inventory Breakdown - Reserves RAW],#(lf)        Dim_ComparableFilter[Exchange Rate Financial] = ""ACT01"",#(lf)        KEEPFILTERS(Dim_ReportCurrency[To-currency] = ""USD"")#(lf)    )#(lf)#(lf)-- APN#(lf)MEASURE Fact_CFIN_Inventory[Sum Amount CFIN Base_APN] = #(lf)CALCULATE(#(lf)    [Sum_Report_Currency_CFIN],#(lf)    REMOVEFILTERS(Dim_ComparableFilter[Comparable Version]),#(lf)    Dim_ComparableFilter[Exchange Rate Financial] = ""APN"",#(lf)    KEEPFILTERS(Dim_ReportCurrency[To-currency] = ""USD"")#(lf))#(lf)#(lf)MEASURE Fact_CFIN_Inventory[CFIN Amount Excl Inventory Reserves_APN] = #(lf)    [Sum Amount CFIN Base_APN] - #(lf)    CALCULATE(#(lf)        [CFIN Inventory Breakdown - Reserves RAW],#(lf)        Dim_ComparableFilter[Exchange Rate Financial] = ""APN"",#(lf)        KEEPFILTERS(Dim_ReportCurrency[To-currency] = ""USD"")#(lf)    )#(lf)#(lf)-- AFX#(lf)MEASURE Fact_CFIN_Inventory[Sum Amount CFIN Base_AFX] = #(lf)CALCULATE(#(lf)    [Sum_Report_Currency_CFIN],#(lf)    REMOVEFILTERS(Dim_ComparableFilter[Comparable Version]),#(lf)    Dim_ComparableFilter[Exchange Rate Financial] = ""AFX"",#(lf)    KEEPFILTERS(Dim_ReportCurrency[To-currency] = ""USD"")#(lf))#(lf)#(lf)MEASURE Fact_CFIN_Inventory[CFIN Amount Excl Inventory Reserves_AFX] = #(lf)    [Sum Amount CFIN Base_AFX] - #(lf)    CALCULATE(#(lf)        [CFIN Inventory Breakdown - Reserves RAW],#(lf)        Dim_ComparableFilter[Exchange Rate Financial] = ""AFX"",#(lf)        KEEPFILTERS(Dim_ReportCurrency[To-currency] = ""USD"")#(lf)    )#(lf)#(lf)EVALUATE#(lf)SUMMARIZECOLUMNS(#(lf)    Dim_Date[Date],#(lf)    Dim_Date[P_YearPeriod],#(lf)    Fact_CFIN_Inventory[Profit Center],#(lf)    Fact_CFIN_Inventory[Account Number],#(lf)    Fact_CFIN_Inventory[Material Number],#(lf)    Fact_CFIN_Inventory[Category],#(lf)    ""Sum Amount CFIN Base"", [Sum Amount CFIN Base],#(lf)    ""CFIN Amount Excl Inventory Reserves"", [CFIN Amount Excl Inventory Reserves],#(lf)    ""Sum Amount CFIN Base_APN"", [Sum Amount CFIN Base_APN],#(lf)    ""CFIN Amount Excl Inventory Reserves_APN"", [CFIN Amount Excl Inventory Reserves_APN],#(lf)    ""Sum Amount CFIN Base_AFX"", [Sum Amount CFIN Base_AFX],#(lf)    ""CFIN Amount Excl Inventory Reserves_AFX"", [CFIN Amount Excl Inventory Reserves_AFX]#(lf))#(lf)ORDER BY #(lf)    Dim_Date[Date] ASC,#(lf)    Dim_Date[P_YearPeriod] ASC,#(lf)    Fact_CFIN_Inventory[Profit Center] ASC,#(lf)    Fact_CFIN_Inventory[Account Number] ASC,#(lf)    Fact_CFIN_Inventory[Material Number] ASC,#(lf)    Fact_CFIN_Inventory[Category] ASC#(lf)/* END QUERY BUILDER */#(lf)", Implementation="2.0"]),
				    #"Renamed Columns" = Table.RenameColumns(Fact_CFIN_Inventory,{{"Dim_Date[Date]", "Date"}, {"Dim_Date[P_YearPeriod]", "YearPeriod"}, {"Fact_CFIN_Inventory[Profit Center]", "Profit Center"}, {"Fact_CFIN_Inventory[Account Number]", "Account Number"}, {"Fact_CFIN_Inventory[Category]", "Category"}, {"[Sum Amount CFIN Base]", "Sum Amount CFIN Base"}, {"[CFIN Amount Excl Inventory Reserves]", "CFIN Amount Excl Inventory Reserves"}, {"Fact_CFIN_Inventory[Material Number]", "Material Number"}, {"[CFIN Amount Excl Inventory Reserves_AFX]", "CFIN Amount Excl Inventory Reserves_AFX"}, {"[Sum Amount CFIN Base_AFX]", "Sum Amount CFIN Base_AFX"}, {"[CFIN Amount Excl Inventory Reserves_APN]", "CFIN Amount Excl Inventory Reserves_APN"}, {"[Sum Amount CFIN Base_APN]", "Sum Amount CFIN Base_APN"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

