table Fact_OEE
	lineageTag: 3f61f95a-6eac-4c6a-8470-152a91e76f37

	column 'Location UUID'
		dataType: string
		lineageTag: 6a4d4fc5-34ca-4e8d-a8eb-cd5808fb2a44
		summarizeBy: none
		sourceColumn: Location UUID

		annotation SummarizationSetBy = Automatic

	column 'Site UUID'
		dataType: string
		lineageTag: 3a03c1ed-6730-4185-b764-10e4d2710ce6
		summarizeBy: none
		sourceColumn: Site UUID

		annotation SummarizationSetBy = Automatic

	column 'Area UUID'
		dataType: string
		lineageTag: 5ebfdd50-bd65-4fb8-9183-309e376a3f05
		summarizeBy: none
		sourceColumn: Area UUID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: General Date
		lineageTag: a0edd380-b769-496a-8c73-bb7440bd58a6
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column 'Up Seconds'
		dataType: double
		lineageTag: c44dc011-d70b-466a-967a-e871ec904c51
		summarizeBy: sum
		sourceColumn: Up Seconds

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Down Seconds'
		dataType: double
		lineageTag: 0b19d137-cd3b-419b-b34f-7a6b106b9599
		summarizeBy: sum
		sourceColumn: Down Seconds

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Out Count'
		dataType: double
		lineageTag: 4778a482-4055-4ac5-a4c7-9f086c8c8579
		summarizeBy: sum
		sourceColumn: Out Count

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'In Count'
		dataType: double
		lineageTag: e52ef18e-e9d6-4d58-a143-c29d5140545e
		summarizeBy: sum
		sourceColumn: In Count

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Run Theoretical Quantity'
		dataType: double
		lineageTag: 564ccc18-9087-4797-9068-fe222ed4e79b
		summarizeBy: sum
		sourceColumn: Run Theoretical Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Elapsed Time'
		dataType: double
		lineageTag: e61fd907-33b1-4604-aba9-25887f4d4789
		summarizeBy: sum
		sourceColumn: Total Elapsed Time

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Refresh DateTime'
		dataType: dateTime
		formatString: General Date
		lineageTag: 12a351e6-e2fd-42e5-942d-181572558600
		summarizeBy: none
		sourceColumn: Refresh DateTime

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition Fact_OEE = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Fact_OEE = AnalysisServices.Database("powerbi://api.powerbi.com/v1.0/myorg/Redzone", "Redzone Engineering Dataset", [Query="EVALUATE#(lf)#(lf)SUMMARIZECOLUMNS(#(lf)#(lf)    'Fact Shift Run Segments'[Location UUID],#(lf)#(lf)    'Fact Shift Run Segments'[Site UUID],#(lf)#(lf)    'Fact Shift Run Segments'[Area UUID],#(lf)#(lf)    'Fact Shift Run Segments'[Date],#(lf)#(lf) #(lf)#(lf)    ""Up Seconds"", [Up Seconds],#(lf)#(lf)    ""Down Seconds"", [Down Seconds],#(lf)#(lf)    ""Out Count"", [Out Count],#(lf)#(lf)    ""In Count"", [In Count],#(lf)#(lf)    ""Run Theoretical Quantity"", [Run Theoretical Quantity],#(lf)#(lf)    ""Total Elapsed Time"", [Total Elapsed Time],#(lf)""Refresh DateTime"", MAX('Data Refreshed'[Refresh DateTime])#(lf))#(lf)#(lf)ORDER BY#(lf)#(lf)    'Fact Shift Run Segments'[Location UUID] ASC,#(lf)#(lf)    'Fact Shift Run Segments'[Site UUID] ASC,#(lf)#(lf)    'Fact Shift Run Segments'[Area UUID] ASC,#(lf)#(lf)    'Fact Shift Run Segments'[Date] ASC", Implementation="2.0"]),
				    #"Renamed Columns" = Table.RenameColumns(Fact_OEE,{{"Fact Shift Run Segments[Location UUID]", "Location UUID"}, {"Fact Shift Run Segments[Site UUID]", "Site UUID"}, {"Fact Shift Run Segments[Area UUID]", "Area UUID"}, {"Fact Shift Run Segments[Date]", "Date"}, {"[Up Seconds]", "Up Seconds"}, {"[Down Seconds]", "Down Seconds"}, {"[Out Count]", "Out Count"}, {"[In Count]", "In Count"}, {"[Run Theoretical Quantity]", "Run Theoretical Quantity"}, {"[Total Elapsed Time]", "Total Elapsed Time"}, {"[Refresh DateTime]", "Refresh DateTime"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"Date", "Location UUID", "Site UUID", "Area UUID", "Up Seconds", "Down Seconds", "Out Count", "In Count", "Run Theoretical Quantity", "Total Elapsed Time"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

