table Fact_OEE_Baseline
	lineageTag: 1432526c-5efa-4289-af1e-a33e06ebc7c6

	column 'Site Name'
		dataType: string
		lineageTag: 0e7a5991-8d67-4e6f-83e9-7d8cf23948bc
		summarizeBy: none
		sourceColumn: Site Name

		annotation SummarizationSetBy = Automatic

	column 'Location UUID'
		dataType: string
		lineageTag: df789c4e-c180-4755-929b-f58ebd313fde
		summarizeBy: none
		sourceColumn: Location UUID

		annotation SummarizationSetBy = Automatic

	column Baseline
		dataType: double
		lineageTag: 156912b3-f3e5-405d-9126-6f537d77a624
		summarizeBy: sum
		sourceColumn: Baseline

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Quarterly Target'
		dataType: double
		lineageTag: 4c5a7584-466f-4b0e-ab35-2ebe788b8f60
		summarizeBy: sum
		sourceColumn: Quarterly Target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 40eed2fe-f2aa-49f5-86cd-df16a7e84320
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Fact_OEE_Baseline = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Fact_OEE = AnalysisServices.Database("powerbi://api.powerbi.com/v1.0/myorg/Redzone", "Redzone Engineering Dataset", [Query="/* START QUERY BUILDER */#(lf)EVALUATE#(lf)SUMMARIZECOLUMNS(#(lf)    'Fact Baselines'[Site Name],#(lf)    'Fact Baselines'[Location UUID],#(lf)    'Dim Dates'[Year],#(lf)    'Dim Dates'[Month],#(lf)    KEEPFILTERS( FILTER( ALL( 'Fact Baselines'[Focus Lines] ), SEARCH( ""Y"", 'Fact Baselines'[Focus Lines], 1, 0 ) >= 1 )),#(lf)    ""Baseline"", [Baseline],#(lf)    ""Quarterly Target"", [Quarterly Target]#(lf))#(lf)ORDER BY #(lf)    'Fact Baselines'[Site Name] ASC,#(lf)    'Fact Baselines'[Location UUID] ASC,#(lf)    'Dim Dates'[Year] ASC,#(lf)    'Dim Dates'[Month] ASC#(lf)/* END QUERY BUILDER */", Implementation="2.0"]),
				    #"Renamed Columns" = Table.RenameColumns(Fact_OEE,{{"Fact Baselines[Site Name]", "Site Name"}, {"Fact Baselines[Location UUID]", "Location UUID"}, {"[Baseline]", "Baseline"}, {"[Quarterly Target]", "Quarterly Target"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([#"Dim Dates[Month]"] <> null)),
				    #"Added Custom" = Table.AddColumn(#"Filtered Rows", "Date", each #date([#"Dim Dates[Year]"],[#"Dim Dates[Month]"],1)),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"Date", type date}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Dim Dates[Year]", "Dim Dates[Month]"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

