table Fact_Safety
	lineageTag: 485146ba-0176-4589-9691-38a3d043c362

	measure Map_Safety_Target =
			
			Var area = SELECTEDVALUE(Dim_Profit_Center[Area])
			var site_area = SELECTEDVALUE(Fact_Safety[Area])
			RETURN
			IF(DISTINCTCOUNT(Dim_Profit_Center[Area]) > 1 , 1,
			    IF(area = site_area,1,0))
		lineageTag: a3a919e8-a210-42d9-b176-af4d65fcfaa7

	column 'Date/ Period (Fiscal Period)'
		dataType: string
		lineageTag: a681668b-220c-470f-a007-d94c1f2d8566
		summarizeBy: none
		sourceColumn: Date/ Period (Fiscal Period)

		annotation SummarizationSetBy = Automatic

	column 'profit center'
		dataType: string
		lineageTag: 96b16c77-4d98-442a-a987-80ed1b9a30bd
		summarizeBy: none
		sourceColumn: profit center

		annotation SummarizationSetBy = Automatic

	column 'Site name/Site UUID/Location UUID'
		dataType: string
		lineageTag: 2d689961-3440-485a-ab6e-a924e21eacf1
		summarizeBy: none
		sourceColumn: Site name/Site UUID/Location UUID

		annotation SummarizationSetBy = Automatic

	column 'ASTM - Rate'
		dataType: double
		lineageTag: 5a99f7d6-9565-4dbe-a0ba-8df25115321a
		summarizeBy: sum
		sourceColumn: ASTM - Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Target - ASTM - Rate '
		dataType: string
		lineageTag: 1cbd989c-a5a9-4f92-a545-30953142bc40
		summarizeBy: none
		sourceColumn: "Target - ASTM - Rate "

		annotation SummarizationSetBy = Automatic

	column ASTM-Incidents
		dataType: double
		lineageTag: 2fb74e0f-b71a-496a-9c73-8c86d57b11de
		summarizeBy: sum
		sourceColumn: ASTM-Incidents

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Target - ASTM - Incidents'
		dataType: string
		lineageTag: b3b8f8cd-8d01-46b2-b689-6399851df28c
		summarizeBy: none
		sourceColumn: Target - ASTM - Incidents

		annotation SummarizationSetBy = Automatic

	column 'pSIF SIFs Focus at our Sites - Action Past Due Closure Rate'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c42cb448-a692-461d-aef0-0702d7130112
		summarizeBy: sum
		sourceColumn: pSIF SIFs Focus at our Sites - Action Past Due Closure Rate

		annotation SummarizationSetBy = Automatic

	column 'Target - pSIF SIFs Focus at our Sites - Action Past Due Closure Rate'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bdcdd0ca-cefd-4df4-b914-39cb5a9a471a
		summarizeBy: sum
		sourceColumn: Target - pSIF SIFs Focus at our Sites - Action Past Due Closure Rate

		annotation SummarizationSetBy = Automatic

	column 'GOOD Catch Closure Rate '
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0a15bf51-7427-4a18-8dd2-7e07c1f7161d
		summarizeBy: sum
		sourceColumn: "GOOD Catch Closure Rate "

		annotation SummarizationSetBy = Automatic

	column 'Target - GOOD Catch Closure Rate %'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 104413ef-cb0d-4164-9277-81b7e14e4018
		summarizeBy: sum
		sourceColumn: Target - GOOD Catch Closure Rate %

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: int64
		formatString: 0
		lineageTag: b884b335-3930-4684-815c-cef94c225497
		summarizeBy: sum
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 6f0a6eb4-5453-4789-b6f3-5438242b67ed
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column YearPeriod
		dataType: string
		lineageTag: 4341f01c-a2fc-41ae-852f-f83495f0ba76
		summarizeBy: none
		sourceColumn: YearPeriod

		annotation SummarizationSetBy = Automatic

	column 'Closing Date' = LOOKUPVALUE('Dim_Closing Dates'[P_Closing Period Date],'Dim_Closing Dates'[P_YearMonth],Fact_Safety[YearPeriod])
		formatString: General Date
		lineageTag: 62ac9f59-b650-4d10-b4ec-5abbe545c086
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Site Group'
		dataType: string
		lineageTag: 8f0e0392-bf84-4784-9229-b0577142c809
		summarizeBy: none
		sourceColumn: Site Group

		annotation SummarizationSetBy = Automatic

	column 'Site Name'
		dataType: string
		lineageTag: 6cbf9a27-545d-4a17-bf25-7dcb729e6f0d
		summarizeBy: none
		sourceColumn: Site Name

		annotation SummarizationSetBy = Automatic

	column CSCA_flag = IF(Fact_Safety[Site Group] = "CSCA","Yes","No")
		lineageTag: 05ceb588-d8c3-4946-972a-76ba039c4b3f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CSCI_flag = IF(Fact_Safety[Site Group] = "CSCI","Yes","No")
		lineageTag: 960a3626-9efc-4b5b-8ed2-dd0d6a071780
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Area =
			SWITCH(Fact_Safety[Site name/Site UUID/Location UUID],
			                    "CSCA", "CSCA",
			                    "Michigan OTC", "CSCA",
			                    "Nutritional", "CSCA",
			                    "Logistics", "CSCA",
			                    "Vermont (PVT)","CSCA",
			                    "Michigan-Allegan (PMI)","CSCA",
			                    "Wisconsin (PWI)","CSCA",
			                    "Ohio (POH)","CSCA",
			                    "Michigan-Grand Rapids (POC)","CSCA",
			                    "New York (PNY)","CSCA",
			                    "Michigan-Holland (PMH)","CSCA",
			                    "CSCI", "CSCI",
			                    "UK-Braunton (PUK)", "CSCI",
			                    "Germany-Herrenberg", "CSCI",
			                    "France-Plelo", "CSCI",
			                    "France-Laboratoire de la Mer", "CSCI",
			                    "Belgium-Medgenix", "CSCI"
			)
		lineageTag: 56300e14-3703-44af-8e95-3ff15db56a1d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Fact_Safety = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://perrigo.sharepoint.com/sites/O365GRP_CentralizedSupplyChainAnalytics/Shared%20Documents/Sigmoid-Business-Documentation/Reports/Supporting%20Documents/Safety_of_people.xlsx")),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Removed Top Rows" = Table.Skip(Sheet1_Sheet,1),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Replaced Value" = Table.ReplaceValue(#"Promoted Headers","-","",Replacer.ReplaceValue,{"pSIF SIFs Focus at our Sites - Action Past Due Closure Rate"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{{"pSIF SIFs Focus at our Sites - Action Past Due Closure Rate", Percentage.Type}, {"GOOD Catch Closure Rate ", Percentage.Type}, {"Target - GOOD Catch Closure Rate %", Percentage.Type}, {"Target - pSIF SIFs Focus at our Sites - Action Past Due Closure Rate", Percentage.Type}, {"ASTM - Rate", type number}, {"Target - ASTM - Rate ", type text}, {"ASTM-Incidents", type number}, {"Target - ASTM - Incidents", type text}}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type", {{"pSIF SIFs Focus at our Sites - Action Past Due Closure Rate", 0}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Replaced Errors", "Date/ Period (Fiscal Period)", "Date/ Period (Fiscal Period) - Copy"),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Duplicated Column", "Date/ Period (Fiscal Period) - Copy", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"Date/ Period (Fiscal Period) - Copy.1", "Date/ Period (Fiscal Period) - Copy.2"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Date/ Period (Fiscal Period) - Copy.1", type text}, {"Date/ Period (Fiscal Period) - Copy.2", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Date/ Period (Fiscal Period) - Copy.2", "Year"}, {"Date/ Period (Fiscal Period) - Copy.1", "Period"}}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Renamed Columns","P","",Replacer.ReplaceText,{"Period"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value1",{{"Period", Int64.Type}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type2", "YearPeriod", each [Year] * 100 + [Period]),
				    #"Added Conditional Column" = Table.AddColumn(#"Added Custom", "Site Name", each if [#"Site name/Site UUID/Location UUID"] = "Michigan-Allegan (PMI)" then "PMI" else if [#"Site name/Site UUID/Location UUID"] = "Michigan-Holland (PMH)" then "PMH" else if [#"Site name/Site UUID/Location UUID"] = "New York (PNY)" then "PNY" else if [#"Site name/Site UUID/Location UUID"] = "Michigan-Grand Rapids (POC)" then "POC" else if [#"Site name/Site UUID/Location UUID"] = "Vermont (PVT)" then "PVT" else if [#"Site name/Site UUID/Location UUID"] = "Ohio (POH)" then "POH" else if [#"Site name/Site UUID/Location UUID"] = "Wisconsin (PWI)" then "PWI" else if [#"Site name/Site UUID/Location UUID"] = "Belgium-Medgenix" then "MGX" else if [#"Site name/Site UUID/Location UUID"] = "France-Laboratoire de la Mer" then "LDM" else if [#"Site name/Site UUID/Location UUID"] = "Germany-Herrenberg" then "HER" else if [#"Site name/Site UUID/Location UUID"] = "UK-Braunton (PUK)" then "PUK" else if [#"Site name/Site UUID/Location UUID"] = "Michigan OTC" then "MI OTC" else if [#"Site name/Site UUID/Location UUID"] = "Nutritional" then "Nutrition" else [#"Site name/Site UUID/Location UUID"]),
				    #"Added Conditional Column1" = Table.AddColumn(#"Added Conditional Column", "Site Group", each if [Site Name] = "PNY" then "NY OTC" else if [Site Name] = "POC" then "Oral Care" else if [Site Name] = "MGX" then "PMED" else if [Site Name] = "LDM" then "PLAB/France Saint-Malo" else if [Site Name] = "HER" then "PHER" else [Site Name])
				in
				    #"Added Conditional Column1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

