table Fact_Target
	lineageTag: 3945f5ab-aaeb-4693-bfe9-712651f85ebd

	column KPI_Name
		dataType: string
		lineageTag: a1a6d491-3684-4084-9ffd-25b5e4cceae9
		summarizeBy: none
		sourceColumn: KPI_Name

		annotation SummarizationSetBy = Automatic

	column Plan/Flex
		dataType: string
		lineageTag: 05c93f6c-f6e7-47f9-b187-8ad1d414d973
		summarizeBy: none
		sourceColumn: Plan/Flex

		annotation SummarizationSetBy = Automatic

	column Frequency
		dataType: string
		lineageTag: 32f666ff-9b8f-4bf9-b221-5d2da99cc78a
		summarizeBy: none
		sourceColumn: Frequency

		annotation SummarizationSetBy = Automatic

	column Period/Year
		dataType: int64
		formatString: 0
		lineageTag: f2507c69-9cd0-4906-9d8c-152efdd7a62a
		summarizeBy: sum
		sourceColumn: Period/Year

		annotation SummarizationSetBy = Automatic

	column 'Site name'
		dataType: string
		lineageTag: abe13599-aa70-4a99-871b-c32f0aafa2eb
		summarizeBy: none
		sourceColumn: Site name

		annotation SummarizationSetBy = Automatic

	column Cluster
		dataType: string
		lineageTag: 3723dcb1-2d79-4983-b081-2675106731b8
		summarizeBy: none
		sourceColumn: Cluster

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: 15b9d501-815f-4790-bce0-d2575cb4b2cb
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column CompositeKey
		dataType: string
		lineageTag: ffc64b73-4d77-468d-9563-200d4d536c0e
		summarizeBy: none
		sourceColumn: CompositeKey

		annotation SummarizationSetBy = Automatic

	column Target
		dataType: int64
		formatString: 0
		lineageTag: 06017a92-1acd-446a-9526-6cdf314b225d
		summarizeBy: sum
		sourceColumn: Target

		annotation SummarizationSetBy = Automatic

	column Year-Month = CONCATENATE(Fact_Target[Period/Year],RIGHT(Fact_Target[Period],2))
		lineageTag: 76ba9644-4c98-4315-86d6-7596a9cd48ab
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Closing Date' = LOOKUPVALUE('Dim_Closing Dates'[P_Closing Period Date],'Dim_Closing Dates'[P_YearMonth],Fact_Target[Year-Month])
		formatString: General Date
		lineageTag: b180789c-18fe-467e-8bf4-034d65bb4288
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Profit Center Dummy Key'
		dataType: string
		lineageTag: 449637b8-c296-4b81-a489-218738ef0489
		summarizeBy: none
		sourceColumn: Profit Center Dummy Key

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: string
		lineageTag: cc856004-5c0b-4a87-8887-72d0b64ac8df
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: a382c9cc-7eeb-4332-9faa-269d8607ea5c
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	partition Fact_Target = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://perrigo.sharepoint.com/sites/O365GRP_CentralizedSupplyChainAnalytics/Shared%20Documents/Sigmoid-Business-Documentation/Reports/Supporting%20Documents/Fact_Target.xlsx"), null, true),
				    Target_Split_Table = Source{[Item="Target_Split",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Target_Split_Table,{{"KPI_Name", type text}, {"Plan/Flex", type text}, {"Frequency", type text}, {"Period/Year", Int64.Type}, {"Site name", type text}, {"Cluster", type text}, {"Profit Center Dummy Key", type text}, {"Area", type text}, {"CompositeKey", type text}, {"Period", type text}, {"Target", Int64.Type}, {"Unit", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

