table Fact_Customer_Fines
	lineageTag: 51a1bd27-2826-45e9-ac65-f852cfd497ce

	measure Map_Customer_Target =
			
			Var area = SELECTEDVALUE(Dim_Profit_Center[Area])
			var site_area = SELECTEDVALUE(Fact_Target[Area])
			RETURN
			IF(DISTINCTCOUNT(Dim_Profit_Center[Area]) > 1 , 1,
			    IF(area = site_area,1,0))
		formatString: 0
		lineageTag: de774137-13b1-433a-b471-acb9a919dcd5

	column 'Document Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ef662c41-5cbc-447c-97eb-b38b0bd97ae1
		summarizeBy: none
		sourceColumn: Document Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Report Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6d21ed26-3bb5-45a9-b3ac-8e9164c3d0e8
		summarizeBy: none
		sourceColumn: Report Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Perrigo Material #'
		dataType: string
		lineageTag: d7a060e8-d36e-4100-bbaa-3183e630da31
		summarizeBy: none
		sourceColumn: Perrigo Material #

		annotation SummarizationSetBy = Automatic

	column 'Business Unit'
		dataType: string
		lineageTag: d5a40549-494b-47cb-9f42-3c2c7f0c355a
		summarizeBy: none
		sourceColumn: Business Unit

		annotation SummarizationSetBy = Automatic

	column 'Charge Type'
		dataType: string
		lineageTag: f13ec451-1dbd-4d9a-a0e4-a171e53b766c
		summarizeBy: none
		sourceColumn: Charge Type

		annotation SummarizationSetBy = Automatic

	column 'Split Amount'
		dataType: double
		lineageTag: b86bee76-1177-4696-ad49-c787ac96d084
		summarizeBy: sum
		sourceColumn: Split Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ComplianceName
		dataType: string
		lineageTag: 11914df7-d8a8-479a-a16d-fb759c1255e4
		summarizeBy: none
		sourceColumn: ComplianceName

		annotation SummarizationSetBy = Automatic

	column 'Last Refreshed'
		dataType: dateTime
		formatString: General Date
		lineageTag: 5d7666c8-0e60-45df-97f9-4177832f5d82
		summarizeBy: none
		sourceColumn: Last Refreshed

		annotation SummarizationSetBy = Automatic

	column 'Customer Name' = SWITCH(Fact_Customer_Fines[ComplianceName],"AssociatedWholesaleGrocers","Associated Wholesale Grocers",Fact_Customer_Fines[ComplianceName])
		lineageTag: ca68cbb2-f382-498a-b988-12af1d98d055
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Fact_Customer_Fines = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Fact_Customer_Fines = AnalysisServices.Database("powerbi://api.powerbi.com/v1.0/myorg/Analytics%20Team%20Sandbox", "Compliance Fine Management new split", [Query="/* START QUERY BUILDER */#(lf)#(lf)DEFINE#(lf)    MEASURE 'Split Total Compliance'[Total SplitAmount] =#(lf)        SUM ( 'Split Total Compliance'[SplitAmount] )#(lf)#(lf)    MEASURE 'Split Total Compliance'[Last Refreshed] =#(lf)        MAX ( 'Date Last Refreshed'[Date Last Refreshed] )#(lf)#(lf)EVALUATE#(lf)SUMMARIZECOLUMNS(#(lf)    'Split Total Compliance'[DocumentDate],#(lf)    'Split Total Compliance'[ReportDate],#(lf)    'Split Total Compliance'[Perrigo Material #],#(lf)    'Split Total Compliance'[Business Unit],#(lf)    'Split Total Compliance'[ComplianceName],#(lf)    'Split Total Compliance'[ChargeType],#(lf)#(lf)    ""SplitAmount"", [Total SplitAmount],#(lf)    ""Last Refreshed"", [Last Refreshed]#(lf))#(lf)ORDER BY #(lf)    'Split Total Compliance'[DocumentDate] ASC,#(lf)    'Split Total Compliance'[ReportDate] ASC,#(lf)    'Split Total Compliance'[Perrigo Material #] ASC,#(lf)    'Split Total Compliance'[Business Unit] ASC,#(lf)    'Split Total Compliance'[ComplianceName] ASC,#(lf)    'Split Total Compliance'[ChargeType] ASC#(lf)#(lf)/* END QUERY BUILDER */#(lf)", Implementation="2.0"]),
				    #"Renamed Columns" = Table.RenameColumns(Fact_Customer_Fines,{{"Split Total Compliance[DocumentDate]", "Document Date"}, {"Split Total Compliance[ReportDate]", "Report Date"}, {"Split Total Compliance[Perrigo Material #]", "Perrigo Material #"}, {"Split Total Compliance[Business Unit]", "Business Unit"}, {"Split Total Compliance[ChargeType]", "Charge Type"}, {"[SplitAmount]", "Split Amount"}, {"Split Total Compliance[ComplianceName]", "ComplianceName"}, {"[Last Refreshed]", "Last Refreshed"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Document Date", type date}, {"Report Date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

