table KPI_Metadata
	lineageTag: cee11cc8-5c38-4057-bf37-2cec58f821a2

	measure 'Green Count (Visible)' = ```
			
			CALCULATE (
			    COUNTROWS ( KPI_Metadata ),
			    FILTER (
			        KPI_Metadata,
			        [KPI Status Numeric] = 1
			            && NOT ISBLANK ( [KPI Status Numeric] )
			    )
			)
			
			```
		formatString: 0
		lineageTag: 1d2a050a-42ae-4ed0-934e-9ae67f4e4418

	measure 'KPI Status Icon' = ```
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "FA_Lag1_vsPlan", [FA Target L1 Diff raw],
			        // "FA_Lag1_vsLYTD", [FA% LYTD CSCI],
			        // "FA_Lag1_vsYoY", [FA% YoY L1 raw CSCI],
			        // "FA_Lag1_vsPP", [FA% MoM L1 raw CSCI],
			
			        // "FA_Lag2_vsPlan", [FA% Lag 2 Target Diff%],
			        // "FA_Lag2_vsLYTD", CALCULATE([FA% CSCA LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2")),
			        // "FA_Lag2_vsYoY", [FA% Lag2 YoY%],
			        // "FA_Lag2_vsPP", [FA% Lag2 MoM%],
			
			        // "FA_Lag4_CSCA_vsPlan", [FA% Lag 4 Target Diff%],
			        // "FA_Lag4_CSCA_vsLYTD", CALCULATE([FA% CSCA LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        // "FA_Lag4_CSCA_vsYoY", [FA% Lag4 YoY%],
			        // "FA_Lag4_CSCA_vsPP", [FA% Lag4 MoM%],
			        // "FA_Lag4_CSCI_vsPlan", [FA Target L4 Diff raw],
			        // "FA_Lag4_CSCI_vsLYTD", [FA% LYTD CSCI],
			        // "FA_Lag4_CSCI_vsYoY", [FA% YoY L4 raw CSCI],
			        // "FA_Lag4_CSCI_vsPP", [FA% MoM CSCI L4],
			
			        // "Bias_Lag1_vsPlan", [Bias Target Diff%_CSCI L1],
			        // "Bias_Lag1_vsLYTD", CALCULATE([Bias % LYTD CSCI], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="1")),
			        // "Bias_Lag1_vsYoY", [Bias YoY % L1 Raw CSCI],
			        // "Bias_Lag1_vsPP", [Bias MoM%_raw L1 CSCI],
			        
			        // "Bias_Lag2_vsPlan", [Bias Lag2 Target Diff%],
			        // "Bias_Lag2_vsLYTD", CALCULATE([Bias% LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2")),
			        // "Bias_Lag2_vsYoY", [Bias Lag2 YoY%],
			        // "Bias_Lag2_vsPP", CALCULATE([Bias MoM%], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2")),
			
			        // "Bias_Lag4_CSCA_vsPlan", [Bias Lag4 Target Diff%],
			        // "Bias_Lag4_CSCA_vsLYTD", CALCULATE([Bias% LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        // "Bias_Lag4_CSCA_vsYoY", [Bias Lag4 YoY%],
			        // "Bias_Lag4_CSCA_vsPP", CALCULATE([Bias MoM%], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        // "Bias_Lag4_CSCI_vsPlan", [Bias Target Diff%_CSCI L4],
			        // "Bias_Lag4_CSCI_vsLYTD", CALCULATE([Bias % LYTD CSCI], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        // "Bias_Lag4_CSCI_vsYoY", [Bias YoY % L4 Raw CSCI],
			        // "Bias_Lag4_CSCI_vsPP", [Bias MoM%_raw L4 CSCI],
			
			        // "Net_Inventory_vsPlan", [Net Inventory_APN],
			        // "Net_Inventory_vsFlex", [Net Inventory_AFX],
			        // "Net_Inventory_vsLYTD", [Net Inventory LYTD],
			        // "Net_Inventory_vsPP", [Net Inventory MoM%],
			        // "Net_Inventory_vsYoY", [Net Inventory YoY%],
			
			        // "Gross_Inventory_vsPlan", [Gross Inventory_APN],
			        // "Gross_Inventory_vsFlex", [Gross Inventory_AFX],
			        // "Gross_Inventory_vsLYTD", [Gross Inv LYTD],
			        // "Gross_Inventory_vsPP", [Gross Inventory MoM%],
			        // "Gross_Inventory_vsYoY", [Gross Inventory YoY%],
			
			        // "Expired_Inventory_vsPP", [Expired Inventory MoM%],
			        // "Expired_Inventory_vsYoY", [Expired Inventory YoY%],
			        // "Expired_Inventory_vsLYTD", [Expired Inventory LYTD],
			
			        // "Inflated_Inventory_vsPP", [Inflated Inventory MoM%],
			        // "Inflated_Inventory_vsYoY", [Inflated Inventory YoY%],
			        // "Inflated_Inventory_vsLYTD", [Inflated Inv LYTD],
			
			        // "DIO_vsPlan", [DIO_APN],
			        // "DIO_vsPP", [DIO MoM%],
			        // "DIO_vsFlex", [DIO_AFX],
			        // "DIO_vsYoY", [DIO YoY%],
			
			        // "SSSO_Conversions_vsPlan", [SSSO: Obsolescenes linked to Conversions_APN],
			        // "SSSO_Conversions_vsLYTD", [SSSO: Obs LYTD],
			        // "SSSO_Conversions_vsPP", [SSSO: Obs linked to Conv MoM%],
			        // "SSSO_Conversions_vsYoY", [SSSO: Obs linked to Conv YoY%],
			        // "SSSO_Conversions_vsFlex", [SSSO: Obs linked to conv F66_Final],
			
			        // "SSSO_Salvage_Obsolescence_vsPlan", [SSSO: Salvage & Obsolescence_APN],
			        // "SSSO_Salvage_Obsolescence_vsLYTD", [SSSO: Salvage LYTD],
			        // "SSSO_Salvage_Obsolescence_vsPP", [SSSO: Salvage & obs MoM%],
			        // "SSSO_Salvage_Obsolescence_vsYoY", [SSSO: Salvage YoY%],
			        // "SSSO_Salvage_Obsolescence_vsFlex", [SSSO: Salvage & Obs F66_Final],
			
			        // "SSSO_Scrap_vsPlan", [SSSO: Scrap-Off_APN],
			        // "SSSO_Scrap_vsLYTD", [SSSO: Scrap-off LYTD],
			        // "SSSO_Scrap_vsPP", [SSSO: Scrap-Off MoM%],
			        // "SSSO_Scrap_vsYoY", [SSSO: Scrap-Off YoY%],
			        // "SSSO_Scrap_vsFlex", [SSSO: Scrap-Off_F66],
			
			        // "DPO_vsPP", [DPO MoM%],
			        // "DPO_vsYoY", [DPO YoY%],
			
			        // "OEE_vsPlan", [OEE Target diff%],
			        // "OEE_vsPP", [OEE% MoM%],
			        // "OEE_vsYoY", [OEE% YoY%],
			        // "OEE_vsLYTD", [OEE LYTD],
			
			        // "COGS_vsPlan", [COGS_APN],
			        // "COGS_vsPP", [COGS Actual MoM%],
			        // "COGS_vsYoY", [COGS Actual YoY%],
			        // "COGS_vsLYTD", [COGS Actual LYTD],
			
			        // "Dist_to_COGS_vsPlan", [Total Distribution on COGS_APN],
			        // "Dist_to_COGS_vsPP", [Total Distribution on COGS Actual MoM%],
			        // "Dist_to_COGS_vsYoY", [Total Distribution on COGS Actual YoY%],
			        // "Dist_to_COGS_vsLYTD", [Total Distribution on COGS LYTD],
			
			        // "Log_to_Sales_vsPlan", [Total Logistics on Net Sales_APN],
			        // "Log_to_Sales_vsPP", [Total Logistics on Net Sales Actual MoM%],
			        // "Log_to_Sales_vsYoY", [Total Logistics on Net Sales Actual YoY%],
			        // "Log_to_Sales_vsLYTD", [Total Logistics on Net Sales LYTD],
			
			        // "Schedule_Attainment_vsPlan", [Schedule Attn Target Diff%],
			        // "Schedule_Attainment_vsPP", [SA MoM%],
			        // "Schedule_Attainment_vsYoY", [SA YoY%],
			        // "Schedule_Attainment_vsLYTD", [Schedule Attn LYTD],
			
			        // "Net_Sales_vsPlan", [Net Sales_APN],
			        // "Net_Sales_vsPP", [Net Sales Actual MoM%],
			        // "Net_Sales_vsYoY", [Net Sales Actual YoY%],
			        // "Net_Sales_vsLYTD", [Net Sales Actual LYTD],
			
			        // "DSO_vsPP", [DSO MoM%],
			        // "DSO_vsYoY", [DSO YoY%],
			
			        // "Service_Level_Gap_vsPlan", [Service Target Diff%],
			        // "Service_Level_Gap_vsPP", [Service Rate% MoM%],
			        // "Service_Level_Gap_vsYoY", [Service Rate YoY%],
			        // "Service_Level_Gap_vsLYTD", [Service Rate LYTD],
			
			        // "Service_Level_Total_vsPlan", [Service Target Diff%_CSCI],
			        // "Service_Level_Total_vsPP", [Service Level MoM%],
			        // "Service_Level_Total_vsYoY", [Service Level YoY%],
			        // "Service_Level_Total_vsLYTD", [Service Level LYTD],
			
			        // "Customer_Fines_vsPlan", [Cust Fine Target Diff%],
			        // "Customer_Fines_vsPP", [Cust Fine MoM%],
			        // "Customer_Fines_vsYoY", [Cust fine YoY%],
			        // "Customer_Fines_vsLYTD", [Cust Fine LYTD],
			
			        // "Case_fill_rate_vsPlan", [CFR Target Diff%],
			        // "Case_fill_rate_vsPP", [CFR MoM%],
			        // "Case_fill_rate_vsYoY", [CFR YoY%],
			        // "Case_fill_rate_vsLYTD", [CFR LYTD],
			        BLANK()
			    )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, "游릭", "游댮" ),
			        IF ( _value < 0, "游댮", "游릭" )
			    )
			```
		lineageTag: c39a6b2b-98e1-4ba1-94c6-7d110abbb902

	measure 'KPI Status Icon (Customer Service)' =
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "Service_Level_Gap_vsPlan", [Service Target Diff%],
			        "Service_Level_Gap_vsPP", [Service Rate% MoM%],
			        "Service_Level_Gap_vsYoY", [Service Rate YoY%],
			        "Service_Level_Gap_vsLYTD", [Service Rate LYTD],
			
			        "Service_Level_Total_vsPlan", [Service Target Diff%_CSCI],
			        "Service_Level_Total_vsPP", [Service Level MoM%],
			        "Service_Level_Total_vsYoY", [Service Level YoY%],
			        "Service_Level_Total_vsLYTD", [Service Level LYTD],
			
			        "Customer_Fines_vsPlan", [Cust Fine Target Diff%],
			        "Customer_Fines_vsPP", [Cust Fine MoM%],
			        "Customer_Fines_vsYoY", [Cust fine YoY%],
			        "Customer_Fines_vsLYTD", [Cust Fine LYTD],
			
			        "Case_fill_rate_vsPlan", [CFR Target Diff%],
			        "Case_fill_rate_vsPP", [CFR MoM%],
			        "Case_fill_rate_vsYoY", [CFR YoY%],
			        "Case_fill_rate_vsLYTD", [CFR LYTD],
			        BLANK()
			    )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, "游릭", "游댮" ),
			        IF ( _value < 0, "游댮", "游릭" )
			    )
		lineageTag: 540b0bd3-4b9f-4861-aac2-c3e8afa3eb2e

	measure 'KPI Status Icon (Demand)' = ```
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "FA_Lag1_vsPlan", [FA Target L1 Diff raw],
			        "FA_Lag1_vsLYTD", [FA% LYTD CSCI],
			        "FA_Lag1_vsYoY", [FA% YoY L1 raw CSCI],
			        "FA_Lag1_vsPP", [FA% MoM L1 raw CSCI],
			
			        "FA_Lag2_vsPlan", [FA% Lag 2 Target Diff%],
			        "FA_Lag2_vsLYTD", CALCULATE([FA% CSCA LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2")),
			        "FA_Lag2_vsYoY", [FA% Lag2 YoY%],
			        "FA_Lag2_vsPP", [FA% Lag2 MoM%],
			
			        "FA_Lag4_CSCA_vsPlan", [FA% Lag 4 Target Diff%],
			        "FA_Lag4_CSCA_vsLYTD", CALCULATE([FA% CSCA LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        "FA_Lag4_CSCA_vsYoY", [FA% Lag4 YoY%],
			        "FA_Lag4_CSCA_vsPP", [FA% Lag4 MoM%],
			        "FA_Lag4_CSCI_vsPlan", [FA Target L4 Diff raw],
			        "FA_Lag4_CSCI_vsLYTD", [FA% LYTD CSCI],
			        "FA_Lag4_CSCI_vsYoY", [FA% YoY L4 raw CSCI],
			        "FA_Lag4_CSCI_vsPP", [FA% MoM CSCI L4],
			
			        "Bias_Lag1_vsPlan", [Bias Target Diff%_CSCI L1],
			        "Bias_Lag1_vsLYTD", CALCULATE([Bias % LYTD CSCI], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="1")),
			        "Bias_Lag1_vsYoY", [Bias YoY % L1 Raw CSCI],
			        "Bias_Lag1_vsPP", [Bias MoM%_raw L1 CSCI],
			        
			        "Bias_Lag2_vsPlan", [Bias Lag2 Target Diff%],
			        "Bias_Lag2_vsLYTD", CALCULATE([Bias% LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2")),
			        "Bias_Lag2_vsYoY", [Bias Lag2 YoY%],
			        "Bias_Lag2_vsPP", CALCULATE([Bias MoM%], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2")),
			
			        "Bias_Lag4_CSCA_vsPlan", [Bias Lag4 Target Diff%],
			        "Bias_Lag4_CSCA_vsLYTD", CALCULATE([Bias% LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        "Bias_Lag4_CSCA_vsYoY", [Bias Lag4 YoY%],
			        "Bias_Lag4_CSCA_vsPP", CALCULATE([Bias MoM%], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        "Bias_Lag4_CSCI_vsPlan", [Bias Target Diff%_CSCI L4],
			        "Bias_Lag4_CSCI_vsLYTD", CALCULATE([Bias % LYTD CSCI], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        "Bias_Lag4_CSCI_vsYoY", [Bias YoY % L4 Raw CSCI],
			        "Bias_Lag4_CSCI_vsPP", [Bias MoM%_raw L4 CSCI],
			        BLANK()
			    )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, "游릭", "游댮" ),
			        IF ( _value < 0, "游댮", "游릭" )
			    )
			```
		lineageTag: 8c97b6cc-c44a-45de-a264-00cf3827cc63

	measure 'KPI Status Icon (Fullfilment)' =
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "Net_Sales_vsPlan", [Net Sales_APN],
			        "Net_Sales_vsPP", [Net Sales Actual MoM%],
			        "Net_Sales_vsYoY", [Net Sales Actual YoY%],
			        "Net_Sales_vsLYTD", [Net Sales Actual LYTD],
			
			
			        "DSO_vsPlan", [DSO_APN],
			        "DSO_vsPP", [DSO MoM%],
			        "DSO_vsYoY", [DSO YoY%],
			
			        BLANK()
			    )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, "游릭", "游댮" ),
			        IF ( _value < 0, "游댮", "游릭" )
			    )
		lineageTag: 32c01af7-92b9-4f4c-ae7a-06445b397d3a

	measure 'KPI Status Icon (Inventory)' =
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "Net_Inventory_vsPlan", [Net Inventory_APN],
			        "Net_Inventory_vsFlex", [Net Inventory_AFX],
			        "Net_Inventory_vsLYTD", [Net Inventory LYTD],
			        "Net_Inventory_vsPP", [Net Inventory MoM%],
			        "Net_Inventory_vsYoY", [Net Inventory YoY%],
			
			        "Gross_Inventory_vsPlan", [Gross Inventory_APN],
			        "Gross_Inventory_vsFlex", [Gross Inventory_AFX],
			        "Gross_Inventory_vsLYTD", [Gross Inv LYTD],
			        "Gross_Inventory_vsPP", [Gross Inventory MoM%],
			        "Gross_Inventory_vsYoY", [Gross Inventory YoY%],
			
			        "Expired_Inventory_vsPP", [Expired Inventory MoM%],
			        "Expired_Inventory_vsYoY", [Expired Inventory YoY%],
			        "Expired_Inventory_vsLYTD", [Expired Inventory LYTD],
			
			        "Inflated_Inventory_vsPP", [Inflated Inventory MoM%],
			        "Inflated_Inventory_vsYoY", [Inflated Inventory YoY%],
			        "Inflated_Inventory_vsLYTD", [Inflated Inv LYTD],
			
			        "DIO_vsPlan", [DIO_APN],
			        "DIO_vsPP", [DIO MoM%],
			        "DIO_vsFlex", [DIO_AFX],
			        "DIO_vsYoY", [DIO YoY%],
			
			        "SSSO_Conversions_vsPlan", [SSSO: Obsolescenes linked to Conversions_APN],
			        "SSSO_Conversions_vsLYTD", [SSSO: Obs LYTD],
			        "SSSO_Conversions_vsPP", [SSSO: Obs linked to Conv MoM%],
			        "SSSO_Conversions_vsYoY", [SSSO: Obs linked to Conv YoY%],
			        "SSSO_Conversions_vsFlex", [SSSO: Obs linked to conv F66_Final],
			
			        "SSSO_Salvage_Obsolescence_vsPlan", [SSSO: Salvage & Obsolescence_APN],
			        "SSSO_Salvage_Obsolescence_vsLYTD", [SSSO: Salvage LYTD],
			        "SSSO_Salvage_Obsolescence_vsPP", [SSSO: Salvage & obs MoM%],
			        "SSSO_Salvage_Obsolescence_vsYoY", [SSSO: Salvage YoY%],
			        "SSSO_Salvage_Obsolescence_vsFlex", [SSSO: Salvage & Obs F66_Final],
			
			        "SSSO_Scrap_vsPlan", [SSSO: Scrap-Off_APN],
			        "SSSO_Scrap_vsLYTD", [SSSO: Scrap-off LYTD],
			        "SSSO_Scrap_vsPP", [SSSO: Scrap-Off MoM%],
			        "SSSO_Scrap_vsYoY", [SSSO: Scrap-Off YoY%],
			        "SSSO_Scrap_vsFlex", [SSSO: Scrap-Off_F66],
			
			        "SSSO_Shrinkage_vsPlan", [SSSO: Shrinkage_APN],
			        "SSSO_Shrinkage_vsLYTD", [SSSO: Shrinkage LYTD],
			        "SSSO_Shrinkage_vsPP", [SSSO: Shrinkage MoM%],
			        "SSSO_Shrinkage_vsYoY", [SSSO: Shrinkage YoY%],
			        "SSSO_Shrinkage_vsFlex", [SSSO: Shrinkage_F66],
			        BLANK()
			        )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, "游릭", "游댮" ),
			        IF ( _value < 0, "游댮", "游릭" )
			    )
		lineageTag: 30bcdc07-943f-4ed1-94fa-7c24b51e73fb

	measure 'KPI Status Icon (Logistics)' =
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "Dist_to_COGS_vsPlan", [Total Distribution on COGS_APN],
			        "Dist_to_COGS_vsPP", [Total Distribution on COGS Actual MoM%],
			        "Dist_to_COGS_vsYoY", [Total Distribution on COGS Actual YoY%],
			        "Dist_to_COGS_vsLYTD", [Total Distribution on COGS LYTD],
			
			        "Log_to_Sales_vsPlan", [Total Logistics on Net Sales_APN],
			        "Log_to_Sales_vsPP", [Total Logistics on Net Sales Actual MoM%],
			        "Log_to_Sales_vsYoY", [Total Logistics on Net Sales Actual YoY%],
			        "Log_to_Sales_vsLYTD", [Total Logistics on Net Sales LYTD],
			
			        "Schedule_Attainment_vsPlan", [Schedule Attn Target Diff%],
			        "Schedule_Attainment_vsPP", [SA MoM%],
			        "Schedule_Attainment_vsYoY", [SA YoY%],
			        "Schedule_Attainment_vsLYTD", [Schedule Attn LYTD],
			        BLANK()
			    )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, "游릭", "游댮" ),
			        IF ( _value < 0, "游댮", "游릭" )
			    )
		lineageTag: 5c34cc7f-eed8-4e70-bacb-f16301694222

	measure 'KPI Status Icon (Manufacturing)' =
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "OEE_vsPlan", [OEE Target diff%],
			        "OEE_vsPP", [OEE% MoM%],
			        "OEE_vsYoY", [OEE% YoY%],
			        "OEE_vsLYTD", [OEE LYTD],
			
			        "COGS_vsPlan", [COGS_APN],
			        "COGS_vsPP", [COGS Actual MoM%],
			        "COGS_vsYoY", [COGS Actual YoY%],
			        "COGS_vsLYTD", [COGS Actual LYTD],
			        BLANK()
			    )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, "游릭", "游댮" ),
			        IF ( _value < 0, "游댮", "游릭" )
			    )
		lineageTag: a0e28e0b-6a78-4739-84d7-105252889ce3

	measure 'KPI Status Icon (Procurement)' =
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "DPO_vsPlan", [DPO_APN],
			        "DPO_vsPP", [DPO MoM%],
			        "DPO_vsYoY", [DPO YoY%],
			        BLANK()
			    )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, "游릭", "游댮" ),
			        IF ( _value < 0, "游댮", "游릭" )
			    )
		lineageTag: 64623ad6-23a6-45cb-b829-dd959a0920eb

	measure 'KPI Status Numeric' = ```
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode = SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "FA_Lag1_vsPlan", [FA Target L1 Diff raw],
			        "FA_Lag1_vsLYTD", [FA% LYTD CSCI],
			        "FA_Lag1_vsYoY", [FA% YoY L1 raw CSCI],
			        "FA_Lag1_vsPP", [FA% MoM L1 raw CSCI],
			
			        "FA_Lag2_vsPlan", [FA% Lag 2 Target Diff%],
			        "FA_Lag2_vsLYTD", CALCULATE([FA% CSCA LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2")),
			        "FA_Lag2_vsYoY", [FA% Lag2 YoY%],
			        "FA_Lag2_vsPP", [FA% Lag2 MoM%],
			
			        "FA_Lag4_CSCA_vsPlan", [FA% Lag 4 Target Diff%],
			        "FA_Lag4_CSCA_vsLYTD", CALCULATE([FA% CSCA LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        "FA_Lag4_CSCA_vsYoY", [FA% Lag4 YoY%],
			        "FA_Lag4_CSCA_vsPP", [FA% Lag4 MoM%],
			        "FA_Lag4_CSCI_vsPlan", [FA Target L4 Diff raw],
			        "FA_Lag4_CSCI_vsLYTD", [FA% LYTD CSCI],
			        "FA_Lag4_CSCI_vsYoY", [FA% YoY L4 raw CSCI],
			        "FA_Lag4_CSCI_vsPP", [FA% MoM CSCI L4],
			
			        "Bias_Lag1_vsPlan", [Bias Target Diff%_CSCI L1],
			        "Bias_Lag1_vsLYTD", CALCULATE([Bias % LYTD CSCI], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="1")),
			        "Bias_Lag1_vsYoY", [Bias YoY % L1 Raw CSCI],
			        "Bias_Lag1_vsPP", [Bias MoM%_raw L1 CSCI],
			        
			        "Bias_Lag2_vsPlan", [Bias Lag2 Target Diff%],
			        "Bias_Lag2_vsLYTD", CALCULATE([Bias% LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2")),
			        "Bias_Lag2_vsYoY", [Bias Lag2 YoY%],
			        "Bias_Lag2_vsPP", CALCULATE([Bias MoM%], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2")),
			
			        "Bias_Lag4_CSCA_vsPlan", [Bias Lag4 Target Diff%],
			        "Bias_Lag4_CSCA_vsLYTD", CALCULATE([Bias% LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        "Bias_Lag4_CSCA_vsYoY", [Bias Lag4 YoY%],
			        "Bias_Lag4_CSCA_vsPP", CALCULATE([Bias MoM%], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        "Bias_Lag4_CSCI_vsPlan", [Bias Target Diff%_CSCI L4],
			        "Bias_Lag4_CSCI_vsLYTD", CALCULATE([Bias % LYTD CSCI], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        "Bias_Lag4_CSCI_vsYoY", [Bias YoY % L4 Raw CSCI],
			        "Bias_Lag4_CSCI_vsPP", [Bias MoM%_raw L4 CSCI],
			
			        "Service_Top_11_vsPlan", [Service Top 11 Target Diff%],
			        "Service_Top_11_vsYoY", [Service Top 11 YoY%],
			        "Service_Top_11_vsLYTD", [Service Top 11 LYTD],
			        "Service_Top_11_vsPP", [Service Top 11 MoM%],
			
			        "Net_Inventory_vsPlan", [Net Inventory_APN],
			        "Net_Inventory_vsFlex", [Net Inventory_AFX],
			        "Net_Inventory_vsLYTD", [Net Inventory LYTD],
			        "Net_Inventory_vsPP", [Net Inventory MoM%],
			        "Net_Inventory_vsYoY", [Net Inventory YoY%],
			
			        "Gross_Inventory_vsPlan", [Gross Inventory_APN],
			        "Gross_Inventory_vsFlex", [Gross Inventory_AFX],
			        "Gross_Inventory_vsLYTD", [Gross Inv LYTD],
			        "Gross_Inventory_vsPP", [Gross Inventory MoM%],
			        "Gross_Inventory_vsYoY", [Gross Inventory YoY%],
			
			        "Expired_Inventory_vsPP", [Expired Inventory MoM%],
			        "Expired_Inventory_vsYoY", [Expired Inventory YoY%],
			        "Expired_Inventory_vsLYTD", [Expired Inventory LYTD],
			
			        "Inflated_Inventory_vsPP", [Inflated Inventory MoM%],
			        "Inflated_Inventory_vsYoY", [Inflated Inventory YoY%],
			        "Inflated_Inventory_vsLYTD", [Inflated Inv LYTD],
			
			        "DIO_vsPlan", [DIO_APN],
			        "DIO_vsPP", [DIO MoM%],
			        "DIO_vsFlex", [DIO_AFX],
			        "DIO_vsYoY", [DIO YoY%],
			
			        "SSSO_Conversions_vsPlan", [SSSO: Obsolescenes linked to Conversions_APN],
			        "SSSO_Conversions_vsLYTD", [SSSO: Obs LYTD],
			        "SSSO_Conversions_vsPP", [SSSO: Obs linked to Conv MoM%],
			        "SSSO_Conversions_vsYoY", [SSSO: Obs linked to Conv YoY%],
			        "SSSO_Conversions_vsFlex", [SSSO: Obs linked to conv F66_Final],
			
			        "SSSO_Salvage_Obsolescence_vsPlan", [SSSO: Salvage & Obsolescence_APN],
			        "SSSO_Salvage_Obsolescence_vsLYTD", [SSSO: Salvage LYTD],
			        "SSSO_Salvage_Obsolescence_vsPP", [SSSO: Salvage & obs MoM%],
			        "SSSO_Salvage_Obsolescence_vsYoY", [SSSO: Salvage YoY%],
			        "SSSO_Salvage_Obsolescence_vsFlex", [SSSO: Salvage & Obs F66_Final],
			
			        "SSSO_Scrap_vsPlan", [SSSO: Scrap-Off_APN],
			        "SSSO_Scrap_vsLYTD", [SSSO: Scrap-off LYTD],
			        "SSSO_Scrap_vsPP", [SSSO: Scrap-Off MoM%],
			        "SSSO_Scrap_vsYoY", [SSSO: Scrap-Off YoY%],
			        "SSSO_Scrap_vsFlex", [SSSO: Scrap-Off_F66],
			        
			        "DPO_vsPP", [DPO MoM%],
			        "DPO_vsYoY", [DPO YoY%],
			
			        "OEE_vsPlan", [OEE Target diff%],
			        "OEE_vsPP", [OEE% MoM%],
			        "OEE_vsYoY", [OEE% YoY%],
			        "OEE_vsLYTD", [OEE LYTD],
			
			        "COGS_vsPlan", [COGS_APN],
			        "COGS_vsPP", [COGS Actual MoM%],
			        "COGS_vsYoY", [COGS Actual YoY%],
			        "COGS_vsLYTD", [COGS Actual LYTD],
			
			        "Dist_to_COGS_vsPlan", [Total Distribution on COGS_APN],
			        "Dist_to_COGS_vsPP", [Total Distribution on COGS Actual MoM%],
			        "Dist_to_COGS_vsYoY", [Total Distribution on COGS Actual YoY%],
			        "Dist_to_COGS_vsLYTD", [Total Distribution on COGS LYTD],
			
			        "Log_to_Sales_vsPlan", [Total Logistics on Net Sales_APN],
			        "Log_to_Sales_vsPP", [Total Logistics on Net Sales Actual MoM%],
			        "Log_to_Sales_vsYoY", [Total Logistics on Net Sales Actual YoY%],
			        "Log_to_Sales_vsLYTD", [Total Logistics on Net Sales LYTD],
			
			        "Schedule_Attainment_vsPlan", [Schedule Attn Target Diff%],
			        "Schedule_Attainment_vsPP", [SA MoM%],
			        "Schedule_Attainment_vsYoY", [SA YoY%],
			        "Schedule_Attainment_vsLYTD", [Schedule Attn LYTD],
			
			        "On_Time_Deviation_vsPlan", [On Time Closure of Deviations Target Diff%],
			        "On_Time_Deviation_vsYoY", [On Time Closure of Deviations YoY%],
			        "On_Time_Deviation_vsLYTD", [On Time Closure of Deviations LYTD],
			        "On_Time_Deviation_vsPP", [On Time Closure of Deviations MoM%],
			
			        "CAPA_Completion_vsPlan", [CAPA Completion Rate Target Diff%],
			        "CAPA_Completion_vsPP", [CAPA Completion Rate MoM%],
			        "CAPA_Completion_vsYoY", [CAPA Completion Rate YoY%],
			        "CAPA_Completion_vsLYTD", [CAPA Closed LYTD],
			
			        "Right_First_Time_vsPlan", [RFT Target Diff%],
			        "Right_First_Time_vsPP", [RFT MoM%],
			        "Right_First_Time_vsYoY", [RFT YoY%],
			        "Right_First_Time_vsLYTD", [RFT LYTD],
			
			        "Critical/Major_vsPP", [Critical or Major Observations MoM%],
			        "Critical/Major_vsYoY", [Critical or Major Observations YoY%],
			        "Critical/Major_vsLYTD", [Critical or Major Observations LYTD],
			
			        "Net_Sales_vsPlan", [Net Sales_APN],
			        "Net_Sales_vsPP", [Net Sales Actual MoM%],
			        "Net_Sales_vsYoY", [Net Sales Actual YoY%],
			        "Net_Sales_vsLYTD", [Net Sales Actual LYTD],
			
			        "DSO_vsPP", [DSO MoM%],
			        "DSO_vsYoY", [DSO YoY%],
			
			        "Service_Level_Gap_vsPlan", [Service Target Diff%],
			        "Service_Level_Gap_vsPP", [Service Rate% MoM%],
			        "Service_Level_Gap_vsYoY", [Service Rate YoY%],
			        "Service_Level_Gap_vsLYTD", [Service Rate LYTD],
			
			        "Service_Level_Total_vsPlan", [Service Target Diff%_CSCI],
			        "Service_Level_Total_vsPP", [Service Level MoM%],
			        "Service_Level_Total_vsYoY", [Service Level YoY%],
			        "Service_Level_Total_vsLYTD", [Service Level LYTD],
			
			        "Customer_Fines_vsPlan", [Cust Fine Target Diff%],
			        "Customer_Fines_vsPP", [Cust Fine MoM%],
			        "Customer_Fines_vsYoY", [Cust fine YoY%],
			        "Customer_Fines_vsLYTD", [Cust Fine LYTD],
			
			        "Case_fill_rate_vsPlan", [CFR Target Diff%],
			        "Case_fill_rate_vsPP", [CFR MoM%],
			        "Case_fill_rate_vsYoY", [CFR YoY%],
			        "Case_fill_rate_vsLYTD", [CFR LYTD],
			
			        "ABP_Variances_vsPlan", [ABP Variance_APN],
			        "ABP_Variances_vsPP", [ABP Variance MoM%],
			        "ABP_Variances_vsYoY", [ABP Variance YoY%],
			        "ABP_Variances_vsLYTD", [ABP Variance LYTD],
			
			        "Net_POV_vsPlan", [Net POV_APN],
			        "Net_POV_vsPP", [Net POV Actual MoM%],
			        "Net_POV_vsYoY", [Net POV Actual YoY%],
			        "Net_POV_vsLYTD", [Net POV Actual LYTD],
			
			        "Gross_PPV_vsPlan", [Gross PPV_APN],
			        "Gross_PPV_vsPP", [Gross PPV Actual MoM%],
			        "Gross_PPV_vsYoY", [Gross PPV Actual YoY%],
			        "Gross_PPV_vsLYTD", [Gross PPV Actual LYTD],
			
			        "Operating_Income_vsPlan", [Operating Income_APN],
			        "Operating_Income_vsPP", [Operating Income Actual MoM%],
			        "Operating_Income_vsYoY", [Operating Income Actual YoY%],
			        "Operating_Income_vsLYTD", [Operating Income Actual LYTD],
			
			        BLANK()
			    )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, 1, 0 ),
			        IF ( _value < 0, 0, 1 )
			    )
			
			```
		formatString: 0
		lineageTag: be19d0b0-cf51-4fac-94ab-03e50a49644e

	measure 'Red Count (Last Closed)' = ```
			
			CALCULATE (
			    COUNTROWS ( KPI_Metadata ),
			    FILTER (
			        KPI_Metadata,
			        [KPI Status Numeric] = 0
			            && NOT ISBLANK ( [KPI Status Numeric] )
			    )
			)
			
			```
		formatString: 0
		lineageTag: ad666069-eafc-4514-a3f0-22ac58d64ae5

	measure 'Selected Metric' =
			
			SELECTEDVALUE(KPI_Metadata[Metrics])
		lineageTag: 0dcfdbc0-c2d0-429a-a583-a8e937ca7f1d

	measure 'KPI Status Icon (Sales Growth)' = ```
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "FA_Lag1_vsPlan", [FA Target L1 Diff raw],
			        "FA_Lag1_vsLYTD", [FA% LYTD CSCI],
			        "FA_Lag1_vsYoY", [FA% YoY L1 raw CSCI],
			        "FA_Lag1_vsPP", [FA% MoM L1 raw CSCI],
			
			        "FA_Lag2_vsPlan", [FA% Lag 2 Target Diff%],
			        "FA_Lag2_vsLYTD", CALCULATE([FA% CSCA LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2")),
			        "FA_Lag2_vsYoY", [FA% Lag2 YoY%],
			        "FA_Lag2_vsPP", [FA% Lag2 MoM%],
			
			        "FA_Lag4_CSCA_vsPlan", [FA% Lag 4 Target Diff%],
			        "FA_Lag4_CSCA_vsLYTD", CALCULATE([FA% CSCA LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        "FA_Lag4_CSCA_vsYoY", [FA% Lag4 YoY%],
			        "FA_Lag4_CSCA_vsPP", [FA% Lag4 MoM%],
			        "FA_Lag4_CSCI_vsPlan", [FA Target L4 Diff raw],
			        "FA_Lag4_CSCI_vsLYTD", [FA% LYTD CSCI],
			        "FA_Lag4_CSCI_vsYoY", [FA% YoY L4 raw CSCI],
			        "FA_Lag4_CSCI_vsPP", [FA% MoM CSCI L4],
			
			        "Bias_Lag1_vsPlan", [Bias Target Diff%_CSCI L1],
			        "Bias_Lag1_vsLYTD", CALCULATE([Bias % LYTD CSCI], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="1")),
			        "Bias_Lag1_vsYoY", [Bias YoY % L1 Raw CSCI],
			        "Bias_Lag1_vsPP", [Bias MoM%_raw L1 CSCI],
			        
			        "Bias_Lag2_vsPlan", [Bias Lag2 Target Diff%],
			        "Bias_Lag2_vsLYTD", CALCULATE([Bias% LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2")),
			        "Bias_Lag2_vsYoY", [Bias Lag2 YoY%],
			        "Bias_Lag2_vsPP", CALCULATE([Bias MoM%], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2")),
			
			        "Bias_Lag4_CSCA_vsPlan", [Bias Lag4 Target Diff%],
			        "Bias_Lag4_CSCA_vsLYTD", CALCULATE([Bias% LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        "Bias_Lag4_CSCA_vsYoY", [Bias Lag4 YoY%],
			        "Bias_Lag4_CSCA_vsPP", CALCULATE([Bias MoM%], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        "Bias_Lag4_CSCI_vsPlan", [Bias Target Diff%_CSCI L4],
			        "Bias_Lag4_CSCI_vsLYTD", CALCULATE([Bias % LYTD CSCI], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        "Bias_Lag4_CSCI_vsYoY", [Bias YoY % L4 Raw CSCI],
			        "Bias_Lag4_CSCI_vsPP", [Bias MoM%_raw L4 CSCI],
			
			        "Service_Top_11_vsPlan", [Service Top 11 Target Diff%],
			        "Service_Top_11_vsYoY", [Service Top 11 YoY%],
			        "Service_Top_11_vsLYTD", [Service Top 11 LYTD],
			        "Service_Top_11_vsPP", [Service Top 11 MoM%],
			        "Case_fill_rate_vsPlan", [CFR Target Diff%],
			
			        "Case_fill_rate_vsPP", [CFR MoM%],
			        "Case_fill_rate_vsYoY", [CFR YoY%],
			        "Case_fill_rate_vsLYTD", [CFR LYTD],
			
			        "Service_Level_Gap_vsPlan", [Service Target Diff%],
			        "Service_Level_Gap_vsPP", [Service Rate% MoM%],
			        "Service_Level_Gap_vsYoY", [Service Rate YoY%],
			        "Service_Level_Gap_vsLYTD", [Service Rate LYTD],
			
			        "Service_Level_Total_vsPlan", [Service Target Diff%_CSCI],
			        "Service_Level_Total_vsPP", [Service Level MoM%],
			        "Service_Level_Total_vsYoY", [Service Level YoY%],
			        "Service_Level_Total_vsLYTD", [Service Level LYTD],
			        BLANK()
			    )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, "游릭", "游댮" ),
			        IF ( _value < 0, "游댮", "游릭" )
			    )
			```
		lineageTag: b206bd87-be69-4542-b8bd-a539f8e7747d

	measure 'KPI Status Icon (Operations&Quality)' =
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "OEE_vsPlan", [OEE Target diff%],
			        "OEE_vsPP", [OEE% MoM%],
			        "OEE_vsYoY", [OEE% YoY%],
			        "OEE_vsLYTD", [OEE LYTD],
			
			        "Schedule_Attainment_vsPlan", [Schedule Attn Target Diff%],
			        "Schedule_Attainment_vsPP", [SA MoM%],
			        "Schedule_Attainment_vsYoY", [SA YoY%],
			        "Schedule_Attainment_vsLYTD", [Schedule Attn LYTD],
			
			        "On_Time_Deviation_vsPlan", [On Time Closure of Deviations Target Diff%],
			        "On_Time_Deviation_vsYoY", [On Time Closure of Deviations YoY%],
			        "On_Time_Deviation_vsLYTD", [On Time Closure of Deviations LYTD],
			        "On_Time_Deviation_vsPP", [On Time Closure of Deviations MoM%],
			
			        "CAPA_Completion_vsPlan", [CAPA Completion Rate Target Diff%],
			        "CAPA_Completion_vsPP", [CAPA Completion Rate MoM%],
			        "CAPA_Completion_vsYoY", [CAPA Completion Rate YoY%],
			        "CAPA_Completion_vsLYTD", [CAPA Closed LYTD],
			
			        "Right_First_Time_vsPlan", [RFT Target Diff%],
			        "Right_First_Time_vsPP", [RFT MoM%],
			        "Right_First_Time_vsYoY", [RFT YoY%],
			        "Right_First_Time_vsLYTD", [RFT LYTD],
			
			        "Critical/Major_vsPP", [Critical or Major Observations MoM%],
			        "Critical/Major_vsYoY", [Critical or Major Observations YoY%],
			        "Critical/Major_vsLYTD", [Critical or Major Observations LYTD],
			
			
			        BLANK()
			    )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, "游릭", "游댮" ),
			        IF ( _value < 0, "游댮", "游릭" )
			    )
		lineageTag: 4d1f87cd-4d92-4b56-9c53-254b724f1f1c

	measure 'KPI Status Icon (Working Capital)' =
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "Net_Inventory_vsPlan", [Net Inventory_APN],
			        "Net_Inventory_vsFlex", [Net Inventory_AFX],
			        "Net_Inventory_vsLYTD", [Net Inventory LYTD],
			        "Net_Inventory_vsPP", [Net Inventory MoM%],
			        "Net_Inventory_vsYoY", [Net Inventory YoY%],
			
			        "Gross_Inventory_vsPlan", [Gross Inventory_APN],
			        "Gross_Inventory_vsFlex", [Gross Inventory_AFX],
			        "Gross_Inventory_vsLYTD", [Gross Inv LYTD],
			        "Gross_Inventory_vsPP", [Gross Inventory MoM%],
			        "Gross_Inventory_vsYoY", [Gross Inventory YoY%],
			
			        "Expired_Inventory_vsPP", [Expired Inventory MoM%],
			        "Expired_Inventory_vsYoY", [Expired Inventory YoY%],
			        "Expired_Inventory_vsLYTD", [Expired Inventory LYTD],
			
			        "Inflated_Inventory_vsPP", [Inflated Inventory MoM%],
			        "Inflated_Inventory_vsYoY", [Inflated Inventory YoY%],
			        "Inflated_Inventory_vsLYTD", [Inflated Inv LYTD],
			
			        "DIO_vsPlan", [DIO_APN],
			        "DIO_vsPP", [DIO MoM%],
			        "DIO_vsFlex", [DIO_AFX],
			        "DIO_vsYoY", [DIO YoY%],
			
			        "DPO_vsPP", [DPO MoM%],
			        "DPO_vsYoY", [DPO YoY%],
			
			        "DSO_vsPP", [DSO MoM%],
			        "DSO_vsYoY", [DSO YoY%],
			
			        BLANK()
			    )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, "游릭", "游댮" ),
			        IF ( _value < 0, "游댮", "游릭" )
			    )
		lineageTag: 995204bd-ef24-4f64-8edb-f72456b8146a

	measure 'KPI Status Icon (Operating Income)' =
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "SSSO_Conversions_vsPlan", [SSSO: Obsolescenes linked to Conversions_APN],
			        "SSSO_Conversions_vsLYTD", [SSSO: Obs LYTD],
			        "SSSO_Conversions_vsPP", [SSSO: Obs linked to Conv MoM%],
			        "SSSO_Conversions_vsYoY", [SSSO: Obs linked to Conv YoY%],
			        "SSSO_Conversions_vsFlex", [SSSO: Obs linked to conv F66_Final],
			
			        "SSSO_Salvage_Obsolescence_vsPlan", [SSSO: Salvage & Obsolescence_APN],
			        "SSSO_Salvage_Obsolescence_vsLYTD", [SSSO: Salvage LYTD],
			        "SSSO_Salvage_Obsolescence_vsPP", [SSSO: Salvage & obs MoM%],
			        "SSSO_Salvage_Obsolescence_vsYoY", [SSSO: Salvage YoY%],
			        "SSSO_Salvage_Obsolescence_vsFlex", [SSSO: Salvage & Obs F66_Final],
			
			        "SSSO_Scrap_vsPlan", [SSSO: Scrap-Off_APN],
			        "SSSO_Scrap_vsLYTD", [SSSO: Scrap-off LYTD],
			        "SSSO_Scrap_vsPP", [SSSO: Scrap-Off MoM%],
			        "SSSO_Scrap_vsYoY", [SSSO: Scrap-Off YoY%],
			        "SSSO_Scrap_vsFlex", [SSSO: Scrap-Off_F66],
			
			        "SSSO_Shrinkage_vsPlan", [SSSO: Shrinkage_APN],
			        "SSSO_Shrinkage_vsLYTD", [SSSO: Shrinkage LYTD],
			        "SSSO_Shrinkage_vsPP", [SSSO: Shrinkage MoM%],
			        "SSSO_Shrinkage_vsYoY", [SSSO: Shrinkage YoY%],
			        "SSSO_Shrinkage_vsFlex", [SSSO: Shrinkage_F66],
			
			        "Net_Sales_vsPlan", [Net Sales_APN],
			        "Net_Sales_vsPP", [Net Sales Actual MoM%],
			        "Net_Sales_vsYoY", [Net Sales Actual YoY%],
			        "Net_Sales_vsLYTD", [Net Sales Actual LYTD],
			
			        "COGS_vsPlan", [COGS_APN],
			        "COGS_vsPP", [COGS Actual MoM%],
			        "COGS_vsYoY", [COGS Actual YoY%],
			        "COGS_vsLYTD", [COGS Actual LYTD],
			
			        "Log_to_Sales_vsPlan", [Total Logistics on Net Sales_APN],
			        "Log_to_Sales_vsPP", [Total Logistics on Net Sales Actual MoM%],
			        "Log_to_Sales_vsYoY", [Total Logistics on Net Sales Actual YoY%],
			        "Log_to_Sales_vsLYTD", [Total Logistics on Net Sales LYTD],
			
			        "Dist_to_COGS_vsPlan", [Total Distribution on COGS_APN],
			        "Dist_to_COGS_vsPP", [Total Distribution on COGS Actual MoM%],
			        "Dist_to_COGS_vsYoY", [Total Distribution on COGS Actual YoY%],
			        "Dist_to_COGS_vsLYTD", [Total Distribution on COGS LYTD],
			
			        "Net_POV_vsPlan", [Net POV_APN],
			        "Net_POV_vsPP", [Net POV Actual MoM%],
			        "Net_POV_vsYoY", [Net POV Actual YoY%],
			        "Net_POV_vsLYTD", [Net POV Actual LYTD],
			
			        "Gross_PPV_vsPlan", [Gross PPV_APN],
			        "Gross_PPV_vsPP", [Gross PPV Actual MoM%],
			        "Gross_PPV_vsYoY", [Gross PPV Actual YoY%],
			        "Gross_PPV_vsLYTD", [Gross PPV Actual LYTD],
			
			        "Operating_Income_vsPlan", [Operating Income_APN],
			        "Operating_Income_vsPP", [Operating Income Actual MoM%],
			        "Operating_Income_vsYoY", [Operating Income Actual YoY%],
			        "Operating_Income_vsLYTD", [Operating Income Actual LYTD],
			
			        "ABP_Variances_vsPlan", [ABP Variance_APN],
			        "ABP_Variances_vsPP", [ABP Variance MoM%],
			        "ABP_Variances_vsYoY", [ABP Variance YoY%],
			        "ABP_Variances_vsLYTD", [ABP Variance LYTD],
			
			        "Customer_Fines_vsPlan", [Cust Fine Target Diff%],
			        "Customer_Fines_vsPP", [Cust Fine MoM%],
			        "Customer_Fines_vsYoY", [Cust fine YoY%],
			        "Customer_Fines_vsLYTD", [Cust Fine LYTD],
			
			        BLANK()
			    )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, "游릭", "游댮" ),
			        IF ( _value < 0, "游댮", "游릭" )
			    )
		lineageTag: 3c43eba9-48bb-4ce1-9c55-2f528ebaecca

	measure 'Green Count (Sales Growth)' = ```
			
			CALCULATE (
			    COUNTROWS ( KPI_Metadata ),
			    FILTER (
			        KPI_Metadata,
			        [KPI Status Numeric] = "游릭"
			            && NOT ISBLANK ( [KPI Status Numeric] )
			    )
			)
			
			```
		formatString: 0
		lineageTag: ed8ace2f-d3df-4fb2-a07c-2402c9e0075b

	column Metrics
		lineageTag: fb6eb0f0-7794-44a9-b2f4-eebff3e474bc
		summarizeBy: none
		isNameInferred
		sourceColumn: [Metrics]

		annotation SummarizationSetBy = Automatic

	column KPI
		lineageTag: 2c6f3509-5157-48a3-8668-d748688c4f3c
		summarizeBy: none
		isNameInferred
		sourceColumn: [KPI]

		annotation SummarizationSetBy = Automatic

	column KPI_ID
		lineageTag: 62a8849f-7698-47cb-a697-88f33f0377de
		summarizeBy: none
		isNameInferred
		sourceColumn: [KPI_ID]

		annotation SummarizationSetBy = Automatic

	column Comparison
		lineageTag: cd5f1077-c382-429b-9532-b86fff10437e
		summarizeBy: none
		isNameInferred
		sourceColumn: [Comparison]

		annotation SummarizationSetBy = Automatic

	column Area
		lineageTag: 92ccf43c-a77e-4027-bfea-d3e5fcc25de3
		summarizeBy: none
		isNameInferred
		sourceColumn: [Area]

		annotation SummarizationSetBy = Automatic

	column SignRule_YTD
		lineageTag: 39da4d8a-9ae5-48a5-936c-effe64849f41
		summarizeBy: none
		isNameInferred
		sourceColumn: [SignRule_YTD]

		annotation SummarizationSetBy = Automatic

	column SignRule_PTD
		lineageTag: 62955e86-0207-4e20-8544-579eed190c56
		summarizeBy: none
		isNameInferred
		sourceColumn: [SignRule_PTD]

		annotation SummarizationSetBy = Automatic

	partition KPI_Metadata = calculated
		mode: import
		source = ```
				
				DATATABLE(
				    "Metrics", STRING,
				    "KPI", STRING,
				    "KPI_ID", STRING,
				    "Comparison", STRING,
				    "Area", STRING,
				    "SignRule_YTD", STRING,
				    "SignRule_PTD", STRING,
				    {
				        {"Demand", "FA Lag 1 (%)", "FA_Lag1_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        {"Demand", "FA Lag 1 (%)", "FA_Lag1_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				        {"Demand", "FA Lag 1 (%)", "FA_Lag1_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        {"Demand", "FA Lag 1 (%)", "FA_Lag1_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        {"Demand", "FA Lag 1 (%)", "FA_Lag1_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				
				        {"Demand", "FA Lag 2 (%)", "FA_Lag2_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        {"Demand", "FA Lag 2 (%)", "FA_Lag2_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				        {"Demand", "FA Lag 2 (%)", "FA_Lag2_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Demand", "FA Lag 2 (%)", "FA_Lag2_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        {"Demand", "FA Lag 2 (%)", "FA_Lag2_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				
				        {"Demand", "FA Lag 4 (%)", "FA_Lag4_CSCA_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        {"Demand", "FA Lag 4 (%)", "FA_Lag4_CSCA_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				        {"Demand", "FA Lag 4 (%)", "FA_Lag4_CSCA_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Demand", "FA Lag 4 (%)", "FA_Lag4_CSCA_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        {"Demand", "FA Lag 4 (%)", "FA_Lag4_CSCA_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        {"Demand", "FA Lag 4 (%)", "FA_Lag4_CSCI_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        {"Demand", "FA Lag 4 (%)", "FA_Lag4_CSCI_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				        {"Demand", "FA Lag 4 (%)", "FA_Lag4_CSCI_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        {"Demand", "FA Lag 4 (%)", "FA_Lag4_CSCI_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        {"Demand", "FA Lag 4 (%)", "FA_Lag4_CSCI_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				
				        {"Demand", "Bias (%) Lag 1", "Bias_Lag1_vsPlan", "vs Plan","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Demand", "Bias (%) Lag 1", "Bias_Lag1_vsLYTD", "LYTD","CSCI","GoodIfNeg","BadIfNeg"},
				        {"Demand", "Bias (%) Lag 1", "Bias_Lag1_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        {"Demand", "Bias (%) Lag 1", "Bias_Lag1_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        {"Demand", "Bias (%) Lag 1", "Bias_Lag1_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				
				        {"Demand", "Bias (%) Lag 2", "Bias_Lag2_vsPlan", "vs Plan","CSCA","GoodIfNeg","BadIfNeg"},
				        {"Demand", "Bias (%) Lag 2", "Bias_Lag2_vsLYTD", "LYTD","CSCA","GoodIfNeg","BadIfNeg"},
				        {"Demand", "Bias (%) Lag 2", "Bias_Lag2_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Demand", "Bias (%) Lag 2", "Bias_Lag2_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        {"Demand", "Bias (%) Lag 2", "Bias_Lag2_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				
				        {"Demand", "Bias (%) Lag 4", "Bias_Lag4_CSCA_vsPlan", "vs Plan","CSCA","GoodIfNeg","BadIfNeg"},
				        {"Demand", "Bias (%) Lag 4", "Bias_Lag4_CSCA_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				        {"Demand", "Bias (%) Lag 4", "Bias_Lag4_CSCA_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Demand", "Bias (%) Lag 4", "Bias_Lag4_CSCA_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        {"Demand", "Bias (%) Lag 4", "Bias_Lag4_CSCA_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        {"Demand", "Bias (%) Lag 4", "Bias_Lag4_CSCI_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        {"Demand", "Bias (%) Lag 4", "Bias_Lag4_CSCI_vsLYTD", "LYTD","CSCI","GoodIfNeg","BadIfNeg"},
				        {"Demand", "Bias (%) Lag 4", "Bias_Lag4_CSCI_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        {"Demand", "Bias (%) Lag 4", "Bias_Lag4_CSCI_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        {"Demand", "Bias (%) Lag 4", "Bias_Lag4_CSCI_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				
				        {"Supply", "Supplier OTIF Inbound (%)", "Supplier_OTIF_Inbound_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        {"Supply", "Supplier OTIF Inbound (%)", "Supplier_OTIF_Inbound_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				        {"Supply", "Supplier OTIF Inbound (%)", "Supplier_OTIF_Inbound_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        {"Supply", "Supplier OTIF Inbound (%)", "Supplier_OTIF_Inbound_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Supply", "Supplier OTIF Inbound (%)", "Supplier_OTIF_Inbound_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				
				        {"Supply", "Supplier OTIF Inbound (%)", "Supplier_OTIF_Inbound_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        {"Supply", "Supplier OTIF Inbound (%)", "Supplier_OTIF_Inbound_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				        {"Supply", "Supplier OTIF Inbound (%)", "Supplier_OTIF_Inbound_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        {"Supply", "Supplier OTIF Inbound (%)", "Supplier_OTIF_Inbound_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        {"Supply", "Supplier OTIF Inbound (%)", "Supplier_OTIF_Inbound_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				
				        {"Supply", "Supplier OTIF Outbound (%)", "Supplier_OTIF_Outbound_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        {"Supply", "Supplier OTIF Outbound (%)", "Supplier_OTIF_Outbound_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				        {"Supply", "Supplier OTIF Outbound (%)", "Supplier_OTIF_Outbound_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        {"Supply", "Supplier OTIF Outbound (%)", "Supplier_OTIF_Outbound_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Supply", "Supplier OTIF Outbound (%)", "Supplier_OTIF_Outbound_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        
				        {"Supply", "Supplier OTIF Outbound (%)", "Supplier_OTIF_Outbound_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        {"Supply", "Supplier OTIF Outbound (%)", "Supplier_OTIF_Outbound_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				        {"Supply", "Supplier OTIF Outbound (%)", "Supplier_OTIF_Outbound_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        {"Supply", "Supplier OTIF Outbound (%)", "Supplier_OTIF_Outbound_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        {"Supply", "Supplier OTIF Outbound (%)", "Supplier_OTIF_Outbound_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				
				        {"Inventory", "Net Inventory ($)", "Net_Inventory_vsPlan", "vs Plan","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "Net Inventory ($)", "Net_Inventory_vsLYTD", "LYTD","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "Net Inventory ($)", "Net_Inventory_vsFlex", "vs Flex","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "Net Inventory ($)", "Net_Inventory_vsPP", "vs PP","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "Net Inventory ($)", "Net_Inventory_vsYoY", "vs YoY","CSCA","GoodIfNeg","GoodIfNeg"},
				
				        {"Inventory", "Net Inventory ($)", "Net_Inventory_vsPlan", "vs Plan","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "Net Inventory ($)", "Net_Inventory_vsLYTD", "LYTD","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "Net Inventory ($)", "Net_Inventory_vsFlex", "vs Flex","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "Net Inventory ($)", "Net_Inventory_vsPP", "vs PP","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "Net Inventory ($)", "Net_Inventory_vsYoY", "vs YoY","CSCI","GoodIfNeg","GoodIfNeg"},
				
				        {"Inventory", "Gross Inventory ($)", "Gross_Inventory_vsPlan", "vs Plan","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "Gross Inventory ($)", "Gross_Inventory_vsFlex", "vs Flex","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "Gross Inventory ($)", "Gross_Inventory_vsLYTD", "LYTD","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "Gross Inventory ($)", "Gross_Inventory_vsPP", "vs PP","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "Gross Inventory ($)", "Gross_Inventory_vsYoY", "vs YoY","CSCA","GoodIfNeg","GoodIfNeg"},
				
				        {"Inventory", "Gross Inventory ($)", "Gross_Inventory_vsPlan", "vs Plan","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "Gross Inventory ($)", "Gross_Inventory_vsFlex", "vs Flex","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "Gross Inventory ($)", "Gross_Inventory_vsLYTD", "LYTD","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "Gross Inventory ($)", "Gross_Inventory_vsPP", "vs PP","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "Gross Inventory ($)", "Gross_Inventory_vsYoY", "vs YoY","CSCI","GoodIfNeg","GoodIfNeg"},
				
				        {"Inventory", "Expired Inventory ($)", "Expired_Inventory_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        {"Inventory", "Expired Inventory ($)", "Expired_Inventory_vsPP", "vs PP","CSCA","BadIfNeg","GoodIfNeg"},
				        {"Inventory", "Expired Inventory ($)", "Expired_Inventory_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        {"Inventory", "Expired Inventory ($)", "Expired_Inventory_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Inventory", "Expired Inventory ($)", "Expired_Inventory_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        {"Inventory", "Expired Inventory ($)", "Expired_Inventory_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        {"Inventory", "Expired Inventory ($)", "Expired_Inventory_vsPP", "vs PP","CSCI","BadIfNeg","GoodIfNeg"},
				        {"Inventory", "Expired Inventory ($)", "Expired_Inventory_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				        {"Inventory", "Expired Inventory ($)", "Expired_Inventory_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        {"Inventory", "Expired Inventory ($)", "Expired_Inventory_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				
				        {"Inventory", "Inflated Inventory ($)", "Inflated_Inventory_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        {"Inventory", "Inflated Inventory ($)", "Inflated_Inventory_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        {"Inventory", "Inflated Inventory ($)", "Inflated_Inventory_vsPP", "vs PP","CSCA","BadIfNeg","GoodIfNeg"},
				        {"Inventory", "Inflated Inventory ($)", "Inflated_Inventory_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Inventory", "Inflated Inventory ($)", "Inflated_Inventory_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				        
				        {"Inventory", "Inflated Inventory ($)", "Inflated_Inventory_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        {"Inventory", "Inflated Inventory ($)", "Inflated_Inventory_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				        {"Inventory", "Inflated Inventory ($)", "Inflated_Inventory_vsPP", "vs PP","CSCI","BadIfNeg","GoodIfNeg"},
				        {"Inventory", "Inflated Inventory ($)", "Inflated_Inventory_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        {"Inventory", "Inflated Inventory ($)", "Inflated_Inventory_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				
				        {"Inventory", "DIO (days)", "DIO_vsPlan", "vs Plan","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "DIO (days)", "DIO_vsPP", "vs PP","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "DIO (days)", "DIO_vsFlex", "vs Flex","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "DIO (days)", "DIO_vsYoY", "vs YoY","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "DIO (days)", "DIO_vsLYTD", "LYTD","CSCA","GoodIfNeg","GoodIfNeg"},
				
				        {"Inventory", "DIO (days)", "DIO_vsPlan", "vs Plan","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "DIO (days)", "DIO_vsPP", "vs PP","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "DIO (days)", "DIO_vsFlex", "vs Flex","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "DIO (days)", "DIO_vsYoY", "vs YoY","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "DIO (days)", "DIO_vsLYTD", "LYTD","CSCI","GoodIfNeg","GoodIfNeg"},
				
				        {"Inventory", "SSSO: Conversions", "SSSO_Conversions_vsPlan", "vs Plan","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Conversions", "SSSO_Conversions_vsLYTD", "LYTD","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Conversions", "SSSO_Conversions_vsPP", "vs PP","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Conversions", "SSSO_Conversions_vsYoY", "vs YoY","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Conversions", "SSSO_Conversions_vsFlex", "vs Flex","CSCA","GoodIfNeg","GoodIfNeg"},
				
				        {"Inventory", "SSSO: Shrinkage", "SSSO_Shrinkage_vsPlan", "vs Plan","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Shrinkage", "SSSO_Shrinkage_vsLYTD", "LYTD","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Shrinkage", "SSSO_Shrinkage_vsPP", "vs PP","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Shrinkage", "SSSO_Shrinkage_vsYoY", "vs YoY","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Shrinkage", "SSSO_Shrinkage_vsFlex", "vs Flex","CSCI","GoodIfNeg","GoodIfNeg"},
				
				        {"Inventory", "SSSO: Salvage & Obs", "SSSO_Salvage_Obsolescence_vsPlan", "vs Plan","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Salvage & Obs", "SSSO_Salvage_Obsolescence_vsLYTD", "LYTD","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Salvage & Obs", "SSSO_Salvage_Obsolescence_vsPP", "vs PP","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Salvage & Obs", "SSSO_Salvage_Obsolescence_vsYoY", "vs YoY","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Salvage & Obs", "SSSO_Salvage_Obsolescence_vsFlex", "vs Flex","CSCA","GoodIfNeg","GoodIfNeg"},
				
				        {"Inventory", "SSSO: Salvage & Obs", "SSSO_Salvage_Obsolescence_vsPlan", "vs Plan","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Salvage & Obs", "SSSO_Salvage_Obsolescence_vsLYTD", "LYTD","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Salvage & Obs", "SSSO_Salvage_Obsolescence_vsPP", "vs PP","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Salvage & Obs", "SSSO_Salvage_Obsolescence_vsYoY", "vs YoY","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Salvage & Obs", "SSSO_Salvage_Obsolescence_vsFlex", "vs Flex","CSCI","GoodIfNeg","GoodIfNeg"},
				
				        {"Inventory", "SSSO: Scrap", "SSSO_Scrap_vsPlan", "vs Plan","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Scrap", "SSSO_Scrap_vsLYTD", "LYTD","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Scrap", "SSSO_Scrap_vsPP", "vs PP","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Scrap", "SSSO_Scrap_vsYoY", "vs YoY","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Scrap", "SSSO_Scrap_vsFlex", "vs Flex","CSCA","GoodIfNeg","GoodIfNeg"},
				
				        {"Inventory", "SSSO: Scrap", "SSSO_Scrap_vsPlan", "vs Plan","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Scrap", "SSSO_Scrap_vsLYTD", "LYTD","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Scrap", "SSSO_Scrap_vsPP", "vs PP","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Scrap", "SSSO_Scrap_vsYoY", "vs YoY","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Inventory", "SSSO: Scrap", "SSSO_Scrap_vsFlex", "vs Flex","CSCI","GoodIfNeg","GoodIfNeg"},
				
				        {"Procurement", "Gross PPV ($)", "Gross_PPV_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        {"Procurement", "Gross PPV ($)", "Gross_PPV_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        {"Procurement", "Gross PPV ($)", "Gross_PPV_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        {"Procurement", "Gross PPV ($)", "Gross_PPV_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Procurement", "Gross PPV ($)", "Gross_PPV_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        {"Procurement", "Gross PPV ($)", "Gross_PPV_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        {"Procurement", "Gross PPV ($)", "Gross_PPV_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        {"Procurement", "Gross PPV ($)", "Gross_PPV_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				        {"Procurement", "Gross PPV ($)", "Gross_PPV_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        {"Procurement", "Gross PPV ($)", "Gross_PPV_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				
				        {"Procurement", "DPO (days)", "DPO_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        {"Procurement", "DPO (days)", "DPO_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        {"Procurement", "DPO (days)", "DPO_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Procurement", "DPO (days)", "DPO_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        {"Procurement", "DPO (days)", "DPO_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        {"Procurement", "DPO (days)", "DPO_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        {"Procurement", "DPO (days)", "DPO_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        {"Procurement", "DPO (days)", "DPO_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        {"Procurement", "DPO (days)", "DPO_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				        {"Procurement", "DPO (days)", "DPO_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				
				        {"Manufacturing", "On Time Closure of Deviations (%)", "On_Time_Deviation_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "On Time Closure of Deviations (%)", "On_Time_Deviation_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "On Time Closure of Deviations (%)", "On_Time_Deviation_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "On Time Closure of Deviations (%)", "On_Time_Deviation_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "On Time Closure of Deviations (%)", "On_Time_Deviation_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        {"Manufacturing", "On Time Closure of Deviations (%)", "On_Time_Deviation_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "On Time Closure of Deviations (%)", "On_Time_Deviation_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "On Time Closure of Deviations (%)", "On_Time_Deviation_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "On Time Closure of Deviations (%)", "On_Time_Deviation_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "On Time Closure of Deviations (%)", "On_Time_Deviation_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				
				        {"Manufacturing", "CAPA Completion Rate (%)", "CAPA_Completion_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "CAPA Completion Rate (%)", "CAPA_Completion_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "CAPA Completion Rate (%)", "CAPA_Completion_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "CAPA Completion Rate (%)", "CAPA_Completion_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "CAPA Completion Rate (%)", "CAPA_Completion_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        {"Manufacturing", "CAPA Completion Rate (%)", "CAPA_Completion_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "CAPA Completion Rate (%)", "CAPA_Completion_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "CAPA Completion Rate (%)", "CAPA_Completion_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "CAPA Completion Rate (%)", "CAPA_Completion_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "CAPA Completion Rate (%)", "CAPA_Completion_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},   
				
				        {"Manufacturing", "Right First Time (%)", "Right_First_Time_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "Right First Time (%)", "Right_First_Time_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "Right First Time (%)", "Right_First_Time_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "Right First Time (%)", "Right_First_Time_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "Right First Time (%)", "Right_First_Time_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        {"Manufacturing", "Right First Time (%)", "Right_First_Time_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "Right First Time (%)", "Right_First_Time_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "Right First Time (%)", "Right_First_Time_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "Right First Time (%)", "Right_First_Time_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "Right First Time (%)", "Right_First_Time_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				        
				        {"Manufacturing", "Critical/Major Observations", "Critical/Major_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "Critical/Major Observations", "Critical/Major_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "Critical/Major Observations", "Critical/Major_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "Critical/Major Observations", "Critical/Major_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "Critical/Major Observations", "Critical/Major_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        {"Manufacturing", "Critical/Major Observations", "Critical/Major_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "Critical/Major Observations", "Critical/Major_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "Critical/Major Observations", "Critical/Major_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "Critical/Major Observations", "Critical/Major_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "Critical/Major Observations", "Critical/Major_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				
				        {"Manufacturing", "OEE (%)", "OEE_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "OEE (%)", "OEE_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "OEE (%)", "OEE_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "OEE (%)", "OEE_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "OEE (%)", "OEE_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        {"Manufacturing", "OEE (%)", "OEE_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "OEE (%)", "OEE_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "OEE (%)", "OEE_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "OEE (%)", "OEE_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "OEE (%)", "OEE_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				
				        {"Manufacturing", "COGS ($)", "COGS_vsPlan", "vs Plan","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Manufacturing", "COGS ($)", "COGS_vsPP", "vs PP","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Manufacturing", "COGS ($)", "COGS_vsYoY", "vs YoY","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Manufacturing", "COGS ($)", "COGS_vsFlex", "vs Flex","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Manufacturing", "COGS ($)", "COGS_vsLYTD", "LYTD","CSCA","GoodIfNeg","GoodIfNeg"},
				
				        {"Manufacturing", "COGS ($)", "COGS_vsPlan", "vs Plan","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Manufacturing", "COGS ($)", "COGS_vsPP", "vs PP","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Manufacturing", "COGS ($)", "COGS_vsYoY", "vs YoY","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Manufacturing", "COGS ($)", "COGS_vsFlex", "vs Flex","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Manufacturing", "COGS ($)", "COGS_vsLYTD", "LYTD","CSCI","GoodIfNeg","GoodIfNeg"},
				
				        {"Manufacturing", "ABP Variances (%)", "ABP_Variances_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "ABP Variances (%)", "ABP_Variances_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "ABP Variances (%)", "ABP_Variances_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "ABP Variances (%)", "ABP_Variances_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "ABP Variances (%)", "ABP_Variances_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        {"Manufacturing", "ABP Variances (%)", "ABP_Variances_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "ABP Variances (%)", "ABP_Variances_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "ABP Variances (%)", "ABP_Variances_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "ABP Variances (%)", "ABP_Variances_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				        {"Manufacturing", "ABP Variances (%)", "ABP_Variances_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				
				        {"Manufacturing", "Net POV (#)", "Net_POV_vsPlan", "vs Plan","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Manufacturing", "Net POV (#)", "Net_POV_vsPP", "vs PP","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Manufacturing", "Net POV (#)", "Net_POV_vsYoY", "vs YoY","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Manufacturing", "Net POV (#)", "Net_POV_vsFlex", "vs Flex","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Manufacturing", "Net POV (#)", "Net_POV_vsLYTD", "LYTD","CSCA","GoodIfNeg","GoodIfNeg"},
				
				        {"Manufacturing", "Net POV (#)", "Net_POV_vsPlan", "vs Plan","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Manufacturing", "Net POV (#)", "Net_POV_vsPP", "vs PP","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Manufacturing", "Net POV (#)", "Net_POV_vsYoY", "vs YoY","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Manufacturing", "Net POV (#)", "Net_POV_vsFlex", "vs Flex","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Manufacturing", "Net POV (#)", "Net_POV_vsLYTD", "LYTD","CSCI","GoodIfNeg","GoodIfNeg"},
				
				        {"Logistics & Distribution", "Distribution to COGS (%)", "Dist_to_COGS_vsPlan", "vs Plan","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Logistics & Distribution", "Distribution to COGS (%)", "Dist_to_COGS_vsPP", "vs PP","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Logistics & Distribution", "Distribution to COGS (%)", "Dist_to_COGS_vsYoY", "vs YoY","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Logistics & Distribution", "Distribution to COGS (%)", "Dist_to_COGS_vsFlex", "vs Flex","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Logistics & Distribution", "Distribution to COGS (%)", "Dist_to_COGS_vsLYTD", "LYTD","CSCA","GoodIfNeg","GoodIfNeg"},
				
				        {"Logistics & Distribution", "Distribution to COGS (%)", "Dist_to_COGS_vsPlan", "vs Plan","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Logistics & Distribution", "Distribution to COGS (%)", "Dist_to_COGS_vsPP", "vs PP","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Logistics & Distribution", "Distribution to COGS (%)", "Dist_to_COGS_vsYoY", "vs YoY","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Logistics & Distribution", "Distribution to COGS (%)", "Dist_to_COGS_vsFlex", "vs Flex","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Logistics & Distribution", "Distribution to COGS (%)", "Dist_to_COGS_vsLYTD", "LYTD","CSCI","GoodIfNeg","GoodIfNeg"},
				
				        {"Logistics & Distribution", "Logistics to Net Sales(%)", "Log_to_Sales_vsPlan", "vs Plan","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Logistics & Distribution", "Logistics to Net Sales(%)", "Log_to_Sales_vsPP", "vs PP","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Logistics & Distribution", "Logistics to Net Sales(%)", "Log_to_Sales_vsYoY", "vs YoY","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Logistics & Distribution", "Logistics to Net Sales(%)", "Log_to_Sales_vsFlex", "vs Flex","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Logistics & Distribution", "Logistics to Net Sales(%)", "Log_to_Sales_vsLYTD", "LYTD","CSCA","GoodIfNeg","GoodIfNeg"},
				
				        {"Logistics & Distribution", "Logistics to Net Sales(%)", "Log_to_Sales_vsPlan", "vs Plan","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Logistics & Distribution", "Logistics to Net Sales(%)", "Log_to_Sales_vsPP", "vs PP","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Logistics & Distribution", "Logistics to Net Sales(%)", "Log_to_Sales_vsYoY", "vs YoY","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Logistics & Distribution", "Logistics to Net Sales(%)", "Log_to_Sales_vsFlex", "vs Flex","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Logistics & Distribution", "Logistics to Net Sales(%)", "Log_to_Sales_vsLYTD", "LYTD","CSCI","GoodIfNeg","GoodIfNeg"},
				
				        {"Logistics & Distribution", "Schedule Attainment (%)", "Schedule_Attainment_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        {"Logistics & Distribution", "Schedule Attainment (%)", "Schedule_Attainment_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        {"Logistics & Distribution", "Schedule Attainment (%)", "Schedule_Attainment_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Logistics & Distribution", "Schedule Attainment (%)", "Schedule_Attainment_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        {"Logistics & Distribution", "Schedule Attainment (%)", "Schedule_Attainment_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        {"Logistics & Distribution", "Schedule Attainment (%)", "Schedule_Attainment_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        {"Logistics & Distribution", "Schedule Attainment (%)", "Schedule_Attainment_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        {"Logistics & Distribution", "Schedule Attainment (%)", "Schedule_Attainment_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        {"Logistics & Distribution", "Schedule Attainment (%)", "Schedule_Attainment_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				        {"Logistics & Distribution", "Schedule Attainment (%)", "Schedule_Attainment_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				
				        {"Fulfillment", "Net Sales ($)", "Net_Sales_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        {"Fulfillment", "Net Sales ($)", "Net_Sales_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        {"Fulfillment", "Net Sales ($)", "Net_Sales_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Fulfillment", "Net Sales ($)", "Net_Sales_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        {"Fulfillment", "Net Sales ($)", "Net_Sales_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        {"Fulfillment", "Net Sales ($)", "Net_Sales_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        {"Fulfillment", "Net Sales ($)", "Net_Sales_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        {"Fulfillment", "Net Sales ($)", "Net_Sales_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        {"Fulfillment", "Net Sales ($)", "Net_Sales_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				        {"Fulfillment", "Net Sales ($)", "Net_Sales_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				
				        {"Fulfillment", "DSO (days)", "DSO_vsPlan", "vs Plan","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Fulfillment", "DSO (days)", "DSO_vsPP", "vs PP","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Fulfillment", "DSO (days)", "DSO_vsYoY", "vs YoY","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Fulfillment", "DSO (days)", "DSO_vsFlex", "vs Flex","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Fulfillment", "DSO (days)", "DSO_vsLYTD", "LYTD","CSCA","GoodIfNeg","GoodIfNeg"},
				
				        {"Fulfillment", "DSO (days)", "DSO_vsPlan", "vs Plan","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Fulfillment", "DSO (days)", "DSO_vsPP", "vs PP","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Fulfillment", "DSO (days)", "DSO_vsYoY", "vs YoY","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Fulfillment", "DSO (days)", "DSO_vsFlex", "vs Flex","CSCI","GoodIfNeg","GoodIfNeg"},
				        {"Fulfillment", "DSO (days)", "DSO_vsLYTD", "LYTD","CSCI","GoodIfNeg","GoodIfNeg"},
				        // {"Fulfillment", "Sales Growth (%)", "Sales_Growth", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        // {"Fulfillment", "Logistics to Net Sales (%)", "Log_to_Sales_Fulfillment", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        // {"Fulfillment", "Schedule Attainment (%)", "Schedule_Attainment_Fulfillment", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				
				        {"Customer Service", "Service Level - Incl. Gap Orders (%)", "Service_Level_Gap_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        {"Customer Service", "Service Level - Incl. Gap Orders (%)", "Service_Level_Gap_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        {"Customer Service", "Service Level - Incl. Gap Orders (%)", "Service_Level_Gap_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Customer Service", "Service Level - Incl. Gap Orders (%)", "Service_Level_Gap_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        {"Customer Service", "Service Level - Incl. Gap Orders (%)", "Service_Level_Gap_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        {"Customer Service", "Total Service Level (%)", "Service_Level_Total_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        {"Customer Service", "Total Service Level (%)", "Service_Level_Total_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        {"Customer Service", "Total Service Level (%)", "Service_Level_Total_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        {"Customer Service", "Total Service Level (%)", "Service_Level_Total_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				        {"Customer Service", "Total Service Level (%)", "Service_Level_Total_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				
				        {"Customer Service", "Customer Fines ($)", "Customer_Fines_vsPlan", "vs Plan","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Customer Service", "Customer Fines ($)", "Customer_Fines_vsPP", "vs PP","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Customer Service", "Customer Fines ($)", "Customer_Fines_vsYoY", "vs YoY","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Customer Service", "Customer Fines ($)", "Customer_Fines_vsFlex", "vs Flex","CSCA","GoodIfNeg","GoodIfNeg"},
				        {"Customer Service", "Customer Fines ($)", "Customer_Fines_vsLYTD", "LYTD","CSCA","GoodIfNeg","GoodIfNeg"},
				
				        {"Customer Service", "Case Fill Rate %", "Case_fill_rate_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        {"Customer Service", "Case Fill Rate %", "Case_fill_rate_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        {"Customer Service", "Case Fill Rate %", "Case_fill_rate_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Customer Service", "Case Fill Rate %", "Case_fill_rate_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        {"Customer Service", "Case Fill Rate %", "Case_fill_rate_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        {"Customer Service", "Service Top 11", "Service_Top_11_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        {"Customer Service", "Service Top 11", "Service_Top_11_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        {"Customer Service", "Service Top 11", "Service_Top_11_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Customer Service", "Service Top 11", "Service_Top_11_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        // {"EHS / ESG", "ASTM - No. of Incidents (#)", "ASTM_Incidents_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "ASTM - No. of Incidents (#)", "ASTM_Incidents_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "ASTM - No. of Incidents (#)", "ASTM_Incidents_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "ASTM - No. of Incidents (#)", "ASTM_Incidents_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "ASTM - No. of Incidents (#)", "ASTM_Incidents_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        // {"EHS / ESG", "ASTM - No. of Incidents (#)", "ASTM_Incidents_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "ASTM - No. of Incidents (#)", "ASTM_Incidents_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "ASTM - No. of Incidents (#)", "ASTM_Incidents_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "ASTM - No. of Incidents (#)", "ASTM_Incidents_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "ASTM - No. of Incidents (#)", "ASTM_Incidents_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				
				
				        // {"EHS / ESG", "ASTM - Rate of Incidents (%)", "ASTM_Incident_Rate_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "ASTM - Rate of Incidents (%)", "ASTM_Incident_Rate_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "ASTM - Rate of Incidents (%)", "ASTM_Incident_Rate_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "ASTM - Rate of Incidents (%)", "ASTM_Incident_Rate_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "ASTM - Rate of Incidents (%)", "ASTM_Incident_Rate_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        // {"EHS / ESG", "ASTM - Rate of Incidents (%)", "ASTM_Incident_Rate_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "ASTM - Rate of Incidents (%)", "ASTM_Incident_Rate_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "ASTM - Rate of Incidents (%)", "ASTM_Incident_Rate_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "ASTM - Rate of Incidents (%)", "ASTM_Incident_Rate_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "ASTM - Rate of Incidents (%)", "ASTM_Incident_Rate_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				
				        {"EHS / ESG", "pSIF Action Closure Rate (%)", "pSIF_Closure_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        {"EHS / ESG", "pSIF Action Closure Rate (%)", "pSIF_Closure_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        {"EHS / ESG", "pSIF Action Closure Rate (%)", "pSIF_Closure_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"EHS / ESG", "pSIF Action Closure Rate (%)", "pSIF_Closure_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        {"EHS / ESG", "pSIF Action Closure Rate (%)", "pSIF_Closure_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        // {"EHS / ESG", "pSIF Action Closure Rate (%)", "pSIF_Closure_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "pSIF Action Closure Rate (%)", "pSIF_Closure_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "pSIF Action Closure Rate (%)", "pSIF_Closure_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "pSIF Action Closure Rate (%)", "pSIF_Closure_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "pSIF Action Closure Rate (%)", "pSIF_Closure_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				
				        // {"EHS / ESG", "Good Catch Closure Rate (%)", "Good_Catch_Closure_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "Good Catch Closure Rate (%)", "Good_Catch_Closure_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "Good Catch Closure Rate (%)", "Good_Catch_Closure_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "Good Catch Closure Rate (%)", "Good_Catch_Closure_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        // {"EHS / ESG", "Good Catch Closure Rate (%)", "Good_Catch_Closure_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        {"EHS / ESG", "Good Catch Closure Rate (%)", "Good_Catch_Closure_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        {"EHS / ESG", "Good Catch Closure Rate (%)", "Good_Catch_Closure_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        {"EHS / ESG", "Good Catch Closure Rate (%)", "Good_Catch_Closure_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        {"EHS / ESG", "Good Catch Closure Rate (%)", "Good_Catch_Closure_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				        {"EHS / ESG", "Good Catch Closure Rate (%)", "Good_Catch_Closure_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				
				
				        // {"Cross Functional", "NPI, Relaunch, Conv. OTIF (%)", "NPI_OTIF_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "NPI, Relaunch, Conv. OTIF (%)", "NPI_OTIF_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "NPI, Relaunch, Conv. OTIF (%)", "NPI_OTIF_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "NPI, Relaunch, Conv. OTIF (%)", "NPI_OTIF_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "NPI, Relaunch, Conv. OTIF (%)", "NPI_OTIF_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        // {"Cross Functional", "NPI, Relaunch, Conv. OTIF (%)", "NPI_OTIF_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "NPI, Relaunch, Conv. OTIF (%)", "NPI_OTIF_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "NPI, Relaunch, Conv. OTIF (%)", "NPI_OTIF_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "NPI, Relaunch, Conv. OTIF (%)", "NPI_OTIF_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "NPI, Relaunch, Conv. OTIF (%)", "NPI_OTIF_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				
				        {"Cross Functional", "Operating Income ($)", "Operating_Income_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        {"Cross Functional", "Operating Income ($)", "Operating_Income_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        {"Cross Functional", "Operating Income ($)", "Operating_Income_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Cross Functional", "Operating Income ($)", "Operating_Income_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        {"Cross Functional", "Operating Income ($)", "Operating_Income_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        {"Cross Functional", "Operating Income ($)", "Operating_Income_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        {"Cross Functional", "Operating Income ($)", "Operating_Income_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        {"Cross Functional", "Operating Income ($)", "Operating_Income_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        {"Cross Functional", "Operating Income ($)", "Operating_Income_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				        {"Cross Functional", "Operating Income ($)", "Operating_Income_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				
				        // {"Cross Functional", "Voluntary Turnover (%)", "Vol_Turnover_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "Voluntary Turnover (%)", "Vol_Turnover_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "Voluntary Turnover (%)", "Vol_Turnover_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "Voluntary Turnover (%)", "Vol_Turnover_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "Voluntary Turnover (%)", "Vol_Turnover_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        // {"Cross Functional", "Voluntary Turnover (%)", "Vol_Turnover_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "Voluntary Turnover (%)", "Vol_Turnover_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "Voluntary Turnover (%)", "Vol_Turnover_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "Voluntary Turnover (%)", "Vol_Turnover_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "Voluntary Turnover (%)", "Vol_Turnover_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				
				        // {"Cross Functional", "Involuntary Turnover (%)", "Invol_Turnover_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "Involuntary Turnover (%)", "Invol_Turnover_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "Involuntary Turnover (%)", "Invol_Turnover_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "Involuntary Turnover (%)", "Invol_Turnover_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "Involuntary Turnover (%)", "Invol_Turnover_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        // {"Cross Functional", "Involuntary Turnover (%)", "Invol_Turnover_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "Involuntary Turnover (%)", "Invol_Turnover_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "Involuntary Turnover (%)", "Invol_Turnover_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "Involuntary Turnover (%)", "Invol_Turnover_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				        // {"Cross Functional", "Involuntary Turnover (%)", "Invol_Turnover_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"},
				
				        {"Cross Functional", "Learning Program Completion (%)", "Learning_Completion_vsPlan", "vs Plan","CSCA","BadIfNeg","BadIfNeg"},
				        {"Cross Functional", "Learning Program Completion (%)", "Learning_Completion_vsPP", "vs PP","CSCA","BadIfNeg","BadIfNeg"},
				        {"Cross Functional", "Learning Program Completion (%)", "Learning_Completion_vsYoY", "vs YoY","CSCA","BadIfNeg","BadIfNeg"},
				        {"Cross Functional", "Learning Program Completion (%)", "Learning_Completion_vsFlex", "vs Flex","CSCA","BadIfNeg","BadIfNeg"},
				        {"Cross Functional", "Learning Program Completion (%)", "Learning_Completion_vsLYTD", "LYTD","CSCA","BadIfNeg","BadIfNeg"},
				
				        {"Cross Functional", "Learning Program Completion (%)", "Learning_Completion_vsPlan", "vs Plan","CSCI","BadIfNeg","BadIfNeg"},
				        {"Cross Functional", "Learning Program Completion (%)", "Learning_Completion_vsPP", "vs PP","CSCI","BadIfNeg","BadIfNeg"},
				        {"Cross Functional", "Learning Program Completion (%)", "Learning_Completion_vsYoY", "vs YoY","CSCI","BadIfNeg","BadIfNeg"},
				        {"Cross Functional", "Learning Program Completion (%)", "Learning_Completion_vsFlex", "vs Flex","CSCI","BadIfNeg","BadIfNeg"},
				        {"Cross Functional", "Learning Program Completion (%)", "Learning_Completion_vsLYTD", "LYTD","CSCI","BadIfNeg","BadIfNeg"}
				        
				
				    }
				)
				```

	annotation PBI_Id = e8286c3ee3d146378bb4092b4d5f757d

