table Measure
	lineageTag: 40405884-f649-4165-ab7d-331920f9f41c

	defaultDetailRowsDefinition = ```
			------------------------------
			-- Measure: [COGS Actual LYTD]
			------------------------------
			MEASURE 'Measure'[COGS Actual LYTD] = 
			    VAR LYTD = DIVIDE([Total Logistics LYTD], [Net Sales LYTD])
			    Return
			    [COGS Actual] - LYTD
			    , FormatString = "0.00%;-0.00%;0.00%"
			
			------------------------------------
			-- Measure: [COGS Actual LYTD_Final]
			------------------------------------
			MEASURE 'Measure'[COGS Actual LYTD_Final] = 
			    VAR kpi_ =  [COGS Actual LYTD]
			    VAR perc_ = abs(kpi_)
			    VAR Format_ = Format( perc_,"0.0%")
			    VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			    Return 
			    Result_
			
			------------------------------
			-- Measure: [COGS Actual MoM%]
			------------------------------
			MEASURE 'Measure'[COGS Actual MoM%] = 
			    VAR alldate_ = all(Dim_Date)
			    VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			    VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			    VAR Net_PM = Calculate([COGS Actual],filter_)
			    VAR Result = DIVIDE(([COGS Actual] - Net_PM),Net_PM)
			    RETURN
			    Result
			
			-----------------------------------
			-- Measure: [COGS Actual MoM_Final]
			-----------------------------------
			MEASURE 'Measure'[COGS Actual MoM_Final] = 
			    VAR kpi_ =  [COGS Actual MoM%]
			    VAR perc_ = abs(kpi_)
			    VAR Format_ = Format( perc_,"0.0%")
			    VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			    Return 
			    Result_
			
			----------------------------
			-- Measure: [COGS Actual PY]
			----------------------------
			MEASURE 'Measure'[COGS Actual PY] = 
			    VAR alldate_ = all(Dim_Date)
			    VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			    VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			    
			    RETURN
			    Calculate([COGS Actual],filter_)
			    , FormatString = "0.0"
			
			------------------------------
			-- Measure: [COGS Actual YoY%]
			------------------------------
			MEASURE 'Measure'[COGS Actual YoY%] = DIVIDE(([COGS Actual] - [COGS Actual PY]),[COGS Actual PY])
			
			-----------------------------------
			-- Measure: [COGS Actual YoY_Final]
			-----------------------------------
			MEASURE 'Measure'[COGS Actual YoY_Final] = 
			    VAR kpi_ =  [COGS Actual YoY%]
			    VAR perc_ = abs(kpi_)
			    VAR Format_ = Format( perc_,"0.0%")
			    VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			    Return 
			    Result_
			
			-----------------------------
			-- Measure: [COGS Actual YTD]
			-----------------------------
			MEASURE 'Measure'[COGS Actual YTD] = 
			    VAR _LastMonth = MAX(Dim_Date[P_YearMonth Number])
			    VAR _SelectedYear = MAX(Dim_Date[P_Year])
			    RETURN
			        SUMX(
			            FILTER(
			                ALL(Dim_Date),
			                Dim_Date[P_YearMonth Number] <= _LastMonth && Dim_Date[P_Year] = _SelectedYear
			            ),
			            [COGS Actual]
			        )
			    , FormatString = "0.0"
			
			-------------------------------
			-- Measure: [COGS_Actual_Color]
			-------------------------------
			MEASURE MetricSelector[COGS_Actual_Color] = 
			    VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			    
			    VAR kpi_value =
			        SWITCH(
			            _sel,
			            "vs PP", [COGS Actual MoM%],
			            "LYTD", [COGS Actual LYTD],
			            "vs YoY", [COGS Actual YoY%], 
			            BLANK()
			        )
			    
			    RETURN
			            IF(
			                kpi_value > 0,
			                "#D7191C",  -- red for ▼ down
			                "#1A9641"   -- green for ▲ up
			            )
			    , DisplayFolder = "Cond.format_measure"
			
			-------------------------
			-- Measure: [COGS_Actual]
			-------------------------
			MEASURE MetricSelector[COGS_Actual] = 
			    VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			      RETURN
			        SWITCH(
			          _sel,
			          "vs PP", [COGS Actual MoM_Final],
			          "LYTD",               [COGS Actual LYTD],
			          "vs YoY",               [COGS Actual YoY_Final],
			          BLANK()
			        )
			    , DisplayFolder = "Switch Measures"
			```

	measure 'Net Inventory' = SUM(Fact_CFIN_Inventory[Sum Amount CFIN Base])
		formatString: #,0.0
		displayFolder: Net Inventory
		lineageTag: ab1cbb42-348c-421e-8f32-2cb1762129d4

	measure 'Gross Inventory' = SUM(Fact_CFIN_Inventory[CFIN Amount Excl Inventory Reserves])
		formatString: #,0.0
		displayFolder: Gross Inventory
		lineageTag: 181f4461-1371-405d-9adf-08008747ebbd

	measure 'Inventory Avg L4M' =
			
			VAR _LastMonth = MAX( Dim_Date[P_YearMonth Number] )
			VAR _FirstMonth = _LastMonth - 3
			RETURN
			    AVERAGEX(
			        FILTER(
			                ALL(Dim_Date),
			                Dim_Date[P_YearMonth Number] >= _FirstMonth && Dim_Date[P_YearMonth Number] <= _LastMonth
			            ),
			        [Net Inventory]
			    )
		formatString: #,0.0
		displayFolder: DIO
		lineageTag: 184b6241-3ed8-4bb5-a16e-5a7f4a0a28d9

	measure 'Total COGS GR' = SUM(Fact_Group_Reporting[Total COGS GR])
		displayFolder: DIO
		lineageTag: 7c59e34e-3e2f-439b-9632-f9af99f809b9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total COGS GR L3M' =
			
			VAR _Months = 3
			VAR _LastMonth = VALUE(MAX(Dim_Date[YearPeriodSeq]))
			VAR _FirstMonth = _LastMonth - (_Months-1)
			RETURN
			    SUMX(
			        FILTER(
			            ALL( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= _FirstMonth && Dim_Date[YearPeriodSeq] <= _LastMonth
			        ),
			        [Total COGS GR]
			    )
		displayFolder: DIO
		lineageTag: d9229ae6-16d7-4dfa-aef0-7eda0ffcd68a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DIO =
			
			VAR _Months = 3
			VAR _TotalCOGS = CALCULATE([Total COGS GR L3M],KEEPFILTERS(Dim_Date[Is Closed] = "TRUE"))
			VAR _AvgInventory = CALCULATE([Inventory Avg L4M],KEEPFILTERS(Dim_Date[Is Closed] = "TRUE"))
			RETURN
			    DIVIDE( _AvgInventory, _TotalCOGS ) * (30.3333*_Months)
		formatString: 0
		displayFolder: DIO
		lineageTag: dd2f5f12-d99c-4f8e-a108-82e3e69dce9f

	measure 'SSSO: Scrap-Off' = CALCULATE(SUM(Fact_SSSO[SSSO]),KEEPFILTERS(Fact_SSSO[Functional Area] = "25"))
		formatString: 0.0
		displayFolder: SSSO Scrap-Off
		lineageTag: fb6011ed-9f0b-4a06-ba96-5ea00ae2ee25

	measure 'SSSO Obsolescence' = CALCULATE(SUM(Fact_SSSO[SSSO]),KEEPFILTERS(Fact_SSSO[Functional Area] = "26"))
		formatString: 0.0
		displayFolder: SSSO Obs linked to Conv
		lineageTag: d73fe601-a954-46b3-8399-fbf2703a2883

	measure 'SSSO Salvage' = CALCULATE(SUM(Fact_SSSO[SSSO]),KEEPFILTERS(Fact_SSSO[Functional Area] = "23"))
		formatString: 0.0
		displayFolder: SSSO Salvage & Obs
		lineageTag: 5ac3a033-6d99-444c-8235-c4e0a72039b4

	measure 'SSSO: Obsolescenes linked to Conversions' = [SSSO: Scrap-Off] + [SSSO Obsolescence] + [SSSO Salvage]
		formatString: 0.0
		displayFolder: SSSO Obs linked to Conv
		lineageTag: 562692b2-b615-40c6-93ab-08c5d8dbe254

	measure 'SSSO: Salvage & Obsolescence' = [SSSO Obsolescence] + ([SSSO Salvage])
		formatString: 0.0
		displayFolder: SSSO Salvage & Obs
		lineageTag: faf75843-20fd-4343-9166-4da7af7c42e3

	measure 'Net Inventory YTD' =
			VAR _LastMonth = MAX(Dim_Date[P_YearMonth Number])
			VAR _SelectedYear = MAX(Dim_Date[P_Year])
			RETURN
			    SUMX(
			        FILTER(
			            ALL(Dim_Date),
			            Dim_Date[P_YearMonth Number] <= _LastMonth && Dim_Date[P_Year] = _SelectedYear
			        ),
			        [Net Inventory]
			    )
		formatString: 0.0
		displayFolder: Net Inventory
		lineageTag: 3bbe80c1-41ea-4f68-9e94-7100e4713ea6

	measure 'Net Inventory YoY%' = DIVIDE(([Net Inventory] - [Net Inventory PY]),[Net Inventory PY])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Net Inventory
		lineageTag: 140ca208-2cd8-4228-a4c9-085509ba07f6

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "YearToDate"
				}

		changedProperty = FormatString

	measure 'Net Inventory PY' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Net Inventory],filter_)
		formatString: 0.0
		displayFolder: Net Inventory
		lineageTag: a20b24c0-15be-4139-a0f3-3ecc069c940f

	measure 'Net Inventory MoM%' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([Net Inventory],filter_)
			VAR Result = DIVIDE(([Net Inventory] - Net_PM),Net_PM)
			RETURN
			Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Net Inventory
		lineageTag: 8a130a4b-2077-4fcb-bbb0-38a05cde013f

	measure 'Gross Inventory YTD' =
			VAR _LastMonth = MAX(Dim_Date[P_YearMonth Number])
			VAR _SelectedYear = MAX(Dim_Date[P_Year])
			RETURN
			    SUMX(
			        FILTER(
			            ALL(Dim_Date),
			            Dim_Date[P_YearMonth Number] <= _LastMonth && Dim_Date[P_Year] = _SelectedYear
			        ),
			        [Gross Inventory]
			    )
		formatString: 0.0
		displayFolder: Gross Inventory
		lineageTag: b5217a39-6c9e-4c8d-9ed8-67b26b2660b8

	measure 'Gross Inventory PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Gross Inventory],filter_)
			
			```
		formatString: 0.0
		displayFolder: Gross Inventory
		lineageTag: ba349cc3-e124-441c-a43c-4b6bf0266c39

	measure 'Gross Inventory YoY%' = DIVIDE(([Gross Inventory] - [Gross Inventory PY]),[Gross Inventory PY])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Gross Inventory
		lineageTag: 27f29739-fc1d-4516-8aac-54cc8a65cfd0

	measure 'Gross Inventory MoM%' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([Gross Inventory],filter_)
			VAR Result = DIVIDE(([Gross Inventory] - Net_PM),Net_PM)
			RETURN
			Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Gross Inventory
		lineageTag: 9b84a80c-99a4-47c6-b0ef-e0da54183cd4

	measure 'SSSO: Obs linked to Conv YTD' =
			VAR _LastMonth = MAX(Dim_Date[P_YearMonth Number])
			VAR _SelectedYear = MAX(Dim_Date[P_Year])
			RETURN
			    SUMX(
			        FILTER(
			            ALL(Dim_Date),
			            Dim_Date[P_YearMonth Number] <= _LastMonth && Dim_Date[P_Year] = _SelectedYear
			        ),
			        [SSSO: Obsolescenes linked to Conversions]
			    )
		formatString: 0.0
		displayFolder: SSSO Obs linked to Conv
		lineageTag: f00ab7e4-27e7-4d33-bd44-f9b6ee803aff

	measure 'SSSO: Obs linked to Conv PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([SSSO: Obsolescenes linked to Conversions],filter_)
			
			```
		formatString: 0.0
		displayFolder: SSSO Obs linked to Conv
		lineageTag: e0d1f119-9211-4a62-b624-d37517b52167

	measure 'SSSO: Obs linked to Conv YoY%' =
			
			DIVIDE(([SSSO: Obsolescenes linked to Conversions] - [SSSO: Obs linked to Conv PY]),[SSSO: Obs linked to Conv PY])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SSSO Obs linked to Conv
		lineageTag: 0fb58fe1-7d21-432a-b139-61251e7f072f

	measure 'SSSO: Obs linked to Conv MoM%' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([SSSO: Obsolescenes linked to Conversions],filter_)
			VAR Result = DIVIDE(([SSSO: Obsolescenes linked to Conversions] - Net_PM),Net_PM)
			RETURN
			Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SSSO Obs linked to Conv
		lineageTag: 18431b9b-9f5b-4965-aa5d-024c7938ba37

	measure 'SSSO: Salvage YTD' =
			VAR _LastMonth = MAX(Dim_Date[P_YearMonth Number])
			VAR _SelectedYear = MAX(Dim_Date[P_Year])
			RETURN
			    SUMX(
			        FILTER(
			            ALL(Dim_Date),
			            Dim_Date[P_YearMonth Number] <= _LastMonth && Dim_Date[P_Year] = _SelectedYear
			        ),
			        [SSSO: Salvage & Obsolescence]
			    )
		formatString: 0.0
		displayFolder: SSSO Salvage & Obs
		lineageTag: cd143dcf-4712-41bf-9f5d-27d511637f4a

	measure 'SSSO: Salvage & Obs PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([SSSO: Salvage & Obsolescence],filter_)
			
			```
		formatString: 0.0
		displayFolder: SSSO Salvage & Obs
		lineageTag: f4fc588e-4a8d-4e39-9316-8c7c83bedc1a

	measure 'SSSO: Salvage YoY%' = DIVIDE(([SSSO: Salvage & Obsolescence] - [SSSO: Salvage & Obs PY]),[SSSO: Salvage & Obs PY])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SSSO Salvage & Obs
		lineageTag: c01dc9d9-8d64-45f9-99cc-08498b55bd17

	measure 'SSSO: Salvage & obs MoM%' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([SSSO: Salvage & Obsolescence],filter_)
			VAR Result = DIVIDE(([SSSO: Salvage & Obsolescence] - Net_PM),Net_PM)
			RETURN
			Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SSSO Salvage & Obs
		lineageTag: c43bc164-f4dd-4721-977e-68f035b73e93

	measure 'SSSO: Scrap-Off PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([SSSO: Scrap-Off],filter_)
			
			```
		formatString: 0.0
		displayFolder: SSSO Scrap-Off
		lineageTag: d28647b9-e899-4858-bd06-372993df56fe

	measure 'SSSO: Scrap-Off YoY%' = DIVIDE(([SSSO: Scrap-Off] - [SSSO: Scrap-Off PY]),[SSSO: Scrap-Off PY])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SSSO Scrap-Off
		lineageTag: 5b4ff4bc-f544-46b2-b2c1-679f770ad319

	measure 'SSSO: Scrap-Off YTD' =
			VAR _LastMonth = MAX(Dim_Date[P_YearMonth Number])
			VAR _SelectedYear = MAX(Dim_Date[P_Year])
			RETURN
			    SUMX(
			        FILTER(
			            ALL(Dim_Date),
			            Dim_Date[P_YearMonth Number] <= _LastMonth && Dim_Date[P_Year] = _SelectedYear
			        ),
			        [SSSO: Scrap-Off]
			    )
		formatString: 0.0
		displayFolder: SSSO Scrap-Off
		lineageTag: 22f1a0aa-0bc5-4c48-965a-138c127afc49

	measure 'SSSO: Scrap-Off MoM%' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([SSSO: Scrap-Off],filter_)
			VAR Result = DIVIDE(([SSSO: Scrap-Off] - Net_PM),Net_PM)
			RETURN
			Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SSSO Scrap-Off
		lineageTag: abb1d546-65e8-4f73-a954-f27372de2284

	measure 'DIO PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			VAR py = Calculate([DIO],filter_)
			RETURN
			IF(SELECTEDVALUE(Dim_Date[Is Closed]) = "TRUE",py,BLANK())
			
			```
		formatString: 0
		displayFolder: DIO
		lineageTag: e6ef20d4-80a4-4856-819f-9b826edeaf0b

	measure 'DIO YoY%' = DIVIDE(([DIO] - [DIO PY]),[DIO PY])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: DIO
		lineageTag: fb07b4ec-fee9-4c45-9960-d9087180153f

	measure 'DIO YTD' = TOTALYTD([DIO],Dim_Date[Date])
		displayFolder: DIO
		lineageTag: f925f772-6f28-4397-9a88-da9958434049

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DIO MoM%' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([DIO],filter_)
			VAR Result = DIVIDE(([DIO] - Net_PM),Net_PM)
			RETURN
			IF(SELECTEDVALUE(Dim_Date[Is Closed]) = "TRUE",Result,BLANK())
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: DIO
		lineageTag: e8e2db32-9833-4e62-988d-967b66f08d3b

	measure 'SSSO: Salvage YoY_Final' =
			
			VAR kpi_ = [SSSO: Salvage YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: SSSO Salvage & Obs
		lineageTag: a8ecb3fa-43e4-4575-bc04-7c4a7770bff1

	measure 'SSSO: Obs linked to Conv YoY_Final' =
			
			VAR kpi_ = [SSSO: Obs linked to Conv YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: SSSO Obs linked to Conv
		lineageTag: c9cfc228-551e-4069-b2fe-15f87df615cb

	measure 'SSSO: Scrap-Off YoY_Final' =
			
			VAR kpi_ = [SSSO: Scrap-Off YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: SSSO Scrap-Off
		lineageTag: e18c5881-a10e-42a3-9b8f-98ea6e7ccd1b

	measure 'DIO YoY_Final' =
			
			VAR kpi_ =  [DIO YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: DIO
		lineageTag: a9b71bec-1ac2-4cc0-9e22-0e79134f0e95

	measure 'Gross Inventory YoY_Final' =
			
			VAR kpi_ =  [Gross Inventory YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Gross Inventory
		lineageTag: a530ffa9-4e91-4476-8337-32b3143b172b

	measure 'Net Inventory YoY_Final' =
			
			VAR kpi_ =  [Net Inventory YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Net Inventory
		lineageTag: 733a3aac-7ad4-4e0f-ac0a-590a7ce992c3

	measure 'DIO MoM_Final' = ```
			
			VAR kpi_ =  [DIO MoM%]
			Return 
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
			```
		displayFolder: DIO
		lineageTag: 5e5ea728-f04f-4252-8fda-2903aa2d4bd0

	measure 'SSSO: Scrap-Off MoM_Final' = ```
			
			VAR kpi_ =  [SSSO: Scrap-Off MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: SSSO Scrap-Off
		lineageTag: 491f2458-e1c0-44e9-abc7-1d20ac969db3

	measure 'SSSO: Obs Linked to Conv MoM_Final' = ```
			
			VAR kpi_ =  [SSSO: Obs linked to Conv MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: SSSO Obs linked to Conv
		lineageTag: 6a3eafbe-55cd-460f-8d3f-e6288ea5b0d2

	measure 'Gross Inventory MoM_Final' = ```
			
			VAR kpi_ =  [Gross Inventory MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Gross Inventory
		lineageTag: 3da32a40-2e9a-4d27-91c4-3dd6a2e5f13d

	measure 'Net Inventory MoM_Final' = ```
			
			VAR kpi_ =  [Net Inventory MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Net Inventory
		lineageTag: 29421bfe-a592-48a7-ac59-e1d88215cb2c

	measure 'SSSO: Salvage MoM_Final' = ```
			
			VAR kpi_ =  [SSSO: Salvage & obs MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: SSSO Salvage & Obs
		lineageTag: daff27e1-fdd7-4d08-ad1d-fd703eb1a417

	measure 'Total Shipments' = SUM(Fact_Forecast_Accuracy[Total Shipments])
		displayFolder: Forecast Accuracy CSCA
		lineageTag: a5e83a55-eccc-4e25-9c03-48daa0ee7ddc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Abs Demand Draft Var SSID' =
			CALCULATE(
			SUMX(
			    SUMMARIZE(
			        Fact_Forecast_Accuracy,Fact_Forecast_Accuracy[SSID],
			        Fact_Forecast_Accuracy[Fiscal Year/Period],
			        "Variance", ABS([Demand Draft] - [Total Shipments])),[Variance]),
			REMOVEFILTERS(Fact_Forecast_Accuracy[Source Material Key])
			)
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 3f06f1dc-fc9f-402f-9aec-d566b7ccadcf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Demand Draft' = SUM(Fact_Forecast_Accuracy[Demand Draft])
		displayFolder: Forecast Accuracy CSCA
		lineageTag: fbf269cf-f42c-4a57-99cd-cad432808fd4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FA% SSID' = ```
			
			VAR TotalShipments = [Total Shipments]
			VAR VarianceAgg = [Abs Demand Draft Var SSID]
			
			RETURN 
			IF(
			    ISBLANK(VarianceAgg),
			    BLANK(),  // Return BLANK if VarianceAgg is blank or zero
			    VAR Result = 1 - DIVIDE(VarianceAgg, TotalShipments, 1)
			    RETURN IF(Result < 0, 0, Result)
			)
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 2b2069c5-6535-47ad-95db-089e9020509b

	measure 'FA% MoM%' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([FA% CSCA],filter_)
			VAR Result = [FA% CSCA] - Net_PM
			RETURN
			Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 965af87e-1352-4d15-bcb8-a7e292cca73b

	measure 'FA% MoM_Final' = ```
			
			VAR kpi_ =  [FA% MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_
			```
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 7fb22ffa-3bff-460d-ba13-d79e9f87056e

	measure 'FA% YTD' = TOTALYTD([FA% CSCA],Dim_Date[Date])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: e8c2fa8a-2e8b-4033-ac41-0ecc5c1958bc

	measure 'FA% PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([FA% CSCA],filter_)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 04f859d2-41cf-4a67-bf8a-140a2a4df5a5

	measure 'FA% YoY%' = [FA% CSCA] - [FA% PY]
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 5f0e0d26-8723-4f72-a8d1-6a360db69338

	measure 'FA% YoY_Final' =
			
			VAR kpi_ =  [FA% YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 7567f433-6c42-4bfb-a180-9022e9551b0c

	measure 'Service Rate%' =
			CALCULATE(SUM(Fact_Service[On Delivery EA])/SUM(Fact_Service[Order EA]),
			REMOVEFILTERS(Bridge_CSCA_CSCI[Area]),REMOVEFILTERS(Dim_Profit_Center[Level 3]))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Service Rate CSCA
		lineageTag: 887a4d69-b579-4175-9eeb-cc6ce1a42aee

	measure 'Service Rate% YTD' = TOTALYTD([Service Rate%],Dim_Date[Date])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Service Rate CSCA
		lineageTag: d6338872-6b28-45d3-a6ca-397cbd0fbf38

	measure 'Service Rate% PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Service Rate%],filter_)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Service Rate CSCA
		lineageTag: 4dbaec03-b970-4498-b934-43395f91ea19

	measure 'Service Rate% YoY_Final' =
			
			VAR kpi_ =  [Service Rate YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Service Rate CSCA
		lineageTag: 5fc56eed-e057-424c-838f-67ca0c4abedb

	measure 'Service Rate% MoM%' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([Service Rate%],filter_)
			VAR Result = [Service Rate%] - Net_PM
			RETURN
			Result
		displayFolder: Service Rate CSCA
		lineageTag: 6fbbb692-2eb6-4b42-830e-c21f2e74f313

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Service Rate% MoM_Final' = ```
			
			VAR kpi_ =  [Service Rate% MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Service Rate CSCA
		lineageTag: bd8c3781-f72f-49a3-93ec-4ce6f131a505

	measure Bias% =
			
			DIVIDE(
			    ([Demand Draft] - [Total Shipments]),
			    [Total Shipments],
			    1)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Bias CSCA
		lineageTag: 1a3e1c22-6fd8-4fc2-a471-53b451acd73b

	measure 'Bias MoM%' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([Bias%],filter_)
			VAR Result = [Bias%] - Net_PM
			RETURN
			Result
		displayFolder: Bias CSCA
		lineageTag: d24d2404-f4e5-4b5b-9e48-e147e65e8a78

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bias MoM_Final' = ```
			
			VAR kpi_ =  [Bias MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Bias CSCA
		lineageTag: e89753d3-3443-4f04-b83f-2e5cb4d62971

	measure 'Service Rate YoY%' = [Service Rate%] - [Service Rate% PY]
		displayFolder: Service Rate CSCA
		lineageTag: c12addd9-9c40-4d2a-9f05-e564487bb36e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bias PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Bias%],filter_)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Bias CSCA
		lineageTag: c9c28b3c-5307-4293-bb8c-88c3bdb403e4

	measure 'Bias YoY%' = [Bias%] - [Bias PY]
		displayFolder: Bias CSCA
		lineageTag: 8ddbe253-7b88-4b5d-b835-c3fcc8f1b445

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bias YoY_Final' =
			
			VAR kpi_ =  [Bias YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: Bias CSCA
		lineageTag: 7eb80396-a437-4a33-b613-93039ab055e4

	measure 'Bias YTD' = TOTALYTD([Bias%],Dim_Date[Date])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Bias CSCA
		lineageTag: 089997b2-ab0e-4b53-8655-a7433ed3c519

	measure 'Inflated Inventory' = SUM(Fact_BW_Inventory[Sum Amount Stock Value Inflated])
		formatString: 0.0
		displayFolder: Inflated Inventory
		lineageTag: 9b66eb0d-42fa-41a6-ab03-a48a8c3e7090

	measure 'Inflated Inventory YTD' =
			VAR _LastMonth = MAX(Dim_Date[P_YearMonth Number])
			VAR _SelectedYear = MAX(Dim_Date[P_Year])
			RETURN
			    SUMX(
			        FILTER(
			            ALL(Dim_Date),
			            Dim_Date[P_YearMonth Number] <= _LastMonth && Dim_Date[P_Year] = _SelectedYear
			        ),
			        [Inflated Inventory]
			    )
		formatString: 0.0
		displayFolder: Inflated Inventory
		lineageTag: c5d963b6-b96a-41fe-83df-01df7fc52540

	measure 'Inflated Inventory PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Inflated Inventory],filter_)
			
			```
		formatString: 0.0
		displayFolder: Inflated Inventory
		lineageTag: eeb986c9-d6de-418c-88a9-e5adf21eeaa6

	measure 'Inflated Inventory YoY%' = DIVIDE(([Inflated Inventory] - [Inflated Inventory PY]),[Inflated Inventory PY])
		displayFolder: Inflated Inventory
		lineageTag: 96254605-fb4f-4bcb-8b96-6d89fd788895

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Inflated Inventory YoY_Final' =
			
			VAR kpi_ =  [Inflated Inventory YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Inflated Inventory
		lineageTag: 73e68a48-2a0f-4b92-9f68-df0efcd24b03

	measure 'Inflated Inventory MoM%' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([Inflated Inventory],filter_)
			VAR Result = DIVIDE(([Inflated Inventory] - Net_PM),Net_PM)
			RETURN
			Result
		displayFolder: Inflated Inventory
		lineageTag: 645aab62-e41b-4ee2-aa18-421af4d7e237

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Inflated Inventory MoM_Final' = ```
			
			VAR kpi_ =  [Inflated Inventory MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Inflated Inventory
		lineageTag: 42fcadb3-a970-40f3-828d-beac3d8fc741

	measure 'Expired Inventory' =
			CALCULATE(SUM(Fact_BW_Inventory[Sum Amount Stock Value Inflated]),
			                    KEEPFILTERS(Dim_Expiration_Buckets[Expiration Bucket] = "Expired")
			    )
		formatString: 0.0
		displayFolder: Expired Inventory
		lineageTag: d241f22f-6a8a-44de-87f0-46862925d847

	measure 'Expired Inventory PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Expired Inventory],filter_)
			
			```
		formatString: 0.0
		displayFolder: Expired Inventory
		lineageTag: dbe0627f-3d40-4d77-a3fc-a3a361ff5c53

	measure 'Expired Inventory YoY%' = DIVIDE(([Expired Inventory] - [Expired Inventory PY]),[Expired Inventory PY])
		displayFolder: Expired Inventory
		lineageTag: d01f521c-3994-4e4a-a6fe-5255eac954e3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Expired Inventory YoY_Final' =
			
			VAR kpi_ =  [Expired Inventory YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Expired Inventory
		lineageTag: d634fb5a-0dda-420c-8d91-d30d2d9d7d2a

	measure 'Expired Inventory YTD' =
			VAR _LastMonth = MAX(Dim_Date[P_YearMonth Number])
			VAR _SelectedYear = MAX(Dim_Date[P_Year])
			RETURN
			    SUMX(
			        FILTER(
			            ALL(Dim_Date),
			            Dim_Date[P_YearMonth Number] <= _LastMonth && Dim_Date[P_Year] = _SelectedYear
			        ),
			        [Expired Inventory]
			    )
		displayFolder: Expired Inventory
		lineageTag: c537c5cf-c3ac-41a1-a6ac-30baa29c8735

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Expired Inventory MoM%' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([Expired Inventory],filter_)
			VAR Result = DIVIDE(([Expired Inventory] - Net_PM),Net_PM)
			RETURN
			Result
		displayFolder: Expired Inventory
		lineageTag: 86b8ba4d-f18a-4900-9715-bdcbbff19ef5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Expired Inventory MoM_Final' = ```
			
			VAR kpi_ =  [Expired Inventory MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Expired Inventory
		lineageTag: 92aef5f6-0be1-4ec1-8a8f-c296775a9b49

	measure 'Quality Loss' = [In Count] - [Out Count]
		displayFolder: OEE
		lineageTag: 698bfbc8-db07-4eea-b831-e4ce9438a928

	measure 'Run Speed' = DIVIDE( [Run Theoretical Quantity], [Total Elapsed Time])
		displayFolder: OEE
		lineageTag: 8ecd97ba-b4d8-4ba0-a419-a566aad45f64

	measure 'Run Theoretical Quantity' = SUM(Fact_OEE[Run Theoretical Quantity])
		displayFolder: OEE
		lineageTag: 242a1948-8c38-405e-bbd5-97a192ebd8ee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Elapsed Time' = [Up Seconds] + [Down Seconds]
		displayFolder: OEE
		lineageTag: bbaf02c3-6cdf-4bd0-b89f-e837ed1e62e0

	measure Availability = DIVIDE( [Up Seconds] , [Total Elapsed Time])
		displayFolder: OEE
		lineageTag: 25dc4fbe-6586-4d4b-8ad4-9fd740a3ae06

	measure 'Down Seconds' = SUM(Fact_OEE[Down Seconds])
		displayFolder: OEE
		lineageTag: be4c4681-b923-487c-86fc-addfef5d759b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'In Count' = SUM(Fact_OEE[In Count])
		displayFolder: OEE
		lineageTag: 4140725a-1de7-46c9-a2a6-4014b9e0c5c3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure OEE% = [Availability] * [Performance] * [Quality]
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: OEE
		lineageTag: 59aacec0-203e-46dc-88c6-4157674831dc

	measure 'Out Count' = SUM(Fact_OEE[Out Count])
		displayFolder: OEE
		lineageTag: 6f7edca5-9be9-44a3-a245-a50f9926ba95

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Performance = DIVIDE( ([Out Count] + [Quality Loss]) ,([Up Seconds] * [Run Speed]) )
		displayFolder: OEE
		lineageTag: d520f40a-3ce7-447b-836e-91d83015325c

	measure Quality = DIVIDE( [Out Count] , ([Out Count] + [Quality Loss]))
		displayFolder: OEE
		lineageTag: ef6b2eed-0950-4663-838c-3e1aee1027cd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Up Seconds' = SUM(Fact_OEE[Up Seconds])
		displayFolder: OEE
		lineageTag: 8afdb4fd-e7c5-40ac-b903-e66b8b83dbc8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OEE% YTD' = TOTALYTD([OEE%],Dim_Date[Date])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: OEE
		lineageTag: f014e406-db96-404d-8ecb-9285c2ed75be

	measure 'OEE% PY' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([OEE%],filter_)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: OEE
		lineageTag: 98ce04d3-0309-4fb6-b1f4-33bfa1175fb9

	measure 'OEE% YoY%' = [OEE%] - [OEE% PY]
		displayFolder: OEE
		lineageTag: 276cf5bd-1e9e-440a-ac33-4dca9a086f53

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OEE% YoY_Final' =
			
			VAR kpi_ =  [OEE% YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: OEE
		lineageTag: 727b12a7-c5e4-446c-946b-d7c9d7dff91a

	measure 'OEE% MoM%' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([OEE%],filter_)
			VAR Result = [OEE%] - Net_PM
			RETURN
			Result
		displayFolder: OEE
		lineageTag: c7acba63-af25-424b-9e36-17186a3d5711

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OEE% MoM_Final' = ```
			
			VAR kpi_ =  [OEE% MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: OEE
		lineageTag: 5a256b58-eeed-4adc-82e8-4bd97e383744

	measure Switch_YoY_OI = ```
			SWITCH(
			    VALUES( Operating_Parameter[Operating_Parameter] ),
			    "SSSO: Salvage & Obs", [SSSO: Salvage & Obs PY],
			    "SSSO: Obs linked to Conv", [SSSO: Obs linked to Conv PY],
			    "SSSO: Shrinkage",[SSSO: Shrinkage PY],
			    "SSSO: Scrap-Off", [SSSO: Scrap-Off PY],
			    "Net Sales", [Net Sales Actual PY],
			    "COGS", [COGS Actual PY],
			    "Distribution to COGS", [Total Distribution on COGS Actual PY],
			    "% Logistics vs Net Sales", [Total Logistics on Net Sales Actual PY],
			    "Customer Fines", [Cust fine PY],
			    "Operating Income", [Operating Income Actual PY],
			    "Gross PPV", [Gross PPV Actual PY],
			    "Net POV", [Net POV Actual PY]
			)
			
			```
		displayFolder: Switch Measures
		lineageTag: 55e0225c-6990-43d7-8b96-6d1119ba881e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Switch_YTD_OI = ```
			SWITCH(
			    VALUES( Operating_Parameter[Operating_Parameter] ),
			    "SSSO: Salvage & Obs", [SSSO: Salvage YTD],
			    "SSSO: Obs linked to Conv", [SSSO: Obs linked to Conv YTD],
			    "SSSO: Shrinkage",[SSSO: Shrinkage YTD],
			    "SSSO: Scrap-Off", [SSSO: Scrap-Off YTD],
			    "Net Sales", [Net Sales Actual YTD],
			    "COGS", [COGS Actual YTD],
			    "Distribution to COGS", [Total Distribution on COGS Actual YTD],
			    "% Logistics vs Net Sales", [Total Logistics on Net Sales Actual YTD],
			    "Customer Fines", [Cust Fine YTD],
			    "Operating Income", [Operating Income Actual YTD],
			    "Gross PPV", [Gross PPV Actual YTD],
			    "Net POV", [Net POV Actual YTD],
			    "ABP Variance", [ABP Variance YTD]
			)
			
			```
		displayFolder: Switch Measures
		lineageTag: 5afa0918-1f82-41f7-92bb-228d94f303f3

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(Operating_Parameter[Parameter Name]),
				    "SSSO: Salvage & Obs", "#,0",
				    "SSSO: Scrap-Off", "#,0",
				    "COGS", "#,0",
				    "Distribution to COGS", "0.0%",
				    "Operating Income", "#,0",
				    "Net POV", "#,0",
				    "SSSO: Obs linked to Conv","#,0",
				    "Net Sales", "#,0",
				    "% Logistics vs Net Sales", "0.0%",
				    "Customer Fines", "#,0",
				    "Gross PPV","#,0",
				    "ABP Variance","#,0"
				)

	measure Slicer_CrossFilter =
			INT(NOT ISEMPTY(Fact_CFIN_Inventory) &&
			                        NOT ISEMPTY(Fact_BW_Inventory))
		formatString: 0
		displayFolder: Misc
		lineageTag: 24c1a302-5b6b-4e40-9e11-cafa44dc639a

	measure 'FA% Lag2' = CALCULATE([FA% CSCA],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "2"))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: b81950d5-8ab5-475b-93f0-357ef042c805

	measure 'FA% Lag4' = CALCULATE([FA% CSCA],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "4"))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: c498bc62-c723-4016-a9bc-2baa41067d8e

	measure Switch_YoY_Sales =
			SWITCH(VALUES(Sales_Parameter[Sales_Parameter]),
			            "FA% Lag 2", CALCULATE([FA% PY],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "2")),
			            "FA% Lag 4", CALCULATE([FA% PY],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "4")),
			            "Service%", [Service Rate% PY],
			            "Bias% Lag 2", CALCULATE([Bias PY],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "2")),
			            "Bias% Lag 4", CALCULATE([Bias PY],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "4")),
			            "Schedule Attainment%", [SA PY],
			            "CFR%", [CFR PY],
			            "Service Top 11", [Service Top 11 PY],
			            BLANK())
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Switch Measures
		lineageTag: 60a5ad7b-77d6-444b-aed0-b32a5c8cbf46

	measure Switch_YTD_Sales = ```
			SWITCH(VALUES(Sales_Parameter[Sales_Parameter]),
			            "FA% Lag 2", CALCULATE([FA% YTD],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "2")),
			            "FA% Lag 4", CALCULATE([FA% YTD],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "4")),
			            "Service%", [Service Rate% YTD],
			            "Bias% Lag 2", CALCULATE([Bias YTD],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "2")),
			            "Bias% Lag 4", CALCULATE([Bias YTD],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "4")),
			            "Schedule Attainment%", [SA YTD],
			            "CFR%", [CFR YTD],
			            "Service Top 11", [Service Top 11 YTD],
			            BLANK())
			
			```
		displayFolder: Switch Measures
		lineageTag: 454e0097-983e-40fc-823c-84896952712f

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(Sales_Parameter[Parameter Name]),
				    "FA% Lag 2", "0.0%",
				    "FA% Lag 4", "0.0%",
				    "Bias% Lag 2", "0.0%",
				    "Bias% Lag 4", "0.0%",
				    "Service%", "0.0%",
				    "CFR%", "0.0%",
				    "Service Top 11","#,0"
				)

	measure Dummy = "--"
		displayFolder: Misc
		lineageTag: 2049e684-7f2a-4464-9bf6-205c89f3c95a

	measure 'OEE Target' = AVERAGE(Dim_Locations[_Target])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: OEE
		lineageTag: 15b8c1af-ca3d-43c0-af1d-87c2d1e94fd5

	measure 'OEE Target_Final' = ```
			
			VAR kpi_ =  [OEE%] - [OEE Target]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_  & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: OEE
		lineageTag: cdb3a6f6-5435-44b5-9bda-fa287167f4d8

	measure 'OEE Target diff%' = [OEE%] - [OEE Target]
		displayFolder: OEE
		lineageTag: 3e0d8c08-e6cd-4306-8cdc-7c65eebd523a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Switch_YoY_Operations = ```
			SWITCH(VALUES(Operations_Parameter[Operations_Parameter]),
			            "OEE%", [OEE% PY],
			            "Schedule Attainment%", [SA PY],
			            "On Time Closure of Deviations%",[On Time Closure of Deviations PY],
			            "CAPA Completion Rate%",[CAPA Completion Rate PY],
			            "RFT%", [RFT% PY],
			            "Critical or Major Observations", [Critical or Major Observations PY],
			            "ASTM Rate",[ASTM Rate PY],
			    "ASTM Incidents",[ASTM Incidents PY],
			    "Good Catch Closure Rate%",[Good Catch Closure Rate PY],
			    "pSIF SIF Focus Action%",[pSIF SIFs Focus PY],
			    "PWS Benefits",[PWS Benefits PY]
			            )
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Switch Measures
		lineageTag: 454fb01e-53cc-4c26-8800-a30c14f31b6f

	measure Switch_YTD_Operations = ```
			SWITCH(VALUES(Operations_Parameter[Operations_Parameter]),
			            "OEE%", [OEE% YTD],
			            "Schedule Attainment%", [SA YTD],
			            "On Time Closure of Deviations%",[On Time Closure of Deviations YTD],
			            "CAPA Completion Rate%",[CAPA Completion Rate YTD],
			            "RFT%", [RFT YTD],
			            "Critical or Major Observations", [Critical or Major Observations YTD],
			            // "ASTM Rate",[ASTM Rate YTD],
			            // "ASTM Incidents",[ASTM Incidents YTD],
			            // "Good Catch Closure Rate%",[Good Catch Closure Rate YTD],
			            // "pSIF SIF Focus Action%",[pSIF SIFs Focus YTD],
			            "PWS Benefits",[PWS Benefits YTD]
			            )
			
			```
		displayFolder: Switch Measures
		lineageTag: 68fe463c-34f9-4f8c-8525-075917555f91

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(Operations_Parameter[Parameter Name]),
				    "CAPA Completion Rate%", "0.0%",
				    "On Time Closure of Deviations%", "0.0%",
				    "RFT%", "0.0%",
				    "Critical or Major Observations", "#,0",
				    "OEE%", "0.0%",
				    "Schedule Attainment%", "0.0%",
				    "ASTM Rate","#,00",
				    "ASTM Incidents","#,00",
				    "Good Catch Closure Rate%","0.0%",
				    "pSIF SIF Focus Action%","0.0%",
				    "PWS Benefits", "#,0",
				    "#,0"  --fallback
				)

	measure 'Closed Period' = MAX(Dim_Date[P_YearPeriod])
		displayFolder: Misc
		lineageTag: bc58d87a-a458-4fb9-995d-27630420ef13

	measure 'Service Target Final' = ```
			
			VAR kpi_ =  [Service Target Diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Service Rate CSCA
		lineageTag: 8bb8bb93-720a-41b4-a0da-1def644a2b08

	measure 'Service Target' =
			
			Var tar = CALCULATE(MAX(Fact_Target[Target]),KEEPFILTERS(Fact_Target[KPI_Name] = "Service (Incl gap orders) (%)"))
			RETURN
			DIVIDE(tar,100)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Service Rate CSCA
		lineageTag: 627b20f4-253d-4e32-8a1d-173e007622d9

	measure 'Service Target Diff%' = [Service Rate%] - [Service Target]
		displayFolder: Service Rate CSCA
		lineageTag: 6192f793-2d2b-4dc6-a7de-5f4792807a39

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Switch_Plan_Sales =
			
			SWITCH(VALUES(Sales_Parameter[Sales_Parameter]),
			"Service%", 0.9,
			"FA% Lag 2", .62,
			"FA% Lag 4", .70,
			"Bias% Lag 2",.03,
			"Bias% Lag 4",.03,
			"Schedule Attainment%", 0.92,
			"CFR%", 0.94,
			"Service Top 11", [Service Top 11 Target])
		displayFolder: Switch Measures
		lineageTag: 6a4d05a3-5bba-40ce-9ccb-d44ad91b71a7

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(Sales_Parameter[Parameter Name]),
				    "FA% Lag 2", "0.0%",
				    "FA% Lag 4", "0.0%",
				    "Bias% Lag 2", "0.0%",
				    "Bias% Lag 4", "0.0%",
				    "Service%", "0.0%",
				    "CFR%", "0.0%",
				    "Service Top 11","#,0"
				)

	measure 'SSSO: Salvage LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [SSSO: Salvage & Obs PY])
			VAR Result = Sumx(Table_,[Measure])
			RETURN
			IF(
			    ISBLANK(Result) || Result = 0,
			    BLANK(),
			    DIVIDE([SSSO: Salvage & Obsolescence] - Result,Result)
			)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SSSO Salvage & Obs
		lineageTag: 522319d5-cde0-4adf-8650-2227b5632c3b

	measure Comparison_Filter =
			
			VAR SelectedPeriod = SELECTEDVALUE(CG_PeriodSelection[Period])
			VAR SelectedComp = SELECTEDVALUE(MetricSelector[Metric])
			RETURN
			SWITCH(
			    TRUE(),
			    SelectedPeriod = "YTD" && SelectedComp IN { "LYTD", "vs Plan", "vs Flex"}, 1,
			    SelectedPeriod = "PTD" && SelectedComp IN { "vs PP", "vs YoY", "vs Plan", "vs Flex", "vs 3M avg"}, 1,
			    0
			)
		formatString: 0
		displayFolder: Misc
		lineageTag: 297e1fbb-694b-49ef-b447-6dd7d32153db

	measure 'SSSO: Salvage LYTD_Final' =
			
			VAR kpi_ =  [SSSO: Salvage LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: SSSO Salvage & Obs
		lineageTag: c8e1d0d6-63cf-40e3-a913-51e4cd51baec

	measure 'Total Logistics Actual' = sum(Fact_Logistics[Amount Total Logistics Act])
		displayFolder: Logistic
		lineageTag: c21210d0-c066-423f-9051-3740817ba3bb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Logistics on Net Sales Actual' = DIVIDE([Total Logistics Actual], [Net Sales Actual])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Logistic vs Net Sales
		lineageTag: cbb9192f-b2cf-4c13-ac11-c00c4d9f2834

	measure 'Total Logistics on Net Sales Actual MoM%' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([Total Logistics on Net Sales Actual],filter_)
			VAR Result = ([Total Logistics on Net Sales Actual] - Net_PM)
			RETURN
			Result
		displayFolder: Logistic vs Net Sales
		lineageTag: 5bcbf093-f7fa-4ac1-953d-020babee4228

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Logistics on Net Sales Actual MoM_Final' = ```
			VAR kpi_ =  [Total Logistics on Net Sales Actual MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Logistic vs Net Sales
		lineageTag: 7c1dd430-09a0-4bbc-8b0b-a18a7353f301

	measure 'Total Logistics on Net Sales Actual PY' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Total Logistics on Net Sales Actual],filter_)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Logistic vs Net Sales
		lineageTag: d5a31556-8130-42f6-ab18-5cec6c2b09d1

	measure 'Total Logistics on Net Sales Actual YoY%' = ([Total Logistics on Net Sales Actual] - [Total Logistics on Net Sales Actual PY])
		displayFolder: Logistic vs Net Sales
		lineageTag: 0b1fbe3f-6411-4bee-b41c-2c42fb5ccaf1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Logistics on Net Sales Actual YoY_Final' =
			VAR kpi_ =  [Total Logistics on Net Sales Actual YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Logistic vs Net Sales
		lineageTag: c1020b66-b8a1-4d2e-a5bf-6609fe16d33a

	measure 'Total Logistics on Net Sales Actual YTD' = DIVIDE( [Total logistics actual YTD], [Net Sales Actual YTD] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Logistic vs Net Sales
		lineageTag: 876740fb-35e2-474c-a62b-bee8c5513fba

	measure 'Total Logistics Plan' = sum(Fact_Logistics[Amount Total Logistics Plan])
		displayFolder: Logistic
		lineageTag: 47ed2198-6175-47b9-863e-8bd86e80098f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Sales Actual' = CALCULATE(sum(Fact_Logistics[Net Sales Act]) , KEEPFILTERS( Dim_Profit_Center[FP&A Country] <> "Feldkirchen"))
		displayFolder: Net Sales
		lineageTag: 9606c3f8-dbc0-4ce5-8d31-1571c7cd3841

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Sales Plan' = ```
			sum(Fact_Logistics[Net Sales Plan]) 
			```
		displayFolder: Net Sales
		lineageTag: a61ab426-9ab0-480a-a74f-c4c610e685df

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Schedule Attn' = ```
			
			CALCULATE(divide(sum(Fact_Schedule[+/- 10% Adh no penatly early]),count(Fact_Schedule[Order Number])),REMOVEFILTERS(Bridge_CSCA_CSCI[Area]),REMOVEFILTERS(Dim_Profit_Center[Level 3]))
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Schedule Attainment
		lineageTag: 0763e022-0de3-4c7a-957d-9b0d69758676

	measure 'SA MoM%' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([Schedule Attn],filter_)
			VAR Result = [Schedule Attn] - Net_PM
			RETURN
			Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Schedule Attainment
		lineageTag: e3c05ffe-a15c-490c-ae09-25a135c59516

	measure 'SA MoM_Final' = ```
			
			VAR kpi_ =  [SA MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Schedule Attainment
		lineageTag: 7770fdeb-5f90-48d0-aecb-ef32aa18cdd3

	measure 'SA PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Schedule Attn],filter_)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Schedule Attainment
		lineageTag: 18064b59-a3ba-48f6-9948-db29c35e3494

	measure 'SA YoY%' = [Schedule Attn] - [SA PY]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Schedule Attainment
		lineageTag: 552326dc-8d30-43bd-a68a-ec2e7771100f

	measure 'SA YoY_Final' =
			
			VAR kpi_ =  [SA YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Schedule Attainment
		lineageTag: f7997757-254f-4515-a060-48e832e0a28d

	measure 'SA YTD' = TOTALYTD([Schedule Attn],Dim_Date[Date])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Schedule Attainment
		lineageTag: 262a6732-35de-437b-a6df-e652bd6d0b94

	measure 'SSSO: Obs LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [SSSO: Obs linked to Conv PY])
			VAR Result = Sumx(Table_,[Measure])
			RETURN
			IF(
			    ISBLANK(Result) || Result = 0,
			    BLANK(),
			    DIVIDE([SSSO: Obsolescenes linked to Conversions] - Result,Result)
			)
			```
		displayFolder: SSSO Obs linked to Conv
		lineageTag: 91bbeda9-37ed-48bd-8d67-7d32fd48fd78

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO: Obs LYTD_Final' =
			
			VAR kpi_ =  [SSSO: Obs LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: SSSO Obs linked to Conv
		lineageTag: 98ed311a-c660-46f1-b793-47fe4a9ef04b

	measure 'SSSO: Scrap-off LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [SSSO: Scrap-Off PY])
			VAR Result = Sumx(Table_,[Measure])
			RETURN
			IF(
			    ISBLANK(Result) || Result = 0,
			    BLANK(),
			    DIVIDE([SSSO: Scrap-Off] - Result,Result)
			)
			```
		displayFolder: SSSO Scrap-Off
		lineageTag: e48d7b6f-8e08-452e-bb79-f3074cced861

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO: Scrap-off LYTD_Final' =
			
			VAR kpi_ =  [SSSO: Scrap-off LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: SSSO Scrap-Off
		lineageTag: 316effff-f4a0-4f8c-a943-541a8d426b57

	measure 'Expired Inventory LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Expired Inventory PY])
			VAR Result = Sumx(Table_,[Measure])
			RETURN
			IF(
			    ISBLANK(Result) || Result = 0,
			    BLANK(),
			    DIVIDE([Expired Inventory] - Result,Result)
			)
			```
		displayFolder: Expired Inventory
		lineageTag: 0a4410a4-7467-48f9-a52b-33b847efd3eb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Expired Inv LYTD_Final' =
			
			VAR kpi_ =  [Expired Inventory LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Expired Inventory
		lineageTag: 9140535e-84cd-4c21-897e-094b1a7ce388

	measure 'Net Inventory LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Net Inventory PY])
			VAR Result = Sumx(Table_,[Measure])
			RETURN
			IF(
			    ISBLANK(Result) || Result = 0,
			    BLANK(),
			    DIVIDE([Net Inventory] - Result,Result)
			)
			```
		displayFolder: Net Inventory
		lineageTag: f14979e2-92d3-44d9-858c-08d95b5170c9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Inv LYTD_Final' =
			
			VAR kpi_ =  [Net Inventory LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Net Inventory
		lineageTag: bfa70ddd-90ae-4179-b065-a7a0c943d852

	measure 'Gross Inv LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Gross Inventory PY])
			VAR Result = Sumx(Table_,[Measure])
			RETURN
			IF(
			    ISBLANK(Result) || Result = 0,
			    BLANK(),
			    DIVIDE([Gross Inventory] - Result,Result)
			)
			```
		displayFolder: Gross Inventory
		lineageTag: ee1252bd-3a1c-49fd-bac9-7efd395e1d68

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Inv LYTD_Final' =
			
			VAR kpi_ =  [Gross Inv LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Gross Inventory
		lineageTag: a20a292a-4b3e-4119-8be1-50293d815c7c

	measure 'Inflated Inv LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Inflated Inventory PY])
			VAR Result = Sumx(Table_,[Measure])
			RETURN
			IF(
			    ISBLANK(Result) || Result = 0,
			    BLANK(),
			    DIVIDE([Inflated Inventory] - Result,Result)
			)
			
			```
		displayFolder: Inflated Inventory
		lineageTag: e99eb12f-5ad3-45ed-b43a-8f05fd69e574

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Inflated Inv LYTD_Final' =
			
			VAR kpi_ =  [Inflated Inv LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Inflated Inventory
		lineageTag: 3123b53e-4ff5-45de-85dd-b56f93987c7f

	measure 'Abs Demand Draft Var SSID LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Abs Demand Draft SSID_PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			
			```
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 21913c1a-f1aa-4646-a402-6a5245c4f03b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Shipments PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Total Shipments],filter_)
			
			```
		displayFolder: Forecast Accuracy CSCA
		lineageTag: bf9c1f1f-48eb-42d9-824a-04bd2e1f01b3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Demand Draft PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Demand Draft],filter_)
			
			```
		displayFolder: Forecast Accuracy CSCA
		lineageTag: ad09f2b5-753f-4f9c-bf79-cea517d8bf60

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Shipments LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Total Shipments PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			```
		displayFolder: Forecast Accuracy CSCA
		lineageTag: ac94a969-3364-47cd-966d-498cc0a2fc9e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Demand Draft LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Demand Draft PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			```
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 2eeb01ec-e144-4bee-b427-36bebe36fb41

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bias% LYTD' =
			
			VAR LYTD = DIVIDE(
			    [Demand Draft LYTD] - [Total Shipments LYTD],
			    [Total Shipments LYTD],
			    1
			)
			
			RETURN
			[Bias%] - LYTD
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Bias CSCA
		lineageTag: faa51ea4-40c2-4976-9f58-f6ff4f66f547

	measure 'Bias% LYTD_Final' =
			
			VAR kpi_ =  [Bias% LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Bias CSCA
		lineageTag: 25d92ae1-72a7-4baf-806c-7f9e37178e80

	measure 'On Delivery PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate(SUM(Fact_Service[On Delivery EA]),filter_)
			
			```
		displayFolder: Service Rate CSCA
		lineageTag: e35a7974-3b30-4d92-8d47-df731e16e29d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Order EA PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate(SUM(Fact_Service[Order EA]),filter_)
			
			```
		displayFolder: Service Rate CSCA
		lineageTag: 1a578270-15f3-4ed2-91fc-18155ff875c4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'On Delivery LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [On Delivery PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			```
		displayFolder: Service Rate CSCA
		lineageTag: 37f6a4fd-751f-44e4-9f3c-72922369532a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Order EA LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Order EA PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			```
		displayFolder: Service Rate CSCA
		lineageTag: 2a331d7d-5548-4b77-b2f0-f91920297a23

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Service Rate LYTD' = ```
			
			VAR LYTD = DIVIDE([On Delivery LYTD],[Order EA LYTD])
			
			RETURN
			
			IF(
			    ISBLANK(LYTD) || LYTD = 0,
			    BLANK(),
			    [Service Rate%] - LYTD
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Service Rate CSCA
		lineageTag: a261ab25-734f-45b1-9098-844703b727c0

	measure 'Service LYTD_Final' =
			
			VAR kpi_ =  [Service Rate LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Service Rate CSCA
		lineageTag: e6e2ffa9-c3ba-4edc-92b0-39f5c2afbb31

	measure '10% adh PY' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate(SUM(Fact_Schedule[+/- 10% Adh no penatly early]),filter_)
		formatString: 0
		displayFolder: Schedule Attainment
		lineageTag: 55149e56-1446-4d1b-94be-3291f02686d2

	measure 'SA Orders PY' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate(COUNT(Fact_Schedule[Order Number]),filter_)
		formatString: 0
		displayFolder: Schedule Attainment
		lineageTag: fc495e93-4093-405e-adfd-52c6aeb7749a

	measure 'SA Orders LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [SA Orders PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			```
		formatString: 0
		displayFolder: Schedule Attainment
		lineageTag: 38988536-c9a8-48fb-9877-7cf70ce8577b

	measure '10% adh LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [10% adh PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			```
		formatString: 0
		displayFolder: Schedule Attainment
		lineageTag: 9b2d34ba-c737-46cb-b62b-bcb0cefd7a43

	measure 'Schedule Attn LYTD' =
			
			VAR LYTD = DIVIDE([10% adh LYTD],[SA Orders LYTD],0)
			
			RETURN
			
			
			IF(
			    ISBLANK(LYTD) || LYTD = 0,
			    BLANK(),
			    [Schedule Attn] - LYTD
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Schedule Attainment
		lineageTag: 037e0363-67c1-477c-9988-e49593b0542e

	measure 'Schedule Attn LYTD_Final' =
			
			VAR kpi_ =  [Schedule Attn LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Schedule Attainment
		lineageTag: eafdc8e4-5706-4e9c-8be5-2f6c33b1d917

	measure 'Availability PY' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Availability],filter_)
		displayFolder: OEE
		lineageTag: b512ee63-1d69-4d0e-8bc1-1e8f618ae761

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Performance PY' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Performance],filter_)
		displayFolder: OEE
		lineageTag: da127939-584d-4900-a4ef-4f3b6b5a338d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quality PY' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Quality],filter_)
		displayFolder: OEE
		lineageTag: 5ee6bf44-be1f-4988-a991-50da4c7a810b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Availability LYTD' =
			
			DIVIDE([UpSeconds LYTD], [TotalElapsed LYTD])
		displayFolder: OEE
		lineageTag: de3816b7-d1a5-46cb-b4bf-5da8e3aa74c7

	measure 'Performance LYTD' =
			
			VAR Numerator = [OutCount LYTD] + [Qloss LYTD]
			VAR Denominator = [UpSeconds LYTD] * [RunSpeed LYTD]
			
			RETURN
			    DIVIDE(Numerator, Denominator)
		displayFolder: OEE
		lineageTag: 1ddb54d5-050e-43d1-8a12-2b57e145043d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quality LYTD' =
			
			Var QLoss = [InCount LYTD] - [OutCount LYTD]
			RETURN
			DIVIDE( [OutCount LYTD] , ([OutCount LYTD] + QLoss))
		displayFolder: OEE
		lineageTag: 92b75578-8ec5-494c-a7ee-61a73956103a

	measure 'OEE LYTD' =
			
			VAR LYTD = [Availability LYTD] * [Performance LYTD] * [Quality LYTD]
			
			RETURN
			[OEE%] - LYTD
		displayFolder: OEE
		lineageTag: 90a8417d-c800-4c0b-8d3f-58caf8318edc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Sales PY' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Net Sales Actual],filter_)
		displayFolder: Net Sales
		lineageTag: f0612baf-df21-450e-a16c-039e5d48c41d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Logistics PY' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Total Logistics Actual],filter_)
		displayFolder: Logistic
		lineageTag: 90d3fc12-3203-4393-bead-d5e3f14affc7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Sales LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Net Sales PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			```
		displayFolder: Net Sales
		lineageTag: fb8d8412-bf55-43bf-8414-1a1ab1e79c6a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Logistics LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Total Logistics PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			```
		displayFolder: Logistic
		lineageTag: 0dbf5aa3-a120-4158-aab4-af1aa482200f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Logistics on Net Sales LYTD' =
			
			VAR LYTD = DIVIDE([Total Logistics LYTD], [Net Sales LYTD])
			Return
			[Total Logistics on Net Sales Actual] - LYTD
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Logistic vs Net Sales
		lineageTag: 351fd67f-c2ac-43b4-8493-63a39ba5f98a

	measure 'Total Logistics on Net Sales LYTD_Final' =
			
			VAR kpi_ =  [Total Logistics on Net Sales LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Logistic vs Net Sales
		lineageTag: ed46c9e3-b567-40c7-9237-807f4341333a

	measure 'COGS Actual' = CALCULATE(SUM( Fact_Logistics[COGS Act] ),KEEPFILTERS( Dim_Profit_Center[FP&A Country] <> "Feldkirchen"))
		formatString: #,0.0
		displayFolder: COGS
		lineageTag: 7e900fc1-d7da-4408-9791-f6d9ca525dfb

	measure 'Distribution Actual' = SUM( Fact_Logistics[Distribution Act] )
		formatString: #,0.0
		displayFolder: Distribution on COGS
		lineageTag: 40143676-6e68-474c-b987-12a57612168e

	measure 'Total Distribution on COGS Actual' = DIVIDE([Distribution Actual], [COGS Actual])
		formatString: #,##0.00 %
		displayFolder: Distribution on COGS
		lineageTag: 246bab5b-5f23-426b-9849-450fdf0789a8

	measure 'Total Distribution on COGS Actual MoM%' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([Total Distribution on COGS Actual],filter_)
			VAR Result = ([Total Distribution on COGS Actual] - Net_PM)
			RETURN
			Result
		displayFolder: Distribution on COGS
		lineageTag: f6164a6e-06c1-4955-83d5-08abb011d1e6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Distribution on COGS Actual MoM_Final' = ```
			VAR kpi_ =  [Total Distribution on COGS Actual MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Distribution on COGS
		lineageTag: 0c7a413d-99e8-4b48-b21a-8d7fd310406f

	measure 'Total Distribution on COGS Actual PY' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Total Distribution on COGS Actual],filter_)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Distribution on COGS
		lineageTag: b3e849b6-697a-45f6-9fa0-3beb717c91d6

	measure 'Total Distribution on COGS Actual YoY%' = ([Total Distribution on COGS Actual] - [Total Distribution on COGS Actual PY])
		displayFolder: Distribution on COGS
		lineageTag: c09fcb89-9bdd-4a8b-b91f-2686a2899661

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Distribution on COGS Actual YoY_Final' =
			
			VAR kpi_ =  [Total Distribution on COGS Actual YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Distribution on COGS
		lineageTag: 9156dd9a-b554-4e7b-80d6-f589adb6b8c9

	measure 'Total Distribution on COGS Actual YTD' = DIVIDE([Distribution Actual YTD], [COGS Actual YTD])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Distribution on COGS
		lineageTag: 335e9732-9e14-4c58-9e92-ede5ae25f272

	measure 'Total Distribution on COGS LYTD' =
			VAR LYTD = DIVIDE([Distribution Actual LYTD], [COGS Actual LYTD_base])
			Return
			[Total Distribution on COGS Actual] - LYTD
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Distribution on COGS
		lineageTag: ab07fa53-6a44-45df-a715-931823e5b402

	measure 'Total Distribution on COGS LYTD_Final' =
			VAR kpi_ =  [Total Distribution on COGS LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Distribution on COGS
		lineageTag: b37b284b-95ec-42e5-9d2a-991a43506dc0

	measure 'Net Sales Actual LYTD' = ```
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Net Sales Actual PY])
			VAR Result = Sumx(Table_,[Measure])
			RETURN
			IF(
			    ISBLANK(Result) || Result = 0,
			    BLANK(),
			DIVIDE([Net Sales Actual] - Result,Result)
			)
			
			```
		displayFolder: Net Sales
		lineageTag: f5bfd51e-577e-4068-b2e9-744e962a282b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Sales Actual MoM%' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([Net Sales Actual],filter_)
			VAR Result = DIVIDE(([Net Sales Actual] - Net_PM),Net_PM)
			RETURN
			Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Net Sales
		lineageTag: 6402244c-beb6-4584-a832-01ff1ee84f22

	measure 'Net Sales Actual MoM_Final' = ```
			VAR kpi_ =  [Net Sales Actual MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Net Sales
		lineageTag: e78dd823-bb95-4db5-a192-f06a3242bf6d

	measure 'Net Sales Actual PY' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Net Sales Actual],filter_)
		formatString: 0.0
		displayFolder: Net Sales
		lineageTag: 7d117047-c6a0-448d-b58d-ba3bb75c27ee

	measure 'Net Sales Actual YoY%' = DIVIDE(([Net Sales Actual] - [Net Sales Actual PY]),[Net Sales Actual PY])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Net Sales
		lineageTag: 49a31613-3c41-4efb-8aa7-a9f551f83f1f

	measure 'Net Sales Actual YoY_Final' =
			VAR kpi_ =  [Net Sales Actual YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Net Sales
		lineageTag: c0a2ff2e-d5c9-4fbf-b171-b109474523f9

	measure 'Net Sales Actual YTD' =
			VAR _LastMonth = MAX(Dim_Date[P_YearMonth Number])
			VAR _SelectedYear = MAX(Dim_Date[P_Year])
			RETURN
			    SUMX(
			        FILTER(
			            ALL(Dim_Date),
			            Dim_Date[P_YearMonth Number] <= _LastMonth && Dim_Date[P_Year] = _SelectedYear
			        ),
			        [Net Sales Actual]
			    )
		formatString: 0.0
		displayFolder: Net Sales
		lineageTag: b11edf8c-cefe-4cc3-9526-21036874bc4b

	measure 'SSSO: Scrap-Off_APN' =
			
			VAR Plan = [SSSO: Scrap-off APN_Base]
			RETURN
			DIVIDE([SSSO: Scrap-Off] - Plan,Plan)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: SSSO Scrap-Off
		lineageTag: ac65b08e-974a-42b0-a164-9bdd48dcd45f

	measure 'SSSO: Scrap-Off APN_Final' =
			
			VAR kpi_ = [SSSO: Scrap-Off_APN]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: SSSO Scrap-Off
		lineageTag: 21844987-f1a1-4719-9392-b4ba21d78b12

	measure 'SSSO Obs_APN' = CALCULATE(SUM(Fact_SSSO[SSSO_APN]),KEEPFILTERS(Fact_SSSO[Functional Area] = "26"))
		displayFolder: SSSO Obs linked to Conv
		lineageTag: ef4d35ac-aa06-4f48-a4a4-4d9cda974439

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO Salvage_APN' = CALCULATE(SUM(Fact_SSSO[SSSO_APN]),KEEPFILTERS(Fact_SSSO[Functional Area] = "23"))
		displayFolder: SSSO Salvage & Obs
		lineageTag: 42afcbf4-21ef-466e-81e4-3fe05d52eec2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO: Salvage & Obsolescence_APN' =
			
			VAR Plan = [SSSO Obs_APN] - ABS([SSSO Salvage_APN])
			
			RETURN
			DIVIDE([SSSO: Salvage & Obsolescence] - Plan,Plan)
		displayFolder: SSSO Salvage & Obs
		lineageTag: 3750435d-8780-4de0-b54c-fd42db22cda1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO: Obsolescenes linked to Conversions_APN' =
			
			VAR Plan = [SSSO: Scrap-off APN_Base] + [SSSO Obs_APN] +[SSSO Salvage_APN]
			Return
			DIVIDE([SSSO: Obsolescenes linked to Conversions] - Plan,Plan)
		displayFolder: SSSO Obs linked to Conv
		lineageTag: f749e5b8-d710-409c-a57b-d0ce29623db1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO: Obs linked to conv APN_Final' =
			
			VAR kpi_ = [SSSO: Obsolescenes linked to Conversions_APN]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: SSSO Obs linked to Conv
		lineageTag: f3640b8a-837f-4e21-a79b-b392ad024a5a

	measure 'SSSO: Salvage & Obs APN_Final' =
			
			VAR kpi_ = [SSSO: Salvage & Obsolescence_APN]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: SSSO Salvage & Obs
		lineageTag: 13f4ceed-7b2c-4721-aaee-65f9cbfad71a

	measure 'SSSO: Scrap-off APN_Base' = CALCULATE(SUM(Fact_SSSO[SSSO_APN]),KEEPFILTERS(Fact_SSSO[Functional Area] = "25"))
		formatString: #,0.0
		displayFolder: SSSO Scrap-Off
		lineageTag: c6bc5888-52a9-46b0-aff9-98de4d5c2701

	measure 'SSSO Obs_F66' = CALCULATE(SUM(Fact_SSSO[SSSO_AFX]),KEEPFILTERS(Fact_SSSO[Functional Area] = "26"))
		displayFolder: SSSO Obs linked to Conv
		lineageTag: 24f7c7c7-ab3c-4583-8e31-c89184dc2fc5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO Salvage_F66' = CALCULATE(SUM(Fact_SSSO[SSSO_AFX]),KEEPFILTERS(Fact_SSSO[Functional Area] = "23"))
		displayFolder: SSSO Salvage & Obs
		lineageTag: fdd0a9a8-340f-4261-a9e7-fc3a78a59f05

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO: Scrap-off F66_Base' = CALCULATE(SUM(Fact_SSSO[SSSO_AFX]),KEEPFILTERS(Fact_SSSO[Functional Area] = "25"))
		displayFolder: SSSO Scrap-Off
		lineageTag: 1d590305-543e-4d21-8faa-9582eeec4b33

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO: Obsolescenes linked to Conversions_F66' =
			
			VAR Flex = [SSSO: Scrap-off F66_Base] + [SSSO Obs_F66] - ABS([SSSO Salvage_F66])
			Return
			DIVIDE([SSSO: Obsolescenes linked to Conversions] - Flex, Flex)
		displayFolder: SSSO Obs linked to Conv
		lineageTag: a06d55b6-f48d-470b-b41e-50dbc63128f0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO: Salvage & Obsolescence_F66' =
			
			VAR Flex = [SSSO Obs_F66] - ABS([SSSO Salvage_F66])
			
			RETURN
			DIVIDE([SSSO: Salvage & Obsolescence] - Flex,Flex)
		displayFolder: SSSO Salvage & Obs
		lineageTag: 1a881af0-4245-494d-8526-6454c17d25b4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO: Scrap-Off_F66' =
			
			VAR Flex = [SSSO: Scrap-off F66_Base]
			RETURN
			DIVIDE([SSSO: Scrap-Off] - Flex,Flex)
		displayFolder: SSSO Scrap-Off
		lineageTag: ef5b0062-6b17-4490-b459-3e6908ed4afc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO: Scrap-Off F66_Final' =
			
			VAR kpi_ = [SSSO: Scrap-Off_F66]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--" & UNICHAR(160) & UNICHAR(160),
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: SSSO Scrap-Off
		lineageTag: 6107e8fa-1aff-4a71-84f7-5b5204a2d9ba

	measure 'SSSO: Salvage & Obs F66_Final' =
			
			VAR kpi_ = [SSSO: Salvage & Obsolescence_F66]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--" & UNICHAR(160) & UNICHAR(160),
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: SSSO Salvage & Obs
		lineageTag: 92da5366-dd8d-4034-9f95-08feb5414b03

	measure 'SSSO: Obs linked to conv F66_Final' =
			
			VAR kpi_ = [SSSO: Obsolescenes linked to Conversions_F66]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--" & UNICHAR(160) & UNICHAR(160),
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: SSSO Obs linked to Conv
		lineageTag: 17d4210d-01ea-401a-bc1c-e4b9a420bf74

	measure 'Net Inventory_APN' =
			
			VAR Plan = SUM(Fact_CFIN_Inventory[Sum Amount CFIN Base_APN])
			Return
			DIVIDE([Net Inventory] - Plan,Plan)
		formatString: 0.0
		displayFolder: Net Inventory
		lineageTag: dea91ab1-376e-41a2-94b9-40567c1f94d3

	measure 'Net Inventory_APN_Final' =
			
			VAR kpi_ = [Net Inventory_APN]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: Net Inventory
		lineageTag: 05f96b73-d8ea-435f-a993-a27a69a9d52c

	measure 'Gross Inventory_APN' =
			
			VAR Plan = SUM(Fact_CFIN_Inventory[CFIN Amount Excl Inventory Reserves_APN])
			Return
			DIVIDE([Gross Inventory] - Plan,Plan)
		formatString: 0.0
		displayFolder: Gross Inventory
		lineageTag: cd27f9ca-ed25-446c-bf30-03a5aada6bf4

	measure 'Gross Inventory_APN_Final' =
			
			VAR kpi_ = [Gross Inventory_APN]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: Gross Inventory
		lineageTag: 35691105-4dc0-4a68-9821-d66b3535504f

	measure 'Total COGS GR_APN' = SUM(Fact_Group_Reporting[Total COGS GR_APN])
		displayFolder: DIO
		lineageTag: 47f7134b-c8f8-42b3-b492-7f9692953709

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total COGS GR_F66' = SUM(Fact_Group_Reporting[Total COGS GR_F66])
		displayFolder: DIO
		lineageTag: 1b8dbd3a-8a79-424b-887b-b6a3e7c2ed20

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total COGS GR L3M_APN' =
			
			VAR _Months = 3
			VAR _LastMonth = VALUE(MAX(Dim_Date[YearPeriodSeq]))
			VAR _FirstMonth = _LastMonth - (_Months-1)
			RETURN
			    SUMX(
			        FILTER(
			            ALL( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= _FirstMonth && Dim_Date[YearPeriodSeq] <= _LastMonth
			        ),
			        [Total COGS GR_APN]
			    )
		displayFolder: DIO
		lineageTag: f71acd17-18a7-4150-a734-a979fafc2a2b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total COGS GR L3M_F66' =
			
			VAR _Months = 3
			VAR _LastMonth = VALUE(MAX(Dim_Date[YearPeriodSeq]))
			VAR _FirstMonth = _LastMonth - (_Months-1)
			RETURN
			    SUMX(
			        FILTER(
			            ALL( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= _FirstMonth && Dim_Date[YearPeriodSeq] <= _LastMonth
			        ),
			        [Total COGS GR_F66]
			    )
		displayFolder: DIO
		lineageTag: 1b45230a-a501-4705-af53-d950841efdad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Inventory Avg L4M_APN' =
			
			VAR _LastMonth = MAX( Dim_Date[P_YearMonth Number] )
			VAR _FirstMonth = _LastMonth - 3
			RETURN
			    AVERAGEX(
			        FILTER(
			                ALL(Dim_Date),
			                Dim_Date[P_YearMonth Number] >= _FirstMonth && Dim_Date[P_YearMonth Number] <= _LastMonth
			            ),
			        [Net Inventory_APN_Base]
			    )
		displayFolder: DIO
		lineageTag: 50049c20-3838-40dc-8005-65e907a8c38f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Inventory_AFX' =
			
			VAR Plan = SUM(Fact_CFIN_Inventory[Sum Amount CFIN Base_AFX])
			Return
			DIVIDE([Net Inventory] - Plan,Plan)
		displayFolder: Net Inventory
		lineageTag: 1a6d149f-7ab4-4821-84dc-b2135765c2fe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Inventory_AFX_Final' =
			
			VAR kpi_ = [Net Inventory_AFX]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: Net Inventory
		lineageTag: 7765cc42-76e3-482e-accd-37b7dea30b8c

	measure 'Gross Inventory_AFX' =
			
			VAR Plan = SUM(Fact_CFIN_Inventory[CFIN Amount Excl Inventory Reserves_AFX])
			Return
			DIVIDE([Gross Inventory] - Plan,Plan)
		displayFolder: Gross Inventory
		lineageTag: 3166704e-1944-4b2f-82b2-b8d899f5ea54

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Inventory_AFX_Final' =
			
			VAR kpi_ = [Gross Inventory_AFX]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: Gross Inventory
		lineageTag: 34b31ed7-35e2-435c-9750-0a286d955337

	measure 'Inventory Avg L4M_AFX' =
			
			VAR _LastMonth = MAX( Dim_Date[P_YearMonth Number] )
			VAR _FirstMonth = _LastMonth - 3
			RETURN
			    AVERAGEX(
			        FILTER(
			                ALL(Dim_Date),
			                Dim_Date[P_YearMonth Number] >= _FirstMonth && Dim_Date[P_YearMonth Number] <= _LastMonth
			            ),
			        [Net Inventory_AFX_Base]
			    )
		displayFolder: DIO
		lineageTag: 1d836b86-74d9-4914-a758-13d1e8843eb0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DIO_APN =
			
			VAR _Months = 3
			VAR _TotalCOGS = [Total COGS GR L3M_APN]
			VAR _AvgInventory = [Inventory Avg L4M_APN]
			VAR DIO_APN = DIVIDE( _AvgInventory, _TotalCOGS ) * (30.3333*_Months)
			VAR result_ = DIVIDE([DIO] - DIO_APN,DIO_APN)
			Return
			IF(SELECTEDVALUE(Dim_Date[Is Closed]) = "TRUE",result_,BLANK())
		displayFolder: DIO
		lineageTag: 3efae6b5-9132-4770-8bbc-31d9ccb31773

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Inventory_APN_Base' = SUM(Fact_CFIN_Inventory[Sum Amount CFIN Base_APN])
		formatString: #,0.0
		displayFolder: Net Inventory
		lineageTag: 0d105d9e-a36a-4628-a7fb-8bddb0fa9c2c

	measure 'Net Inventory_AFX_Base' = SUM(Fact_CFIN_Inventory[Sum Amount CFIN Base_AFX])
		formatString: 0.0
		displayFolder: Net Inventory
		lineageTag: 9807b10b-d809-47da-96bb-8dea45b15067

	measure DIO_AFX =
			
			VAR _Months = 3
			VAR _TotalCOGS = [Total COGS GR L3M_F66]
			VAR _AvgInventory = [Inventory Avg L4M_AFX]
			VAR DIO_AFX = DIVIDE( _AvgInventory, _TotalCOGS ) * (30.3333*_Months)
			RETURN
			DIVIDE([DIO] - DIO_AFX,DIO_AFX)
		formatString: 0
		displayFolder: DIO
		lineageTag: d193275c-5ee7-4be5-bc27-aa4de6535bfa

	measure DIO_APN_Final =
			
			VAR kpi_ = [DIO_APN]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: DIO
		lineageTag: da4d3b8d-384c-414c-b722-42a516f9194b

	measure DIO_AFX_Final =
			
			VAR kpi_ = [DIO_AFX]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--" & UNICHAR(160) & UNICHAR(160),
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: DIO
		lineageTag: 84156bc6-800c-4d2d-98eb-a622c97edbf3

	measure 'Bias Target' =
			SWITCH(SELECTEDVALUE(Fact_Forecast_Accuracy[LAGs]),"2",[Bias Target CSCA L2],
			                "4",[Bias Target CSCA L4])
		formatString: 0
		displayFolder: Bias CSCA
		lineageTag: 9b70de51-c52b-40ec-b49f-fa4d3d19c7a5

	measure 'Bias Target Diff%' = [Bias%] - [Bias Target]
		displayFolder: Bias CSCA
		lineageTag: 31b95f59-f1f2-4e9e-8ad3-b700a5ec0a67

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bias Target Final' = ```
			
			VAR kpi_ =  [Bias Target Diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Bias CSCA
		lineageTag: 6f405e16-c864-4672-abad-4618e66d8990

	measure 'FA% Target Diff%' = [FA% CSCA] - [FA% Target]
		displayFolder: Forecast Accuracy CSCA
		lineageTag: f8c238b7-9903-49f5-8b93-b1fee299a466

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FA% Target Final' = ```
			
			VAR kpi_ =  [FA% Target Diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_
			```
		displayFolder: Forecast Accuracy CSCA
		lineageTag: a97a81a8-42c9-4673-8b3b-8e973fd3df0e

	measure 'FA% Target' =
			SWITCH(SELECTEDVALUE(Fact_Forecast_Accuracy[LAGs]),"2",[FA% Lag2 Target],
			                "4",[FA% Lag4 Target])
		formatString: 0%;-0%;0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: f9f909fa-4805-4fff-9fa6-ae40907d873d

	measure DIO_APN_Base =
			
			VAR _Months = 3
			VAR _TotalCOGS = CALCULATE([Total COGS GR L3M_APN],KEEPFILTERS(Dim_Date[Is Closed] = "TRUE"))
			VAR _AvgInventory = CALCULATE([Inventory Avg L4M_APN],KEEPFILTERS(Dim_Date[Is Closed] = "TRUE"))
			VAR DIO_APN = DIVIDE( _AvgInventory, _TotalCOGS ) * (30.3333*_Months)
			Return DIO_APN
		formatString: 0
		displayFolder: DIO
		lineageTag: 9725eeeb-adca-4efd-bbae-1628c705f73d

	measure 'SSSO: Obso Conv_APN_Base' =
			
			VAR Plan = [SSSO: Scrap-off APN_Base] + [SSSO Obs_APN] + [SSSO Salvage_APN]
			Return
			Plan
		formatString: #,0.0
		displayFolder: SSSO Obs linked to Conv
		lineageTag: 4a4d94d0-443e-4361-8ee4-263d08ffd0ff

	measure 'SSSO: Salvage & Obs_APN_Base' =
			
			VAR Plan = [SSSO Obs_APN] - ABS([SSSO Salvage_APN])
			
			RETURN
			Plan
		formatString: #,0.0
		displayFolder: SSSO Salvage & Obs
		lineageTag: 3123962c-f633-44ad-8d28-5c9edc3ed778

	measure 'Gross Inventory_APN_Base' = SUM(Fact_CFIN_Inventory[CFIN Amount Excl Inventory Reserves_APN])
		formatString: #,0.0
		displayFolder: Gross Inventory
		lineageTag: 923789d1-04ab-4bf1-81cf-7a23a989ff04

	measure 'DSO MoM%' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[P_YearPeriod Seq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[P_YearPeriod Seq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([DSO],filter_)
			VAR Result = DIVIDE(([DSO] - Net_PM),Net_PM)
			RETURN
			IF(SELECTEDVALUE(Dim_Date[Is Closed]) = "TRUE",Result,BLANK())
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: DSO
		lineageTag: f00c3261-e678-4bc3-a778-0e350c9d9463

	measure 'DSO MoM_Final' = ```
			VAR kpi_ =  [DSO MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: DSO
		lineageTag: a4851f23-dcc5-4b93-8c61-36da0c83138e

	measure 'DSO PY' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX( Dim_Date[P_YearPeriod Seq] ) )
			VAR Filter_ = Filter(alldate_, Dim_Date[P_YearPeriod Seq] = YearPeriodSeq_ -12 )
			VAR py = Calculate([DSO],filter_)
			RETURN
			IF(SELECTEDVALUE(Dim_Date[Is Closed]) = "TRUE", py,BLANK())
		formatString: 0
		displayFolder: DSO
		lineageTag: fe74a30a-f128-4741-b255-ca2807093aa5

	measure 'DSO YoY%' =
			
			IF(SELECTEDVALUE(Dim_Date[Is Closed]) = "TRUE",DIVIDE(([DSO] - [DSO PY]),[DSO PY]),BLANK())
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: DSO
		lineageTag: 3aa2fbeb-9adb-446e-8192-f6b3d54c7143

	measure 'DSO YoY_Final' =
			VAR kpi_ =  [DSO YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: DSO
		lineageTag: 81ef3bf6-840e-4121-ae52-954adcc5f548

	measure 'DPO MoM%' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[P_YearPeriod Seq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[P_YearPeriod Seq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([DPO],filter_)
			VAR Result = DIVIDE(([DPO] - Net_PM),Net_PM)
			RETURN
			IF(SELECTEDVALUE(Dim_Date[Is Closed]) = "TRUE",Result,BLANK())
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: DPO
		lineageTag: 14d57b82-c1d1-40d7-aacc-2a071f0d1aa7

	measure 'DPO PY' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[P_YearPeriod Seq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[P_YearPeriod Seq] = YearPeriodSeq_ -12 )
			VAR py = Calculate([DPO],filter_)
			RETURN
			IF(SELECTEDVALUE(Dim_Date[Is Closed]) = "TRUE", py,BLANK())
		displayFolder: DPO
		lineageTag: e71f96e7-d219-4803-aab8-122e31db49dc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DPO MoM_Final' = ```
			VAR kpi_ =  [DPO MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: DPO
		lineageTag: 55aeb62b-3023-4793-ac4e-61ac62bcb03b

	measure 'DPO YoY%' =
			
			IF(SELECTEDVALUE(Dim_Date[Is Closed]) = "TRUE",DIVIDE(([DPO] - [DPO PY]),[DPO PY]),BLANK())
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: DPO
		lineageTag: 46cee9b0-13c2-4a75-86e6-40e0bdfe09b6

	measure 'DPO YoY_Final' =
			VAR kpi_ =  [DPO YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: DPO
		lineageTag: 1e459b4e-d603-4789-bced-26ddb25e6c69

	measure 'A&P Actual' = SUM( Fact_Logistics[A&P Act] )
		formatString: #,0.0
		displayFolder: Logistic
		lineageTag: b6cfb028-53cd-4da8-94e0-b182d12c82d1

	measure 'COGS Actual YTD' =
			VAR _LastMonth = MAX(Dim_Date[P_YearMonth Number])
			VAR _SelectedYear = MAX(Dim_Date[P_Year])
			RETURN
			    SUMX(
			        FILTER(
			            ALL(Dim_Date),
			            Dim_Date[P_YearMonth Number] <= _LastMonth && Dim_Date[P_Year] = _SelectedYear
			        ),
			        [COGS Actual]
			    )
		formatString: 0.0
		displayFolder: COGS
		lineageTag: 66521ec5-41cf-4b2f-b04e-9150d2a8ea42

	measure 'COGS Actual YoY_Final' =
			VAR kpi_ =  [COGS Actual YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: COGS
		lineageTag: c55cb5a3-2c97-4468-9b42-27bb2165fcd2

	measure 'COGS Actual YoY%' = DIVIDE(([COGS Actual] - [COGS Actual PY]),[COGS Actual PY])
		displayFolder: COGS
		lineageTag: 8d5d26fc-0402-42c2-9751-1908eea9f002

	measure 'COGS Actual PY' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([COGS Actual],filter_)
		formatString: 0.0
		displayFolder: COGS
		lineageTag: b8d4fa82-0c70-4cce-bdb4-deb8e98cda0b

	measure 'COGS Actual MoM_Final' = ```
			VAR kpi_ =  [COGS Actual MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: COGS
		lineageTag: 3ce3d6f9-c8e2-490f-99dd-87e17815011c

	measure 'COGS Actual MoM%' =
			
			VAR Result = DIVIDE(([COGS Actual] - [COGS Actual PP]), [COGS Actual PP])
			RETURN
			Result
		displayFolder: COGS
		lineageTag: bec1d2f8-05fd-45df-b5fb-9c2a5633ac42

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'COGS Actual LYTD_Final' =
			VAR kpi_ =  [COGS Actual LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: COGS
		lineageTag: 31d4fe84-7b85-40da-921f-0e31ebca0212

	measure 'COGS Actual LYTD' = ```
			
			/* 
			VAR LYTD = DIVIDE([Total Logistics LYTD], [Net Sales LYTD])
			Return
			[COGS Actual] - LYTD
			*/
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [COGS Actual PY])
			VAR Result = Sumx(Table_,[Measure])
			RETURN
			IF(
			    ISBLANK(Result) || Result = 0,
			    BLANK(),
			    DIVIDE([COGS Actual] - Result,Result)
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: COGS
		lineageTag: d8f994c5-a505-40f9-897d-e130bbe14d4c

	measure 'Net Sales_APN' =
			
			VAR Plan = [Net Sales_APN_Base]
			Return
			DIVIDE([Net Sales Actual] - Plan,Plan)
		formatString: 0.0
		displayFolder: Net Sales
		lineageTag: c8f6ad87-2541-4e46-9b36-3c1e8929f88e

	measure 'Net Sales_APN_Base' = SUM(Fact_Logistics[Net Sales Plan])
		formatString: #,0.0
		displayFolder: Net Sales
		lineageTag: 9f154c40-d040-4652-ab9a-8c71ec47430a

	measure 'Net Sales_APN_Final' =
			
			VAR kpi_ = [Net Sales_APN]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: Net Sales
		lineageTag: 9ab22e72-1632-49da-b30e-478950c77f2c

	measure COGS_APN_Base = SUM(Fact_Logistics[COGS Plan])
		formatString: #,0.0
		displayFolder: COGS
		lineageTag: cea78f18-8adc-4a21-a812-c9505f437c7b

	measure COGS_APN_Final =
			VAR kpi_ = [COGS_APN]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: COGS
		lineageTag: bfeb341f-a5df-4b86-99cf-b3497b92efdd

	measure COGS_APN =
			VAR Plan = [COGS_APN_Base]
			Return
			DIVIDE([COGS Actual] - Plan,Plan)
		formatString: 0.0
		displayFolder: COGS
		lineageTag: 2070f4d1-eb29-4830-a546-f0a69c842f1b

	measure 'Total Logistics on Net Sales_APN_Base' = DIVIDE([Total Logistics Plan], [Net Sales Plan])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Logistic vs Net Sales
		lineageTag: bc33c33c-ee18-4264-b324-a6653a2b62c1

	measure 'Total Logistics on Net Sales_APN_Final' =
			VAR kpi_ = [Total Logistics on Net Sales_APN]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: Logistic vs Net Sales
		lineageTag: 5e0fc1d5-94c9-4209-8919-df2326df76c6

	measure 'Total Logistics on Net Sales_APN' =
			VAR Plan = [TOTAL LOGISTICS ON NET SALES_APN_Base]
			Return
			[TOTAL LOGISTICS ON NET SALES Actual] - Plan
		displayFolder: Logistic vs Net Sales
		lineageTag: 6f110007-c1f5-4959-b021-e638515216df

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Distribution Plan' = SUM( Fact_Logistics[Distribution Plan] )
		formatString: #,0.0
		displayFolder: Logistic
		lineageTag: 1cee0a10-6ba2-43b6-9537-cb1877f531b1

	measure 'Total Distribution on COGS_APN_Base' = DIVIDE([Distribution Plan], [COGS_APN_Base])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Distribution on COGS
		lineageTag: 20d604fe-5412-4f66-9dc1-e4eeaeba852f

	measure 'Total Distribution on COGS_APN_Final' =
			
			VAR kpi_ = [Total Distribution on COGS_APN]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_  & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: Distribution on COGS
		lineageTag: aa5e4a3c-44cb-492d-97ba-1983faff1881

	measure 'Total Distribution on COGS_APN' =
			VAR Plan = [TOTAL DISTRIBUTION ON COGS_APN_Base]
			Return
			[TOTAL DISTRIBUTION ON COGS Actual] - Plan
		displayFolder: Distribution on COGS
		lineageTag: 17d4541b-ecef-4574-80e1-af6f34948ead

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Variances Act' = SUM(Fact_Logistics[Variances Act])
		formatString: 0.0
		displayFolder: Logistic
		lineageTag: 18b246d9-93e1-4418-b7b7-bd3a7b5fa1eb

	measure 'Last Closed Period' = MAX('Other_Last Closed Month'[Period])
		displayFolder: Misc
		lineageTag: a456bda2-a8b3-4ca5-8f3e-396099d120bc

	measure 'Customer Fines' = SUM(Fact_Customer_Fines[Split Amount])
		displayFolder: Customer Fines
		lineageTag: cd5c859a-f58b-4c18-a251-dfac7c02e692

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Customer Fines Target' =
			
			SWITCH(SELECTEDVALUE(CG_PeriodSelection[Period]), "PTD", 5000000/12, "YTD", 5000000,5000000/12)
		formatString: 0.0
		displayFolder: Customer Fines
		lineageTag: c3739011-c277-427f-8f38-9f257bc37879

	measure 'Cust Fine Target Diff%' = ([Customer Fines] - [Customer Fines Target])/[Customer Fines Target]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Customer Fines
		lineageTag: c3cf8efd-60bf-4447-b97e-83a79c27ccf5

	measure 'Cust fine Target Final' = ```
			
			VAR kpi_ =  [Cust Fine Target Diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Customer Fines
		lineageTag: 302e159f-02ca-4240-95cd-574c5822ae41

	measure 'Cust fine PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Customer Fines],filter_)
			
			```
		displayFolder: Customer Fines
		lineageTag: 9cbdfb3e-a977-4ed4-9153-1750b35e5d8a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cust Fine MoM%' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([Customer Fines],filter_)
			VAR Result = DIVIDE(([Customer Fines] - Net_PM),Net_PM)
			RETURN
			Result
		displayFolder: Customer Fines
		lineageTag: fe18fc17-577b-41a9-aa1b-6d734ca202f0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cust Fine MoM_Final' = ```
			
			VAR kpi_ =  [Cust Fine MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Customer Fines
		lineageTag: ebbcda50-cd61-4217-8cbf-4062252d8abc

	measure 'Cust fine YoY%' = DIVIDE(([Customer Fines] - [Cust fine PY]),[Cust fine PY])
		displayFolder: Customer Fines
		lineageTag: d8fc74b6-ea15-419f-ab5b-93c07a181dbb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cust fine YoY_Final' =
			VAR kpi_ =  [Cust fine YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: Customer Fines
		lineageTag: 7f35a72a-ad49-4fc6-a1de-ab260d7e3659

	measure 'Cust Fine LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Cust fine PY])
			VAR Result = Sumx(Table_,[Measure])
			RETURN
			IF(
			    ISBLANK(Result) || Result = 0,
			    BLANK(),
			    DIVIDE([Customer Fines] - Result,Result)
			)
			```
		displayFolder: Customer Fines
		lineageTag: f082c729-559a-4147-919a-3224a0289d29

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cust fine LYTD_Final' =
			
			VAR kpi_ =  [Cust Fine LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Customer Fines
		lineageTag: e2b8381c-1566-419d-a46b-d188e7aee462

	measure 'Cust Fine YTD' =
			VAR _LastMonth = MAX(Dim_Date[P_YearMonth Number])
			VAR _SelectedYear = MAX(Dim_Date[P_Year])
			RETURN
			    SUMX(
			        FILTER(
			            ALL(Dim_Date),
			            Dim_Date[P_YearMonth Number] <= _LastMonth && Dim_Date[P_Year] = _SelectedYear
			        ),
			        [Customer Fines]
			    )
		displayFolder: Customer Fines
		lineageTag: 491729bf-985d-4a67-8c09-e5f7944fb6d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CFR = DIVIDE(SUM(Fact_CFR[Total Delivery Qty]),SUM(Fact_CFR[Total Order Qty]))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: CFR
		lineageTag: 83654486-06bd-4611-a666-f4c519e66c22

	measure 'CFR MoM%' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([CFR],filter_)
			VAR Result = [CFR] - Net_PM
			RETURN
			Result
		displayFolder: CFR
		lineageTag: a5228272-383a-403f-a1df-0c5eb0e4c58c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CFR MoM_Final' = ```
			
			VAR kpi_ =  [CFR MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: CFR
		lineageTag: a3a2a02b-5174-4a2d-b8e5-ce9364027251

	measure 'CFR PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([CFR],filter_)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: CFR
		lineageTag: f5cbfb6a-9765-40a7-bc2a-b009faf0d190

	measure 'CFR YoY%' = [CFR] - [CFR PY]
		displayFolder: CFR
		lineageTag: ce2aa45d-dce4-46b8-818a-54b52a7a34a4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CFR YoY_Final' =
			
			VAR kpi_ =  [CFR YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: CFR
		lineageTag: 02349e52-cc46-4d70-aae2-21cf5f0ee688

	measure 'CFR YTD' = TOTALYTD([CFR],Dim_Date[Date])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: CFR
		lineageTag: 6cf517c7-1ebc-4631-84ed-dc9ad0bda325

	measure 'CFR Target' =
			
			Var tar = CALCULATE(MAX(Fact_Target[Target]),KEEPFILTERS(Fact_Target[KPI_Name] = "Case Fill Rate (%)"))
			RETURN
			DIVIDE(tar,100)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: CFR
		lineageTag: 8bbb56f3-5ed0-49de-973d-a77b571c748e

	measure 'CFR Target Diff%' = [CFR] - [CFR Target]
		displayFolder: CFR
		lineageTag: ec953ac8-eea9-46b4-a964-7e1d07b91b8d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CFR Target Final' = ```
			
			VAR kpi_ =  [CFR Target Diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: CFR
		lineageTag: 99e52b5f-6b97-486d-95ed-9af365e6dbc1

	measure 'CFR Orders LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [CFR Orders PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			```
		formatString: 0
		displayFolder: CFR
		lineageTag: 80f18d2e-06f0-45be-9cfa-e61b46184e05

	measure 'CFR Orders PY' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate(SUM(Fact_CFR[Total Order Qty]),filter_)
		displayFolder: CFR
		lineageTag: cd726723-73fe-48bf-b648-45c7a2297aeb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CFR Delivery PY' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate(SUM(Fact_CFR[Total Delivery Qty]),filter_)
		displayFolder: CFR
		lineageTag: f688c17e-624e-4e30-8f66-b3dda6d7e256

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CFR Delivery LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [CFR Delivery PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			```
		displayFolder: CFR
		lineageTag: bfa6947f-50c9-405e-84bf-7d0ac7d6a49a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CFR LYTD' =
			
			VAR LYTD = DIVIDE([CFR Delivery LYTD], [CFR Orders LYTD],0)
			
			RETURN
			[CFR] - LYTD
		displayFolder: CFR
		lineageTag: aa344dab-9b4c-4adb-8287-425bd5799471

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CFR LYTD_Final' =
			
			VAR kpi_ =  [CFR LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: CFR
		lineageTag: 848a9169-1ce4-443f-9f9e-cb5a55d25b96

	measure 'Schedule Attn Target' =
			
			Var tar = CALCULATE(MAX(Fact_Target[Target]),KEEPFILTERS(Fact_Target[KPI_Name] = "Schedule Attainment (%)"))
			RETURN
			DIVIDE(tar,100)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Schedule Attainment
		lineageTag: e957bc12-a25a-4558-b37a-9fa5c668af90

	measure 'Schedule Attn Target Diff%' = [Schedule Attn] - [Schedule Attn Target]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Schedule Attainment
		lineageTag: 368e7ee8-4894-41bd-bc41-9ca1726622c8

	measure 'Schedule Attn Target Final' = ```
			
			VAR kpi_ =  [Schedule Attn Target Diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Schedule Attainment
		lineageTag: b73a7e1c-d281-40f3-a4b2-faa86574c30d

	measure 'Bias% Lag 2' = CALCULATE([Bias%],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "2"))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Bias CSCA
		lineageTag: 17de22a2-87ff-49bf-86bb-dc2d7c9d4548

	measure 'Bias% Lag 4' = CALCULATE([Bias%],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "4"))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Bias CSCA
		lineageTag: ec6dde8d-416d-4a4d-8283-a3949d80e5ad

	measure 'FA% Lag2 MoM_Final' = CALCULATE([FA% MoM_Final],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "2")) & UNICHAR(160) & UNICHAR(160)
		displayFolder: Forecast Accuracy CSCA
		lineageTag: f5b7a238-1542-43b3-83b9-234764c5b2b2

	measure 'FA% Lag4 MoM_Final' = CALCULATE([FA% MoM_Final],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "4")) & UNICHAR(160) & UNICHAR(160)
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 10a7b0ab-74da-4eed-93ba-421bba673144

	measure 'FA% Lag2 YTD' = CALCULATE([FA% YTD],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "2"))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: d4f2b3eb-73a4-4081-b735-45fdd659570f

	measure 'FA% Lag4 YTD' = CALCULATE([FA% YTD],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "4"))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: f1a705da-865a-4c1e-92a9-946cae5afcfc

	measure 'FA% Lag2 YoY_Final' = CALCULATE([FA% YoY_Final],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2")) & UNICHAR(160) & UNICHAR(160)
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 0a4838cf-2a77-4adc-b8eb-b5c34e9f41b0

	measure 'FA% Lag4 YoY_Final' = CALCULATE([FA% YoY_Final],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")) & UNICHAR(160) & UNICHAR(160)
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 48be6021-6ecb-4f61-8443-571475aba586

	measure 'FA% Lag2 Target_Final' = ```
			
			VAR kpi_ =  [FA% Lag 2 Target Diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 5724b98e-7ae9-4c7f-af35-c9e2c3ccd295

	measure 'FA% Lag4 Target_Final' = ```
			
			VAR kpi_ =  [FA% Lag 4 Target Diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Forecast Accuracy CSCA
		lineageTag: aace5e30-2c4b-446d-9be4-445043d6cceb

	measure 'Bias% Lag2 YTD' = CALCULATE([Bias YTD],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "2"))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Bias CSCA
		lineageTag: 3717fe84-6e88-431a-a391-0b7c5a96ea1b

	measure 'Bias% Lag4 YTD' = CALCULATE([Bias YTD],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "4"))
		displayFolder: Bias CSCA
		lineageTag: f110cf14-10af-4d24-8acb-94386f93722b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bias% Lag2 MoM_Final' = CALCULATE([Bias MoM_Final],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "2")) & UNICHAR(160) & UNICHAR(160)
		displayFolder: Bias CSCA
		lineageTag: 5157d3ba-6d28-48f7-a042-1711b507c54d

	measure 'Bias% Lag4 MoM_Final' = CALCULATE([Bias MoM_Final],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "4")) & UNICHAR(160) & UNICHAR(160)
		displayFolder: Bias CSCA
		lineageTag: 4057c104-8b6d-4d85-a4c2-4e7e6c42e89c

	measure 'Bias% Lag2 YoY_Final' = CALCULATE([Bias YoY_Final],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "2")) & UNICHAR(160) & UNICHAR(160)
		displayFolder: Bias CSCA
		lineageTag: ff13f938-aadc-4d15-8d88-959041903777

	measure 'Bias% Lag4 YoY_Final' = CALCULATE([Bias YoY_Final],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "4")) & UNICHAR(160) & UNICHAR(160)
		displayFolder: Bias CSCA
		lineageTag: 82910963-7603-445c-8ed0-8300cd828ec5

	measure 'Bias% Lag2 Target_Final' = CALCULATE([Bias Target Final],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "2")) & UNICHAR(160) & UNICHAR(160)
		displayFolder: Bias CSCA
		lineageTag: f1d1f4a2-79d6-4535-8f06-b949d1ab8c03

	measure 'Bias% Lag4 Target_Final' = CALCULATE([Bias Target Final],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "4")) & UNICHAR(160) & UNICHAR(160)
		displayFolder: Bias CSCA
		lineageTag: 6f47bf01-3bf2-4b63-9fb9-ed2d7b8c2784

	measure Switch_YoY_WC = ```
			SWITCH(
			    VALUES( Working_Capital_Parameter[Working_Capital_Parameter] ),
			    "Gross Inventory", [Gross Inventory PY],
			    "Net Inventory", [Net Inventory PY],
			    "Inflated Inventory", [Inflated Inventory PY],
			    "Expired Inventory", [Expired Inventory PY],
			    "DSO", [DSO PY],
			    "DPO", [DPO PY],
			    "DIO", [DIO PY]
			)
			
			```
		displayFolder: Switch Measures
		lineageTag: 4bb47335-25f8-49c4-8c4b-2fe57298f8d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Switch_YTD_WC = ```
			SWITCH(
			    VALUES( Working_Capital_Parameter[Working_Capital_Parameter] ),
			    "Gross Inventory", [Gross Inventory],
			    "Net Inventory", [Net Inventory],
			    "Inflated Inventory", [Inflated Inventory],
			    "Expired Inventory", [Expired Inventory],
			    "DSO", [DSO],
			    "DPO", [DPO],
			    "DIO", [DIO]
			)
			
			```
		displayFolder: Switch Measures
		lineageTag: 3dfab3aa-5487-40cc-b7f9-d097382a68cf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Inventory PP' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([Gross Inventory],filter_)
			
			RETURN Net_PM
		formatString: 0.0
		displayFolder: Gross Inventory
		lineageTag: 4afd3352-435d-44d6-8cb0-ef4b0a996b95

	measure 'Gross Inventory AFX_Base' = SUM(Fact_CFIN_Inventory[CFIN Amount Excl Inventory Reserves_AFX])
		formatString: 0.0
		displayFolder: Gross Inventory
		lineageTag: ef997859-1e98-4aaa-987a-ffffbca1df49

	measure 'Net Inventory PP' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([Net Inventory],filter_)
			
			RETURN Net_PM
		displayFolder: Net Inventory
		lineageTag: a1c51a58-bd49-486a-9088-9e3c06bf4d54

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Inflated Inventory PP' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([Inflated Inventory],filter_)
			
			RETURN Net_PM
		displayFolder: Inflated Inventory
		lineageTag: e450dc66-6c0e-4227-ad00-877c695da019

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Expired Inventory PP' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([Expired Inventory],filter_)
			
			RETURN Net_PM
		displayFolder: Expired Inventory
		lineageTag: d4285329-2bbd-4d47-804a-db22e39ebd96

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DSO PP' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[P_YearPeriod Seq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[P_YearPeriod Seq] = YearPeriodSeq_ -1)
			VAR Net_PM = Calculate([DSO],Filter_)
			Return
			IF(SELECTEDVALUE(Dim_Date[Is Closed]) = "TRUE", Net_PM, BLANK())
		formatString: 0
		displayFolder: DSO
		lineageTag: 6bc0d88b-1789-42c2-988d-a9c07a0d74fb

	measure 'DPO PP' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[P_YearPeriod Seq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[P_YearPeriod Seq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([DPO],filter_)
			Return
			IF(SELECTEDVALUE(Dim_Date[Is Closed]) = "TRUE", Net_PM, BLANK())
		formatString: 0
		displayFolder: DPO
		lineageTag: 9d6914cb-166c-481f-b866-f6065ccaa1d0

	measure 'DIO PP' = ```
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[P_YearPeriod Seq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[P_YearPeriod Seq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([DIO],filter_)
			Return 
			IF(SELECTEDVALUE(Dim_Date[Is Closed]) = "TRUE",Net_PM,BLANK())
			```
		formatString: 0
		displayFolder: DIO
		lineageTag: d0d62941-df3d-4645-ac92-a3d25fd8f8af

	measure DIO_AFX_Base =
			
			VAR _Months = 3
			VAR _TotalCOGS = CALCULATE([Total COGS GR L3M_F66],KEEPFILTERS(Dim_Date[Is Closed] = "TRUE"))
			VAR _AvgInventory = CALCULATE([Inventory Avg L4M_AFX],KEEPFILTERS(Dim_Date[Is Closed] = "TRUE"))
			VAR DIO_AFX = DIVIDE( _AvgInventory, _TotalCOGS ) * (30.3333*_Months)
			RETURN
			DIO_AFX
		displayFolder: DIO
		lineageTag: b0673e43-b8e3-40f2-9a23-471c82837c7d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OEE% PP' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([OEE%],filter_)
			
			RETURN
			Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: OEE
		lineageTag: 3b8f33e5-3af8-4eb3-9916-b2aea00f4a02

	measure Switch_Plan_WC = ```
			SWITCH(
			    VALUES( Working_Capital_Parameter[Working_Capital_Parameter] ),
			    "Gross Inventory", [Gross Inventory_APN_Base],
			    "Net Inventory", [Net Inventory_APN_Base],
			    "DIO", [DIO_APN_Base],
			    "DSO", [DSO_APN_Base],
			    "DPO", [DPO_APN_Base]
			)
			
			```
		displayFolder: Switch Measures
		lineageTag: 658d96ab-c80b-42f5-befc-3d8ec474e452

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Switch_Flex_WC = ```
			SWITCH(
			    VALUES( Working_Capital_Parameter[Working_Capital_Parameter] ),
			    "Gross Inventory", [Gross Inventory_AFX_Base],
			    "Net Inventory", [Net Inventory_AFX_Base],
			    "DIO", [DIO_AFX_Base]
			)
			
			```
		displayFolder: Switch Measures
		lineageTag: 46263d21-280a-490a-baef-9d581928d279

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Inventory_AFX_Base' = SUM(Fact_CFIN_Inventory[CFIN Amount Excl Inventory Reserves_AFX])
		displayFolder: Gross Inventory
		lineageTag: c05aef6d-5685-4ab3-af7c-0bb5bb953c45

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO: Salvage & obs PP' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([SSSO: Salvage & Obsolescence],filter_)
			RETURN
			Result
		displayFolder: SSSO Salvage & Obs
		lineageTag: 68157b7b-90a6-440e-a750-0b87c9dd110c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO: Obs linked to Conv PP' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([SSSO: Obsolescenes linked to Conversions],filter_)
			RETURN
			Result
		displayFolder: SSSO Obs linked to Conv
		lineageTag: 027efcd4-d1f1-4410-bacc-1a5c6010a89d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO: Scrap-Off PP' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([SSSO: Scrap-Off],filter_)
			RETURN
			Result
		displayFolder: SSSO Scrap-Off
		lineageTag: b08e2569-5ed5-4c29-9801-4402499164c1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Distribution on COGS Actual PP' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([Total Distribution on COGS Actual],filter_)
			RETURN
			Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Distribution on COGS
		lineageTag: 49395a6f-12c8-4016-afad-5d08aa82f954

	measure 'Total Logistics on Net Sales Actual PP' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([Total Logistics on Net Sales Actual],filter_)
			RETURN
			Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Logistic vs Net Sales
		lineageTag: 21996a4c-ef72-4af6-aa84-59e99a24a463

	measure 'SSSO: Salvage & Obs_AFX_Base' =
			
			VAR AFX = [SSSO Obs_F66] - ABS([SSSO Salvage_F66])
			
			RETURN
			AFX
		displayFolder: SSSO Salvage & Obs
		lineageTag: 5dda1a5e-5009-423c-a999-166fbd6b3bcd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO: Obso Conv_AFX_Base' =
			
			VAR AFX = [SSSO: Scrap-off F66_Base] + [SSSO Obs_F66] - ABS([SSSO Salvage_F66])
			Return
			AFX
		displayFolder: SSSO Obs linked to Conv
		lineageTag: cae50f8b-c92f-4b8b-a1bd-310acaee02f4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Sales Actual PP' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([Net Sales Actual],filter_)
			RETURN
			Result
		formatString: 0.0
		displayFolder: Net Sales
		lineageTag: e2bcada7-43d7-477c-aa57-800102ff4a70

	measure 'COGS Actual PP' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([COGS Actual],filter_)
			RETURN
			Result
		formatString: 0.0
		displayFolder: COGS
		lineageTag: f0462e0d-b875-48f9-9878-6473a83a932e

	measure 'Cust Fine PP' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([Customer Fines],filter_)
			RETURN
			Result
		formatString: 0.0
		displayFolder: Customer Fines
		lineageTag: 895686ef-3c9f-40c0-b11e-4b8b3368da05

	measure 'Bias PP' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([Bias%],filter_)
			RETURN
			Result
		displayFolder: Bias CSCA
		lineageTag: 27e874e4-745a-4a32-9057-86b4bb5ca3e0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bias Lag2 PP' = CALCULATE([Bias PP], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "2"))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Bias CSCA
		lineageTag: af2c9731-fe6e-4c90-9fdb-198ae72485f0

	measure 'Bias Lag4 PP' = CALCULATE([Bias PP], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "4"))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Bias CSCA
		lineageTag: 39bdf3b9-ed61-4dc5-b0d3-2b95eb4e9a17

	measure 'FA% PP' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([FA% CSCA],filter_)
			RETURN
			Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 73cf70d3-678d-455d-bf99-2e02a975939c

	measure 'FA% Lag2 PP' = CALCULATE([FA% PP],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2"))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 74a51d70-e8cf-4e0c-a465-7ff1f75c0ac4

	measure 'FA% Lag4 PP' = CALCULATE([FA% PP],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4"))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 031bcabd-5af4-4709-8142-0dece8bcad86

	measure 'SA PP' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([Schedule Attn],filter_)
			RETURN
			Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Schedule Attainment
		lineageTag: 0cdf13f3-51ad-42d5-9af0-c0cb95692960

	measure 'CFR PP' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([CFR],filter_)
			RETURN
			Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: CFR
		lineageTag: d6df3d20-8599-4dac-a1ff-ae651ab9ed1a

	measure 'FA% Lag2 PY' = CALCULATE([FA% PY],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "2"))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 8b9fed1f-107d-453b-92e5-5719f61eb176

	measure 'FA% Lag4 PY' = CALCULATE([FA% PY],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "4"))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 9f37f77a-4c3c-4070-9a9e-11bafce01fb8

	measure 'Bias Lag2 PY' = CALCULATE([Bias PY],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "2"))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Bias CSCA
		lineageTag: 321385cc-4fcf-4202-b79b-18a66443e1f6

	measure 'Bias Lag4 PY' = CALCULATE([Bias PY],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "4"))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Bias CSCA
		lineageTag: a45cfdc6-5bbf-43c4-95cc-d6bff0efaf48

	measure 'Service Rate% PP' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([Service Rate%],filter_)
			RETURN
			Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Service Rate CSCA
		lineageTag: 60347ad6-f8fc-4c47-a02f-3409573f5371

	measure 'FA% Lag2 MoM%' = CALCULATE([FA% MoM%],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "2"))
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 319628f8-62ec-48d1-8a4e-79111c461e72

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FA% Lag4 MoM%' = CALCULATE([FA% MoM%],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "4"))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: aacab4de-94d8-4c1b-9e23-e9dd9791fc56

	measure 'FA% Lag2 YoY%' = CALCULATE([FA% YoY%],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "2"))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: d46358d2-30a1-43df-8325-df8738a3e162

	measure 'FA% Lag4 YoY%' = CALCULATE([FA% YoY%],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "4"))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 57ec18bc-5b77-428f-b286-21c8a1bb5f95

	measure 'FA% Lag2 Target Diff' = CALCULATE([FA% Target Diff%], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "2"))
		displayFolder: Forecast Accuracy CSCA
		lineageTag: e5c1ef98-f4ef-48ae-ba53-14835e36396b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FA% Lag4 Target Diff' = CALCULATE([FA% Target Diff%], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "4"))
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 8e209fbc-412d-4a74-bb83-4ca81c6a8b3e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bias Lag2 Target Diff%' = CALCULATE([Bias Target Diff%],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "2"))
		displayFolder: Bias CSCA
		lineageTag: ccfcff81-c0ff-404f-96fa-ba181ab769f2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bias Lag4 Target Diff%' = CALCULATE([Bias Target Diff%],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "4"))
		displayFolder: Bias CSCA
		lineageTag: fa95dbcc-dc92-427d-9d5b-f71b9f98808d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bias Lag2 MoM%' = CALCULATE([Bias MoM%],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "2"))
		displayFolder: Bias CSCA
		lineageTag: 48a9e8f6-a6d1-4c2a-95f5-438f9a510942

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bias Lag4 MoM%' = CALCULATE([Bias MoM%],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "4"))
		displayFolder: Bias CSCA
		lineageTag: 50edeb50-5289-489a-b6ee-7cbcf6c46553

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bias Lag2 YoY%' = CALCULATE([Bias YoY%],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "2"))
		displayFolder: Bias CSCA
		lineageTag: df5af22c-1b99-4145-82fa-f378180c0ce3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bias Lag4 YoY%' = CALCULATE([Bias YoY%],KEEPFILTERS(Fact_Forecast_Accuracy[LAGs] = "4"))
		displayFolder: Bias CSCA
		lineageTag: 3e285136-99d9-4890-95eb-12da2bce5ef2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Switch_Plan_Operations = ```
			SWITCH(
			    VALUES( Operations_Parameter[Operations_Parameter] ),
			    "OEE%", [OEE Target],
			    "Schedule Attainment%", [Schedule Attn Target],
			    "On Time Closure of Deviations%",[Deviations Plan],
			    "CAPA Completion Rate%",[CAPA Plan],
			    "RFT%", [RFT Plan],
			    "Good Catch Closure Rate%",[Good Catch Closure Plan],
			    "pSIF SIF Focus Action%",[pSIF SIFs Focus Plan_Target],
			    "PWS Benefits",[PWS Benefits Plan]
			)
			
			```
		displayFolder: Switch Measures
		lineageTag: 46ad6b7c-6671-4187-b08a-d072791c8fce

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(Operations_Parameter[Parameter Name]),
				    "CAPA Completion Rate%", "0.0%",
				    "On Time Closure of Deviations%", "0.0%",
				    "RFT%", "0.0%",
				    "Critical or Major Observations", "#,0",
				    "OEE%", "0.0%",
				    "Schedule Attainment%", "0.0%",
				    "Good Catch Closure Rate%","0.0%",
				    "pSIF SIF Focus Action%","0.0%",
				    "PWS Benefits", "#,0",
				    "--"  --fallback
				)

	measure Switch_Plan_OI = ```
			SWITCH(
			    VALUES( Operating_Parameter[Operating_Parameter] ),
			    "SSSO: Salvage & Obs", [SSSO: Salvage & Obs_APN_Base],
			    "SSSO: Obs linked to Conv", [SSSO: Obso Conv_APN_Base],
			    "SSSO: Scrap-Off", [SSSO: Scrap-off APN_Base],
			    "Net Sales", [Net Sales_APN_Base],
			    "COGS", [COGS_APN_Base],
			    "Distribution to COGS", [Total Distribution on COGS_APN_Base],
			    "% Logistics vs Net Sales", [Total Logistics on Net Sales_APN_Base],
			    "Customer Fines", [Customer Fines Target],
			    "Operating Income", [Operating Income APN_Base],
			    "Gross PPV", [Gross PPV APN_base],
			    "Net POV", [Net POV APN_base],
			    "ABP Variance", [ABP Variance_APN_Base]
			)
			
			```
		displayFolder: Switch Measures
		lineageTag: 7168448d-b758-4fcd-8195-1e2f65824ef8

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(Operating_Parameter[Parameter Name]),
				    "SSSO: Salvage & Obs", "#,0",
				    "SSSO: Scrap-Off", "#,0",
				    "COGS", "#,0",
				    "Distribution to COGS", "0.0%",
				    "Operating Income", "#,0",
				    "Net POV", "#,0",
				    "SSSO: Obs linked to Conv","#,0",
				    "Net Sales", "#,0",
				    "% Logistics vs Net Sales", "0.0%",
				    "Customer Fines", "#,0",
				    "Gross PPV","#,0",
				    "ABP Variance","#,0"
				)

	measure Switch_Flex_OI = ```
			SWITCH(
			    VALUES( Operating_Parameter[Operating_Parameter] ),
			    "SSSO: Salvage & Obs", [SSSO: Salvage & Obs_AFX_Base],
			    "SSSO: Obs linked to Conv", [SSSO: Obso Conv_AFX_Base],
			    "SSSO: Scrap-Off", [SSSO: Scrap-off F66_Base],
			    "COGS", [COGS_AFX_Base],
			    "Distribution to COGS", [Total Distribution on COGS_AFX_Base],
			    "% Logistics vs Net Sales", [Total Logistics on Net Sales_AFX_Base]
			)
			
			```
		displayFolder: Switch Measures
		lineageTag: fdc38a5b-b697-43de-a8c2-ec8696ad9eec

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Inflated Inventory MoM' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([Inflated Inventory],filter_)
			VAR Result = [Inflated Inventory] - Net_PM
			RETURN
			Result
		displayFolder: Inflated Inventory
		lineageTag: bb4e146c-5b4c-46ed-ac4b-03acd354b979

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Expired Inventory MoM' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([Expired Inventory],filter_)
			VAR Result = [Expired Inventory] - Net_PM
			RETURN
			Result
		displayFolder: Expired Inventory
		lineageTag: 42dc6417-4ea5-4c0e-b49c-6d9cb360d473

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DSO MoM' =
			
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[P_YearPeriod Seq]) )
			VAR Filter_ = Filter(all(Dim_Date),Dim_Date[P_YearPeriod Seq]= YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([DSO],filter_)
			VAR Result = [DSO] - Net_PM
			RETURN
			Result
		displayFolder: DSO
		lineageTag: cd694068-0782-45b4-b49c-6973310618d0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DPO MoM' =
			
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[P_YearPeriod Seq]) )
			VAR Filter_ = Filter(all(Dim_Date),Dim_Date[P_YearPeriod Seq]= YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([DPO],filter_)
			VAR Result = [DPO] - Net_PM
			RETURN
			Result
		displayFolder: DPO
		lineageTag: f85f40b2-8708-4ab2-92f9-fad3d45ab063

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DIO MoM' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([DIO],filter_)
			VAR Result = [DIO] - Net_PM
			RETURN
			Result
		displayFolder: DIO
		lineageTag: 3111b21c-4c4a-4c7a-ab83-4501487deadc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net POV Actual' = CALCULATE(SUM(Fact_COPA_Global[Net POV Actual]), KEEPFILTERS( Dim_Profit_Center[FP&A Country] <> "Feldkirchen"))
		displayFolder: Net POV
		lineageTag: 682c3c2c-720d-478a-94e9-44e65156dce3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net POV Actual LYTD' = ```
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Net POV Actual PY])
			VAR Result = Sumx(Table_,[Measure])
			RETURN
			IF(
			    ISBLANK(Result) || Result = 0,
			    BLANK(),
			    DIVIDE([Net POV Actual] - Result, Result)
			)
			
			```
		displayFolder: Net POV
		lineageTag: 4ecf8c42-c212-4df6-937d-8497767eadf6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net POV Actual MoM_Final' = ```
			VAR kpi_ =  [Net POV Actual MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Net POV
		lineageTag: 5d7cb07d-bd7f-4341-86c3-84375f89c222

	measure 'Net POV Actual MoM%' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([Net POV Actual],filter_)
			VAR Result = DIVIDE(([Net POV Actual] - Net_PM),Net_PM)
			RETURN
			Result
		displayFolder: Net POV
		lineageTag: 93b051de-7475-4ea2-b620-5d43aa135d85

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net POV Actual PP' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([Net POV Actual],filter_)
			RETURN
			Result
		displayFolder: Net POV
		lineageTag: 4e0e3e2f-2661-4da2-972f-863b10b305c9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net POV Actual PY' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Net POV Actual],filter_)
		displayFolder: Net POV
		lineageTag: 29ecad30-d9c1-4234-94db-8d1d0ccd6b05

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net POV Actual YoY_Final' =
			VAR kpi_ =  [Net POV Actual YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Net POV
		lineageTag: 12e2f707-f8ec-4256-865c-38481a755787

	measure 'Net POV Actual YoY%' = DIVIDE(([Net POV Actual] - [Net POV Actual PY]),[Net POV Actual PY])
		displayFolder: Net POV
		lineageTag: 7701f75a-1f69-4eae-95f0-d7cd8f2013da

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net POV Actual YTD' =
			VAR _LastMonth = MAX(Dim_Date[P_YearMonth Number])
			VAR _SelectedYear = MAX(Dim_Date[P_Year])
			RETURN
			    SUMX(
			        FILTER(
			            ALL(Dim_Date),
			            Dim_Date[P_YearMonth Number] <= _LastMonth && Dim_Date[P_Year] = _SelectedYear
			        ),
			        [Net POV Actual]
			    )
		displayFolder: Net POV
		lineageTag: 9598874d-c497-40c2-8633-cd4a9fe83908

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net POV APN_base' = SUM(Fact_COPA_Global[Net POV Plan])
		formatString: #,0.0
		displayFolder: Net POV
		lineageTag: a8d2f4f1-4fe1-4a22-9389-4a5e89bb3b36

	measure 'Net POV LYTD' = ```
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Net POV Actual PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			```
		displayFolder: Net POV
		lineageTag: 301e3dec-612a-496a-8657-32bb285890ec

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net POV_APN' =
			VAR Plan = [Net POV APN_Base]
			Return
			DIVIDE([Net POV Actual] - Plan,Plan)
		displayFolder: Net POV
		lineageTag: a581a5a4-553c-4d68-b20c-12937ff33abf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net POV_APN_Final' =
			VAR kpi_ = [Net POV_APN]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: Net POV
		lineageTag: 9a60fce9-5d4b-4628-8230-e466db210ba0

	measure 'Gross PPV Actual' = CALCULATE(SUM(Fact_COPA_Global[Gross PPV Actual]),KEEPFILTERS( Dim_Profit_Center[FP&A Country] <> "Feldkirchen"))
		displayFolder: Gross PPV
		lineageTag: 1ead4e52-fd37-4ab8-aea4-abc040372c6e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross PPV Actual LYTD' = ```
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Gross PPV Actual PY])
			VAR Result = Sumx(Table_,[Measure])
			RETURN
			IF(
			    ISBLANK(Result) || Result = 0,
			    BLANK(),
			    DIVIDE([Gross PPV Actual] - Result,Result)
			)
			```
		displayFolder: Gross PPV
		lineageTag: 7c15aa88-6832-4b29-a0e9-6a08a46f91f9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross PPV Actual MoM_Final' = ```
			VAR kpi_ =  [Gross PPV Actual MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Gross PPV
		lineageTag: 088513ca-926c-4fee-a2e4-3dcebe3c88f5

	measure 'Gross PPV Actual MoM%' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([Gross PPV Actual],filter_)
			VAR Result = DIVIDE(([Gross PPV Actual] - Net_PM),Net_PM)
			RETURN
			Result
		displayFolder: Gross PPV
		lineageTag: 058cf2fa-bd3b-4a18-9060-a82004adb2e1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross PPV Actual PP' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([Gross PPV Actual],filter_)
			RETURN
			Result
		displayFolder: Gross PPV
		lineageTag: a0e35219-aa70-4363-b603-aadd96d325fa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross PPV Actual PY' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Gross PPV Actual],filter_)
		displayFolder: Gross PPV
		lineageTag: 7b258b2d-3328-463c-9014-78e12fac572a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross PPV Actual YoY_Final' =
			VAR kpi_ =  [Gross PPV Actual YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Gross PPV
		lineageTag: df241a7a-007b-4735-a700-c278553da8e0

	measure 'Gross PPV Actual YoY%' = DIVIDE(([Gross PPV Actual] - [Gross PPV Actual PY]),[Gross PPV Actual PY])
		displayFolder: Gross PPV
		lineageTag: 33f866a0-7cda-4fe5-8110-4ffcd3dec3e3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross PPV Actual YTD' =
			VAR _LastMonth = MAX(Dim_Date[P_YearMonth Number])
			VAR _SelectedYear = MAX(Dim_Date[P_Year])
			RETURN
			    SUMX(
			        FILTER(
			            ALL(Dim_Date),
			            Dim_Date[P_YearMonth Number] <= _LastMonth && Dim_Date[P_Year] = _SelectedYear
			        ),
			        [Gross PPV Actual]
			    )
		displayFolder: Gross PPV
		lineageTag: 88360143-f6fc-4fd7-aabf-4efff20e0c55

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross PPV APN_base' = SUM(Fact_COPA_Global[Net PPV Plan])
		formatString: #,0.0
		displayFolder: Gross PPV
		lineageTag: de280fd9-4fea-47b7-b6ff-33357cfa4d25

	measure 'Gross PPV LYTD' = ```
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Gross PPV Actual PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			```
		displayFolder: Gross PPV
		lineageTag: 8d027159-2f62-4152-b05a-2140d42e9c67

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross PPV_APN' =
			VAR Plan = [Gross PPV APN_base]
			Return
			DIVIDE([Gross PPV Actual] - Plan,Plan)
		displayFolder: Gross PPV
		lineageTag: 7007a5b7-69e0-4ff1-ac59-8c846363ab54

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross PPV_APN_Final' =
			VAR kpi_ = [Gross PPV_APN]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: Gross PPV
		lineageTag: f0adb735-c9c5-4ed5-8d43-c99e05d56821

	measure 'Operating Income Actual' = CALCULATE(SUM(Fact_COPA_Global[Operating Income Actual]),KEEPFILTERS( Dim_Profit_Center[FP&A Country] <> "Feldkirchen"))
		displayFolder: Operating Income
		lineageTag: f7defad4-2cb8-4f72-91b9-90f0fbd9b957

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Operating Income Actual LYTD' = ```
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Operating Income Actual PY])
			VAR Result = Sumx(Table_,[Measure])
			RETURN
			IF(
			    ISBLANK(Result) || Result = 0,
			    BLANK(),
			    DIVIDE([Operating Income Actual] - Result,Result)
			)
			
			```
		displayFolder: Operating Income
		lineageTag: 8c10fe0d-cdfb-4e80-a0fb-9ee887b51012

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Operating Income Actual MoM_Final' = ```
			VAR kpi_ =  [Operating Income Actual MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Operating Income
		lineageTag: c8493e31-9063-46c3-bb02-bac5a15573fa

	measure 'Operating Income Actual MoM%' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([Operating Income Actual],filter_)
			VAR Result = DIVIDE(([Operating Income Actual] - Net_PM),Net_PM)
			RETURN
			Result
		displayFolder: Operating Income
		lineageTag: 29f5c337-86a5-497f-8784-511376572379

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Operating Income Actual PP' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([Operating Income Actual],filter_)
			RETURN
			Result
		displayFolder: Operating Income
		lineageTag: 66657473-b000-4b62-a63f-72808fa9f6bb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Operating Income Actual PY' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Operating Income Actual],filter_)
		displayFolder: Operating Income
		lineageTag: 467dd3e0-fe51-44a1-9a51-a856b05d13e2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Operating Income Actual YoY_Final' =
			VAR kpi_ =  [Operating Income Actual YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Operating Income
		lineageTag: 664c82ab-7f58-4015-a7e3-484096d4a034

	measure 'Operating Income Actual YoY%' = DIVIDE(([Operating Income Actual] - [Operating Income Actual PY]),[Operating Income Actual PY])
		displayFolder: Operating Income
		lineageTag: e54b6630-2cf7-4660-a1db-1eb366e30013

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Operating Income Actual YTD' =
			VAR _LastMonth = MAX(Dim_Date[P_YearMonth Number])
			VAR _SelectedYear = MAX(Dim_Date[P_Year])
			RETURN
			    SUMX(
			        FILTER(
			            ALL(Dim_Date),
			            Dim_Date[P_YearMonth Number] <= _LastMonth && Dim_Date[P_Year] = _SelectedYear
			        ),
			        [Operating Income Actual]
			    )
		displayFolder: Operating Income
		lineageTag: d81418f5-044a-4068-90e1-916efd908f8b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Operating Income APN_Base' = SUM(Fact_COPA_Global[Operating Income Plan])
		formatString: #,0.0
		displayFolder: Operating Income
		lineageTag: a79a8550-10e9-4694-8105-e243ddfd9e3b

	measure 'Operating Income LYTD' = ```
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Operating Income PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			```
		displayFolder: Operating Income
		lineageTag: c118920e-4b83-4888-99e4-9216ce087e4c

	measure 'Operating Income PY' = ```
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			    
			
			        Calculate( [Operating Income Actual], filter_ )
			```
		displayFolder: Operating Income
		lineageTag: e84c64f1-cbf8-4049-8a7d-8e60094973f6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Operating Income_APN' =
			VAR Plan = [Operating Income APN_Base]
			Return
			DIVIDE([Operating Income Actual] - Plan,Plan)
		displayFolder: Operating Income
		lineageTag: bfb9e7ef-845f-4223-8b4b-9e4ec38f569f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Operating Income_APN_Final' =
			VAR kpi_ = [Operating Income_APN]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: Operating Income
		lineageTag: 410ed7a6-5a45-4fea-a9f3-988336757311

	measure 'FA% Lag 2 Target Diff%' = [FA% Lag2] - [FA% Lag2 Target]
		displayFolder: Forecast Accuracy CSCA
		lineageTag: a5cd57a3-8215-44d5-a39d-27910edd6dcf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FA% Lag 4 Target Diff%' = [FA% Lag4] - [FA% Lag4 Target]
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 24005a5d-c869-4b31-ade1-d0d9bdb2f15b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FA% Lag2 Target' =
			
			Var tar = CALCULATE(MAX(Fact_Target[Target]),KEEPFILTERS(Fact_Target[KPI_Name] = "Forecast Accuracy Lag2 (%)"))
			RETURN
			DIVIDE(tar,100)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 8ab6b503-9f0c-4913-87d5-cd2929fbe7c6

	measure 'Net Sales Actual LYTD_Final' =
			
			VAR kpi_ =  [Net Sales Actual LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Net Sales
		lineageTag: 7e06759b-301d-408e-aae2-6dd8fd96e6ba

	measure 'Gross PPV Actual LYTD_Final' =
			
			VAR kpi_ =  [Gross PPV Actual LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Gross PPV
		lineageTag: f6718f6f-db76-481b-a199-b29dbd7bdcb7

	measure 'Net POV Actual LYTD_Final' =
			
			VAR kpi_ =  [Net POV Actual LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Net POV
		lineageTag: c9d0f241-90fe-4fc9-b054-311f1551886b

	measure 'Operating Income Actual LYTD_Final' =
			
			VAR kpi_ =  [Operating Income Actual LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Operating Income
		lineageTag: 1a1dfabb-e62c-4ef0-b9f4-406c05203c7d

	measure 'OEE% LYTD_Final' =
			
			VAR kpi_ =  [OEE LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: OEE
		lineageTag: 611bdc4b-e841-4d32-aab5-4782e02250f3

	measure 'InCount LYTD' = ```
			
			    
			VAR In_ =  ADDCOLUMNS(SUMMARIZE(Dim_Date, Dim_Date[P_YearPeriod]), "Measure", [InCount_PY])
			
			VAR InCountLYTD = SUMX(In_, [Measure])
			RETURN InCountLYTD
			```
		displayFolder: OEE
		lineageTag: 2de2ca06-1c9e-49a2-9087-861deceddac3

	measure InCount_PY =
			
			VAR AllDates = ALL(Dim_Date)
			VAR CurrentSeq = VALUE(MAX(Dim_Date[YearPeriodSeq]))
			VAR PYSeq = CurrentSeq - 12
			
			RETURN
			    CALCULATE([In Count], FILTER(AllDates, Dim_Date[YearPeriodSeq] = PYSeq))
		displayFolder: OEE
		lineageTag: 98576661-56d0-46c6-9031-6665b358b566

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure OutCount_PY =
			
			VAR AllDates = ALL(Dim_Date)
			VAR CurrentSeq = VALUE(MAX(Dim_Date[YearPeriodSeq]))
			VAR PYSeq = CurrentSeq - 12
			
			RETURN
			    CALCULATE([Out Count], FILTER(AllDates, Dim_Date[YearPeriodSeq] = PYSeq))
		displayFolder: OEE
		lineageTag: e1a4f5c3-d71b-47aa-bf2d-31b340a5f638

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OutCount LYTD' = ```
			
			    
			VAR Out =  ADDCOLUMNS(SUMMARIZE(Dim_Date, Dim_Date[P_YearPeriod]), "Measure", [OutCount_PY])
			
			VAR OutCountLYTD = SUMX(Out, [Measure])
			RETURN OutCountLYTD
			
			```
		displayFolder: OEE
		lineageTag: 66de8ccd-1fc5-4caf-9562-120e4ff06797

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure UpSeconds_PY =
			
			VAR AllDates = ALL(Dim_Date)
			VAR CurrentSeq = VALUE(MAX(Dim_Date[YearPeriodSeq]))
			VAR PYSeq = CurrentSeq - 12
			
			RETURN
			    CALCULATE([Up Seconds], FILTER(AllDates, Dim_Date[YearPeriodSeq] = PYSeq))
		displayFolder: OEE
		lineageTag: 9f674593-2788-4174-83ce-13b517dd6149

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DownSeconds_PY =
			
			VAR AllDates = ALL(Dim_Date)
			VAR CurrentSeq = VALUE(MAX(Dim_Date[YearPeriodSeq]))
			VAR PYSeq = CurrentSeq - 12
			
			RETURN
			    CALCULATE([Down Seconds], FILTER(AllDates, Dim_Date[YearPeriodSeq] = PYSeq))
		displayFolder: OEE
		lineageTag: 442a67b7-bec6-4060-8f79-86922b07a187

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DownSeconds LYTD' = ```
			
			    
			VAR Out =  ADDCOLUMNS(SUMMARIZE(Dim_Date, Dim_Date[P_YearPeriod]), "Measure", [DownSeconds_PY])
			
			VAR OutCountLYTD = SUMX(Out, [Measure])
			RETURN OutCountLYTD
			
			```
		displayFolder: OEE
		lineageTag: 39fa85fc-725d-46a9-81fc-2d4deb109e93

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'UpSeconds LYTD' = ```
			
			    
			VAR Out =  ADDCOLUMNS(SUMMARIZE(Dim_Date, Dim_Date[P_YearPeriod]), "Measure", [UpSeconds_PY])
			
			VAR OutCountLYTD = SUMX(Out, [Measure])
			RETURN OutCountLYTD
			
			```
		displayFolder: OEE
		lineageTag: 51a654c1-7d37-479b-90ad-31a97f081c68

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TotalElapsed LYTD' = [UpSeconds LYTD] + [DownSeconds LYTD]
		displayFolder: OEE
		lineageTag: 34d3296c-93f8-4368-b145-b8dab9164fc7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RunQty_PY =
			
			VAR AllDates = ALL(Dim_Date)
			VAR CurrentSeq = VALUE(MAX(Dim_Date[YearPeriodSeq]))
			VAR PYSeq = CurrentSeq - 12
			
			RETURN
			    CALCULATE([Run Theoretical Quantity], FILTER(AllDates, Dim_Date[YearPeriodSeq] = PYSeq))
		displayFolder: OEE
		lineageTag: 91720cb9-3cb3-4558-9891-f6aa8da2c63d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RunQty LYTD' = ```
			
			    
			VAR Out =  ADDCOLUMNS(SUMMARIZE(Dim_Date, Dim_Date[P_YearPeriod]), "Measure", [RunQty_PY])
			
			VAR OutCountLYTD = SUMX(Out, [Measure])
			RETURN OutCountLYTD
			
			```
		displayFolder: OEE
		lineageTag: 220ead1d-6250-48a2-a10c-e829033e3e57

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RunSpeed LYTD' = ```
			DIVIDE([RunQty LYTD], [TotalElapsed LYTD]) 
			```
		displayFolder: OEE
		lineageTag: 97d22ade-9c81-473d-90f3-566e121d72e6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qloss LYTD' = [InCount LYTD] - [OutCount LYTD]
		displayFolder: OEE
		lineageTag: a31c9d6d-a6f0-4f5d-9588-8bcb6b51bba4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Abs Demand Draft Var 5 Digit' =
			CALCULATE(
			SUMX(
			    SUMMARIZE(
			        Fact_Forecast_Accuracy,Fact_Forecast_Accuracy[SSID 5-Digit],
			        Fact_Forecast_Accuracy[Fiscal Year/Period],
			        "Variance", ABS([Demand Draft] - [Total Shipments])),[Variance]),
			REMOVEFILTERS(Fact_Forecast_Accuracy[Source Material Key])
			)
		displayFolder: Forecast Accuracy CSCA
		lineageTag: c0875e69-fce8-48bb-9f36-78ba6bc34738

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FA% 5 Digit' = ```
			
			VAR TotalShipments = [Total Shipments]
			VAR VarianceAgg = [Abs Demand Draft Var 5 Digit]
			
			RETURN 
			IF(
			    ISBLANK(VarianceAgg),
			    BLANK(),  // Return BLANK if VarianceAgg is blank or zero
			    VAR Result = 1 - DIVIDE(VarianceAgg, TotalShipments, 1)
			    RETURN IF(Result < 0, 0, Result)
			)
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: e6563f0c-c756-47c1-8111-d804bd23a9e1

	measure 'FA% CSCA' = SWITCH(SELECTEDVALUE(Par_SSID_5Digit[Par Name]),"SSID", [FA% SSID],"5 Digit",[FA% 5 Digit],[FA% SSID])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 284d0bae-709c-4ef2-a95f-3647c4ebf971

	measure 'Abs Demand Draft Var 5 Digit LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Abs Demand Draft 5 Digit_PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			
			```
		displayFolder: Forecast Accuracy CSCA
		lineageTag: aa244a65-ed21-470a-9104-4c7b6683e681

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FA% SSID LYTD' = ```
			
			VAR TotalShipments = [Total Shipments LYTD]
			VAR VarianceAgg = [Abs Demand Draft Var SSID LYTD]
			
			RETURN 
			IF(
			    ISBLANK(VarianceAgg),
			    BLANK(),  // Return BLANK if VarianceAgg is blank or zero
			    VAR Result = 1 - DIVIDE(VarianceAgg, TotalShipments, 1)
			    RETURN IF(Result < 0, 0, Result)
			)
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 2842d072-5016-4168-a95d-999998f716e8

	measure 'FA% 5 Digit LYTD' = ```
			
			VAR TotalShipments = [Total Shipments LYTD]
			VAR VarianceAgg = [Abs Demand Draft Var 5 Digit LYTD]
			
			RETURN 
			IF(
			    ISBLANK(VarianceAgg),
			    BLANK(),  // Return BLANK if VarianceAgg is blank or zero
			    VAR Result = 1 - DIVIDE(VarianceAgg, TotalShipments, 1)
			    RETURN IF(Result < 0, 0, Result)
			)
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 057244a0-c1e4-4056-bf9c-aaf9882f9a13

	measure 'FA% CSCA LYTD' =
			
			Var FA_lytd = SWITCH(VALUES(Par_SSID_5Digit[Par Name]),"SSID", [FA% SSID LYTD],"5 Digit",[FA% 5 Digit LYTD],[FA% SSID LYTD])
			
			RETURN [FA% CSCA] - FA_lytd
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 33cc7793-7ae9-479b-bdb0-829abde293d9

	measure 'Abs Demand Draft SSID_PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Abs Demand Draft Var SSID],filter_)
			
			```
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 7f3e398f-88df-48f1-a793-6dda6ea50276

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Abs Demand Draft 5 Digit_PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Abs Demand Draft Var 5 Digit],filter_)
			
			```
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 5195bcaa-dc7a-44cb-85fb-062beb1198df

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FA% CSCA LYTD_Final' =
			
			VAR kpi_ =  [FA% CSCA LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 5f5790cd-3b64-4d89-a836-fcfd7255db3d

	measure ShowExternalFlag = ```
			
			VAR ToggleSelection = SELECTEDVALUE(External_Toggle[Show External], "Yes")
			RETURN
			    IF(
			        ToggleSelection = "No",
			        IF(
			            MAX(Dim_Value_Stream[IsExternal]) = "Yes", 
			            0, 
			            1
			        ),
			        1
			    )
			```
		formatString: 0
		displayFolder: Misc
		lineageTag: 3685e3ef-195e-4ff6-97bb-35aea647e52d

	measure 'On Delivery' = SUM(Fact_Service[On Delivery EA])
		displayFolder: Service Rate CSCA
		lineageTag: 229e7541-5e00-4d2a-b65e-33b90f91bdb1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Order = SUM(Fact_Service[Order EA])
		displayFolder: Service Rate CSCA
		lineageTag: 0b7b7138-7bca-411d-b5d3-fa9d824ae80f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'On Time Closure of Deviations%' =
			
			DIVIDE(SUM(Fact_Quality[Deviation: Total Closed on Time in Period]),SUM(Fact_Quality[Deviation: Total Closed in Period]))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: On Time Closure of Deviations
		lineageTag: d4645308-60fc-4e0c-a23b-d9305755c218

	measure 'On Time Closure of Deviations PP' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([On Time Closure of Deviations%],filter_)
			RETURN
			Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: On Time Closure of Deviations
		lineageTag: 33e04bb9-6f7b-4181-b33c-b98190f05d30

	measure 'On Time Closure of Deviations PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([On Time Closure of Deviations%],filter_)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: On Time Closure of Deviations
		lineageTag: 8a588cdd-6d98-4569-83cc-c863037ee40a

	measure 'On Time Closure of Deviations MoM%' =
			
			VAR Result =  [On Time Closure of Deviations%] - [On Time Closure of Deviations PP]
			RETURN
			Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: On Time Closure of Deviations
		lineageTag: a29e44c4-328b-47ce-aa7d-fd44f8cff825

	measure 'On Time Closure of Deviations MoM_Final' = ```
			
			VAR kpi_ = [On Time Closure of Deviations MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: On Time Closure of Deviations
		lineageTag: 544a7783-6d86-499d-a48c-ca300631e8a7

	measure 'On Time Closure of Deviations YoY%' =
			
			IF(ISBLANK([On Time Closure of Deviations PY]), BLANK(),[On Time Closure of Deviations%] - [On Time Closure of Deviations PY])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: On Time Closure of Deviations
		lineageTag: 466085c4-9776-4863-a705-9d04c9b42df8

	measure 'On Time Closure of Deviations YoY_Final' =
			
			VAR kpi_ =  [On Time Closure of Deviations YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: On Time Closure of Deviations
		lineageTag: 387a7d6f-d67e-4bea-9811-c67bbb167c48

	measure 'On Time Closure of Deviations YTD' = TOTALYTD([On Time Closure of Deviations%],Dim_Date[Date])
		displayFolder: On Time Closure of Deviations
		lineageTag: 91fa4bcd-e300-4fd2-a79e-c61a0357fd4b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Deviations Closed on Time' = SUM(Fact_Quality[Deviation: Total Closed on Time in Period])
		formatString: 0
		displayFolder: On Time Closure of Deviations
		lineageTag: 31957436-d150-46ea-b348-d71683ee3dea

	measure 'Deviations Closed on Time PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Deviations Closed on Time],filter_)
			
			```
		formatString: 0
		displayFolder: On Time Closure of Deviations
		lineageTag: 7ab7675a-5f72-4b7a-8724-1bf05ffe8bdb

	measure 'Deviations Closed on Time LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Deviations Closed on Time PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			```
		formatString: 0
		displayFolder: On Time Closure of Deviations
		lineageTag: e4079846-7178-4fc9-a4b5-64ce1b2c5392

	measure 'Deviations Closed' = SUM(Fact_Quality[Deviation: Total Closed in Period])
		formatString: 0
		displayFolder: On Time Closure of Deviations
		lineageTag: 9e989189-f8eb-4e84-958f-67f8730d5a50

	measure 'Deviations Closed PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Deviations Closed],filter_)
			
			```
		formatString: 0
		displayFolder: On Time Closure of Deviations
		lineageTag: dc6f4023-5869-4e1b-a67c-fa58181dc949

	measure 'Deviations Closed LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Deviations Closed PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			```
		formatString: 0
		displayFolder: On Time Closure of Deviations
		lineageTag: 001ea44e-7655-49ac-a187-92728a39f4ec

	measure 'On Time Closure of Deviations LYTD' =
			
			VAR LYTD = DIVIDE([Deviations Closed on Time LYTD],[Deviations Closed LYTD])
			
			RETURN
			IF(ISBLANK(LYTD), BLANK(),[On Time Closure of Deviations%] - LYTD)
		displayFolder: On Time Closure of Deviations
		lineageTag: 7fae2f03-cc3d-4a63-9fca-a884929942e7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'On Time Closure of Deviations LYTD_Final' =
			
			VAR kpi_ =  [On Time Closure of Deviations LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: On Time Closure of Deviations
		lineageTag: 42126af4-96de-4561-be5b-7b063de313b4

	measure 'Deviations Plan' = AVERAGE(Fact_Quality[Deviations Target])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: On Time Closure of Deviations
		lineageTag: a3a6001d-4bdc-41a7-b308-7cf394d85e74

	measure 'On Time Closure of Deviations Target Diff%' = [On Time Closure of Deviations%] - [Deviations Plan]
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: On Time Closure of Deviations
		lineageTag: 51c7cb97-fc18-487a-8002-f1e05b6c85f4

	measure 'On Time Closure of Deviations Target Final' = ```
			
			VAR kpi_ =  [On Time Closure of Deviations Target Diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: On Time Closure of Deviations
		lineageTag: a90824fb-a6f9-422b-9d1b-3b1430a77b18

	measure 'CAPA Closed on Time' = SUM(Fact_Quality[CAPA: Total Closed on Time in Period])
		formatString: 0
		displayFolder: CAPA Completion Rate
		lineageTag: c17e172d-c84f-4a64-835b-76a078c2cf5e

	measure 'CAPA Closed' = SUM(Fact_Quality[CAPA: Total Closed In Period])
		formatString: 0
		displayFolder: CAPA Completion Rate
		lineageTag: 1cf5fe20-2e63-4e19-ae84-463fc280c193

	measure 'CAPA Completion Rate' = DIVIDE([CAPA Closed on Time],[CAPA Closed])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: CAPA Completion Rate
		lineageTag: 95429529-8a7d-45b7-8b6e-d5bad5e76c58

	measure 'CAPA Completion Rate PP' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([CAPA Completion Rate],filter_)
			RETURN
			Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: CAPA Completion Rate
		lineageTag: e63663f1-96aa-44ca-bc1b-2e9f966a52a2

	measure 'CAPA Completion Rate PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([CAPA Completion Rate],filter_)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: CAPA Completion Rate
		lineageTag: 4f728359-d007-4b29-ac74-b136abf86fe2

	measure 'CAPA Completion Rate MoM%' =
			
			VAR Result =  [CAPA Completion Rate] - [CAPA Completion Rate PP]
			RETURN
			Result
		displayFolder: CAPA Completion Rate
		lineageTag: 212427c4-30e4-4569-98f1-68c33d80698e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CAPA Completion Rate MoM_Final' = ```
			
			VAR kpi_ = [CAPA Completion Rate MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: CAPA Completion Rate
		lineageTag: c531dd52-961f-4ed3-bd0f-f6e6000d461a

	measure 'CAPA Completion Rate YoY%' =
			
			IF(ISBLANK([CAPA Completion Rate PY]), BLANK(),[CAPA Completion Rate] - [CAPA Completion Rate PY])
		displayFolder: CAPA Completion Rate
		lineageTag: 25d26084-3881-4836-8969-c03db6081bc7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CAPA Completion Rate YoY_Final' =
			
			VAR kpi_ =  [CAPA Completion Rate YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: CAPA Completion Rate
		lineageTag: 06efc617-ee13-41dd-baf6-7603c7c711ca

	measure 'CAPA Completion Rate YTD' = TOTALYTD([CAPA Completion Rate],Dim_Date[Date])
		displayFolder: CAPA Completion Rate
		lineageTag: 4f00a904-3a16-4ab2-bedb-65b681f155ca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CAPA Closed PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([CAPA Closed],filter_)
			
			```
		formatString: 0
		displayFolder: CAPA Completion Rate
		lineageTag: b29adf15-0c8c-4aca-8b60-76b4a5bff20b

	measure 'CAPA Closed on Time PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([CAPA Closed on Time],filter_)
			
			```
		formatString: 0
		displayFolder: CAPA Completion Rate
		lineageTag: 7a9566a2-7105-4d47-86d8-a1e3c6dcb871

	measure 'CAPA Closed on Time LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [CAPA Closed on Time PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			```
		formatString: 0
		displayFolder: CAPA Completion Rate
		lineageTag: b2628a98-48c8-4a14-a5f2-e1ea0c380d7b

	measure 'CAPA Closed LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [CAPA Closed PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			```
		formatString: 0
		displayFolder: CAPA Completion Rate
		lineageTag: 4bad0a02-c854-401f-ba71-ffdb697c67d5

	measure 'CAPA Completion Rate LYTD' = DIVIDE([CAPA Closed on Time LYTD],[CAPA Closed LYTD])
		displayFolder: CAPA Completion Rate
		lineageTag: 483bb444-3458-4a92-a264-c458a2f3647c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CAPA Completion Rate LYTD_Final' =
			
			VAR kpi_ =  [CAPA Completion Rate LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: CAPA Completion Rate
		lineageTag: 93c1104e-7f92-4fe6-a9d4-d9de8458bcde

	measure 'CAPA Plan' = AVERAGE(Fact_Quality[CAPA Target])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: CAPA Completion Rate
		lineageTag: d7650970-b9d2-41e1-ad8b-9874b6e5d62d

	measure 'CAPA Completion Rate Target Diff%' = [CAPA Completion Rate] - [CAPA Plan]
		displayFolder: CAPA Completion Rate
		lineageTag: 8a1826ca-21e0-48f5-8f72-21082526065e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CAPA Completion Rate Target Final' = ```
			
			VAR kpi_ =  [CAPA Completion Rate Target Diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: CAPA Completion Rate
		lineageTag: df258cae-ede0-4427-b29a-dd60ff2ebd2f

	measure 'Total # of Batches w deviations' = SUM(Fact_Quality[RFT: Total # of Batches with Deviations])
		formatString: 0
		displayFolder: RFT
		lineageTag: 7e3a64d3-13d8-4d45-ab58-13b9d775ba40

	measure 'Total # of Finished Goods Batches' = SUM(Fact_Quality[RFT: Total # of Finished Goods Batches])
		formatString: 0
		displayFolder: RFT
		lineageTag: 88cc745b-d8b7-4d76-a482-86db76701827

	measure RFT% =
			
			Var kpi_ = DIVIDE([Total # of Batches w deviations],[Total # of Finished Goods Batches])
			
			Return
			IF(ISBLANK(kpi_),BLANK(),1-kpi_)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: RFT
		lineageTag: e3341eff-45f1-49b5-83f9-55afabc1a42a

	measure 'RFT% PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([RFT%],filter_)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: RFT
		lineageTag: f6f5daba-e19c-4670-b27c-20dca12c8df7

	measure 'RFT% PP' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([RFT%],filter_)
			RETURN
			Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: RFT
		lineageTag: aa3be89c-964f-4ad7-8101-10e2db2d7950

	measure 'RFT MoM%' =
			
			VAR Result =  [RFT%] - [RFT% PP]
			RETURN
			Result
		displayFolder: RFT
		lineageTag: 5aff3cae-1da6-499e-a99b-333e16060855

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RFT MoM_Final' = ```
			
			VAR kpi_ = [RFT MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: RFT
		lineageTag: 3a9a90c8-f768-457b-962e-8de5d03dd601

	measure 'RFT YTD' = TOTALYTD([RFT%],Dim_Date[Date])
		displayFolder: RFT
		lineageTag: cf26356a-f861-4f08-8a29-b1e803a0e00b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RFT YoY%' =
			
			IF(ISBLANK([RFT% PY]),BLANK(),[RFT%] - [RFT% PY])
		displayFolder: RFT
		lineageTag: 70bae1a7-4731-4594-bc65-85144df2611f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RFT YoY_Final' =
			
			VAR kpi_ =  [RFT YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: RFT
		lineageTag: 173440f2-a2da-4758-8e2c-89e5b783808b

	measure 'Total # of Batches w deviations PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Total # of Batches w deviations],filter_)
			
			```
		formatString: 0
		displayFolder: RFT
		lineageTag: 3c2afce1-e288-4058-960c-c6700b02bc71

	measure 'Total # of Finished Goods Batches PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Total # of Finished Goods Batches],filter_)
			
			```
		formatString: 0
		displayFolder: RFT
		lineageTag: d4b4eb5d-64af-4f8d-bc71-56b053f770d6

	measure 'Total # of Batches w deviations LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Total # of Batches w deviations PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			```
		formatString: 0
		displayFolder: RFT
		lineageTag: 43c91248-bef7-4738-b96d-1d06e98d2738

	measure 'Total # of Finished Goods Batches LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Total # of Finished Goods Batches PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			```
		formatString: 0
		displayFolder: RFT
		lineageTag: 747fd609-8b76-4da0-9c8f-700ef38b7999

	measure 'RFT LYTD' =
			
			Var kpi_ = DIVIDE([Total # of Batches w deviations LYTD],[Total # of Finished Goods Batches LYTD])
			
			Return
			IF(ISBLANK(kpi_),BLANK(),1-kpi_)
		displayFolder: RFT
		lineageTag: 7989ef8d-2b4f-4939-83c6-79260258ac00

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RFT LYTD_Final' =
			
			VAR kpi_ =  [RFT LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: RFT
		lineageTag: fa4fc465-e9bf-4867-9f32-b86bb319c8af

	measure 'RFT Plan' = AVERAGE(Fact_Quality[RFT Target])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: RFT
		lineageTag: 31822323-d99d-4571-85d1-c72c8d365b32

	measure 'RFT Target Diff%' = [RFT%] - [RFT Plan]
		displayFolder: RFT
		lineageTag: 194d664e-67de-4ffb-ae26-92f7dcfdf980

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RFT Target Final' = ```
			
			VAR kpi_ =  [RFT Target Diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: RFT
		lineageTag: d8d8affd-ba71-4c0a-a12c-866cfd0e0b64

	measure 'Critical or Major Observations' = SUM(Fact_Quality[Critical_Major_Obs_Quarter])
		formatString: 0
		displayFolder: Critical or Major Obs
		lineageTag: d966a903-becc-4282-bc01-81b7a1fb8785

	measure 'Critical or Major Observations PP' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([Critical or Major Observations],filter_)
			RETURN
			Result
		formatString: 0
		displayFolder: Critical or Major Obs
		lineageTag: 806fb950-2d5e-40ec-95da-e2e923cee781

	measure 'Critical or Major Observations PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Critical or Major Observations],filter_)
			
			```
		formatString: 0
		displayFolder: Critical or Major Obs
		lineageTag: 6753a7d1-a0c6-4a12-a808-5951422d717b

	measure 'Critical or Major Observations YTD' =
			VAR _LastMonth = MAX(Dim_Date[P_YearMonth Number])
			VAR _SelectedYear = MAX(Dim_Date[P_Year])
			RETURN
			    SUMX(
			        FILTER(
			            ALL(Dim_Date),
			            Dim_Date[P_YearMonth Number] <= _LastMonth && Dim_Date[P_Year] = _SelectedYear
			        ),
			        [Critical or Major Observations]
			    )
		formatString: 0
		displayFolder: Critical or Major Obs
		lineageTag: 4aa8b54a-66b0-4cc2-bd96-dbca56a655c2

	measure 'Critical or Major Observations YoY%' =
			
			DIVIDE(([Critical or Major Observations] - [Critical or Major Observations PY]),[Critical or Major Observations PY])
		displayFolder: Critical or Major Obs
		lineageTag: 466aa6b1-a529-44c6-9f87-366ccad8b458

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Critical or Major Observations MoM%' =
			
			DIVIDE(([Critical or Major Observations] - [Critical or Major Observations PP]),[Critical or Major Observations PP])
		displayFolder: Critical or Major Obs
		lineageTag: d6e0038f-7790-487e-96c2-31f85d5b92f5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Critical or Major Observations MoM_Final' = ```
			
			VAR kpi_ = [Critical or Major Observations MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: Critical or Major Obs
		lineageTag: 984174b7-9fd8-4622-969a-e46817b3f4d2

	measure 'Critical or Major Observations YoY_Final' =
			
			VAR kpi_ =  [Critical or Major Observations YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Critical or Major Obs
		lineageTag: 08c12c06-db29-4cdd-a6af-fe91f5ba1569

	measure 'Critical or Major Observations LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Critical or Major Observations PY])
			VAR Result = Sumx(Table_,[Measure])
			RETURN
			IF(
			    ISBLANK(Result) || Result = 0,
			    BLANK(),
			    DIVIDE([Critical or Major Observations] - Result,Result)
			)
			```
		displayFolder: Critical or Major Obs
		lineageTag: 4c797d01-b750-4ddd-bb89-52e25aefb6a5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Critical or Major Observations LYTD_Final' =
			
			VAR kpi_ =  [Critical or Major Observations LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Critical or Major Obs
		lineageTag: 540097a8-5a75-4168-91e5-587b9a4c00c8

	measure DSO_APN_Base =
			
			Var num = CALCULATE(SUM(Fact_DSO_DPO_ABP[DSO_Plan_Num]),KEEPFILTERS(Dim_Date[Is Closed] = "TRUE"))
			VAR den = CALCULATE(SUM(Fact_DSO_DPO_ABP[DSO_Plan_Den]),KEEPFILTERS(Dim_Date[Is Closed] = "TRUE"))
			RETURN
			DIVIDE(num,den,0)
		formatString: 0
		displayFolder: DSO
		lineageTag: c0182232-6355-4f58-b268-c664a677e288

	measure 'ABP Variance' = SUM(Fact_DSO_DPO_ABP[ABP_Variance])*1000
		formatString: #,0.0
		displayFolder: ABP Variance
		lineageTag: f3a47495-0f92-47a2-82e6-13df475dc8bb

	measure 'ABP Variance_APN_Base' = SUM(Fact_DSO_DPO_ABP[ABP_Variance_Plan])*1000
		formatString: #,0.0
		displayFolder: ABP Variance
		lineageTag: 01de310b-7071-4630-8ec8-f4eb287ab435

	measure 'ABP Variance_APN' =
			
			VAR Plan = [ABP Variance_APN_Base]
			Return
			DIVIDE([ABP Variance] - Plan,Plan)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: ABP Variance
		lineageTag: 86475614-9c08-4f1b-8c2d-4fe370e78d4e

	measure 'ABP Variance_APN_Final' =
			
			VAR kpi_ = [ABP Variance_APN]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: ABP Variance
		lineageTag: ed91c662-52e7-4ab7-9ac9-846e8024663f

	measure DSO_APN =
			
			VAR Plan = [DSO_APN_Base]
			Return
			DIVIDE([DSO] - Plan,Plan)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: DSO
		lineageTag: cd97b757-0f40-472d-98f5-a4286fffa392

	measure DSO_APN_Final =
			
			VAR kpi_ = [DSO_APN]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: DSO
		lineageTag: 911fbc7a-a7e1-445a-b016-bb039e5cf369

	measure DPO_APN_Base =
			
			Var num = CALCULATE(SUM(Fact_DSO_DPO_ABP[DPO_Plan_Num]),KEEPFILTERS(Dim_Date[Is Closed] = "TRUE"))
			VAR den = CALCULATE(SUM(Fact_DSO_DPO_ABP[DPO_Plan_Den]),KEEPFILTERS(Dim_Date[Is Closed] = "TRUE"))
			RETURN
			DIVIDE(num,den,0)
		formatString: 0
		displayFolder: DPO
		lineageTag: 828f35b9-39e3-4c7a-8008-85040514ed06

	measure DPO_APN =
			
			VAR Plan = [DPO_APN_Base]
			Return
			DIVIDE([DPO] - Plan,Plan)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: DPO
		lineageTag: 978c56d0-d760-4dcd-b260-326fd435f358

	measure DPO_APN_Final =
			
			VAR kpi_ = [DPO_APN]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: DPO
		lineageTag: 5898639d-6f98-4ae4-84ed-da03c8e48e38

	measure 'ABP Variance PP' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([ABP Variance],filter_)
			RETURN
			Result
		formatString: 0.0
		displayFolder: ABP Variance
		lineageTag: 22096135-3c90-46ad-8d56-2e511a0cd778

	measure 'ABP Variance PY' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([ABP Variance],filter_)
		formatString: 0.0
		displayFolder: ABP Variance
		lineageTag: 948d024c-22f0-4f39-980c-427e9819ecd0

	measure 'ABP Variance YoY%' = DIVIDE(([ABP Variance] - [ABP Variance PY]),[ABP Variance PY])
		displayFolder: ABP Variance
		lineageTag: 4defcb38-23dc-4953-82e7-c4811e09abae

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ABP Variance YoY_Final' =
			VAR kpi_ =  [ABP Variance YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: ABP Variance
		lineageTag: 0411fd22-a813-4196-80fe-5a3b035f82cf

	measure 'ABP Variance MoM%' =
			
			VAR Result = DIVIDE(([ABP Variance] - [ABP Variance PP]), [ABP Variance PP])
			RETURN
			Result
		formatString: 0.0
		displayFolder: ABP Variance
		lineageTag: ba33b857-b276-4ffc-8d08-003e51a83c2a

	measure 'ABP Variance MoM_Final' = ```
			VAR kpi_ =  [ABP Variance MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: ABP Variance
		lineageTag: 7691bc0d-7b26-4995-8a50-62620991a6c7

	measure 'ABP Variance LYTD' = ```
			
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [ABP Variance PY])
			VAR Result = Sumx(Table_,[Measure])
			RETURN
			IF(
			    ISBLANK(Result) || Result = 0,
			    BLANK(),
			    DIVIDE([ABP Variance] - Result,Result)
			)
			```
		formatString: 0.0
		displayFolder: ABP Variance
		lineageTag: cad9adcc-2b7c-48e5-8898-03b67ad1a54b

	measure 'ABP Variance LYTD_Final' =
			VAR kpi_ =  [ABP Variance LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: ABP Variance
		lineageTag: 2d8d18d5-851f-4546-9597-89813dbb967c

	measure Sales_bar_graph =
			
			SWITCH(SELECTEDVALUE(External_Toggle[Show External]),"No", CALCULATE([Switch Sales_Parameter],KEEPFILTERS(Dim_Value_Stream[IsExternal] = "No")), "Yes",[Switch Sales_Parameter])
		displayFolder: Misc
		lineageTag: 7a3d34ff-216f-4751-81e9-5b518bae42a4

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(Sales_Parameter[Parameter Name]),
				    "FA% Lag 2", "0.0%",
				    "FA% Lag 4", "0.0%",
				    "Bias% Lag 2", "0.0%",
				    "Bias% Lag 4", "0.0%",
				    "Service%", "0.0%",
				    "CFR%", "0.0%",
				    "Service Top 11","#,0"
				)

	measure Working_Capital_bar_graph =
			
			SWITCH(SELECTEDVALUE(External_Toggle[Show External]),"No", CALCULATE([Switch Working Capital],KEEPFILTERS(Dim_Value_Stream[IsExternal] = "No")), "Yes",[Switch Working Capital])
		displayFolder: Misc
		lineageTag: 80070bed-940d-4ccf-9d43-623944ab1872

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Operating_Income_bar_graph =
			
			SWITCH(SELECTEDVALUE(External_Toggle[Show External]),"No", CALCULATE([Switch Operating_Parameter],KEEPFILTERS(Dim_Value_Stream[IsExternal] = "No")), "Yes",[Switch Operating_Parameter])
		displayFolder: Operating Income
		lineageTag: 6298cb05-0938-4cd5-b947-84a48a0e36e2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ABP Variance YTD' =
			VAR _LastMonth = MAX(Dim_Date[P_YearMonth Number])
			VAR _SelectedYear = MAX(Dim_Date[P_Year])
			RETURN
			    SUMX(
			        FILTER(
			            ALL(Dim_Date),
			            Dim_Date[P_YearMonth Number] <= _LastMonth && Dim_Date[P_Year] = _SelectedYear
			        ),
			        [ABP Variance]
			    )
		formatString: 0.0
		displayFolder: ABP Variance
		lineageTag: f27858ea-29ee-482d-bfc0-8dfb385f06d0

	measure 'Service Top 11' = ```
			SUMX(
			  FILTER( values(Fact_Service[Customer Hierarchy]), Fact_Service[Customer Hierarchy]  
			  IN {
			    "AMAZON",
			    "COSTCO",
			    "CVS",
			    "DOLLAR GENERAL",
			    "KROGER",
			    "MEIJER",
			    "SAM'S CLUB",
			    "TARGET",
			    "TOPCO",
			    "WALGREENS",
			    "WALMART"
			}),
			    
			    VAR ServiceRate = CALCULATE(
			        
			        DIVIDE( SUM( Fact_Service[On Delivery EA] ), SUM( Fact_Service[Order EA] ) ),
			    REMOVEFILTERS( Bridge_CSCA_CSCI[Area] ), REMOVEFILTERS( Dim_Profit_Center[Level 3] ) )
			    
			    RETURN
			    
			    IF( ServiceRate >= 0.90, 1, 0 )
			)
			
			```
		formatString: 0
		displayFolder: Service Top 11
		lineageTag: df125f1d-502a-4b16-bc3a-62baab07647c

	measure 'Top 11 Retailers CFR > 90%' = ```
			SUMX(
			  FILTER( values(Fact_CFR[Customer Hierarchy]), Fact_CFR[Customer Hierarchy]  
			  IN {
			    "AMAZON",
			    "COSTCO",
			    "CVS",
			    "DOLLAR GENERAL",
			    "KROGER",
			    "MEIJER",
			    "SAM'S CLUB",
			    "TARGET",
			    "TOPCO",
			    "WALGREENS",
			    "WALMART"
			}),
			    
			    VAR CFR = 
			  CALCULATE(     
			DIVIDE(SUM(Fact_CFR[Total Delivery Qty]),SUM(Fact_CFR[Total Order Qty])))
			    
			    RETURN
			    
			    IF( CFR >= 0.90, 1, 0 )
			)
			
			```
		formatString: 0
		displayFolder: CFR
		lineageTag: 6e7218de-97af-4113-9169-f5bdc319f9f5

	measure 'Service Top 11 PY' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Service Top 11],filter_)
		formatString: 0
		displayFolder: Service Top 11
		lineageTag: 2518550b-15ac-448e-a836-9691dfcc5731

	measure 'Service Top 11 PP' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([Service Top 11],filter_)
			RETURN
			Result
		formatString: 0
		displayFolder: Service Top 11
		lineageTag: d4df7a30-a561-41c0-af99-33c6ff363881

	measure 'Service Top 11 MoM%' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([Service Top 11],filter_)
			VAR Result = DIVIDE([Service Top 11] - Net_PM,Net_PM)
			RETURN
			Result
		formatString: 0
		displayFolder: Service Top 11
		lineageTag: 3a339552-dbde-4973-a5b6-96356997c308

	measure 'Service Top 11 MoM_Final' = ```
			
			VAR kpi_ =  [Service Top 11 MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Service Top 11
		lineageTag: a23e64ca-5e62-46d1-bb6b-3f189d8d193f

	measure 'Service Top 11 YoY%' = DIVIDE([Service Top 11] - [Service Top 11 PY], [Service Top 11 PY])
		formatString: 0
		displayFolder: Service Top 11
		lineageTag: 952f5126-1d1e-41ee-adc3-d068dc1f41de

	measure 'Service Top 11 YoY_Final' =
			
			VAR kpi_ =  [Service Top 11 YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Service Top 11
		lineageTag: c4b5297e-c302-421e-aa4d-38b721858be6

	measure 'Service Top 11 Target' =
			
			Var tar = CALCULATE(MAX(Fact_Target[Target]),KEEPFILTERS(Fact_Target[KPI_Name] = "Service Top 11 (#)"))
			RETURN
			tar
		formatString: 0
		displayFolder: Service Top 11
		lineageTag: 7d53f875-05d8-45b8-9300-c26825166515

	measure 'Service Top 11 Target Diff%' = DIVIDE([Service Top 11] - [Service Top 11 Target],[Service Top 11 Target])
		formatString: 0
		displayFolder: Service Top 11
		lineageTag: f0dcfb2e-3a04-4e6c-af84-e0d804a100a7

	measure 'Service Top 11 Target Final' = ```
			
			VAR kpi_ =  [Service Top 11 Target Diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Service Top 11
		lineageTag: be09e07a-4949-4c4b-aae7-3f25f09be6c9

	measure 'Service Top 11 LYTD Base' = ```
			SUMX(
			  FILTER( values(Fact_Service[Customer Hierarchy]), Fact_Service[Customer Hierarchy]  
			  IN {
			    "AMAZON",
			    "COSTCO",
			    "CVS",
			    "DOLLAR GENERAL",
			    "KROGER",
			    "MEIJER",
			    "SAM'S CLUB",
			    "TARGET",
			    "TOPCO",
			    "WALGREENS",
			    "WALMART"
			}),
			    
			    VAR ServiceRate = CALCULATE(
			        
			        DIVIDE( [On Delivery LYTD], [Order EA LYTD] ),
			    REMOVEFILTERS( Bridge_CSCA_CSCI[Area] ), REMOVEFILTERS( Dim_Profit_Center[Level 3] ) )
			    
			    RETURN
			    
			    IF( ServiceRate >= 0.90, 1, 0 )
			)
			```
		formatString: 0
		displayFolder: Service Top 11
		lineageTag: b48ba971-4982-4025-bb3a-9755fb350e63

	measure 'Service Top 11 YTD' = ```
			
			SUMX(
			  FILTER( values(Fact_Service[Customer Hierarchy]), Fact_Service[Customer Hierarchy]  
			  IN {
			    "AMAZON",
			    "COSTCO",
			    "CVS",
			    "DOLLAR GENERAL",
			    "KROGER",
			    "MEIJER",
			    "SAM'S CLUB",
			    "TARGET",
			    "TOPCO",
			    "WALGREENS",
			    "WALMART"
			}),
			    
			    VAR ServiceRate = CALCULATE(
			        
			        DIVIDE( SUM( Fact_Service[On Delivery EA] ), SUM( Fact_Service[Order EA] ) ),
			    REMOVEFILTERS( Bridge_CSCA_CSCI[Area] ), REMOVEFILTERS( Dim_Profit_Center[Level 3] ) )
			    
			    Var Result = IF( ServiceRate >= 0.90, 1, 0 )
			    RETURN TOTALYTD(Result,Dim_Date[Date])
			)
			```
		formatString: 0
		displayFolder: Service Top 11
		lineageTag: 274be111-f374-4942-8aaf-13bd20897307

	measure 'Service Top 11 LYTD' =
			
			DIVIDE([Service Top 11] - [Service Top 11 LYTD Base], [Service Top 11 LYTD Base])
		displayFolder: Service Top 11
		lineageTag: 1a3d0f8c-77d8-49bb-af7a-36711a136d35

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Service Top 11 LYTD_Final' =
			
			VAR kpi_ =  [Service Top 11 LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Service Top 11
		lineageTag: 2aa6f8e6-e705-4cd4-b885-a00a14f61c2e

	measure 'Total Logistics Actual LYTD' = ```
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Total Logistics Actual PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			DIVIDE([Total Logistics Actual] - Result,Result)
			```
		displayFolder: Logistic
		lineageTag: c4ad6b27-50d4-434e-a626-8ef287525d01

	measure 'Total Logistics Actual LYTD_Final' =
			
			VAR kpi_ =  [Total Logistics Actual LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Logistic
		lineageTag: 00af8cb4-2afe-45a0-a1f4-40dee5c0fd6a

	measure 'Total Logistics Actual MoM%' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([Total Logistics Actual],filter_)
			VAR Result = DIVIDE(([Total Logistics Actual] - Net_PM),Net_PM)
			RETURN
			Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Logistic
		lineageTag: aecd1849-cc16-4f9b-988b-c21f217b4007

	measure 'Total Logistics Actual MoM_Final' = ```
			VAR kpi_ =  [Total Logistics Actual MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Logistic
		lineageTag: 2c233431-43d1-44df-a028-62cd7d7aa930

	measure 'Total Logistics Actual PP' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([Total Logistics Actual],filter_)
			RETURN
			Result
		formatString: 0.0
		displayFolder: Logistic
		lineageTag: f2e07778-23cf-4d8b-80b6-2908c3e51fb6

	measure 'Total Logistics Actual PY' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Total Logistics Actual],filter_)
		formatString: 0.0
		displayFolder: Logistic
		lineageTag: ee2e5b19-38e5-4b7c-980f-de513aafe696

	measure 'Total Logistics Actual YoY%' = DIVIDE(([Total Logistics Actual] - [Total Logistics Actual PY]),[Total Logistics Actual PY])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Logistic
		lineageTag: 3eaea7f2-0c2f-4b3d-97cb-d6fa9f9979d1

	measure 'Total Logistics Actual YoY_Final' =
			VAR kpi_ =  [Total Logistics Actual YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: Logistic
		lineageTag: baeeebfd-9bf6-4f85-a6af-e3a173a1ec89

	measure 'Total Logistics Actual YTD' =
			VAR _LastMonth = MAX(Dim_Date[P_YearMonth Number])
			VAR _SelectedYear = MAX(Dim_Date[P_Year])
			RETURN
			    SUMX(
			        FILTER(
			            ALL(Dim_Date),
			            Dim_Date[P_YearMonth Number] <= _LastMonth && Dim_Date[P_Year] = _SelectedYear
			        ),
			        [Total Logistics Actual]
			    )
		formatString: 0.0
		displayFolder: Logistic
		lineageTag: 8b17f568-7af0-4f78-a5c2-f0208c236fb5

	measure 'Distribution Actual YTD' =
			VAR _LastMonth = MAX(Dim_Date[P_YearMonth Number])
			VAR _SelectedYear = MAX(Dim_Date[P_Year])
			RETURN
			    SUMX(
			        FILTER(
			            ALL(Dim_Date),
			            Dim_Date[P_YearMonth Number] <= _LastMonth && Dim_Date[P_Year] = _SelectedYear
			        ),
			        [Distribution Actual]
			    )
		formatString: #,0.0
		displayFolder: Distribution on COGS
		lineageTag: 991d5fa4-4623-4dd6-b22a-ae9083ee4b60

	measure 'Distribution Actual LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [Distribution Actual PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			```
		formatString: #,0.0
		displayFolder: Distribution on COGS
		lineageTag: 1b866793-cf0e-47df-b06a-ca3ce6bb4dd7

	measure 'Distribution Actual PY' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Distribution Actual],filter_)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Distribution on COGS
		lineageTag: 017c54df-87d2-47e2-a364-7cda99909c99

	measure 'Selected Filters CSCA' = ```
			
			"Business Unit: " & 
			IF(
			    ISFILTERED('Dim_Profit_Center'[FP&A Cluster]),
			    CONCATENATEX(VALUES('Dim_Profit_Center'[FP&A Cluster]), 'Dim_Profit_Center'[FP&A Cluster], ", "),
			    "All"
			)
			& " | Value Stream: " 
			&  IF(
			    ISFILTERED('Dim_Value_Stream'[Value_Stream_Final]),
			    CONCATENATEX(VALUES('Dim_Value_Stream'[Value_Stream_Final]), 'Dim_Value_Stream'[Value_Stream_Final], ", "),
			    "All"
			)
			& " |  " 
			& IF(
			    ISFILTERED('Dim_DateSlicer'[P_YearPeriod]),
			    CONCATENATEX(VALUES('Dim_DateSlicer'[P_YearPeriod]), 'Dim_DateSlicer'[P_YearPeriod], ", "),
			    "All"
			)
			& " |  " 
			& IF(
			    ISFILTERED('CG_PeriodSelection'[Period]),
			    CONCATENATEX(VALUES('CG_PeriodSelection'[Period]), 'CG_PeriodSelection'[Period], ", "),
			    "All"
			)
			& " |  " 
			& IF(
			    ISFILTERED('MetricSelector'[Metric]),
			    CONCATENATEX(VALUES('MetricSelector'[Metric]), 'MetricSelector'[Metric], ", "),
			    "All"
			)
			```
		displayFolder: Misc
		lineageTag: 2589295c-73b8-40ae-8d3a-c6af2eaacd72

	measure 'Selected Filters CSCI' = ```
			
			"Cluster: " & 
			IF(
			    ISFILTERED('Dim_Profit_Center'[FP&A Cluster]),
			    CONCATENATEX(VALUES('Dim_Profit_Center'[FP&A Cluster]), 'Dim_Profit_Center'[FP&A Cluster], ", "),
			    "All"
			)
			& " |  " 
			& IF(
			    ISFILTERED('Dim_DateSlicer'[P_YearPeriod]),
			    CONCATENATEX(VALUES('Dim_DateSlicer'[P_YearPeriod]), 'Dim_DateSlicer'[P_YearPeriod], ", "),
			    "All"
			)
			& " |  " 
			& IF(
			    ISFILTERED('CG_PeriodSelection'[Period]),
			    CONCATENATEX(VALUES('CG_PeriodSelection'[Period]), 'CG_PeriodSelection'[Period], ", "),
			    "All"
			)
			& " |  " 
			& IF(
			    ISFILTERED('MetricSelector'[Metric]),
			    CONCATENATEX(VALUES('MetricSelector'[Metric]), 'MetricSelector'[Metric], ", "),
			    "All"
			)
			```
		displayFolder: Misc
		lineageTag: 423325f4-791c-4ea5-a78c-727c534a476e

	measure 'ABP Variance _Color' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [ABP Variance MoM%],
			        "LYTD", [ABP Variance LYTD],
			        "vs YoY", [ABP Variance YoY%],
			        "vs Plan", [ABP Variance_APN],
			        "vs 3M avg", [ABP Variance 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value > 0,
			            "#D7191C",  -- red for ▲ up
			            "#1A9641"  -- green for ▼ down
			        )
		displayFolder: ABP Variance
		lineageTag: dda3e5b0-c04c-4d94-b3f7-10636779617b

	measure 'ABP Variance _Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [ABP Variance MoM%],
			        "LYTD", [ABP Variance LYTD],
			        "vs YoY", [ABP Variance YoY%],
			        "vs Plan", [ABP Variance_APN],
			        "vs 3M avg", [ABP Variance 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value > 0,
			            "#D7191C",  -- red
			            "#001489"  -- Blue for ▼ down
			        )
			)
			```
		displayFolder: ABP Variance
		lineageTag: 5a552db2-9736-4306-b944-f7bc3ae29986

	measure 'ABP Variance Switch' = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [ABP Variance MoM_Final],
			      "LYTD", [ABP Variance LYTD_Final],
			      "vs YoY", [ABP Variance YoY_Final],
			      "vs Plan", [ABP Variance_APN_Final],
			      "vs 3M avg", [ABP Variance 3M_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: ABP Variance
		lineageTag: 1b4f5894-c1e9-45a4-a0ad-2f4c000d0841

	measure FA_CSCA_Color_KPI = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [FA% MoM%],
			        "LYTD", [FA% CSCA LYTD],
			        "vs YoY", [FA% YoY%],  
			        "vs Plan", Switch(SELECTEDVALUE(Fact_Forecast_Accuracy[LAGs]),"2",[FA% Lag 2 Target Diff%], "4", [FA% Lag 4 Target Diff%]),
			        "vs 3M avg", [FA 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        _sel = "YTD",
			        "#000000",  -- Always black for YTD
			    IF(
			        ISBLANK(kpi_value), "#001489",  -- black for blank
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#001489"   -- green for ▲ up
			        )
			    )
			)
			```
		displayFolder: Forecast Accuracy CSCA
		lineageTag: f7814614-4b3d-457c-a6b1-09fcccc76831

	measure Forecast_Accuracy_Lag = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [FA% MoM_Final],
			      "LYTD",               [FA% CSCA LYTD_Final],
			      "vs YoY",               [FA% YoY_Final],
			      "vs Plan", SWITCH(SELECTEDVALUE(Fact_Forecast_Accuracy[LAGs]),"2",[FA% Lag2 Target_Final],"4",[FA% Lag4 Target_Final]),
			      "vs 3M avg", [FA% 3M_Final],
			      BLANK()
			    )
			
			```
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 0df02182-49ea-4ccc-b141-c65ea0001be0

	measure Forecast_Accuracy_Lag_Color = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [FA% MoM%],
			        "LYTD", [FA% CSCA LYTD],
			        "vs YoY", [FA% YoY%],  
			        "vs Plan", Switch(SELECTEDVALUE(Fact_Forecast_Accuracy[LAGs]),"2",[FA% Lag 2 Target Diff%],
			        "4",[FA% Lag 4 Target Diff%]),
			        "vs 3M avg", [FA 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        _sel = "YTD",
			        "#000000",  -- Always black for YTD
			    IF(
			        ISBLANK(kpi_value), "#000000",  -- black for blank
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#1A9641"   -- green for ▲ up
			        )
			    )
			)
			```
		displayFolder: Forecast Accuracy CSCA
		lineageTag: cc90c6c1-1a6e-4f64-80a9-d71e27f6a224

	measure 'Gross Inventory _Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Gross Inventory MoM%],
			        "LYTD", [Gross Inv LYTD],
			        "vs YoY", [Gross Inventory YoY%],
			        "vs Plan", [Gross Inventory_APN],
			        "vs Flex", [Gross Inventory_AFX],
			        "vs 3M avg", [Gross Inventory 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value > 0,
			                "#D7191C",  -- Red for ▲ up
			                "#001489"   -- Green for ▼ down
			        )
			)
			```
		displayFolder: Gross Inventory
		lineageTag: 93daddeb-ac4c-4805-a0e5-37cff8c957ad

	measure Gross_Inventory = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Gross Inventory MoM_Final],
			      "LYTD",               [Gross Inv LYTD_Final],
			      "vs YoY",               [Gross Inventory YoY_Final],
			      "vs Plan", [Gross Inventory_APN_Final],
			      "vs Flex", [Gross Inventory_AFX_Final],
			      "vs 3M avg", [Gross Inventory 3M_Final],
			      BLANK()
			    )
			```
		displayFolder: Gross Inventory
		lineageTag: ceafa47a-354b-4324-8248-ae2bf82e8e14

	measure Gross_Inventory_Color =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Gross Inventory MoM%],
			        "LYTD", [Gross Inv LYTD],
			        "vs YoY", [Gross Inventory YoY%],
			        "vs Plan", [Gross Inventory_APN],
			        "vs Flex", [Gross Inventory_AFX],
			        "vs 3M avg", [Gross Inventory 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#1A9641",  -- green for ▼ down
			            "#D7191C"   -- red for ▲ up
			        )
		displayFolder: Gross Inventory
		lineageTag: 01a21988-f77d-49c9-a7cc-a6f087fc4e81

	measure 'Inflated Inventory _Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Inflated Inventory MoM%],
			        "LYTD", [Inflated Inv LYTD],
			        "vs YoY", [Inflated Inventory YoY%],
			        "vs 3M avg", [Inflated Inventory 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value > 0,
			                "#D7191C",  -- Red for ▲ up
			                "#001489"   -- Green for ▼ down
			        )
			)
			```
		displayFolder: Inflated Inventory
		lineageTag: ee18417c-4d91-4374-9d7d-b658161639bf

	measure Inflated_Inventory = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Inflated Inventory MoM_Final],
			      "LYTD",               [Inflated Inv LYTD_Final],
			      "vs YoY",               [Inflated Inventory YoY_Final],
			      "vs 3M avg", [Inflated Inventory 3M_Final],
			      BLANK()
			    )
			
			```
		displayFolder: Inflated Inventory
		lineageTag: 4142541c-b983-4249-81dc-8c2cd55b1fb4

	measure Inflated_Inventory_Color =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Inflated Inventory MoM%],
			        "LYTD", [Inflated Inv LYTD],
			        "vs YoY", [Inflated Inventory YoY%],
			        "vs 3M avg", [Inflated Inventory 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#1A9641",  -- green for ▼ down
			            "#D7191C"   -- red for ▲ up
			        )
		displayFolder: Inflated Inventory
		lineageTag: 856c2e81-9dbc-41c9-bdac-120fa14755e8

	measure 'Net Inventory _Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Net Inventory MoM%],
			        "LYTD", [Net Inventory LYTD],
			        "vs YoY", [Net Inventory YoY%],
			        "vs Plan", [Net Inventory_APN],
			        "vs Flex", [Net Inventory_AFX],
			        "vs 3M avg", [Net Inventory 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value > 0,
			                "#D7191C",  -- Red for ▲ up
			                "#001489"   -- Green for ▼ down
			        )
			)
			```
		displayFolder: Net Inventory
		lineageTag: e6e21601-117e-4ef0-a1db-fd0f376470e0

	measure 'Net POV_Color' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Net POV Actual MoM%],
			        "LYTD", [Net POV Actual LYTD],
			        "vs YoY", [Net POV Actual YoY%], 
			        "vs Plan", [Net POV_APN],
			        "vs 3M avg", [Net POV 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#000000", 
			        IF(
			            kpi_value < 0,
			            "#1A9641",  -- green for ▼ down
			            "#D7191C"   -- red for ▲ up
			        )
			)
			```
		displayFolder: Net POV
		lineageTag: 06476168-c605-4c2b-853c-f9c7f43b6551

	measure 'Net POV_Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Net POV Actual MoM%],
			        "LYTD", [Net POV Actual LYTD],
			        "vs YoY", [Net POV Actual YoY%], 
			        "vs Plan", [Net POV_APN],
			        "vs 3M avg", [Net POV 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#001489",  -- green for ▼ down
			            "#D7191C"   -- red for ▲ up
			        )
			)
			```
		displayFolder: Net POV
		lineageTag: 8f3d95c8-f2a7-4423-8652-b9e33244f269

	measure Net_Inventory = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Net Inventory MoM_Final],
			      "LYTD",               [Net Inv LYTD_Final],
			      "vs YoY",               [Net Inventory YoY_Final],
			      "vs Plan", [Net Inventory_APN_Final],
			      "vs Flex", [Net Inventory_AFX_Final],
			      "vs 3M avg", [Net Inventory 3M_Final],
			      BLANK()
			    )
			
			```
		displayFolder: Net Inventory
		lineageTag: 9641f29e-d5e6-47d5-b11c-7eff043f4732

	measure Net_Inventory_Color =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Net Inventory MoM%],
			        "LYTD", [Net Inventory LYTD],
			        "vs YoY", [Net Inventory YoY%],
			        "vs Plan", [Net Inventory_APN],
			        "vs Flex", [Net Inventory_AFX],
			        "vs 3M avg", [Net Inventory 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#1A9641",  -- green for ▼ down
			            "#D7191C"   -- red for ▲ up
			        )
		displayFolder: Net Inventory
		lineageTag: 2682106c-541b-4134-a970-546eb8033819

	measure 'CAPA _Color' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [CAPA Completion Rate MoM%],
			        "LYTD", [CAPA Completion Rate LYTD],
			        "vs YoY", [CAPA Completion Rate YoY%],
			        "vs Plan", [CAPA Completion Rate Target Diff%],
			        "vs 3M avg", [CAPA Completion 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value > 0,
			            "#1A9641",  -- green for ▲ up
			            "#D7191C"  -- red for ▼ down
			        )
		displayFolder: CAPA Completion Rate
		lineageTag: 19d83f4e-8863-433f-ba49-f0a77c7be310

	measure 'CAPA _Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [CAPA Completion Rate MoM%],
			        "LYTD", [CAPA Completion Rate LYTD],
			        "vs YoY", [CAPA Completion Rate YoY%],
			        "vs Plan", [CAPA Completion Rate Target Diff%],
			        "vs 3M avg", [CAPA Completion 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value > 0,
			            "#001489",  -- blue by default
			            "#D7191C"  -- red for ▼ down
			        )
			)
			```
		displayFolder: CAPA Completion Rate
		lineageTag: 712ff5f9-1a54-47fa-93e9-1f7a435b47ea

	measure 'CAPA Switch' = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [CAPA Completion Rate MoM_Final],
			      "LYTD", [CAPA Completion Rate LYTD_Final],
			      "vs YoY", [CAPA Completion Rate YoY_Final],
			      "vs Plan", [CAPA Completion Rate Target Final],
			      "vs 3M avg", [CAPA Completion Rate 3M_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: CAPA Completion Rate
		lineageTag: 57b5adf4-217b-479f-847b-5a886f1da021

	measure 'RFT _Color' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [RFT MoM%],
			        "LYTD", [RFT LYTD],
			        "vs YoY", [RFT YTD],
			        "vs Plan", [RFT Target Diff%],
			        "vs 3M avg", [RFT 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value > 0,
			            "#1A9641",  -- green for ▲ up
			            "#D7191C"  -- red for ▼ down
			        )
		displayFolder: RFT
		lineageTag: 42b2e445-ffda-49e5-b252-bdc8d21c0e73

	measure 'RFT _Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [RFT MoM%],
			        "LYTD", [RFT LYTD],
			        "vs YoY", [RFT YoY%],
			        "vs Plan", [RFT Target Diff%],
			        "vs 3M avg", [RFT 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value > 0,
			            "#001489",  -- blue by default
			            "#D7191C"  -- red for ▼ down
			        )
			)
			```
		displayFolder: RFT
		lineageTag: a0b8ff3a-6bb4-465b-9af2-1f29f6636561

	measure 'RFT Switch' = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [RFT MoM_Final],
			      "LYTD", [RFT LYTD_Final],
			      "vs YoY", [RFT YoY_Final],
			      "vs Plan", [RFT Target Final],
			      "vs 3M avg", [RFT 3M_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: RFT
		lineageTag: 93c1f698-59ac-4d8b-9b41-da39e8f315ec

	measure 'Critical or Major Observations _Color' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Critical or Major Observations MoM%],
			        "LYTD", [Critical or Major Observations LYTD],
			        "vs YoY", [Critical or Major Observations YTD],
			        "vs Plan","--",
			        "vs 3M avg", [Critical Major Obs 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#1A9641",  -- green for ▲ up
			            "#D7191C"  -- red for ▼ down
			        )
		displayFolder: Critical or Major Obs
		lineageTag: 1d7617d7-9fc4-4d04-97a7-5004c9f8a209

	measure 'Critical or Major Observations _Color_KPI' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Critical or Major Observations MoM%],
			        "LYTD", [Critical or Major Observations LYTD],
			        "vs YoY", [Critical or Major Observations YoY%],
			        "vs Plan", "--",
			        "vs 3M avg", [Critical Major Obs 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        OR(ISBLANK(kpi_value),kpi_value = "--"), "#001489",
			        IF(
			            kpi_value < 0,
			            "#001489",  -- blue by default
			            "#D7191C"  -- red for ▼ down
			        )
			)
		displayFolder: Critical or Major Obs
		lineageTag: 8cd7b0dd-015f-48f8-9b44-f780b10f0122

	measure 'Critical or Major Observations Switch' = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Critical or Major Observations MoM_Final],
			      "LYTD", [Critical or Major Observations LYTD_Final],
			      "vs YoY", [Critical or Major Observations YoY_Final],
			      "vs Plan", "--",
			      "vs 3M avg", [Critical or Major Observations 3M_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: Critical or Major Obs
		lineageTag: 0380be26-08ae-45e6-80ed-64eed0bab944

	measure 'Deviations _Color' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [On Time Closure of Deviations MoM%],
			        "LYTD", [On Time Closure of Deviations LYTD],
			        "vs YoY", [On Time Closure of Deviations YoY%],
			        "vs Plan", [On Time Closure of Deviations Target Diff%],
			        "vs 3M avg", [On Time Closure of Deviations 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value > 0,
			            "#1A9641",  -- green for ▲ up
			            "#D7191C"  -- red for ▼ down
			        )
		displayFolder: On Time Closure of Deviations
		lineageTag: d417ef57-f4c6-4a2b-8e95-a2e12e2002e0

	measure 'Deviations _Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [On Time Closure of Deviations MoM%],
			        "LYTD", [On Time Closure of Deviations LYTD],
			        "vs YoY", [On Time Closure of Deviations YoY%],
			        "vs Plan", [On Time Closure of Deviations Target Diff%],
			        "vs 3M avg", [On Time Closure of Deviations 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value > 0,
			            "#001489",  -- blue by default
			            "#D7191C"  -- red for ▼ down
			        )
			)
			```
		displayFolder: On Time Closure of Deviations
		lineageTag: 1cac5b71-4aa9-4944-9ecf-1851147a27d8

	measure 'Deviations Switch' = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [On Time Closure of Deviations MoM_Final],
			      "LYTD", [On Time Closure of Deviations LYTD_Final],
			      "vs YoY", [On Time Closure of Deviations YoY_Final],
			      "vs Plan", [On Time Closure of Deviations Target Final],
			      "vs 3M avg", [On Time Closure of Deviations 3M_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: On Time Closure of Deviations
		lineageTag: ed252ca9-2aa6-4023-971d-d70acef28a88

	measure 'Bias Switch' = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Bias MoM_Final],
			      "LYTD",               [Bias% LYTD_Final],
			      "vs YoY",               [Bias YoY_Final],
			      "vs Plan", [Bias Target Final],
			      "vs 3M avg", [Bias 3M_Final],
			      BLANK()
			    )
			
			```
		displayFolder: Bias CSCA
		lineageTag: 35cd6896-b861-469f-b15d-3080e543393e

	measure Bias_Color = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Bias MoM%],
			        "LYTD", [Bias% LYTD],
			        "vs YoY", [Bias YoY%],
			        "vs Plan", [Bias Target Diff%],
			        "vs 3M avg", [Bias 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			    IF(
			        ISBLANK(kpi_value), "#000000",  // black for blank
			        IF(
			            ABS(kpi_value) <= 0.03,     // between -3% and +3%
			            "#1A9641",                  // green
			            "#D7191C"                   // red
			        )
			    )
			
			```
		displayFolder: Bias CSCA
		lineageTag: d9006fc7-626b-453f-8839-d76881195577

	measure Bias_CSCA_Color_KPI = ```
			
			/*
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			// Current KPI value (raw % bias)
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Bias MoM%],
			        "LYTD", [Bias% LYTD],
			        "vs YoY", [Bias YoY%],
			        "vs Plan", [Bias Target Diff%],
			        BLANK()
			    )
			
			// Previous period's KPI value
			VAR prev_kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", CALCULATE([Bias MoM%], Dim_Date[YearPeriodSeq] = MAX(Dim_Date[YearPeriodSeq]) - 1),
			        "LYTD", CALCULATE([Bias% LYTD], Dim_Date[YearPeriodSeq] = MAX(Dim_Date[YearPeriodSeq]) - 1),
			        "vs YoY", CALCULATE([Bias YoY%], Dim_Date[YearPeriodSeq] = MAX(Dim_Date[YearPeriodSeq]) - 1),
			        "vs Plan", CALCULATE([Bias Target Diff%], Dim_Date[YearPeriodSeq] = MAX(Dim_Date[YearPeriodSeq]) - 1),
			        BLANK()
			    )
			
			// Is bias within acceptable range of -5% to +5%
			VAR isAcceptable = NOT ISBLANK(kpi_value) && ABS(kpi_value) <= 0.05
			
			// Is bias improving (getting closer to 0 compared to previous)
			VAR isImproving = 
			    NOT isAcceptable &&
			    NOT ISBLANK(kpi_value) &&
			    NOT ISBLANK(prev_kpi_value) &&
			    ABS(kpi_value) < ABS(prev_kpi_value)
			
			RETURN
			    IF(
			        _sel = "YTD", "#000000",  // black for YTD
			        IF(
			            ISBLANK(kpi_value), "#000000",  // black for blank
			            IF(
			                isAcceptable || isImproving,
			                "#1A9641",  // green for acceptable or improving
			                "#D7191C"   // red for bad + not improving
			            )
			        )
			    )
			
			//another calculation
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Bias MoM%],
			        "LYTD", [Bias% LYTD],
			        "vs YoY", [Bias YoY%],
			        "vs Plan", [Bias Target Diff%],
			        BLANK()
			    )
			
			RETURN
			    IF(
			        ISBLANK(kpi_value), "#001489",  
			        IF(
			            ABS(kpi_value) <= 0.03,     // between -3% and +3%
			            "#001489",                  // Blue
			            "#D7191C"                   // red
			        )
			    )
			*/
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			VAR BiasValue = [Bias%] 
			VAR CompValue =
			    SWITCH(
			        _sel,
			        "vs PP", [Bias MoM%],
			        "LYTD", [Bias% LYTD],
			        "vs YoY", [Bias YoY%],
			        "vs Plan", [Bias Target Diff%],
			        "vs 3M avg", [Bias 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			    IF(
			        ISBLANK(CompValue), "#001489",  // fallback for blank
			        IF(
			            ABS(BiasValue) <= 0.03,     // green for bias within ±3%
			            "#001489",                  // green
			            "#D7191C"                   // red
			        )
			    )
			
			```
		displayFolder: Bias CSCA
		lineageTag: e07330fb-b52a-4afa-9cb5-8ad0efe057ea

	measure 'CFR _Color' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [CFR MoM%],
			        "LYTD", [CFR LYTD],
			        "vs YoY", [CFR YoY%],
			        "vs Plan", [CFR Target Diff%],
			        "vs 3M avg", [CFR 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value > 0,
			            "#1A9641",  -- green for ▲ up
			            "#D7191C"  -- red for ▼ down
			        )
		displayFolder: CFR
		lineageTag: e4ca5e4c-aaf6-4845-ae38-4787454da709

	measure 'CFR _Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [CFR MoM%],
			        "LYTD", [CFR LYTD],
			        "vs YoY", [CFR YoY%],
			        "vs Plan", [CFR Target Diff%],
			        "vs 3M avg", [CFR 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value > 0,
			            "#001489",  -- green for ▲ up
			            "#D7191C"  -- red for ▼ down
			        )
			)
			```
		displayFolder: CFR
		lineageTag: b54c830d-13b8-4beb-b276-a7252188ff39

	measure CFR_switch = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [CFR MoM_Final],
			      "LYTD",               [CFR LYTD_Final],
			      "vs YoY",               [CFR YoY_Final],
			      "vs Plan", [CFR Target Final],
			      "vs 3M avg", [CFR 3M_Final],
			      BLANK()
			    )
			```
		displayFolder: CFR
		lineageTag: 0f8b1637-a243-466d-b38d-32eaa49bf546

	measure COGS_Actual = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [COGS Actual MoM_Final],
			      "LYTD",               [COGS Actual LYTD_Final],
			      "vs YoY",               [COGS Actual YoY_Final],
			      "vs Plan", [COGS_APN_Final],
			      "vs Flex",[COGS_AFX_Final],
			      "vs 3M avg", [COGS Actual 3M_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: COGS
		lineageTag: 6d9487a3-6008-4ad4-9dd1-62a455d2f02f

		annotation PBI_FormatHint = {"isText":true}

	measure COGS_Actual_Color = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [COGS Actual MoM%],
			        "LYTD", [COGS Actual LYTD],
			        "vs YoY", [COGS Actual YoY%], 
			        "vs Plan", [COGS_APN],
			        "vs Flex",[COGS_AFX],
			        "vs 3M avg", [COGS 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			    IF(
			        ISBLANK(kpi_value), "#000000",         // black for blank
			        IF(
			            kpi_value < 0,
			            "#1A9641",  // green → down is good (COGS reduced)
			            "#D7191C"   // red → up is bad (COGS increased)
			        )
			    )
			
			```
		displayFolder: COGS
		lineageTag: 64617715-861c-49d7-80aa-96d3fe6cf662

	measure COGS_Color_KPI = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [COGS Actual MoM%],
			        "LYTD", [COGS Actual LYTD],
			        "vs YoY", [COGS Actual YoY%], 
			        "vs Plan", [COGS_APN],
			        "vs Flex",[COGS_AFX],
			        "vs 3M avg", [COGS 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#001489",   -- Blue for ▼ down
			            "#D7191C"    -- red for ▲ up
			        )
			)
			```
		displayFolder: COGS
		lineageTag: 6280ce49-6091-4ed0-95ad-54efeb144211

	measure 'Cust Fine_Color' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Cust Fine MoM%],
			        "LYTD", [Cust Fine LYTD],
			        "vs YoY", [Cust fine YoY%], 
			        "vs Plan", [Cust Fine Target Diff%],
			        "vs 3M avg", [Customer Fines 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#1A9641",  -- green for ▼ down
			            "#D7191C"   -- red for ▲ up
			        )
			```
		displayFolder: Customer Fines
		lineageTag: 567425fd-d2c2-4c4b-8601-b934c144f23b

	measure 'Cust Fine_Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Cust Fine MoM%],
			        "LYTD", [Cust Fine LYTD],
			        "vs YoY", [Cust fine YoY%], 
			        "vs Plan", [Cust Fine Target Diff%],
			        "vs 3M avg", [Customer Fines 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#001489",  -- green for ▼ down
			            "#D7191C"   -- red for ▲ up
			        )
			)
			```
		displayFolder: Customer Fines
		lineageTag: 8f456d45-80a7-47a0-888a-6a94759b6b3a

	measure 'Customer Fine Switch' = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Cust Fine MoM_Final],
			      "LYTD",               [Cust fine LYTD_Final],
			      "vs YoY",               [Cust fine YoY_Final],
			      "vs Plan", [Cust fine Target Final],
			      "vs 3M avg", [Customer Fines 3M_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: Customer Fines
		lineageTag: 7d24d324-ecca-4e2d-8e7a-a707ebe03941

	measure DIO_ = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [DIO MoM_Final],
			      "YTD",               [DIO YTD],
			      "vs YoY",               [DIO YoY_Final],
			      "vs Plan", [DIO_APN_Final],
			      "vs Flex", [DIO_AFX_Final],
			      "vs 3M avg", [DIO 3M_Final],
			      BLANK()
			    )
			
			```
		formatString: 0.0
		displayFolder: DIO
		lineageTag: 21e1375a-300b-4aad-bd12-18a069b96c6b

	measure DIO_Color =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [DIO MoM%],
			        "YTD", [DIO YTD],
			        "vs YoY", [DIO YoY%],
			        "vs Plan", [DIO_APN],
			        "vs Flex", [DIO_AFX],
			        "vs 3M avg", [DIO 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			    IF(
			            _sel = "YTD",
			            "#000000",  -- Always black for YTD
			        IF(
			            ISBLANK(kpi_value), "#000000",  -- black for blank
			            IF(
			                kpi_value < 0,
			                "#1A9641",  -- Green for ▼ down
			                "#D7191C"   -- Red for ▲ up
			            )
			        )
			    )
		displayFolder: DIO
		lineageTag: 453cac8f-4b98-4d01-b350-016983217915

	measure DIO_Color_KPI =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [DIO MoM%],
			        "YTD", [DIO YTD],
			        "vs YoY", [DIO YoY%],
			        "vs Plan", [DIO_APN],
			        "vs Flex", [DIO_AFX],
			        "vs 3M avg", [DIO 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			    IF(
			            _sel = "YTD",
			            "#000000",  -- Always black for YTD
			        IF(
			            ISBLANK(kpi_value), "#001489",  -- black for blank
			            IF(
			                kpi_value < 0,
			                "#001489",  -- Green for ▼ down
			                "#D7191C"   -- Red for ▲ up
			            )
			        )
			    )
		displayFolder: DIO
		lineageTag: c924dc8f-d16b-4243-a5a4-07c58f38141f

	measure DPO = ```
			
			Var num = CALCULATE(SUM(Fact_DSO_DPO_ABP[DPO_Num]),KEEPFILTERS(Dim_Date[Is Closed] = "TRUE"))
			VAR den = CALCULATE(SUM(Fact_DSO_DPO_ABP[DPO_Den]),KEEPFILTERS(Dim_Date[Is Closed] = "TRUE"))
			RETURN
			DIVIDE(num,den,0) 
			 
			 /*
			 VAR _Months = 3
			VAR _COGS = -CALCULATE( [COGS Actual]+ [A&P Actual]+[Variances Act]+[Distribution Actual] , DATESINPERIOD(Dim_Date[P_DateKey_Monthly], MAX( Dim_Date[P_DateKey_Monthly] ), -3, MONTH) )
			VAR _AvgAP = [Accounts Payable Avg L4M]
			RETURN
			    DIVIDE( _AvgAP, _COGS ) * (30.3334*_Months)
			    */
			```
		formatString: 0
		displayFolder: DPO
		lineageTag: 4318eaad-12d6-402e-8b6a-c68c4ecdb181

	measure DPO_ =
			VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [DPO MoM_Final],
			      "LYTD",             BLANK(),
			      "vs YoY",               [DPO YoY_Final],
			      "vs Plan", [DPO_APN_Final],
			      "vs 3M avg", [DPO 3M_Final],
			      BLANK()
			    )
		displayFolder: DPO
		lineageTag: 03c321ea-6235-4816-9e0e-d027a8dbd14e

	measure DPO_Color = ```
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [DPO MoM%],
			        "LYTD", BLANK(),
			        "vs YoY", [DPO YoY%], 
			        "vs Plan", [DPO_APN],
			        "vs 3M avg", [DPO 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			                "#1A9641",  -- Green for ▼ down
			                "#D7191C"   -- Red for ▲ up
			        )
			```
		displayFolder: DPO
		lineageTag: 065ebdbd-7356-4922-9657-ae2e162ee6da

	measure DPO_Color_KPI = ```
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [DPO MoM%],
			        "LYTD", BLANK(),
			        "vs YoY", [DPO YoY%], 
			        "vs Plan",[DPO_APN],
			        "vs 3M avg", [DPO 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value > 0,
			                "#D7191C",  -- Red for ▲ up
			                "#001489"   -- Green for ▼ down
			        )
			)
			```
		displayFolder: DPO
		lineageTag: 4faa936f-df86-4205-b4f8-72c30df21673

	measure DSO =
			
			Var num = CALCULATE(SUM(Fact_DSO_DPO_ABP[DSO_Num]),KEEPFILTERS(Dim_Date[Is Closed] = "TRUE"))
			VAR den = CALCULATE(SUM(Fact_DSO_DPO_ABP[DSO_Den]),KEEPFILTERS(Dim_Date[Is Closed] = "TRUE"))
			RETURN
			DIVIDE(num,den,0)
			/*
			VAR _Months = 3
			VAR _NIV = CALCULATE( [Net Sales Actual], DATESINPERIOD(Dim_Date[P_DateKey_Monthly], MAX( Dim_DateSlicer[P_DateKey_Monthly] ), -3, MONTH) )
			VAR _AvgAR = [Accounts Receivable Avg L4M]
			RETURN
			    DIVIDE( _AvgAR, _NIV ) * (30.3334*_Months)
			*/
		formatString: 0
		displayFolder: DSO
		lineageTag: d4c2a733-714c-4395-b963-2899e727949f

	measure 'DSO New' =
			
			Var num = SUM(Fact_DSO_DPO_ABP[DSO_Num])
			VAR den = SUM(Fact_DSO_DPO_ABP[DSO_Den])
			RETURN
			DIVIDE(num,den,0)
		formatString: 0
		displayFolder: DSO
		lineageTag: 2f9d81b8-2e56-4338-b692-5274c0324ead

	measure DSO_ =
			VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [DSO MoM_Final],
			      "LYTD",             BLANK(),
			      "vs YoY",               [DSO YoY_Final],
			      "vs Plan", [DSO_APN_Final],
			      "vs 3M avg", [DSO 3M_Final],
			      BLANK()
			    )
		displayFolder: DSO
		lineageTag: f98738c3-9514-46ea-8165-cdf96cb4bf38

	measure DSO_Color = ```
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [DSO MoM%],
			        "LYTD", BLANK(),
			        "vs YoY", [DSO YoY%], 
			        "vs Plan",[DSO_APN],
			        "vs 3M avg", [DSO 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			         IF(
			            kpi_value < 0,
			                "#1A9641",  -- Green for ▼ down
			                "#D7191C"   -- Red for ▲ up
			        )
			```
		displayFolder: DSO
		lineageTag: 314e75e4-2c75-4785-8b19-e9ae5dc36e72

	measure DSO_Color_KPI = ```
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [DSO MoM%],
			        "LYTD", BLANK(),
			        "vs YoY", [DSO YoY%], 
			        "vs Plan",[DSO_APN],
			        "vs 3M avg", [DSO 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			                "#001489",  -- Green for ▼ down
			                "#D7191C"   -- Red for ▲ up
			        )
			)
			```
		displayFolder: DSO
		lineageTag: 3c8fc342-ffdd-4485-9ac5-90be41a9847e

	measure 'DPO New' =
			
			Var num = SUM(Fact_DSO_DPO_ABP[DPO_Num])
			VAR den = SUM(Fact_DSO_DPO_ABP[DPO_Den])
			RETURN
			DIVIDE(num,den,0)
		formatString: 0
		displayFolder: DPO
		lineageTag: 824d6143-a542-4575-88cd-1dbd7c4690b8

	measure Expired_Inventory = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Expired Inventory MoM_Final],
			      "LYTD",               [Expired Inv LYTD_Final],
			      "vs YoY",               [Expired Inventory YoY_Final],
			      "vs 3M avg", [Expired Inventory 3M_Final],
			      BLANK()
			    )
			
			```
		displayFolder: Expired Inventory
		lineageTag: b78799df-3f7e-4d42-821f-a0626242d7d4

	measure Expired_Inventory_Color =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Expired Inventory MoM%],
			        "LYTD", [Expired Inventory LYTD],
			        "vs YoY", [Expired Inventory YoY%],
			        "vs 3M avg", [Expired Inventory 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			             IF(
			                kpi_value > 0,
			                "#D7191C",  -- Red for ▲ up
			                "#1A9641"   -- Green for ▼ down
			            )
		displayFolder: Expired Inventory
		lineageTag: 8fdc36f2-2570-456f-a9ff-1c7abacfa8a9

	measure Expired_Inventory_Color_KPI = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Expired Inventory MoM%],
			        "LYTD", [Expired Inventory LYTD],
			        "vs YoY", [Expired Inventory YoY%],
			        "vs 3M avg", [Expired Inventory 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			    IF(
			        ISBLANK(kpi_value), "#001489", 
			            IF(
			                kpi_value > 0,
			                "#D7191C",  -- Red for ▲ up
			                "#001489"   -- Green for ▼ down
			            )
			    )
			```
		displayFolder: Expired Inventory
		lineageTag: c5c1c3af-1c1c-4b02-80f5-a8031ab38518

	measure 'Gross PPV_Color' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Gross PPV Actual MoM%],
			        "LYTD", [Gross PPV Actual LYTD],
			        "vs YoY", [Gross PPV Actual YoY%], 
			        "vs Plan", [Gross PPV_APN],
			        "vs 3M avg", [Gross PPV 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#1A9641",  -- Green for ▼ down
			            "#D7191C"   -- red for ▲ up
			        )
			)
			```
		displayFolder: Gross PPV
		lineageTag: 467e9056-b60b-48ad-bdb4-6bad800f7a8b

	measure 'Gross PPV_Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Gross PPV Actual MoM%],
			        "LYTD", [Gross PPV Actual LYTD],
			        "vs YoY", [Gross PPV Actual YoY%], 
			        "vs Plan", [Gross PPV_APN],
			        "vs 3M avg", [Gross PPV 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#001489",  -- green for ▼ down
			            "#D7191C"   -- red for ▲ up
			        )
			)
			```
		displayFolder: Gross PPV
		lineageTag: ff3db1d0-0de0-4034-9a40-b86613134aa7

	measure Gross_PPV = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Gross PPV Actual MoM_Final],
			      "LYTD",               [Gross PPV Actual LYTD_Final],
			      "vs YoY",               [Gross PPV Actual YoY_Final],
			      "vs Plan", [Gross PPV_APN_Final],
			      "vs 3M avg", [Gross PPV 3M_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: Gross PPV
		lineageTag: 98e3fa41-abe5-4d5f-9504-0093e42bb23c

	measure Net_Sales_Actual = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Net Sales Actual MoM_Final],
			      "LYTD",               [Net Sales Actual LYTD_Final],
			      "vs YoY",               [Net Sales Actual YoY_Final],
			      "vs Plan", [Net Sales_APN_Final],
			      "vs Flex", [Net Sales_AFX_Final],
			      "vs 3M avg", [Net Sales 3M_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: Net Sales
		lineageTag: 8aee09ca-7e26-4aa1-a4d4-8fe9827f5614

		annotation PBI_FormatHint = {"isText":true}

	measure Net_Sales_Actual_Color = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Net Sales Actual MoM%],
			        "LYTD", [Net Sales Actual LYTD],
			        "vs YoY", [Net Sales Actual YoY%], 
			        "vs Plan", [Net Sales_APN],
			        "vs Flex",[Net Sales_AFX],
			        "vs 3M avg", [Net Sales 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#1A9641"   -- green for ▲ up
			        )
			```
		displayFolder: Net Sales
		lineageTag: def946ce-1480-40c7-8802-3344b832f624

	measure Net_Sales_Color_KPI = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Net Sales Actual MoM%],
			        "LYTD", [Net Sales Actual LYTD],
			        "vs YoY", [Net Sales Actual YoY%], 
			        "vs Plan", [Net Sales_APN],
			        "vs Flex",[Net Sales_AFX],
			        "vs 3M avg", [Net Sales 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#001489"   -- green for ▲ up
			        )
			)
			```
		displayFolder: Net Sales
		lineageTag: 2b4eac49-7816-4d78-a77b-3791ac9194d1

	measure OEE = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [OEE% MoM_Final],
			      "LYTD",               [OEE% LYTD_Final],
			      "vs YOY",               [OEE% YoY_Final],
			      "vs Plan", [OEE Target_Final],
			      "vs 3M avg", [OEE% 3M_Final],
			      BLANK()
			    )
			
			```
		displayFolder: OEE
		lineageTag: 6bf0cc01-ebf7-412a-9cde-0514745abb15

	measure OEE_Color =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [OEE% MoM%],
			        "YTD", [OEE% YTD],
			        "vs YoY", [OEE% YoY%],
			        "vs Plan", [OEE Target diff%],
			        "LYTD", [OEE LYTD],
			        "vs 3M avg", [OEE% 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        _sel = "YTD",
			        "#000000",  -- Always black for YTD
			    IF(
			        ISBLANK(kpi_value), "#000000",  -- black for blank
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#1A9641"   -- green for ▲ up
			        )
			    )
			)
		displayFolder: OEE
		lineageTag: 980502bb-cbd9-42f8-b167-7100ed8741b6

	measure OEE_Color_KPI =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [OEE% MoM%],
			        "YTD", [OEE% YTD],
			        "vs YoY", [OEE% YoY%],
			        "vs Plan", [OEE Target diff%],
			        "LYTD", [OEE LYTD],
			        "vs 3M avg", [OEE% 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        _sel = "YTD",
			        "#000000",  -- Always black for YTD
			    IF(
			        ISBLANK(kpi_value), "#001489",  -- black for blank
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#001489"   -- green for ▲ up
			        )
			    )
			)
		displayFolder: OEE
		lineageTag: 8d1da3f5-b9ed-4277-8cd5-4d0f18cbbc9f

	measure Operating_Income_Actual = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Operating Income Actual MoM_Final],
			      "LYTD",               [Operating Income Actual LYTD_Final],
			      "vs YoY",               [Operating Income Actual YoY_Final],
			      "vs Plan", [Operating Income_APN_Final],
			      "vs Flex", BLANK(),
			      "vs 3M avg", [Operating Income Actual 3M_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: Operating Income
		lineageTag: 2793fa3d-f884-41c0-9f3c-69edd8de2774

	measure Operating_Income_Color = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Operating Income Actual MoM%],
			        "LYTD", [Operating Income Actual LYTD],
			        "vs YoY", [Operating Income Actual YoY%], 
			        "vs Plan", [Operating Income_APN],
			        "vs 3M avg", [Operating Income 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#000000", 
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#1A9641"   -- green for ▲ up
			        )
			)
			```
		displayFolder: Operating Income
		lineageTag: 53ff79f7-8992-4158-bb1d-8f799bd6ca3e

	measure Operating_Income_Color_KPI = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Operating Income Actual MoM%],
			        "LYTD", [Operating Income Actual LYTD],
			        "vs YoY", [Operating Income Actual YoY%], 
			        "vs Plan", [Operating Income_APN],
			        "vs 3M avg", [Operating Income 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#001489"   -- green for ▲ up
			        )
			)
			```
		displayFolder: Operating Income
		lineageTag: 298cc23d-a900-484d-812d-b4cc7caf9cc2

	measure SA = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [SA MoM_Final],
			      "LYTD",               [Schedule Attn LYTD_Final],
			      "vs YoY",               [SA YoY_Final],
			      "vs Plan", [Schedule Attn Target Final],
			      "vs 3M avg", [Schedule Attainment 3M_Final],
			      BLANK()
			    )
			```
		displayFolder: Schedule Attainment
		lineageTag: 5a08dda7-84dd-4620-bb9e-a3079c2313fd

		annotation PBI_FormatHint = {"isText":true}

	measure 'SA _Color' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [SA MoM%],
			        "LYTD", [Schedule Attn LYTD],
			        "vs YoY", [SA YoY%],
			        "vs Plan", [Schedule Attn Target Diff%],
			        "vs 3M avg", [Schedule Attainment 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value >= 0,
			            "#1A9641",  -- green for ▲ up
			            "#D7191C"  -- red for ▼ down
			        )
		displayFolder: Schedule Attainment
		lineageTag: 6a8b82f4-aeff-46ad-8c49-7755b8a36d00

	measure 'SA _Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [SA MoM%],
			        "LYTD", [Schedule Attn LYTD],
			        "vs YoY", [SA YoY%],
			        "vs Plan", [Schedule Attn Target Diff%],
			        "vs 3M avg", [Schedule Attainment 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value >= 0,
			            "#001489",  -- green for ▲ up
			            "#D7191C"  -- red for ▼ down
			        )
			)
			```
		displayFolder: Schedule Attainment
		lineageTag: caa01288-2c52-48ff-894e-d1d05f4bb009

	measure 'Service rate_Color' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Service Rate% MoM%],
			        "LYTD", [Service Rate LYTD],
			        "vs YoY", [Service Rate YoY%],
			        "vs 3M avg", [Service Rate 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#1A9641"   -- green for ▲ up
			        )
		displayFolder: Service Rate CSCA
		lineageTag: a1ef24e0-4d13-4f17-973f-4e210e679beb

	measure 'Service rate_Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Service Rate% MoM%],
			        "LYTD", [Service Rate LYTD],
			        "vs YoY", [Service Rate YoY%],  
			        "vs Plan", [Service Target Diff%],
			        "vs 3M avg", [Service Rate 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#001489"   -- green for ▲ up
			        )
			)
			```
		displayFolder: Service Rate CSCA
		lineageTag: 46e78951-5837-4fef-9f51-205ae49cc154

	measure 'Service Top 11_Color' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Service Top 11 MoM%],
			        "LYTD", [Service Top 11 LYTD],
			        "vs YoY", [Service Top 11 YoY%],
			        "vs Plan", [Service Top 11 Target Diff%],
			        "vs 3M avg", [Service Top 11 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#1A9641"   -- green for ▲ up
			        )
		displayFolder: Service Top 11
		lineageTag: e8e7e1cc-8b00-4e63-9474-d4cf30fd95a4

	measure 'Service Top 11_Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Service Top 11 MoM%],
			        "LYTD", [Service Top 11 LYTD],
			        "vs YoY", [Service Top 11 YoY%],  
			        "vs Plan", [Service Top 11 Target Diff%],
			        "vs 3M avg", [Service Top 11 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#001489"   -- green for ▲ up
			        )
			)
			```
		displayFolder: Service Top 11
		lineageTag: 60ff18b0-064d-44b0-8fb3-ac11463b8035

	measure 'Service Top 11_Switch' = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Service Top 11 MoM_Final],
			      "LYTD",               [Service Top 11 LYTD_Final],
			      "vs YoY",               [Service Top 11 YoY_Final],
			      "vs Plan", [Service Top 11 Target Final],
			      "vs 3M avg", [Service Top 11 3M_Final],
			      BLANK()
			    )
			```
		displayFolder: Service Top 11
		lineageTag: 6d7a320f-1686-4dbc-a8f8-b55b9fc6ac42

	measure Service_rate = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Service Rate% MoM_Final],
			      "LYTD",               [Service LYTD_Final],
			      "vs YoY",               [Service Rate% YoY_Final],
			      "vs Plan", [Service Target Final],
			      "vs 3M avg", [Service Rate% 3M_Final],
			      BLANK()
			    )
			```
		displayFolder: Service Rate CSCA
		lineageTag: 62cd4ac5-ee85-432e-a828-97324dfd5c90

	measure 'Total Distribution on COGS Actual _Color' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Total Distribution on COGS Actual MoM%],
			        "LYTD", [Total Distribution on COGS LYTD],
			        "vs YoY", [Total Distribution on COGS Actual YoY%], 
			        "vs Plan", [Total Distribution on COGS_APN],
			        "vs Flex",[Total Distribution on COGS_AFX],
			        "vs 3M avg", [Distribution on COGS 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#1A9641", -- green for ▲ up
			            "#D7191C"  -- red for ▼ down 
			        )
			```
		displayFolder: Distribution on COGS
		lineageTag: c69957fc-fb79-4116-84f9-e51d8533fd37

	measure 'Total Distribution on COGS_Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Total Distribution on COGS Actual MoM%],
			        "LYTD", [Total Distribution on COGS LYTD],
			        "vs YoY", [Total Distribution on COGS Actual YoY%], 
			        "vs Plan", [Total Distribution on COGS_APN],
			        "vs Flex",[Total Distribution on COGS_AFX],
			        "vs 3M avg", [Distribution on COGS 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			    IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#001489", -- green for ▲ up
			            "#D7191C"  -- red for ▼ down 
			        )
			    )
			```
		displayFolder: Distribution on COGS
		lineageTag: 51c879fd-830d-4ec0-920d-4f053f3a1c98

	measure 'Total Logistics on Net Sales Actual _Color' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Total Logistics on Net Sales Actual MoM%],
			        "LYTD", [Total Logistics on Net Sales LYTD],
			        "vs YoY", [Total Logistics on Net Sales Actual YoY%],
			        "vs Plan", [Total Logistics on Net Sales_APN],
			        "vs Flex",[Total Logistics on Net Sales_AFX],
			        "vs 3M avg", [Total Logistics 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#1A9641", -- green for ▲ up
			            "#D7191C"  -- red for ▼ down 
			        )
			```
		displayFolder: Logistic vs Net Sales
		lineageTag: e0294879-b309-4989-9fc5-9bed23b9675c

	measure 'Total Logistics on Net Sales_Color' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Total Logistics on Net Sales Actual MoM%],
			        "LYTD", [Total Logistics on Net Sales LYTD],
			        "vs YoY", [Total Logistics on Net Sales Actual YoY%],
			        "vs Plan", [Total Logistics on Net Sales_APN],
			        "vs Flex",[Total Logistics on Net Sales_AFX],
			        "vs 3M avg", [Total Logistics 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			    IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#001489", -- green for ▲ up
			            "#D7191C"  -- red for ▼ down 
			        )
			    )
			```
		displayFolder: Logistic vs Net Sales
		lineageTag: 55eb21b6-62f6-4426-b6f2-921d7afdf911

	measure Total_Distribution_on_COGS = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Total Distribution on COGS Actual MoM_Final],
			      "LYTD",               [Total Distribution on COGS LYTD_Final],
			      "vs YoY",               [Total Distribution on COGS Actual YoY_Final],
			      "vs Plan", [Total Distribution on COGS_APN_Final],
			      "vs Flex",[Total Distribution on COGS_AFX_Final],
			      "vs 3M avg", [Distribution on COGS 3M_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: Distribution on COGS
		lineageTag: 836c8524-513b-4a4a-9fd6-67c388c39b7a

		annotation PBI_FormatHint = {"isText":true}

	measure Total_Logistics_on_Net_Sales = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Total Logistics on Net Sales Actual MoM_Final],
			      "LYTD",               [Total Logistics on Net Sales LYTD_Final],
			      "vs YoY",               [Total Logistics on Net Sales Actual YoY_Final],
			      "vs Plan", [Total Logistics on Net Sales_APN_Final],
			      "vs Flex",[Total Logistics on Net Sales_AFX_Final],
			      "vs 3M avg", [Total Logistics 3M_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: Logistic vs Net Sales
		lineageTag: 10eacfe4-5cad-4ffa-a768-47d7baabe1fc

		annotation PBI_FormatHint = {"isText":true}

	measure SSSO_Obs_Linked_Color =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [SSSO: Obs linked to Conv MoM%],
			        "LYTD", [SSSO: Obs LYTD],
			        "vs YoY", [SSSO: Obs linked to Conv YoY%],
			        "vs Plan", [SSSO: Obsolescenes linked to Conversions_APN],
			        "vs Flex", [SSSO: Obsolescenes linked to Conversions_F66],
			        "vs 3M avg", [SSSO: Obs linked to Conv 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#1A9641",  -- Green for ▼ down
			            "#D7191C"   -- Red for ▲ up
			        )
		displayFolder: SSSO Obs linked to Conv
		lineageTag: 21e5f5e0-6233-4941-999f-0a0e89de6c67

	measure SSSO_Obs_Linked_Color_KPI = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [SSSO: Obs linked to Conv MoM%],
			        "LYTD", [SSSO: Obs LYTD],
			        "vs YoY", [SSSO: Obs linked to Conv YoY%],
			        "vs Plan", [SSSO: Obsolescenes linked to Conversions_APN],
			        "vs Flex", [SSSO: Obsolescenes linked to Conversions_F66],
			        "vs 3M avg", [SSSO: Obs linked to Conv 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#001489",  -- Green for ▼ down
			            "#D7191C"   -- Red for ▲ up
			        )
			)
			```
		displayFolder: SSSO Obs linked to Conv
		lineageTag: 75bc24f5-8115-4d15-ab6e-b81b9aafc5ed

	measure SSSO_Obs_Linked = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [SSSO: Obs Linked to Conv MoM_Final],
			      "LYTD",               [SSSO: Obs LYTD_Final],
			      "vs YoY",               [SSSO: Obs linked to Conv YoY_Final],
			      "vs Plan",[SSSO: Obs linked to conv APN_Final],
			      "vs Flex", [SSSO: Obs linked to conv F66_Final],
			      "vs 3M avg", [SSSO: Obs Linked to Conv 3M_Final],
			      BLANK()
			    )
			
			```
		displayFolder: SSSO Obs linked to Conv
		lineageTag: 64f7d605-77e5-46ad-b7aa-f26bec298bb9

	measure SSSO_Salvage&Obs_Color_KPI = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [SSSO: Salvage & obs MoM%],
			        "LYTD", [SSSO: Salvage LYTD],
			        "vs YoY", [SSSO: Salvage YoY%], 
			        "vs Plan", [SSSO: Salvage & Obsolescence_APN],
			        "vs Flex", [SSSO: Salvage & Obsolescence_F66],
			        "vs 3M avg", [SSSO: Salvage & Obs 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			    IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#001489",  -- Green for ▼ down
			            "#D7191C"   -- red for ▲ up
			        )
			    )
			```
		displayFolder: SSSO Salvage & Obs
		lineageTag: 410517ff-808b-48ae-ba4d-da03b48e6432

	measure SSSO_Salvage&Obs_Color = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [SSSO: Salvage & obs MoM%],
			        "LYTD", [SSSO: Salvage LYTD],
			        "vs YoY", [SSSO: Salvage YoY%], 
			        "vs Plan", [SSSO: Salvage & Obsolescence_APN],
			        "vs Flex", [SSSO: Salvage & Obsolescence_F66],
			        "vs 3M avg", [SSSO: Salvage & Obs 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#1A9641",  -- Green for ▼ down
			            "#D7191C"   -- red for ▲ up
			        )
			```
		displayFolder: SSSO Salvage & Obs
		lineageTag: f0454bf2-86f2-4625-abb9-b1206d4604c4

	measure SSSO_Scrap_off_Color = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [SSSO: Scrap-Off MoM%],
			        "LYTD", [SSSO: Scrap-off LYTD],
			        "vs YoY", [SSSO: Scrap-Off YoY%], 
			        "vs Plan", [SSSO: Scrap-Off_APN],
			        "vs Flex", [SSSO: Scrap-Off_F66],
			        "vs 3M avg", [SSSO: Scrap-Off 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#1A9641",  -- Green for ▼ down
			            "#D7191C"   -- Red for ▲ up
			        )
			```
		displayFolder: SSSO Scrap-Off
		lineageTag: ceecbcf4-8b0d-484e-9d44-1c39040f940a

	measure SSSO_Scrap_Off_ = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [SSSO: Scrap-Off MoM_Final],
			      "LYTD",               [SSSO: Scrap-off LYTD_Final],
			      "vs YoY",               [SSSO: Scrap-Off YoY_Final],
			      "vs Plan", [SSSO: Scrap-Off APN_Final],
			      "vs Flex", [SSSO: Scrap-Off F66_Final],
			      "vs 3M avg", [SSSO: Scrap-Off 3M_Final],
			      BLANK()
			    )
			
			```
		displayFolder: SSSO Scrap-Off
		lineageTag: 611d4f8e-c69f-41a1-be89-4bfc6f8e6e5c

	measure SSSO_Scrap_off_Color_KPI = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [SSSO: Scrap-Off MoM%],
			        "LYTD", [SSSO: Scrap-off LYTD],
			        "vs YoY", [SSSO: Scrap-Off YoY%], 
			        "vs Plan", [SSSO: Scrap-Off_APN],
			        "vs Flex", [SSSO: Scrap-Off_F66],
			        "vs 3M avg", [SSSO: Scrap-Off 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			    IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#001489",  -- Green for ▼ down
			            "#D7191C"   -- Red for ▲ up
			        )
			    )
			```
		displayFolder: SSSO Scrap-Off
		lineageTag: 878dd288-eec4-4485-b5fd-870f4fdfcd70

	measure SSSO_Salvage&Obs = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP",[SSSO: Salvage MoM_Final],
			      "LYTD",[SSSO: Salvage LYTD_Final],
			      "vs YoY",[SSSO: Salvage YoY_Final],
			      "vs Plan",[SSSO: Salvage & Obs APN_Final],
			      "vs Flex", [SSSO: Salvage & Obs F66_Final],
			      "vs 3M avg", [SSSO: Salvage & Obs APN_Final],
			      BLANK()
			    )
			```
		displayFolder: SSSO Salvage & Obs
		lineageTag: 4aee5ee6-baab-4f49-a851-5243d4568032

	measure Reference_lbl_title = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", "vs PP",
			      "LYTD",  "LYTD",
			      "vs YoY", "vs YoY",
			      "vs Plan", "vs Plan",
			      "vs Flex", "vs Flex",
			      "vs 3M avg", "vs 3M avg",
			      BLANK()
			    )
			```
		displayFolder: Misc
		lineageTag: 0f0991da-2fa9-488c-a956-7d8b2c3546ee

	measure Net_POV = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Net POV Actual MoM_Final],
			      "LYTD",               [Net POV Actual LYTD_Final],
			      "vs YoY",               [Net POV Actual YoY_Final],
			      "vs Plan", [Net POV_APN_Final],
			      "vs 3M avg", [Net POV 3M_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: Net POV
		lineageTag: d76ea9a6-406f-4b8f-8531-8c1d35856890

	measure 'KPI Status Icon (Sales Growth)' = ```
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "FA_Lag1_vsPlan", [FA Target L1 Diff raw],
			        "FA_Lag1_vsLYTD", [FA% L1 LYTD CSCI],
			        "FA_Lag1_vsYoY", [FA% YoY L1 raw CSCI],
			        "FA_Lag1_vsPP", [FA% MoM L1 raw CSCI],
			
			        "FA_Lag2_vsPlan", [FA% Lag 2 Target Diff%],
			        "FA_Lag2_vsLYTD", CALCULATE([FA% CSCA LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2")),
			        "FA_Lag2_vsYoY", [FA% Lag2 YoY%],
			        "FA_Lag2_vsPP", [FA% Lag2 MoM%],
			
			        "FA_Lag4_CSCA_vsPlan", [FA% Lag 4 Target Diff%],
			        "FA_Lag4_CSCA_vsLYTD", CALCULATE([FA% CSCA LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        "FA_Lag4_CSCA_vsYoY", [FA% Lag4 YoY%],
			        "FA_Lag4_CSCA_vsPP", [FA% Lag4 MoM%],
			
			        "FA_Lag4_CSCI_vsPlan", [FA Target L4 Diff raw],
			        "FA_Lag4_CSCI_vsLYTD", [FA% L4 LYTD CSCI],
			        "FA_Lag4_CSCI_vsYoY", [FA% YoY L4 raw CSCI],
			        "FA_Lag4_CSCI_vsPP", [FA% MoM L4 raw CSCI],
			
			        "Bias_Lag1_vsPlan", [Bias Target Diff%_CSCI L1],
			        "Bias_Lag1_vsLYTD", [Bias % L1 LYTD CSCI],
			        "Bias_Lag1_vsYoY", [Bias YoY % L1 Raw CSCI],
			        "Bias_Lag1_vsPP", [Bias MoM%_raw L1 CSCI],
			        
			        "Bias_Lag2_vsPlan", [Bias Lag2 Target Diff%],
			        "Bias_Lag2_vsLYTD", CALCULATE([Bias% LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2")),
			        "Bias_Lag2_vsYoY", [Bias Lag2 YoY%],
			        "Bias_Lag2_vsPP", [Bias Lag2 MoM%],
			
			        "Bias_Lag4_CSCA_vsPlan", [Bias Lag4 Target Diff%],
			        "Bias_Lag4_CSCA_vsLYTD", CALCULATE([Bias% LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        "Bias_Lag4_CSCA_vsYoY", [Bias Lag4 YoY%],
			        "Bias_Lag4_CSCA_vsPP", [Bias Lag4 MoM%],
			
			        "Bias_Lag4_CSCI_vsPlan", [Bias Target Diff%_CSCI L4],
			        "Bias_Lag4_CSCI_vsLYTD", [Bias % L4 LYTD CSCI],
			        "Bias_Lag4_CSCI_vsYoY", [Bias YoY % L4 Raw CSCI],
			        "Bias_Lag4_CSCI_vsPP", [Bias MoM%_raw L4 CSCI],
			
			        "Service_Top_11_vsPlan", [Service Top 11 Target Diff%],
			        "Service_Top_11_vsYoY", [Service Top 11 YoY%],
			        "Service_Top_11_vsLYTD", [Service Top 11 LYTD],
			        "Service_Top_11_vsPP", [Service Top 11 MoM%],
			        "Case_fill_rate_vsPlan", [CFR Target Diff%],
			
			        "Case_fill_rate_vsPP", [CFR MoM%],
			        "Case_fill_rate_vsYoY", [CFR YoY%],
			        "Case_fill_rate_vsLYTD", [CFR LYTD],
			
			        "Service_Level_Gap_vsPlan", [Service Target Diff%],
			        "Service_Level_Gap_vsPP", [Service Rate% MoM%],
			        "Service_Level_Gap_vsYoY", [Service Rate YoY%],
			        "Service_Level_Gap_vsLYTD", [Service Rate LYTD],
			
			        "Service_Level_Total_vsPlan", [Service Target Diff%_CSCI],
			        "Service_Level_Total_vsPP", [Service Level MoM%],
			        "Service_Level_Total_vsYoY", [Service Level YoY%],
			        "Service_Level_Total_vsLYTD", [Service Level LYTD],
			        BLANK()
			    )
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			
			        // ✅ Bias Lag2 & Lag4 CSCA (-3% to +3% = green, else red)
			        _kpiID IN { "Bias_Lag2_vsPlan", "Bias_Lag2_vsLYTD", "Bias_Lag2_vsYoY", "Bias_Lag2_vsPP",
			                    "Bias_Lag4_CSCA_vsPlan", "Bias_Lag4_CSCA_vsLYTD", "Bias_Lag4_CSCA_vsYoY", "Bias_Lag4_CSCA_vsPP" },
			            IF ( _value >= -0.03 && _value <= 0.03, "🟢", "🔴" ),
			
			        // ✅ Bias Lag1 & Lag4 CSCI (-10% to +10% = green, else red)
			        _kpiID IN { "Bias_Lag1_vsPlan", "Bias_Lag1_vsLYTD", "Bias_Lag1_vsYoY", "Bias_Lag1_vsPP",
			                    "Bias_Lag4_CSCI_vsPlan", "Bias_Lag4_CSCI_vsLYTD", "Bias_Lag4_CSCI_vsYoY", "Bias_Lag4_CSCI_vsPP" },
			            IF ( _value >= -0.10 && _value <= 0.10, "🟢", "🔴" ),
			
			        // ✅ Other KPIs → normal rules
			        _signRule = "GoodIfNeg", IF ( _value < 0, "🟢", "🔴" ),
			        IF ( _value < 0, "🔴", "🟢" )
			    )
			```
		displayFolder: Landing Page Measures
		lineageTag: b206bd87-be69-4542-b8bd-a539f8e7747d

	measure 'Green Count (Operating Income)' = ```
			
			VAR _count = 
			CALCULATE (
			    COUNTROWS ( KPI_Metadata ),
			    FILTER (
			        KPI_Metadata,
			        [KPI Status Icon (Operating Income)] = "🟢"
			            && NOT ISBLANK ( [KPI Status Icon (Operating Income)] )
			    )
			)
			
			RETURN
			IF (
			    _count = 0,
			    "0",
			    UNICHAR(129137) & " " & _count
			)
			
			```
		displayFolder: Landing Page Measures
		lineageTag: ab9d3eda-6179-42a6-97fb-ba2ae2245175

	measure 'Green Count (Operations)' = ```
			
			VAR _Count = 
			CALCULATE (
			    COUNTROWS ( KPI_Metadata ),
			    FILTER (
			        KPI_Metadata,
			        [KPI Status Icon (Operations&Quality)] = "🟢"
			            && NOT ISBLANK ( [KPI Status Icon (Operations&Quality)] )
			    )
			)
			
			
			RETURN
			IF (
			    _count = 0,
			    "0",
			    UNICHAR(129137) & " " & _count
			)
			
			```
		displayFolder: Landing Page Measures
		lineageTag: c770db70-a3f4-4a59-aa32-dbf9a4b0a9dc

	measure 'Green Count (Sales Growth)' = ```
			
			VAR _count = 
			CALCULATE (
			    COUNTROWS ( KPI_Metadata ),
			    FILTER (
			        KPI_Metadata,
			        [KPI Status Icon (Sales Growth)] = "🟢"
			            && NOT ISBLANK ( [KPI Status Icon (Sales Growth)] )
			    )
			)
			
			RETURN
			IF (
			    _count = 0,
			    "0",
			    UNICHAR(129137) & " " & _count
			)
			
			```
		displayFolder: Landing Page Measures
		lineageTag: ed8ace2f-d3df-4fb2-a07c-2402c9e0075b

	measure 'Total Green Count' = ```
			
			VAR _cnt =
			    CALCULATE (
			        COUNTROWS ( KPI_Metadata ),
			        FILTER (
			            KPI_Metadata,
			            ( [KPI Status Icon (Sales Growth)] = "🟢"
			            || [KPI Status Icon (Operations&Quality)] = "🟢"
			            || [KPI Status Icon (Working Capital)] = "🟢"
			            || [KPI Status Icon (Operating Income)] = "🟢" )
			        )
			    )
			RETURN
			COALESCE ( _cnt, 0 )
			
			```
		formatString: 0
		displayFolder: Landing Page Measures
		lineageTag: 1d2a050a-42ae-4ed0-934e-9ae67f4e4418

	measure 'Green Count (WorkingCapital)' = ```
			
			VAR _count =
			CALCULATE (
			    COUNTROWS ( KPI_Metadata ),
			    FILTER (
			        KPI_Metadata,
			        [KPI Status Icon (Working Capital)] = "🟢"
			            && NOT ISBLANK ( [KPI Status Icon (Working Capital)] )
			    )
			)
			
			RETURN
			IF (
			    _count = 0,
			    "0",
			    UNICHAR(129137) & " " & _count
			)
			
			```
		displayFolder: Landing Page Measures
		lineageTag: a79d755f-2784-4353-b14c-5cd45db88aa7

	measure 'KPI Status Icon' = ```
			
			VAR _kpiID =
			    SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- ✅ Assign value dynamically based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			
			        // -------- Sales Growth --------
			        "FA_Lag1_vsPlan", [FA Target L1 Diff raw],
			        "FA_Lag1_vsLYTD", [FA% L1 LYTD CSCI],
			        "FA_Lag1_vsYoY", [FA% YoY L1 raw CSCI],
			        "FA_Lag1_vsPP", [FA% MoM L1 raw CSCI],
			
			        "FA_Lag2_vsPlan", [FA% Lag 2 Target Diff%],
			        "FA_Lag2_vsLYTD", CALCULATE([FA% CSCA LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2")),
			        "FA_Lag2_vsYoY", [FA% Lag2 YoY%],
			        "FA_Lag2_vsPP", [FA% Lag2 MoM%],
			
			        "FA_Lag4_CSCA_vsPlan", [FA% Lag 4 Target Diff%],
			        "FA_Lag4_CSCA_vsLYTD", CALCULATE([FA% CSCA LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        "FA_Lag4_CSCA_vsYoY", [FA% Lag4 YoY%],
			        "FA_Lag4_CSCA_vsPP", [FA% Lag4 MoM%],
			
			        "FA_Lag4_CSCI_vsPlan", [FA Target L4 Diff raw],
			        "FA_Lag4_CSCI_vsLYTD", [FA% L4 LYTD CSCI],
			        "FA_Lag4_CSCI_vsYoY", [FA% YoY L4 raw CSCI],
			        "FA_Lag4_CSCI_vsPP", [FA% MoM L4 raw CSCI],
			
			        "Bias_Lag1_vsPlan", [Bias Target Diff%_CSCI L1],
			        "Bias_Lag1_vsLYTD", [Bias % L1 LYTD CSCI],
			        "Bias_Lag1_vsYoY", [Bias YoY % L1 Raw CSCI],
			        "Bias_Lag1_vsPP", [Bias MoM%_raw L1 CSCI],
			
			        "Bias_Lag2_vsPlan", [Bias Lag2 Target Diff%],
			        "Bias_Lag2_vsLYTD", CALCULATE([Bias% LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2")),
			        "Bias_Lag2_vsYoY", [Bias Lag2 YoY%],
			        "Bias_Lag2_vsPP", [Bias Lag2 MoM%],
			
			        "Bias_Lag4_CSCA_vsPlan", [Bias Lag4 Target Diff%],
			        "Bias_Lag4_CSCA_vsLYTD", CALCULATE([Bias% LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        "Bias_Lag4_CSCA_vsYoY", [Bias Lag4 YoY%],
			        "Bias_Lag4_CSCA_vsPP", [Bias Lag4 MoM%],
			
			        "Bias_Lag4_CSCI_vsPlan", [Bias Target Diff%_CSCI L4],
			        "Bias_Lag4_CSCI_vsLYTD", [Bias % L4 LYTD CSCI],
			        "Bias_Lag4_CSCI_vsYoY", [Bias YoY % L4 Raw CSCI],
			        "Bias_Lag4_CSCI_vsPP", [Bias MoM%_raw L4 CSCI],
			
			        "Service_Top_11_vsPlan", [Service Top 11 Target Diff%],
			        "Service_Top_11_vsYoY", [Service Top 11 YoY%],
			        "Service_Top_11_vsLYTD", [Service Top 11 LYTD],
			        "Service_Top_11_vsPP", [Service Top 11 MoM%],
			
			        "Case_fill_rate_vsPlan", [CFR Target Diff%],
			        "Case_fill_rate_vsPP", [CFR MoM%],
			        "Case_fill_rate_vsYoY", [CFR YoY%],
			        "Case_fill_rate_vsLYTD", [CFR LYTD],
			
			        "Service_Level_Gap_vsPlan", [Service Target Diff%],
			        "Service_Level_Gap_vsPP", [Service Rate% MoM%],
			        "Service_Level_Gap_vsYoY", [Service Rate YoY%],
			        "Service_Level_Gap_vsLYTD", [Service Rate LYTD],
			
			        "Service_Level_Total_vsPlan", [Service Target Diff%_CSCI],
			        "Service_Level_Total_vsPP", [Service Level MoM%],
			        "Service_Level_Total_vsYoY", [Service Level YoY%],
			        "Service_Level_Total_vsLYTD", [Service Level LYTD],
			
			        // -------- Operations & Quality --------
			        "OEE_vsPlan", [OEE Target diff%],
			        "OEE_vsPP", [OEE% MoM%],
			        "OEE_vsYoY", [OEE% YoY%],
			        "OEE_vsLYTD", [OEE LYTD],
			
			        "Schedule_Attainment_vsPlan", [Schedule Attn Target Diff%],
			        "Schedule_Attainment_vsPP", [SA MoM%],
			        "Schedule_Attainment_vsYoY", [SA YoY%],
			        "Schedule_Attainment_vsLYTD", [Schedule Attn LYTD],
			
			        "On_Time_Deviation_vsPlan", [On Time Closure of Deviations Target Diff%],
			        "On_Time_Deviation_vsYoY", [On Time Closure of Deviations YoY%],
			        "On_Time_Deviation_vsLYTD", [On Time Closure of Deviations LYTD],
			        "On_Time_Deviation_vsPP", [On Time Closure of Deviations MoM%],
			
			        "CAPA_Completion_vsPlan", [CAPA Completion Rate Target Diff%],
			        "CAPA_Completion_vsPP", [CAPA Completion Rate MoM%],
			        "CAPA_Completion_vsYoY", [CAPA Completion Rate YoY%],
			        "CAPA_Completion_vsLYTD", [CAPA Closed LYTD],
			
			        "Right_First_Time_vsPlan", [RFT Target Diff%],
			        "Right_First_Time_vsPP", [RFT MoM%],
			        "Right_First_Time_vsYoY", [RFT YoY%],
			        "Right_First_Time_vsLYTD", [RFT LYTD],
			
			        "Critical/Major_vsPP", [Critical or Major Observations MoM%],
			        "Critical/Major_vsYoY", [Critical or Major Observations YoY%],
			        "Critical/Major_vsLYTD", [Critical or Major Observations LYTD],
			
			        "ASTM_Incidents_vsPP", [ASTM Incidents MoM%],
			        "ASTM_Incidents_vsYoY", [ASTM Incidents YoY%],
			        "ASTM_Incidents_vsLYTD", [ASTM Incidents LYTD],
			
			        "ASTM_Rate_vsPP", [ASTM Rate MoM%],
			        "ASTM_Rate_vsYoY", [ASTM Rate YoY%],
			        "ASTM_Rate_vsLYTD", [ASTM Rate LYTD],
			
			        "Good_Catch_Closure_vsPlan", [Good Catch Closure Rate Target Diff%],
			        "Good_Catch_Closure_vsPP", [Good Catch Closure Rate MoM%],
			        "Good_Catch_Closure_vsYoY", [Good Catch Closure Rate YoY%],
			
			        "pSIF_Closure_vsPlan", [pSIF SIFs Focus Target Diff%],
			        "pSIF_Closure_vsPP", [pSIF SIFs Focus MoM%],
			        "pSIF_Closure_vsYoY", [pSIF SIFs Focus YoY%],
			
			        "PWS_Benefits_vsPlan", [PWS Benefits_APN],
			        "PWS_Benefits_vsPP", [PWS Benefits MoM%],
			        "PWS_Benefits_vsYoY", [PWS Benefits YoY%],
			        "PWS_Benefits_vsLYTD", [PWS Benefits LYTD],
			
			        // -------- Working Capital --------
			        "Net_Inventory_vsPlan", [Net Inventory_APN],
			        "Net_Inventory_vsFlex", [Net Inventory_AFX],
			        "Net_Inventory_vsLYTD", [Net Inventory LYTD],
			        "Net_Inventory_vsPP", [Net Inventory MoM%],
			        "Net_Inventory_vsYoY", [Net Inventory YoY%],
			
			        "Gross_Inventory_vsPlan", [Gross Inventory_APN],
			        "Gross_Inventory_vsFlex", [Gross Inventory_AFX],
			        "Gross_Inventory_vsLYTD", [Gross Inv LYTD],
			        "Gross_Inventory_vsPP", [Gross Inventory MoM%],
			        "Gross_Inventory_vsYoY", [Gross Inventory YoY%],
			
			        "Expired_Inventory_vsPP", [Expired Inventory MoM%],
			        "Expired_Inventory_vsYoY", [Expired Inventory YoY%],
			        "Expired_Inventory_vsLYTD", [Expired Inventory LYTD],
			
			        "Inflated_Inventory_vsPP", [Inflated Inventory MoM%],
			        "Inflated_Inventory_vsYoY", [Inflated Inventory YoY%],
			        "Inflated_Inventory_vsLYTD", [Inflated Inv LYTD],
			
			        "DIO_vsPlan", [DIO_APN],
			        "DIO_vsPP", [DIO MoM%],
			        "DIO_vsFlex", [DIO_AFX],
			        "DIO_vsYoY", [DIO YoY%],
			
			        "DPO_vsPlan", [DPO_APN],
			        "DPO_vsPP", [DPO MoM%],
			        "DPO_vsYoY", [DPO YoY%],
			
			        "DSO_vsPlan", [DSO_APN],
			        "DSO_vsPP", [DSO MoM%],
			        "DSO_vsYoY", [DSO YoY%],
			
			        // -------- Operating Income --------
			        "SSSO_Conversions_vsPlan", [SSSO: Obsolescenes linked to Conversions_APN],
			        "SSSO_Conversions_vsLYTD", [SSSO: Obs LYTD],
			        "SSSO_Conversions_vsPP", [SSSO: Obs linked to Conv MoM%],
			        "SSSO_Conversions_vsYoY", [SSSO: Obs linked to Conv YoY%],
			        "SSSO_Conversions_vsFlex", [SSSO: Obsolescenes linked to Conversions_F66],
			
			        "SSSO_Salvage_Obsolescence_vsPlan", [SSSO: Salvage & Obsolescence_APN],
			        "SSSO_Salvage_Obsolescence_vsLYTD", [SSSO: Salvage LYTD],
			        "SSSO_Salvage_Obsolescence_vsPP", [SSSO: Salvage & obs MoM%],
			        "SSSO_Salvage_Obsolescence_vsYoY", [SSSO: Salvage YoY%],
			        "SSSO_Salvage_Obsolescence_vsFlex", [SSSO: Salvage & Obsolescence_F66],
			
			        "SSSO_Scrap_vsPlan", [SSSO: Scrap-Off_APN],
			        "SSSO_Scrap_vsLYTD", [SSSO: Scrap-off LYTD],
			        "SSSO_Scrap_vsPP", [SSSO: Scrap-Off MoM%],
			        "SSSO_Scrap_vsYoY", [SSSO: Scrap-Off YoY%],
			        "SSSO_Scrap_vsFlex", [SSSO: Scrap-Off_F66],
			
			        "SSSO_Shrinkage_vsPlan", [SSSO: Shrinkage_APN],
			        "SSSO_Shrinkage_vsLYTD", [SSSO: Shrinkage LYTD],
			        "SSSO_Shrinkage_vsPP", [SSSO: Shrinkage MoM%],
			        "SSSO_Shrinkage_vsYoY", [SSSO: Shrinkage YoY%],
			        "SSSO_Shrinkage_vsFlex", [SSSO: Shrinkage_F66],
			
			        "Net_Sales_vsPlan", [Net Sales_APN],
			        "Net_Sales_vsPP", [Net Sales Actual MoM%],
			        "Net_Sales_vsYoY", [Net Sales Actual YoY%],
			        "Net_Sales_vsLYTD", [Net Sales Actual LYTD],
			        "Net_Sales_vsFlex", [Net Sales_AFX],
			
			        "COGS_vsPlan", [COGS_APN],
			        "COGS_vsPP", [COGS Actual MoM%],
			        "COGS_vsYoY", [COGS Actual YoY%],
			        "COGS_vsLYTD", [COGS Actual LYTD],
			        "COGS_vsFlex", [COGS_AFX],
			
			        "Log_to_Sales_vsPlan", [Total Logistics on Net Sales_APN],
			        "Log_to_Sales_vsPP", [Total Logistics on Net Sales Actual MoM%],
			        "Log_to_Sales_vsYoY", [Total Logistics on Net Sales Actual YoY%],
			        "Log_to_Sales_vsLYTD", [Total Logistics on Net Sales LYTD],
			        "Log_to_Sales_vsFlex", [Total Logistics on Net Sales_AFX],
			
			        "Dist_to_COGS_vsPlan", [Total Distribution on COGS_APN],
			        "Dist_to_COGS_vsPP", [Total Distribution on COGS Actual MoM%],
			        "Dist_to_COGS_vsYoY", [Total Distribution on COGS Actual YoY%],
			        "Dist_to_COGS_vsLYTD", [Total Distribution on COGS LYTD],
			        "Dist_to_COGS_vsFlex", [Total Distribution on COGS_AFX],
			
			        "Net_POV_vsPlan", [Net POV_APN],
			        "Net_POV_vsPP", [Net POV Actual MoM%],
			        "Net_POV_vsYoY", [Net POV Actual YoY%],
			        "Net_POV_vsLYTD", [Net POV Actual LYTD],
			
			        "Gross_PPV_vsPlan", [Gross PPV_APN],
			        "Gross_PPV_vsPP", [Gross PPV Actual MoM%],
			        "Gross_PPV_vsYoY", [Gross PPV Actual YoY%],
			        "Gross_PPV_vsLYTD", [Gross PPV Actual LYTD],
			
			        "Operating_Income_vsPlan", [Operating Income_APN],
			        "Operating_Income_vsPP", [Operating Income Actual MoM%],
			        "Operating_Income_vsYoY", [Operating Income Actual YoY%],
			        "Operating_Income_vsLYTD", [Operating Income Actual LYTD],
			
			        "ABP_Variances_vsPlan", [ABP Variance_APN],
			        "ABP_Variances_vsPP", [ABP Variance MoM%],
			        "ABP_Variances_vsYoY", [ABP Variance YoY%],
			        "ABP_Variances_vsLYTD", [ABP Variance LYTD],
			
			        "Customer_Fines_vsPlan", [Cust Fine Target Diff%],
			        "Customer_Fines_vsPP", [Cust Fine MoM%],
			        "Customer_Fines_vsYoY", [Cust fine YoY%],
			        "Customer_Fines_vsLYTD", [Cust Fine LYTD],
			
			        BLANK()
			    )
			
			-- ✅ Output with rules
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			
			        // Special rules (Bias thresholds)
			        _kpiID IN { "Bias_Lag2_vsPlan", "Bias_Lag2_vsLYTD", "Bias_Lag2_vsYoY", "Bias_Lag2_vsPP",
			                    "Bias_Lag4_CSCA_vsPlan", "Bias_Lag4_CSCA_vsLYTD", "Bias_Lag4_CSCA_vsYoY", "Bias_Lag4_CSCA_vsPP" },
			            IF ( _value >= -0.03 && _value <= 0.03, "🟢", "🔴" ),
			
			        _kpiID IN { "Bias_Lag1_vsPlan", "Bias_Lag1_vsLYTD", "Bias_Lag1_vsYoY", "Bias_Lag1_vsPP",
			                    "Bias_Lag4_CSCI_vsPlan", "Bias_Lag4_CSCI_vsLYTD", "Bias_Lag4_CSCI_vsYoY", "Bias_Lag4_CSCI_vsPP" },
			            IF ( _value >= -0.10 && _value <= 0.10, "🟢", "🔴" ),
			
			        -- Normal rule
			        _signRule = "GoodIfNeg", IF ( _value < 0, "🟢", "🔴" ),
			        IF ( _value < 0, "🔴", "🟢" )
			    )
			
			```
		displayFolder: Landing Page Measures
		lineageTag: c39a6b2b-98e1-4ba1-94c6-7d110abbb902

	measure 'KPI Status Icon (Customer Service)' =
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "Service_Level_Gap_vsPlan", [Service Target Diff%],
			        "Service_Level_Gap_vsPP", [Service Rate% MoM%],
			        "Service_Level_Gap_vsYoY", [Service Rate YoY%],
			        "Service_Level_Gap_vsLYTD", [Service Rate LYTD],
			
			        "Service_Level_Total_vsPlan", [Service Target Diff%_CSCI],
			        "Service_Level_Total_vsPP", [Service Level MoM%],
			        "Service_Level_Total_vsYoY", [Service Level YoY%],
			        "Service_Level_Total_vsLYTD", [Service Level LYTD],
			
			        "Customer_Fines_vsPlan", [Cust Fine Target Diff%],
			        "Customer_Fines_vsPP", [Cust Fine MoM%],
			        "Customer_Fines_vsYoY", [Cust fine YoY%],
			        "Customer_Fines_vsLYTD", [Cust Fine LYTD],
			
			        "Case_fill_rate_vsPlan", [CFR Target Diff%],
			        "Case_fill_rate_vsPP", [CFR MoM%],
			        "Case_fill_rate_vsYoY", [CFR YoY%],
			        "Case_fill_rate_vsLYTD", [CFR LYTD],
			        BLANK()
			    )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, "🟢", "🔴" ),
			        IF ( _value < 0, "🔴", "🟢" )
			    )
		displayFolder: Landing Page Measures
		lineageTag: 540b0bd3-4b9f-4861-aac2-c3e8afa3eb2e

	measure 'KPI Status Icon (Demand)' = ```
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "FA_Lag1_vsPlan", [FA Target L1 Diff raw],
			        "FA_Lag1_vsLYTD", [FA% LYTD CSCI],
			        "FA_Lag1_vsYoY", [FA% YoY L1 raw CSCI],
			        "FA_Lag1_vsPP", [FA% MoM L1 raw CSCI],
			
			        "FA_Lag2_vsPlan", [FA% Lag 2 Target Diff%],
			        "FA_Lag2_vsLYTD", CALCULATE([FA% CSCA LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2")),
			        "FA_Lag2_vsYoY", [FA% Lag2 YoY%],
			        "FA_Lag2_vsPP", [FA% Lag2 MoM%],
			
			        "FA_Lag4_CSCA_vsPlan", [FA% Lag 4 Target Diff%],
			        "FA_Lag4_CSCA_vsLYTD", CALCULATE([FA% CSCA LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        "FA_Lag4_CSCA_vsYoY", [FA% Lag4 YoY%],
			        "FA_Lag4_CSCA_vsPP", [FA% Lag4 MoM%],
			        "FA_Lag4_CSCI_vsPlan", [FA Target L4 Diff raw],
			        "FA_Lag4_CSCI_vsLYTD", [FA% LYTD CSCI],
			        "FA_Lag4_CSCI_vsYoY", [FA% YoY L4 raw CSCI],
			        "FA_Lag4_CSCI_vsPP", [FA% MoM CSCI L4],
			
			        "Bias_Lag1_vsPlan", [Bias Target Diff%_CSCI L1],
			        "Bias_Lag1_vsLYTD", CALCULATE([Bias % LYTD CSCI], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="1")),
			        "Bias_Lag1_vsYoY", [Bias YoY % L1 Raw CSCI],
			        "Bias_Lag1_vsPP", [Bias MoM%_raw L1 CSCI],
			        
			        "Bias_Lag2_vsPlan", [Bias Lag2 Target Diff%],
			        "Bias_Lag2_vsLYTD", CALCULATE([Bias% LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2")),
			        "Bias_Lag2_vsYoY", [Bias Lag2 YoY%],
			        "Bias_Lag2_vsPP", CALCULATE([Bias MoM%], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2")),
			
			        "Bias_Lag4_CSCA_vsPlan", [Bias Lag4 Target Diff%],
			        "Bias_Lag4_CSCA_vsLYTD", CALCULATE([Bias% LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        "Bias_Lag4_CSCA_vsYoY", [Bias Lag4 YoY%],
			        "Bias_Lag4_CSCA_vsPP", CALCULATE([Bias MoM%], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        "Bias_Lag4_CSCI_vsPlan", [Bias Target Diff%_CSCI L4],
			        "Bias_Lag4_CSCI_vsLYTD", CALCULATE([Bias % LYTD CSCI], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        "Bias_Lag4_CSCI_vsYoY", [Bias YoY % L4 Raw CSCI],
			        "Bias_Lag4_CSCI_vsPP", [Bias MoM%_raw L4 CSCI],
			        BLANK()
			    )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, "🟢", "🔴" ),
			        IF ( _value < 0, "🔴", "🟢" )
			    )
			```
		displayFolder: Landing Page Measures
		lineageTag: 8c97b6cc-c44a-45de-a264-00cf3827cc63

	measure 'KPI Status Icon (Fullfilment)' =
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "Net_Sales_vsPlan", [Net Sales_APN],
			        "Net_Sales_vsPP", [Net Sales Actual MoM%],
			        "Net_Sales_vsYoY", [Net Sales Actual YoY%],
			        "Net_Sales_vsLYTD", [Net Sales Actual LYTD],
			
			
			        "DSO_vsPlan", [DSO_APN],
			        "DSO_vsPP", [DSO MoM%],
			        "DSO_vsYoY", [DSO YoY%],
			
			        BLANK()
			    )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, "🟢", "🔴" ),
			        IF ( _value < 0, "🔴", "🟢" )
			    )
		displayFolder: Landing Page Measures
		lineageTag: 32c01af7-92b9-4f4c-ae7a-06445b397d3a

	measure 'KPI Status Icon (Inventory)' =
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "Net_Inventory_vsPlan", [Net Inventory_APN],
			        "Net_Inventory_vsFlex", [Net Inventory_AFX],
			        "Net_Inventory_vsLYTD", [Net Inventory LYTD],
			        "Net_Inventory_vsPP", [Net Inventory MoM%],
			        "Net_Inventory_vsYoY", [Net Inventory YoY%],
			
			        "Gross_Inventory_vsPlan", [Gross Inventory_APN],
			        "Gross_Inventory_vsFlex", [Gross Inventory_AFX],
			        "Gross_Inventory_vsLYTD", [Gross Inv LYTD],
			        "Gross_Inventory_vsPP", [Gross Inventory MoM%],
			        "Gross_Inventory_vsYoY", [Gross Inventory YoY%],
			
			        "Expired_Inventory_vsPP", [Expired Inventory MoM%],
			        "Expired_Inventory_vsYoY", [Expired Inventory YoY%],
			        "Expired_Inventory_vsLYTD", [Expired Inventory LYTD],
			
			        "Inflated_Inventory_vsPP", [Inflated Inventory MoM%],
			        "Inflated_Inventory_vsYoY", [Inflated Inventory YoY%],
			        "Inflated_Inventory_vsLYTD", [Inflated Inv LYTD],
			
			        "DIO_vsPlan", [DIO_APN],
			        "DIO_vsPP", [DIO MoM%],
			        "DIO_vsFlex", [DIO_AFX],
			        "DIO_vsYoY", [DIO YoY%],
			
			        "SSSO_Conversions_vsPlan", [SSSO: Obsolescenes linked to Conversions_APN],
			        "SSSO_Conversions_vsLYTD", [SSSO: Obs LYTD],
			        "SSSO_Conversions_vsPP", [SSSO: Obs linked to Conv MoM%],
			        "SSSO_Conversions_vsYoY", [SSSO: Obs linked to Conv YoY%],
			        "SSSO_Conversions_vsFlex", [SSSO: Obs linked to conv F66_Final],
			
			        "SSSO_Salvage_Obsolescence_vsPlan", [SSSO: Salvage & Obsolescence_APN],
			        "SSSO_Salvage_Obsolescence_vsLYTD", [SSSO: Salvage LYTD],
			        "SSSO_Salvage_Obsolescence_vsPP", [SSSO: Salvage & obs MoM%],
			        "SSSO_Salvage_Obsolescence_vsYoY", [SSSO: Salvage YoY%],
			        "SSSO_Salvage_Obsolescence_vsFlex", [SSSO: Salvage & Obs F66_Final],
			
			        "SSSO_Scrap_vsPlan", [SSSO: Scrap-Off_APN],
			        "SSSO_Scrap_vsLYTD", [SSSO: Scrap-off LYTD],
			        "SSSO_Scrap_vsPP", [SSSO: Scrap-Off MoM%],
			        "SSSO_Scrap_vsYoY", [SSSO: Scrap-Off YoY%],
			        "SSSO_Scrap_vsFlex", [SSSO: Scrap-Off_F66],
			
			        "SSSO_Shrinkage_vsPlan", [SSSO: Shrinkage_APN],
			        "SSSO_Shrinkage_vsLYTD", [SSSO: Shrinkage LYTD],
			        "SSSO_Shrinkage_vsPP", [SSSO: Shrinkage MoM%],
			        "SSSO_Shrinkage_vsYoY", [SSSO: Shrinkage YoY%],
			        "SSSO_Shrinkage_vsFlex", [SSSO: Shrinkage_F66],
			        BLANK()
			        )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, "🟢", "🔴" ),
			        IF ( _value < 0, "🔴", "🟢" )
			    )
		displayFolder: Landing Page Measures
		lineageTag: 30bcdc07-943f-4ed1-94fa-7c24b51e73fb

	measure 'KPI Status Icon (Logistics)' =
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "Dist_to_COGS_vsPlan", [Total Distribution on COGS_APN],
			        "Dist_to_COGS_vsPP", [Total Distribution on COGS Actual MoM%],
			        "Dist_to_COGS_vsYoY", [Total Distribution on COGS Actual YoY%],
			        "Dist_to_COGS_vsLYTD", [Total Distribution on COGS LYTD],
			
			        "Log_to_Sales_vsPlan", [Total Logistics on Net Sales_APN],
			        "Log_to_Sales_vsPP", [Total Logistics on Net Sales Actual MoM%],
			        "Log_to_Sales_vsYoY", [Total Logistics on Net Sales Actual YoY%],
			        "Log_to_Sales_vsLYTD", [Total Logistics on Net Sales LYTD],
			
			        "Schedule_Attainment_vsPlan", [Schedule Attn Target Diff%],
			        "Schedule_Attainment_vsPP", [SA MoM%],
			        "Schedule_Attainment_vsYoY", [SA YoY%],
			        "Schedule_Attainment_vsLYTD", [Schedule Attn LYTD],
			        BLANK()
			    )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, "🟢", "🔴" ),
			        IF ( _value < 0, "🔴", "🟢" )
			    )
		displayFolder: Landing Page Measures
		lineageTag: 5c34cc7f-eed8-4e70-bacb-f16301694222

	measure 'KPI Status Icon (Manufacturing)' =
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "OEE_vsPlan", [OEE Target diff%],
			        "OEE_vsPP", [OEE% MoM%],
			        "OEE_vsYoY", [OEE% YoY%],
			        "OEE_vsLYTD", [OEE LYTD],
			
			        "COGS_vsPlan", [COGS_APN],
			        "COGS_vsPP", [COGS Actual MoM%],
			        "COGS_vsYoY", [COGS Actual YoY%],
			        "COGS_vsLYTD", [COGS Actual LYTD],
			        BLANK()
			    )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, "🟢", "🔴" ),
			        IF ( _value < 0, "🔴", "🟢" )
			    )
		displayFolder: Landing Page Measures
		lineageTag: a0e28e0b-6a78-4739-84d7-105252889ce3

	measure 'KPI Status Icon (Operating Income)' = ```
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "SSSO_Conversions_vsPlan", [SSSO: Obsolescenes linked to Conversions_APN],
			        "SSSO_Conversions_vsLYTD", [SSSO: Obs LYTD],
			        "SSSO_Conversions_vsPP", [SSSO: Obs linked to Conv MoM%],
			        "SSSO_Conversions_vsYoY", [SSSO: Obs linked to Conv YoY%],
			        "SSSO_Conversions_vsFlex", [SSSO: Obsolescenes linked to Conversions_F66],
			
			        "SSSO_Salvage_Obsolescence_vsPlan", [SSSO: Salvage & Obsolescence_APN],
			        "SSSO_Salvage_Obsolescence_vsLYTD", [SSSO: Salvage LYTD],
			        "SSSO_Salvage_Obsolescence_vsPP", [SSSO: Salvage & obs MoM%],
			        "SSSO_Salvage_Obsolescence_vsYoY", [SSSO: Salvage YoY%],
			        "SSSO_Salvage_Obsolescence_vsFlex", [SSSO: Salvage & Obsolescence_F66],
			
			        "SSSO_Scrap_vsPlan", [SSSO: Scrap-Off_APN],
			        "SSSO_Scrap_vsLYTD", [SSSO: Scrap-off LYTD],
			        "SSSO_Scrap_vsPP", [SSSO: Scrap-Off MoM%],
			        "SSSO_Scrap_vsYoY", [SSSO: Scrap-Off YoY%],
			        "SSSO_Scrap_vsFlex", [SSSO: Scrap-Off_F66],
			
			        "SSSO_Shrinkage_vsPlan", [SSSO: Shrinkage_APN],
			        "SSSO_Shrinkage_vsLYTD", [SSSO: Shrinkage LYTD],
			        "SSSO_Shrinkage_vsPP", [SSSO: Shrinkage MoM%],
			        "SSSO_Shrinkage_vsYoY", [SSSO: Shrinkage YoY%],
			        "SSSO_Shrinkage_vsFlex", [SSSO: Shrinkage_F66],
			
			        "Net_Sales_vsPlan", [Net Sales_APN],
			        "Net_Sales_vsPP", [Net Sales Actual MoM%],
			        "Net_Sales_vsYoY", [Net Sales Actual YoY%],
			        "Net_Sales_vsLYTD", [Net Sales Actual LYTD],
			        "Net_Sales_vsFlex", [Net Sales_AFX],
			
			        "COGS_vsPlan", [COGS_APN],
			        "COGS_vsPP", [COGS Actual MoM%],
			        "COGS_vsYoY", [COGS Actual YoY%],
			        "COGS_vsLYTD", [COGS Actual LYTD],
			        "COGS_vsFlex", [COGS_AFX],
			
			        "Log_to_Sales_vsPlan", [Total Logistics on Net Sales_APN],
			        "Log_to_Sales_vsPP", [Total Logistics on Net Sales Actual MoM%],
			        "Log_to_Sales_vsYoY", [Total Logistics on Net Sales Actual YoY%],
			        "Log_to_Sales_vsLYTD", [Total Logistics on Net Sales LYTD],
			        "Log_to_Sales_vsFlex", [Total Logistics on Net Sales_AFX],
			
			        "Dist_to_COGS_vsPlan", [Total Distribution on COGS_APN],
			        "Dist_to_COGS_vsPP", [Total Distribution on COGS Actual MoM%],
			        "Dist_to_COGS_vsYoY", [Total Distribution on COGS Actual YoY%],
			        "Dist_to_COGS_vsLYTD", [Total Distribution on COGS LYTD],
			        "Dist_to_COGS_vsFlex", [Total Distribution on COGS_AFX],
			    
			        "Net_POV_vsPlan", [Net POV_APN],
			        "Net_POV_vsPP", [Net POV Actual MoM%],
			        "Net_POV_vsYoY", [Net POV Actual YoY%],
			        "Net_POV_vsLYTD", [Net POV Actual LYTD],
			
			        "Gross_PPV_vsPlan", [Gross PPV_APN],
			        "Gross_PPV_vsPP", [Gross PPV Actual MoM%],
			        "Gross_PPV_vsYoY", [Gross PPV Actual YoY%],
			        "Gross_PPV_vsLYTD", [Gross PPV Actual LYTD],
			
			        "Operating_Income_vsPlan", [Operating Income_APN],
			        "Operating_Income_vsPP", [Operating Income Actual MoM%],
			        "Operating_Income_vsYoY", [Operating Income Actual YoY%],
			        "Operating_Income_vsLYTD", [Operating Income Actual LYTD],
			
			        "ABP_Variances_vsPlan", [ABP Variance_APN],
			        "ABP_Variances_vsPP", [ABP Variance MoM%],
			        "ABP_Variances_vsYoY", [ABP Variance YoY%],
			        "ABP_Variances_vsLYTD", [ABP Variance LYTD],
			
			        "Customer_Fines_vsPlan", [Cust Fine Target Diff%],
			        "Customer_Fines_vsPP", [Cust Fine MoM%],
			        "Customer_Fines_vsYoY", [Cust fine YoY%],
			        "Customer_Fines_vsLYTD", [Cust Fine LYTD],
			
			        BLANK()
			    )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, "🟢", "🔴" ),
			        IF ( _value < 0, "🔴", "🟢" )
			    )
			```
		displayFolder: Landing Page Measures
		lineageTag: 3c43eba9-48bb-4ce1-9c55-2f528ebaecca

	measure 'KPI Status Icon (Operations&Quality)' =
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "OEE_vsPlan", [OEE Target diff%],
			        "OEE_vsPP", [OEE% MoM%],
			        "OEE_vsYoY", [OEE% YoY%],
			        "OEE_vsLYTD", [OEE LYTD],
			
			        "Schedule_Attainment_vsPlan", [Schedule Attn Target Diff%],
			        "Schedule_Attainment_vsPP", [SA MoM%],
			        "Schedule_Attainment_vsYoY", [SA YoY%],
			        "Schedule_Attainment_vsLYTD", [Schedule Attn LYTD],
			
			        "On_Time_Deviation_vsPlan", [On Time Closure of Deviations Target Diff%],
			        "On_Time_Deviation_vsYoY", [On Time Closure of Deviations YoY%],
			        "On_Time_Deviation_vsLYTD", [On Time Closure of Deviations LYTD],
			        "On_Time_Deviation_vsPP", [On Time Closure of Deviations MoM%],
			
			        "CAPA_Completion_vsPlan", [CAPA Completion Rate Target Diff%],
			        "CAPA_Completion_vsPP", [CAPA Completion Rate MoM%],
			        "CAPA_Completion_vsYoY", [CAPA Completion Rate YoY%],
			        "CAPA_Completion_vsLYTD", [CAPA Closed LYTD],
			
			        "Right_First_Time_vsPlan", [RFT Target Diff%],
			        "Right_First_Time_vsPP", [RFT MoM%],
			        "Right_First_Time_vsYoY", [RFT YoY%],
			        "Right_First_Time_vsLYTD", [RFT LYTD],
			
			        "Critical/Major_vsPP", [Critical or Major Observations MoM%],
			        "Critical/Major_vsYoY", [Critical or Major Observations YoY%],
			        "Critical/Major_vsLYTD", [Critical or Major Observations LYTD],
			
			        "ASTM_Incidents_vsPlan",BLANK(),
			        "ASTM_Incidents_vsPP",[ASTM Incidents MoM%],
			        "ASTM_Incidents_vsYoY",[ASTM Incidents YoY%],
			        "ASTM_Incidents_vsLYTD",[ASTM Incidents LYTD],
			
			        "ASTM_Rate_vsPlan",BLANK(),
			        "ASTM_Rate_vsPP",[ASTM Rate MoM%],
			        "ASTM_Rate_vsYoY",[ASTM Rate YoY%],
			        "ASTM_Rate_vsLYTD",[ASTM Rate LYTD],
			
			        "Good_Catch_Closure_vsPlan",[Good Catch Closure Rate Target Diff%],
			        "Good_Catch_Closure_vsPP",[Good Catch Closure Rate MoM%],
			        "Good_Catch_Closure_vsYoY",[Good Catch Closure Rate YoY%],
			        "Good_Catch_Closure_vsLYTD",BLANK(),
			
			        "pSIF_Closure_vsPlan",[pSIF SIFs Focus Target Diff%],
			        "pSIF_Closure_vsPP",[pSIF SIFs Focus MoM%],
			        "pSIF_Closure_vsYoY",[pSIF SIFs Focus YoY%],
			        "pSIF_Closure_vsLYTD",BLANK(),
			
			        "PWS_Benefits_vsPlan",[PWS Benefits_APN],
			        "PWS_Benefits_vsPP",[PWS Benefits MoM%],
			        "PWS_Benefits_vsYoY",[PWS Benefits YoY%],
			        "PWS_Benefits_vsLYTD",[PWS Benefits LYTD],
			
			        BLANK()
			    )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, "🟢", "🔴" ),
			        IF ( _value < 0, "🔴", "🟢" )
			    )
		displayFolder: Landing Page Measures
		lineageTag: 4d1f87cd-4d92-4b56-9c53-254b724f1f1c

	measure 'KPI Status Icon (Procurement)' =
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "DPO_vsPlan", [DPO_APN],
			        "DPO_vsPP", [DPO MoM%],
			        "DPO_vsYoY", [DPO YoY%],
			        BLANK()
			    )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, "🟢", "🔴" ),
			        IF ( _value < 0, "🔴", "🟢" )
			    )
		displayFolder: Landing Page Measures
		lineageTag: 64623ad6-23a6-45cb-b829-dd959a0920eb

	measure 'KPI Status Icon (Working Capital)' =
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode =
			    SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			-- Assign value based on KPI_ID
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "Net_Inventory_vsPlan", [Net Inventory_APN],
			        "Net_Inventory_vsFlex", [Net Inventory_AFX],
			        "Net_Inventory_vsLYTD", [Net Inventory LYTD],
			        "Net_Inventory_vsPP", [Net Inventory MoM%],
			        "Net_Inventory_vsYoY", [Net Inventory YoY%],
			
			        "Gross_Inventory_vsPlan", [Gross Inventory_APN],
			        "Gross_Inventory_vsFlex", [Gross Inventory_AFX],
			        "Gross_Inventory_vsLYTD", [Gross Inv LYTD],
			        "Gross_Inventory_vsPP", [Gross Inventory MoM%],
			        "Gross_Inventory_vsYoY", [Gross Inventory YoY%],
			
			        "Expired_Inventory_vsPP", [Expired Inventory MoM%],
			        "Expired_Inventory_vsYoY", [Expired Inventory YoY%],
			        "Expired_Inventory_vsLYTD", [Expired Inventory LYTD],
			
			        "Inflated_Inventory_vsPP", [Inflated Inventory MoM%],
			        "Inflated_Inventory_vsYoY", [Inflated Inventory YoY%],
			        "Inflated_Inventory_vsLYTD", [Inflated Inv LYTD],
			
			        "DIO_vsPlan", [DIO_APN],
			        "DIO_vsPP", [DIO MoM%],
			        "DIO_vsFlex", [DIO_AFX],
			        "DIO_vsYoY", [DIO YoY%],
			
			        "DPO_vsPlan",[DPO_APN],
			        "DPO_vsPP", [DPO MoM%],
			        "DPO_vsYoY", [DPO YoY%],
			
			        "DSO_vsPlan",[DSO_APN],
			        "DSO_vsPP", [DSO MoM%],
			        "DSO_vsYoY", [DSO YoY%],
			
			        BLANK()
			    )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, "🟢", "🔴" ),
			        IF ( _value < 0, "🔴", "🟢" )
			    )
		displayFolder: Landing Page Measures
		lineageTag: 995204bd-ef24-4f64-8edb-f72456b8146a

	measure 'KPI Status Numeric' = ```
			
			VAR _kpiID = SELECTEDVALUE ( KPI_Metadata[KPI_ID] )
			
			VAR _timeMode = SELECTEDVALUE ( CG_PeriodSelection[Period] )
			
			VAR _signRule =
			    IF (
			        _timeMode = "YTD",
			        LOOKUPVALUE ( KPI_Metadata[SignRule_YTD], KPI_Metadata[KPI_ID], _kpiID ),
			        LOOKUPVALUE ( KPI_Metadata[SignRule_PTD], KPI_Metadata[KPI_ID], _kpiID )
			    )
			
			VAR _value =
			    SWITCH (
			        _kpiID,
			        "FA_Lag1_vsPlan", [FA Target L1 Diff raw],
			        "FA_Lag1_vsLYTD", [FA% L1 LYTD CSCI],
			        "FA_Lag1_vsYoY", [FA% YoY L1 raw CSCI],
			        "FA_Lag1_vsPP", [FA% MoM L1 raw CSCI],
			
			        "FA_Lag2_vsPlan", [FA% Lag 2 Target Diff%],
			        "FA_Lag2_vsLYTD", CALCULATE([FA% CSCA LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2")),
			        "FA_Lag2_vsYoY", [FA% Lag2 YoY%],
			        "FA_Lag2_vsPP", [FA% Lag2 MoM%],
			
			        "FA_Lag4_CSCA_vsPlan", [FA% Lag 4 Target Diff%],
			        "FA_Lag4_CSCA_vsLYTD", CALCULATE([FA% CSCA LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        "FA_Lag4_CSCA_vsYoY", [FA% Lag4 YoY%],
			        "FA_Lag4_CSCA_vsPP", [FA% Lag4 MoM%],
			
			        "FA_Lag4_CSCI_vsPlan", [FA Target L4 Diff raw],
			        "FA_Lag4_CSCI_vsLYTD", [FA% L4 LYTD CSCI],
			        "FA_Lag4_CSCI_vsYoY", [FA% YoY L4 raw CSCI],
			        "FA_Lag4_CSCI_vsPP", [FA% MoM L4 raw CSCI],
			
			        "Bias_Lag1_vsPlan", [Bias Target Diff%_CSCI L1],
			        "Bias_Lag1_vsLYTD", [Bias % L1 LYTD CSCI],
			        "Bias_Lag1_vsYoY", [Bias YoY % L1 Raw CSCI],
			        "Bias_Lag1_vsPP", [Bias MoM%_raw L1 CSCI],
			        
			        "Bias_Lag2_vsPlan", [Bias Lag2 Target Diff%],
			        "Bias_Lag2_vsLYTD", CALCULATE([Bias% LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="2")),
			        "Bias_Lag2_vsYoY", [Bias Lag2 YoY%],
			        "Bias_Lag2_vsPP", [Bias Lag2 MoM%],
			
			        "Bias_Lag4_CSCA_vsPlan", [Bias Lag4 Target Diff%],
			        "Bias_Lag4_CSCA_vsLYTD", CALCULATE([Bias% LYTD], KEEPFILTERS(Fact_Forecast_Accuracy[LAGs]="4")),
			        "Bias_Lag4_CSCA_vsYoY", [Bias Lag4 YoY%],
			        "Bias_Lag4_CSCA_vsPP", [Bias Lag4 MoM%],
			
			        "Bias_Lag4_CSCI_vsPlan", [Bias Target Diff%_CSCI L4],
			        "Bias_Lag4_CSCI_vsLYTD", [Bias % L4 LYTD CSCI],
			        "Bias_Lag4_CSCI_vsYoY", [Bias YoY % L4 Raw CSCI],
			        "Bias_Lag4_CSCI_vsPP", [Bias MoM%_raw L4 CSCI],
			
			        "Service_Level_Gap_vsPlan", [Service Target Diff%],
			        "Service_Level_Gap_vsPP", [Service Rate% MoM%],
			        "Service_Level_Gap_vsYoY", [Service Rate YoY%],
			        "Service_Level_Gap_vsLYTD", [Service Rate LYTD],
			
			        "Service_Top_11_vsPlan", [Service Top 11 Target Diff%],
			        "Service_Top_11_vsYoY", [Service Top 11 YoY%],
			        "Service_Top_11_vsLYTD", [Service Top 11 LYTD],
			        "Service_Top_11_vsPP", [Service Top 11 MoM%],
			
			        "Service_Level_Total_vsPlan", [Service Target Diff%_CSCI],
			        "Service_Level_Total_vsPP", [Service Level MoM%],
			        "Service_Level_Total_vsYoY", [Service Level YoY%],
			        "Service_Level_Total_vsLYTD", [Service Level LYTD],
			
			        "Case_fill_rate_vsPlan", [CFR Target Diff%],
			        "Case_fill_rate_vsPP", [CFR MoM%],
			        "Case_fill_rate_vsYoY", [CFR YoY%],
			        "Case_fill_rate_vsLYTD", [CFR LYTD],
			
			        "OEE_vsPlan", [OEE Target diff%],
			        "OEE_vsPP", [OEE% MoM%],
			        "OEE_vsYoY", [OEE% YoY%],
			        "OEE_vsLYTD", [OEE LYTD],
			
			        "Schedule_Attainment_vsPlan", [Schedule Attn Target Diff%],
			        "Schedule_Attainment_vsPP", [SA MoM%],
			        "Schedule_Attainment_vsYoY", [SA YoY%],
			        "Schedule_Attainment_vsLYTD", [Schedule Attn LYTD],
			
			        "On_Time_Deviation_vsPlan", [On Time Closure of Deviations Target Diff%],
			        "On_Time_Deviation_vsYoY", [On Time Closure of Deviations YoY%],
			        "On_Time_Deviation_vsLYTD", [On Time Closure of Deviations LYTD],
			        "On_Time_Deviation_vsPP", [On Time Closure of Deviations MoM%],
			
			        "CAPA_Completion_vsPlan", [CAPA Completion Rate Target Diff%],
			        "CAPA_Completion_vsPP", [CAPA Completion Rate MoM%],
			        "CAPA_Completion_vsYoY", [CAPA Completion Rate YoY%],
			        "CAPA_Completion_vsLYTD", [CAPA Closed LYTD],
			
			        "Right_First_Time_vsPlan", [RFT Target Diff%],
			        "Right_First_Time_vsPP", [RFT MoM%],
			        "Right_First_Time_vsYoY", [RFT YoY%],
			        "Right_First_Time_vsLYTD", [RFT LYTD],
			
			        "Critical/Major_vsPP", [Critical or Major Observations MoM%],
			        "Critical/Major_vsYoY", [Critical or Major Observations YoY%],
			        "Critical/Major_vsLYTD", [Critical or Major Observations LYTD],
			
			        "Net_Inventory_vsPlan", [Net Inventory_APN],
			        "Net_Inventory_vsFlex", [Net Inventory_AFX],
			        "Net_Inventory_vsLYTD", [Net Inventory LYTD],
			        "Net_Inventory_vsPP", [Net Inventory MoM%],
			        "Net_Inventory_vsYoY", [Net Inventory YoY%],
			
			        "Gross_Inventory_vsPlan", [Gross Inventory_APN],
			        "Gross_Inventory_vsFlex", [Gross Inventory_AFX],
			        "Gross_Inventory_vsLYTD", [Gross Inv LYTD],
			        "Gross_Inventory_vsPP", [Gross Inventory MoM%],
			        "Gross_Inventory_vsYoY", [Gross Inventory YoY%],
			
			        "Expired_Inventory_vsPP", [Expired Inventory MoM%],
			        "Expired_Inventory_vsYoY", [Expired Inventory YoY%],
			        "Expired_Inventory_vsLYTD", [Expired Inventory LYTD],
			
			        "Inflated_Inventory_vsPP", [Inflated Inventory MoM%],
			        "Inflated_Inventory_vsYoY", [Inflated Inventory YoY%],
			        "Inflated_Inventory_vsLYTD", [Inflated Inv LYTD],
			
			        "DIO_vsPlan", [DIO_APN],
			        "DIO_vsPP", [DIO MoM%],
			        "DIO_vsFlex", [DIO_AFX],
			        "DIO_vsYoY", [DIO YoY%],
			
			        "DPO_vsPlan",[DPO_APN],
			        "DPO_vsPP", [DPO MoM%],
			        "DPO_vsYoY", [DPO YoY%],
			
			        "DSO_vsPlan",[DSO_APN],
			        "DSO_vsPP", [DSO MoM%],
			        "DSO_vsYoY", [DSO YoY%],
			
			        "SSSO_Conversions_vsPlan", [SSSO: Obsolescenes linked to Conversions_APN],
			        "SSSO_Conversions_vsLYTD", [SSSO: Obs LYTD],
			        "SSSO_Conversions_vsPP", [SSSO: Obs linked to Conv MoM%],
			        "SSSO_Conversions_vsYoY", [SSSO: Obs linked to Conv YoY%],
			        "SSSO_Conversions_vsFlex", [SSSO: Obsolescenes linked to Conversions_F66],
			
			        "SSSO_Salvage_Obsolescence_vsPlan", [SSSO: Salvage & Obsolescence_APN],
			        "SSSO_Salvage_Obsolescence_vsLYTD", [SSSO: Salvage LYTD],
			        "SSSO_Salvage_Obsolescence_vsPP", [SSSO: Salvage & obs MoM%],
			        "SSSO_Salvage_Obsolescence_vsYoY", [SSSO: Salvage YoY%],
			        "SSSO_Salvage_Obsolescence_vsFlex", [SSSO: Salvage & Obsolescence_F66],
			
			        "SSSO_Scrap_vsPlan", [SSSO: Scrap-Off_APN],
			        "SSSO_Scrap_vsLYTD", [SSSO: Scrap-off LYTD],
			        "SSSO_Scrap_vsPP", [SSSO: Scrap-Off MoM%],
			        "SSSO_Scrap_vsYoY", [SSSO: Scrap-Off YoY%],
			        "SSSO_Scrap_vsFlex", [SSSO: Scrap-Off_F66],
			
			        "SSSO_Shrinkage_vsPlan", [SSSO: Shrinkage_APN],
			        "SSSO_Shrinkage_vsLYTD", [SSSO: Shrinkage LYTD],
			        "SSSO_Shrinkage_vsPP", [SSSO: Shrinkage MoM%],
			        "SSSO_Shrinkage_vsYoY", [SSSO: Shrinkage YoY%],
			        "SSSO_Shrinkage_vsFlex", [SSSO: Shrinkage_F66],
			        
			        "COGS_vsPlan", [COGS_APN],
			        "COGS_vsPP", [COGS Actual MoM%],
			        "COGS_vsYoY", [COGS Actual YoY%],
			        "COGS_vsLYTD", [COGS Actual LYTD],
			        "COGS_vsFlex", [COGS_AFX],
			
			        "Dist_to_COGS_vsPlan", [Total Distribution on COGS_APN],
			        "Dist_to_COGS_vsPP", [Total Distribution on COGS Actual MoM%],
			        "Dist_to_COGS_vsYoY", [Total Distribution on COGS Actual YoY%],
			        "Dist_to_COGS_vsLYTD", [Total Distribution on COGS LYTD],
			        "Dist_to_COGS_vsFlex", [Total Distribution on COGS_AFX],
			
			        "Log_to_Sales_vsPlan", [Total Logistics on Net Sales_APN],
			        "Log_to_Sales_vsPP", [Total Logistics on Net Sales Actual MoM%],
			        "Log_to_Sales_vsYoY", [Total Logistics on Net Sales Actual YoY%],
			        "Log_to_Sales_vsLYTD", [Total Logistics on Net Sales LYTD],
			        "Log_to_Sales_vsFlex", [Total Logistics on Net Sales_AFX],
			
			        "Net_Sales_vsPlan", [Net Sales_APN],
			        "Net_Sales_vsPP", [Net Sales Actual MoM%],
			        "Net_Sales_vsYoY", [Net Sales Actual YoY%],
			        "Net_Sales_vsLYTD", [Net Sales Actual LYTD],
			        "Net_Sales_vsFlex",[Net Sales_AFX],
			
			        "Customer_Fines_vsPlan", [Cust Fine Target Diff%],
			        "Customer_Fines_vsPP", [Cust Fine MoM%],
			        "Customer_Fines_vsYoY", [Cust fine YoY%],
			        "Customer_Fines_vsLYTD", [Cust Fine LYTD],
			
			        "ABP_Variances_vsPlan", [ABP Variance_APN],
			        "ABP_Variances_vsPP", [ABP Variance MoM%],
			        "ABP_Variances_vsYoY", [ABP Variance YoY%],
			        "ABP_Variances_vsLYTD", [ABP Variance LYTD],
			
			        "Net_POV_vsPlan", [Net POV_APN],
			        "Net_POV_vsPP", [Net POV Actual MoM%],
			        "Net_POV_vsYoY", [Net POV Actual YoY%],
			        "Net_POV_vsLYTD", [Net POV Actual LYTD],
			
			        "Gross_PPV_vsPlan", [Gross PPV_APN],
			        "Gross_PPV_vsPP", [Gross PPV Actual MoM%],
			        "Gross_PPV_vsYoY", [Gross PPV Actual YoY%],
			        "Gross_PPV_vsLYTD", [Gross PPV Actual LYTD],
			
			        "Operating_Income_vsPlan", [Operating Income_APN],
			        "Operating_Income_vsPP", [Operating Income Actual MoM%],
			        "Operating_Income_vsYoY", [Operating Income Actual YoY%],
			        "Operating_Income_vsLYTD", [Operating Income Actual LYTD],
			
			        "ASTM_Incidents_vsPlan",BLANK(),
			        "ASTM_Incidents_vsPP",[ASTM Incidents MoM%],
			        "ASTM_Incidents_vsYoY",[ASTM Incidents YoY%],
			        "ASTM_Incidents_vsLYTD",[ASTM Incidents LYTD],
			
			        "ASTM_Rate_vsPlan",BLANK(),
			        "ASTM_Rate_vsPP",[ASTM Rate MoM%],
			        "ASTM_Rate_vsYoY",[ASTM Rate YoY%],
			        "ASTM_Rate_vsLYTD",[ASTM Rate LYTD],
			
			        "Good_Catch_Closure_vsPlan",[Good Catch Closure Rate Target Diff%],
			        "Good_Catch_Closure_vsPP",[Good Catch Closure Rate MoM%],
			        "Good_Catch_Closure_vsYoY",[Good Catch Closure Rate YoY%],
			        "Good_Catch_Closure_vsLYTD",BLANK(),
			
			        "pSIF_Closure_vsPlan",[pSIF SIFs Focus Target Diff%],
			        "pSIF_Closure_vsPP",[pSIF SIFs Focus MoM%],
			        "pSIF_Closure_vsYoY",[pSIF SIFs Focus YoY%],
			        "pSIF_Closure_vsLYTD",BLANK(),
			
			        "PWS_Benefits_vsPlan",[PWS Benefits_APN],
			        "PWS_Benefits_vsPP",[PWS Benefits MoM%],
			        "PWS_Benefits_vsYoY",[PWS Benefits YoY%],
			        "PWS_Benefits_vsLYTD",[PWS Benefits LYTD],
			
			        BLANK()
			    )
			
			RETURN
			    SWITCH (
			        TRUE(),
			        ISBLANK ( _value ), BLANK(),
			        _signRule = "GoodIfNeg", IF ( _value < 0, 1, 0 ),
			        IF ( _value < 0, 0, 1 )
			    )
			
			```
		formatString: 0
		displayFolder: Landing Page Measures
		lineageTag: be19d0b0-cf51-4fac-94ab-03e50a49644e

	measure 'Total Red Count' = ```
			
			VAR _cnt =
			    CALCULATE (
			        COUNTROWS ( KPI_Metadata ),
			        FILTER (
			            KPI_Metadata,
			            ( [KPI Status Icon (Sales Growth)] = "🔴"
			            || [KPI Status Icon (Operations&Quality)] = "🔴"
			            || [KPI Status Icon (Working Capital)] = "🔴"
			            || [KPI Status Icon (Operating Income)] = "🔴" )
			        )
			    )
			RETURN
			COALESCE ( _cnt, 0 )
			
			```
		formatString: 0
		displayFolder: Landing Page Measures
		lineageTag: ad666069-eafc-4514-a3f0-22ac58d64ae5

	measure 'Red Count (OperatingIncome)' = ```
			
			VAR _count = 
			CALCULATE (
			    COUNTROWS ( KPI_Metadata ),
			    FILTER (
			        KPI_Metadata,
			        [KPI Status Icon (Operating Income)] = "🔴"
			            && NOT ISBLANK ( [KPI Status Icon (Operating Income)] )
			    )
			)
			
			
			RETURN
			IF (
			    _count = 0,
			    "0",
			    UNICHAR(129139) & " " & _count
			)
			
			```
		displayFolder: Landing Page Measures
		lineageTag: 65acde62-977b-40d7-af69-48fafeaa7ce0

	measure 'Red Count (Operations)' = ```
			
			VAR _count = 
			CALCULATE (
			    COUNTROWS ( KPI_Metadata ),
			    FILTER (
			        KPI_Metadata,
			        [KPI Status Icon (Operations&Quality)] = "🔴"
			            && NOT ISBLANK ( [KPI Status Icon (Operations&Quality)] )
			    )
			)
			
			
			RETURN
			IF (
			    _count = 0,
			    "0",
			    UNICHAR(129139) & " " & _count
			)
			
			```
		displayFolder: Landing Page Measures
		lineageTag: 8318f1df-7922-42a0-8dac-9cac44b1bd27

	measure 'Red Count (sales)' = ```
			
			VAR _count = 
			CALCULATE (
			    COUNTROWS ( KPI_Metadata ),
			    FILTER (
			        KPI_Metadata,
			        [KPI Status Icon (Sales Growth)] = "🔴"
			            && NOT ISBLANK ( [KPI Status Icon (Sales Growth)] )
			    )
			)
			
			RETURN
			IF (
			    _count = 0,
			    "0",
			    UNICHAR(129139) & " " & _count
			)
			
			```
		displayFolder: Landing Page Measures
		lineageTag: 80335bb2-d024-4786-b7e9-1d147cd8d6f9

	measure 'Red Count (WorkingCapital)' = ```
			
			VAR _count =
			CALCULATE (
			    COUNTROWS ( KPI_Metadata ),
			    FILTER (
			        KPI_Metadata,
			        [KPI Status Icon (Working Capital)] = "🔴"
			            && NOT ISBLANK ( [KPI Status Icon (Working Capital)] )
			    )
			)
			
			RETURN
			IF (
			    _count = 0,
			    "0",
			    UNICHAR(129139) & " " & _count
			)
			
			```
		displayFolder: Landing Page Measures
		lineageTag: cd0d3cb3-507c-49f8-aa9e-ebb1f1f831b7

	measure 'Selected Metric' =
			
			SELECTEDVALUE(KPI_Metadata[Metrics])
		displayFolder: Landing Page Measures
		lineageTag: 0dcfdbc0-c2d0-429a-a583-a8e937ca7f1d

	measure 'Total KPI Count' =
			
			CALCULATE (
			    COUNTROWS ( KPI_Metadata ),
			    FILTER (
			        KPI_Metadata,
			        NOT ISBLANK ( [KPI Status Numeric] )
			    )
			)
		formatString: 0
		displayFolder: Landing Page Measures
		lineageTag: 2803087f-5d12-4fb2-893c-23287a8143b3

	measure Bias_Lower_Limit = ```
			
			VAR _sel = SELECTEDVALUE(Sales_Parameter[Parameter Name])
			RETURN
			IF(
			    _sel IN {"Bias% Lag 2", "Bias% Lag 4"},
			    -0.03,  // -3%
			    BLANK()
			)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Bias CSCA
		lineageTag: 3981de2e-8c08-4e63-b101-66258f77b719

	measure 'Distribution Flex' = SUM( Fact_Logistics[Distribution Flex66] )
		displayFolder: Logistic
		lineageTag: 1248c906-b81e-461b-9899-37800edbc845

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Logistics Flex' = sum(Fact_Logistics[Amount Total Logistics Flex66])
		displayFolder: Logistic
		lineageTag: e550db7c-bbb2-4e55-856c-bb802aba5849

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Sales Flex' = ```
			sum(Fact_Logistics[Net Sales F66]) 
			```
		displayFolder: Net Sales
		lineageTag: 5bed801e-bef6-4d42-8094-4cf35cf7334b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Logistics on Net Sales_AFX_Base' = DIVIDE([Total Logistics Flex], [Net Sales Flex])
		displayFolder: Logistic vs Net Sales
		lineageTag: 55344051-1e55-43fe-bd2d-e1ce38a53290

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Logistics on Net Sales_AFX' =
			
			VAR Flex = [Total Logistics on Net Sales_AFX_Base]
			RETURN
			IF (
			    ISBLANK ( Flex ),
			    BLANK (),
			[TOTAL LOGISTICS ON NET SALES Actual] - Flex
			)
		displayFolder: Logistic vs Net Sales
		lineageTag: 2cb2b527-bb12-47e9-a52f-2514f0a04a68

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Logistics on Net Sales_AFX_Final' =
			VAR kpi_ = [Total Logistics on Net Sales_AFX]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: Logistic vs Net Sales
		lineageTag: 7594275d-1117-4305-9f8b-4d2ee12dd99a

	measure COGS_AFX_Base = SUM(Fact_Logistics[COGS Flex66])
		displayFolder: COGS
		lineageTag: 965d74ab-7e01-43c7-8899-a3f589d27a8c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure COGS_AFX =
			VAR Plan = [COGS_AFX_Base]
			Return
			DIVIDE([COGS Actual] - Plan,Plan)
		displayFolder: COGS
		lineageTag: d4a7a6c3-c977-47a7-8203-fe1bf9bc9aee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure COGS_AFX_Final =
			VAR kpi_ = [COGS_AFX]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: COGS
		lineageTag: 5789399e-2002-4508-9d26-23dc70cb2fd8

	measure 'Total Distribution on COGS_AFX_Base' = DIVIDE([Distribution Flex], [COGS_AFX_Base])
		displayFolder: Distribution on COGS
		lineageTag: a259d370-27ed-428d-9ab5-5f0f0bfc5db6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Distribution on COGS_AFX' = ```
			VAR Plan = [Total Distribution on COGS_AFX_Base]
			RETURN
			IF (
			    ISBLANK ( Plan ),
			    BLANK (),
			    [TOTAL DISTRIBUTION ON COGS Actual] - Plan
			)
			
			```
		displayFolder: Distribution on COGS
		lineageTag: daa046ba-bdb0-4c5a-bbae-a0e81128c970

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Distribution on COGS_AFX_Final' =
			
			VAR kpi_ = [Total Distribution on COGS_AFX]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_  & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: Distribution on COGS
		lineageTag: 3f04eaa3-1c6e-4eff-85cf-848250446209

	measure 'Net Sales_AFX_Base' = SUM(Fact_Logistics[Net Sales F66])
		displayFolder: Net Sales
		lineageTag: bad30eb6-8446-42b0-803b-d52f3044608a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Sales_AFX' =
			
			VAR Plan = [Net Sales_AFX_Base]
			Return
			DIVIDE([Net Sales Actual] - Plan,Plan)
		displayFolder: Net Sales
		lineageTag: 106593ee-8698-4b4b-be54-a651093ce5d4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Sales_AFX_Final' =
			
			VAR kpi_ = [Net Sales_AFX]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: Net Sales
		lineageTag: 2a2be204-6ced-4c69-9a9f-2f742ad498dd

	measure TEST = "test"
		lineageTag: dc2c59a9-34ca-459a-9ad1-d9e420cf1726

	measure 'ASTM -Rate' = ```
			
			VAR _area = SELECTEDVALUE(Bridge_CSCA_CSCI[Area])
			RETURN
			IF(
			    _area = "CSCA" || _area = "CSCI",
			    SELECTEDVALUE(Fact_Safety[ASTM - Rate])
			)
			
			```
		displayFolder: ASTM Rate
		lineageTag: cb287e95-3500-451f-8895-25c3ac6e4f3b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ASTM Incidents' =
			
			VAR _area = SELECTEDVALUE(Bridge_CSCA_CSCI[Area])
			RETURN
			IF(
			    _area = "CSCA" || _area = "CSCI",
			    SELECTEDVALUE(Fact_Safety[ASTM-Incidents])
			)
			/*
			VAR _area = SELECTEDVALUE(Bridge_CSCA_CSCI[Area])   -- Your area field (CSCA / CSCI)
			RETURN
			SWITCH(
			    TRUE(),
			    _area = "CSCA",
			        CALCULATE(
			            SUM(Fact_Safety[ASTM-Incidents]),
			            KEEPFILTERS(
			                Fact_Safety[Site name/Site UUID/Location UUID] IN {
			                    "Logistics",
			                    "Vermont (PVT)",
			                    "Michigan-Allegan (PMI)",
			                    "Wisconsin (PWI)",
			                    "Ohio (POH)",
			                    "Michigan-Grand Rapids (POC)",
			                    "New York (PNY)",
			                    "Michigan-Holland (PMH)"
			                }
			            )
			        ),
			    _area = "CSCI",
			        CALCULATE(
			            SUM(Fact_Safety[ASTM-Incidents]),
			            KEEPFILTERS(
			                Fact_Safety[Site name/Site UUID/Location UUID] IN {
			                    "UK-Braunton (PUK)",
			                    "Germany-Herrenberg",
			                    "France-Plelo",
			                    "France-Laboratoire de la Mer",
			                    "Belgium-Medgenix"
			                }
			            )
			        ),
			    SUM(Fact_Safety[ASTM-Incidents])   -- default if Area not selected
			)
			*/
		formatString: 0.00
		displayFolder: ASTM Incidents
		lineageTag: 734b9a80-ed96-465d-a56d-3bbb7720715f

	measure 'pSIF SIFs Focus' =
			
			VAR _area = SELECTEDVALUE(Bridge_CSCA_CSCI[Area])
			RETURN
			IF(
			    _area = "CSCA" || _area = "CSCI",
			    SELECTEDVALUE(Fact_Safety[pSIF SIFs Focus at our Sites - Action Past Due Closure Rate])
			)
			/*
			VAR _area = SELECTEDVALUE(Bridge_CSCA_CSCI[Area])   -- Your area field (CSCA / CSCI)
			RETURN
			SWITCH(
			    TRUE(),
			    _area = "CSCA",
			        CALCULATE(
			            AVERAGE(Fact_Safety[pSIF SIFs Focus at our Sites - Action Past Due Closure Rate]),
			            KEEPFILTERS(
			                Fact_Safety[Site name/Site UUID/Location UUID] IN {
			                    "Logistics",
			                    "Vermont (PVT)",
			                    "Michigan-Allegan (PMI)",
			                    "Wisconsin (PWI)",
			                    "Ohio (POH)",
			                    "Michigan-Grand Rapids (POC)",
			                    "New York (PNY)",
			                    "Michigan-Holland (PMH)"
			                }
			            )
			        ),
			    _area = "CSCI",
			        CALCULATE(
			            AVERAGE(Fact_Safety[pSIF SIFs Focus at our Sites - Action Past Due Closure Rate]),
			            KEEPFILTERS(
			                Fact_Safety[Site name/Site UUID/Location UUID] IN {
			                    "UK-Braunton (PUK)",
			                    "Germany-Herrenberg",
			                    "France-Plelo",
			                    "France-Laboratoire de la Mer",
			                    "Belgium-Medgenix"
			                }
			            )
			        ),
			    BLANK()   -- default if Area not selected
			)
			*/
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: pSIF SIFs Focus
		lineageTag: 32739a93-d65c-46ca-b1f9-a41d7daef7c4

	measure 'GOOD Catch Closure Rate' =
			
			VAR _area = SELECTEDVALUE(Bridge_CSCA_CSCI[Area])
			RETURN
			IF(
			    _area = "CSCA" || _area = "CSCI",
			    SELECTEDVALUE(Fact_Safety[GOOD Catch Closure Rate ])
			)
			/*
			VAR _area = SELECTEDVALUE(Bridge_CSCA_CSCI[Area])   -- Your area field (CSCA / CSCI)
			RETURN
			SWITCH(
			    TRUE(),
			    _area = "CSCA",
			        CALCULATE(
			            AVERAGE(Fact_Safety[GOOD Catch Closure Rate ]),
			            KEEPFILTERS(
			                Fact_Safety[Site name/Site UUID/Location UUID] IN {
			                    "Logistics",
			                    "Vermont (PVT)",
			                    "Michigan-Allegan (PMI)",
			                    "Wisconsin (PWI)",
			                    "Ohio (POH)",
			                    "Michigan-Grand Rapids (POC)",
			                    "New York (PNY)",
			                    "Michigan-Holland (PMH)"
			                }
			            )
			        ),
			    _area = "CSCI",
			        CALCULATE(
			            AVERAGE(Fact_Safety[GOOD Catch Closure Rate ]),
			            KEEPFILTERS(
			                Fact_Safety[Site name/Site UUID/Location UUID] IN {
			                    "UK-Braunton (PUK)",
			                    "Germany-Herrenberg",
			                    "France-Plelo",
			                    "France-Laboratoire de la Mer",
			                    "Belgium-Medgenix"
			                }
			            )
			        ),
			    BLANK()   -- default if Area not selected
			)
			*/
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: GOOD Catch Closure Rate
		lineageTag: 95652b04-3bcb-4d5f-838d-ff8d1f7bc765

	measure 'ASTM Rate PP' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([ASTM -Rate],filter_)
			RETURN
			Result
		formatString: 0
		displayFolder: ASTM Rate
		lineageTag: b43901b3-e4b7-47c1-a67c-e9fcb66bfaa0

	measure 'ASTM Incidents PP' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([ASTM Incidents],filter_)
			RETURN
			Result
		formatString: 0.00
		displayFolder: ASTM Incidents
		lineageTag: 76375e9f-83e4-447a-9b93-8952bd164f16

	measure 'ASTM Rate PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([ASTM -Rate],filter_)
			
			```
		formatString: 0
		displayFolder: ASTM Rate
		lineageTag: 9a0ccbb6-bd1d-4473-b102-1d7b1819802d

	measure 'ASTM Incidents PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([ASTM Incidents],filter_)
			
			```
		formatString: 0.00
		displayFolder: ASTM Incidents
		lineageTag: 86f8c552-91ee-42b7-a911-805c9dc945a8

	measure 'ASTM Rate MoM%' =
			
			DIVIDE(([ASTM -Rate] - [ASTM Rate PP]),[ASTM Rate PP])
		displayFolder: ASTM Rate
		lineageTag: 985c8672-f686-4606-89af-390ad91b42ed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ASTM Incidents MoM%' =
			
			DIVIDE(([ASTM Incidents] - [ASTM Incidents PP]),[ASTM Incidents PP])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: ASTM Incidents
		lineageTag: fd0bb756-27c0-4d8b-9ffc-f23153765741

	measure 'ASTM Rate YoY%' =
			
			DIVIDE(([ASTM -Rate] - [ASTM Rate PY]),[ASTM Rate PY])
		displayFolder: ASTM Rate
		lineageTag: 76281a1e-4140-4648-beb8-3d44532f81f5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ASTM Incidents YoY%' =
			
			DIVIDE(([ASTM Incidents] - [ASTM Incidents PY]),[ASTM Incidents PY])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: ASTM Incidents
		lineageTag: 0543768d-d72e-4e33-9413-9852ecb8c4db

	measure 'ASTM Rate LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [ASTM Rate PY])
			VAR Result = Sumx(Table_,[Measure])
			RETURN
			IF(
			    ISBLANK(Result) || Result = 0,
			    BLANK(),
			    DIVIDE([ASTM -Rate] - Result,Result)
			)
			```
		displayFolder: ASTM Rate
		lineageTag: 0e1573dc-5d82-457c-9186-13be1f11a51f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ASTM Incidents LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [ASTM Incidents PY])
			VAR Result = Sumx(Table_,[Measure])
			RETURN
			IF(
			    ISBLANK(Result) || Result = 0,
			    BLANK(),
			    DIVIDE([ASTM Incidents] - Result,Result)
			)
			```
		displayFolder: ASTM Incidents
		lineageTag: 247e980a-76c1-47db-a7d8-a4e1b3e0b8ae

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ASTM Rate MoM_Final' = ```
			
			VAR kpi_ = [ASTM Rate MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: ASTM Rate
		lineageTag: eabeb83a-9c94-4383-a422-1d9535661069

	measure 'ASTM Incidents MoM_Final' = ```
			
			VAR kpi_ = [ASTM Incidents MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: ASTM Incidents
		lineageTag: d6bd3445-6cb2-48d6-ab08-53658181c967

	measure 'ASTM Rate YoY_Final' = ```
			
			VAR kpi_ = [ASTM Rate YoY%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: ASTM Rate
		lineageTag: 4bc23885-9709-4936-9a31-c97a55e79b09

	measure 'ASTM Incidents YoY_Final' = ```
			
			VAR kpi_ = [ASTM Incidents YoY%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: ASTM Incidents
		lineageTag: e2f57795-127a-4351-ab7a-6cf04f103d16

	measure 'ASTM Rate LYTD_Final' = ```
			
			VAR kpi_ = [ASTM Rate LYTD]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: ASTM Rate
		lineageTag: 469ff97a-c935-43dd-aa76-72085b669a22

	measure 'ASTM Incidents LYTD_Final' = ```
			
			VAR kpi_ = [ASTM Incidents LYTD]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: ASTM Incidents
		lineageTag: b48d8ce9-339a-47d3-9db3-5e4aa94c8dd3

	measure 'ASTM Rate YTD' =
			VAR _LastMonth = MAX(Dim_Date[P_YearMonth Number])
			VAR _SelectedYear = MAX(Dim_Date[P_Year])
			RETURN
			    SUMX(
			        FILTER(
			            ALL(Dim_Date),
			            Dim_Date[P_YearMonth Number] <= _LastMonth && Dim_Date[P_Year] = _SelectedYear
			        ),
			        [ASTM -Rate]
			    )
		formatString: 0
		displayFolder: ASTM Rate
		lineageTag: f063abd2-65e9-4c90-b77b-a151aeaaac21

	measure 'ASTM Incidents YTD' =
			VAR _LastMonth = MAX(Dim_Date[P_YearMonth Number])
			VAR _SelectedYear = MAX(Dim_Date[P_Year])
			RETURN
			    SUMX(
			        FILTER(
			            ALL(Dim_Date),
			            Dim_Date[P_YearMonth Number] <= _LastMonth && Dim_Date[P_Year] = _SelectedYear
			        ),
			        [ASTM Incidents]
			    )
		formatString: 0.00
		displayFolder: ASTM Incidents
		lineageTag: 33b9d47d-15e1-4037-ba30-45fd5173e89d

	measure 'ASTM Rate Switch' = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [ASTM Rate MoM_Final],
			      "LYTD", [ASTM Rate LYTD_Final],
			      "vs YoY", [ASTM Rate YoY_Final],
			      "vs Plan", BLANK(),
			      "vs 3M avg", [ASTM Rate 3M_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: ASTM Rate
		lineageTag: 79e49ce6-788b-4dcc-99c2-54f7ad6fa671

	measure 'ASTM Incidents Switch' = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [ASTM Incidents MoM_Final],
			      "LYTD", [ASTM Incidents LYTD_Final],
			      "vs YoY", [ASTM Incidents YoY_Final],
			      "vs Plan", BLANK(),
			      "vs 3M avg", [ASTM Incidents 3M_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: ASTM Incidents
		lineageTag: 84b74531-90c5-444c-8322-d302c84c1b5a

	measure 'ASTM Rate_Color' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [ASTM Rate MoM%],
			        "LYTD", [ASTM Rate LYTD],
			        "vs YoY", [ASTM Rate YoY%],
			        "vs Plan",BLANK(),
			        "vs 3M avg", [ASTM Rate 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#1A9641",  -- green for ▼ down
			            "#D7191C"  -- red for ▲ up
			        )
		displayFolder: ASTM Rate
		lineageTag: 35eba65f-be61-444a-9993-7453d9b69d60

	measure 'ASTM Incidents_Color' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [ASTM Incidents MoM%],
			        "LYTD", [ASTM Incidents LYTD],
			        "vs YoY", [ASTM Incidents YoY%],
			        "vs Plan",BLANK(),
			        "vs 3M avg", [ASTM Incidents 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#1A9641",  -- green for ▼ down
			            "#D7191C"  -- red for ▲ up
			        )
		displayFolder: ASTM Incidents
		lineageTag: d0a53cc7-3313-422b-9255-d3de7be8a966

	measure 'ASTM Rate_Color_KPI' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [ASTM Rate MoM%],
			        "LYTD", [ASTM Rate LYTD],
			        "vs YoY", [ASTM Rate YoY%],
			        "vs Plan", BLANK(),
			        "vs 3M avg", [ASTM Rate 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489",
			        IF(
			            kpi_value < 0,
			            "#001489",  -- blue by default
			            "#D7191C"  -- red for ▲ up
			        )
			)
		displayFolder: ASTM Rate
		lineageTag: 078f8d5a-8f90-4ced-b378-dccfbb20f6cc

	measure 'ASTM Incidents_Color_KPI' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [ASTM Incidents MoM%],
			        "LYTD", [ASTM Incidents LYTD],
			        "vs YoY", [ASTM Incidents YoY%],
			        "vs Plan", BLANK(),
			        "vs 3M avg", [ASTM Incidents 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        (ISBLANK(kpi_value)), "#001489",
			        IF(
			            kpi_value < 0,
			            "#001489",  -- blue by default
			            "#D7191C"  -- red for ▲ up
			        )
			)
		displayFolder: ASTM Incidents
		lineageTag: 382a6a27-540c-4b14-863c-d858e200acd6

	measure 'Good Catch Closure Rate PP' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([GOOD Catch Closure Rate],filter_)
			RETURN
			Result
		displayFolder: GOOD Catch Closure Rate
		lineageTag: 78f57a1f-cc0f-4167-9d57-7e9f340f7d97

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'pSIF SIFs Focus PP' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([pSIF SIFs Focus],filter_)
			RETURN
			Result
		displayFolder: pSIF SIFs Focus
		lineageTag: a01cbc42-d0d2-407b-b9c1-8b3db9f488de

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Good Catch Closure Rate PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([Good Catch Closure Rate],filter_)
			
			```
		displayFolder: GOOD Catch Closure Rate
		lineageTag: 1f217f95-4f60-4d43-b91b-9d472f9c9e01

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'pSIF SIFs Focus PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([pSIF SIFs Focus],filter_)
			
			```
		displayFolder: pSIF SIFs Focus
		lineageTag: 1137988e-3082-4e30-8d19-25b49e86b7bd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Good Catch Closure Rate MoM%' =
			
			VAR Result =  [Good Catch Closure Rate] - [Good Catch Closure Rate PP]
			RETURN
			Result
		displayFolder: GOOD Catch Closure Rate
		lineageTag: 908ac8fc-2cda-41e6-98ca-aea5de897d76

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'pSIF SIFs Focus MoM%' =
			
			VAR Result =  [pSIF SIFs Focus] - [pSIF SIFs Focus PP]
			RETURN
			Result
		displayFolder: pSIF SIFs Focus
		lineageTag: 6b297c39-39d0-4243-81b3-44576f76b448

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Good Catch Closure Rate YoY%' =
			
			IF(ISBLANK([Good Catch Closure Rate PY]), BLANK(),[Good Catch Closure Rate] - [Good Catch Closure Rate PY])
		displayFolder: GOOD Catch Closure Rate
		lineageTag: 8846a2a6-c9f5-4f92-a80b-cbdf9bb5e592

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'pSIF SIFs Focus YoY%' =
			
			IF(ISBLANK([pSIF SIFs Focus PY]), BLANK(),[pSIF SIFs Focus] - [pSIF SIFs Focus PY])
		displayFolder: pSIF SIFs Focus
		lineageTag: 67cdae8e-6a9b-4755-9f42-e32de7425e31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Good Catch Closure Rate MoM_Final' = ```
			
			VAR kpi_ = [Good Catch Closure Rate MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: GOOD Catch Closure Rate
		lineageTag: 32b8b005-8c40-4976-b8cb-baa493cee773

	measure 'pSIF SIFs Focus MoM_Final' = ```
			
			VAR kpi_ = [pSIF SIFs Focus MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: pSIF SIFs Focus
		lineageTag: 83d341ab-2d27-480f-b4f9-f33de98ed3ca

	measure 'pSIF SIFs Focus YoY_Final' = ```
			
			VAR kpi_ = [pSIF SIFs Focus YoY%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: pSIF SIFs Focus
		lineageTag: 16150f7d-2341-4365-8418-0f83461d2a2a

	measure 'Good Catch Closure Plan' =
			
			VAR _area = SELECTEDVALUE(Bridge_CSCA_CSCI[Area])
			RETURN
			IF(
			    _area = "CSCA" || _area = "CSCI",
			    SELECTEDVALUE(Fact_Safety[Target - GOOD Catch Closure Rate %])
			)
			/*
			VAR _area = SELECTEDVALUE(Bridge_CSCA_CSCI[Area])   -- Your area field (CSCA / CSCI)
			RETURN
			SWITCH(
			    TRUE(),
			    _area = "CSCA",
			        CALCULATE(
			            AVERAGE(Fact_Safety[Target - GOOD Catch Closure Rate %]),
			            KEEPFILTERS(
			                Fact_Safety[Site name/Site UUID/Location UUID] IN {
			                    "Logistics",
			                    "Vermont (PVT)",
			                    "Michigan-Allegan (PMI)",
			                    "Wisconsin (PWI)",
			                    "Ohio (POH)",
			                    "Michigan-Grand Rapids (POC)",
			                    "New York (PNY)",
			                    "Michigan-Holland (PMH)"
			                }
			            )
			        ),
			    _area = "CSCI",
			        CALCULATE(
			            AVERAGE(Fact_Safety[Target - GOOD Catch Closure Rate %]),
			            KEEPFILTERS(
			                Fact_Safety[Site name/Site UUID/Location UUID] IN {
			                    "UK-Braunton (PUK)",
			                    "Germany-Herrenberg",
			                    "France-Plelo",
			                    "France-Laboratoire de la Mer",
			                    "Belgium-Medgenix"
			                }
			            )
			        ),
			    BLANK()   -- default if Area not selected
			)
			*/
		displayFolder: GOOD Catch Closure Rate
		lineageTag: 1e248639-e2d7-420b-b338-901af65a1206

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'pSIF SIFs Focus Plan' = ```
			
			VAR _area = SELECTEDVALUE(Bridge_CSCA_CSCI[Area])   -- Your area field (CSCA / CSCI)
			RETURN
			SWITCH(
			    TRUE(),
			    _area = "CSCA",
			        CALCULATE(
			            AVERAGE(Fact_Safety[Target - pSIF SIFs Focus at our Sites - Action Past Due Closure Rate]),
			            KEEPFILTERS(
			                Fact_Safety[Site name/Site UUID/Location UUID] IN {
			                    "Logistics",
			                    "Vermont (PVT)",
			                    "Michigan-Allegan (PMI)",
			                    "Wisconsin (PWI)",
			                    "Ohio (POH)",
			                    "Michigan-Grand Rapids (POC)",
			                    "New York (PNY)",
			                    "Michigan-Holland (PMH)"
			                }
			            )
			        ),
			    _area = "CSCI",
			        CALCULATE(
			           AVERAGE(Fact_Safety[Target - pSIF SIFs Focus at our Sites - Action Past Due Closure Rate]),
			            KEEPFILTERS(
			                Fact_Safety[Site name/Site UUID/Location UUID] IN {
			                    "UK-Braunton (PUK)",
			                    "Germany-Herrenberg",
			                    "France-Plelo",
			                    "France-Laboratoire de la Mer",
			                    "Belgium-Medgenix"
			                }
			            )
			        ),
			    BLANK()   -- default if Area not selected
			)
			
			```
		displayFolder: pSIF SIFs Focus
		lineageTag: ac7f594f-63ea-4aae-847a-8ad356478892

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Good Catch Closure Rate Target Diff%' = [GOOD Catch Closure Rate] - [Good Catch Closure Plan]
		displayFolder: GOOD Catch Closure Rate
		lineageTag: 2b6c5d4e-7ab3-4bc4-a002-43f4f4c1dcce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'pSIF SIFs Focus Target Diff%' = [pSIF SIFs Focus] - [pSIF SIFs Focus Plan]
		displayFolder: pSIF SIFs Focus
		lineageTag: 970817dd-a4ca-4394-b3ab-008c6f41bf46

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Good Catch Closure Rate Target Final' = ```
			
			VAR kpi_ =  [Good Catch Closure Rate Target Diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: GOOD Catch Closure Rate
		lineageTag: ed1a90ea-4267-469f-b702-a8825661a124

	measure 'pSIF SIFs Focus Target Final' = ```
			
			VAR kpi_ =  [pSIF SIFs Focus Target Diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: pSIF SIFs Focus
		lineageTag: 72957c12-418c-406a-9167-3ac658e2b0c8

	measure 'Good Catch Closure Rate Switch' = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Good Catch Closure Rate MoM_Final],
			      "LYTD", BLANK(),
			      "vs YoY", [Good Catch Closure Rate YoY_Final],
			      "vs Plan", [Good Catch Closure Rate Target Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: GOOD Catch Closure Rate
		lineageTag: 402af690-e9d2-406e-9bc3-5059e17a4c82

	measure 'Good Catch Closure Rate YoY_Final' = ```
			
			VAR kpi_ = [Good Catch Closure Rate YoY%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: GOOD Catch Closure Rate
		lineageTag: 54f152cc-9723-46cb-918e-aa54cc3a6952

	measure 'pSIF SIFs Focus Switch' = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [pSIF SIFs Focus MoM_Final],
			      "LYTD", BLANK(),
			      "vs YoY", [pSIF SIFs Focus YoY_Final],
			      "vs Plan", [pSIF SIFs Focus Target Final],
			      "vs 3M avg", [pSIF SIFs Focus 3M_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: pSIF SIFs Focus
		lineageTag: b23dfdcf-615a-449b-9369-f63f9253b0bf

	measure 'Good Catch Closure Rate_Color' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Good Catch Closure Rate MoM%],
			        "LYTD", BLANK(),
			        "vs YoY", [Good Catch Closure Rate YoY%],
			        "vs Plan", [Good Catch Closure Rate Target Diff%],
			        "vs 3M avg", [Good Catch Closure 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value > 0,
			            "#1A9641",  -- green for ▲ up
			            "#D7191C"  -- red for ▼ down
			        )
		displayFolder: GOOD Catch Closure Rate
		lineageTag: 5f493a0e-7088-47bd-a95e-62b3a7cf0835

	measure 'Good Catch Closure Rate_Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Good Catch Closure Rate MoM%],
			        "LYTD", BLANK(),
			        "vs YoY", [Good Catch Closure Rate YoY%],
			        "vs Plan", [Good Catch Closure Rate Target Diff%],
			        "vs 3M avg", [Good Catch Closure 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value > 0,
			            "#001489",  -- blue by default
			            "#D7191C"  -- red for ▼ down
			        )
			)
			```
		displayFolder: GOOD Catch Closure Rate
		lineageTag: 87af3950-c37c-4254-b1fc-f6d6ebde35ff

	measure 'pSIF SIFs Focus_Color' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [pSIF SIFs Focus MoM%],
			        "LYTD", BLANK(),
			        "vs YoY", [pSIF SIFs Focus YoY%],
			        "vs Plan", [pSIF SIFs Focus Target Diff%],
			        "vs 3M avg", [pSIF SIFs 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value > 0,
			            "#1A9641",  -- green for ▲ up
			            "#D7191C"  -- red for ▼ down
			        )
		displayFolder: pSIF SIFs Focus
		lineageTag: 4916905c-ec1d-4cf5-9f9d-a1a9fdb8e953

	measure 'pSIF SIFs Focus_Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [pSIF SIFs Focus MoM%],
			        "LYTD", BLANK(),
			        "vs YoY", [pSIF SIFs Focus YoY%],
			        "vs Plan", [pSIF SIFs Focus Target Diff%],
			        "vs 3M avg", [pSIF SIFs 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value > 0,
			            "#001489",  -- blue by default
			            "#D7191C"  -- red for ▼ down
			        )
			)
			```
		displayFolder: pSIF SIFs Focus
		lineageTag: aff6b7fc-7709-4d45-92e8-b16aaa302526

	measure 'SSSO: Obso Conv_switch_target' = ```
			SWITCH(
			    MIN( Par_Targets[Rank] ),
			    
			    1, [SSSO: Obso Conv_APN_Base],
			    2, [SSSO: Obso Conv_AFX_Base]
			)
			```
		displayFolder: SSSO Obs linked to Conv
		lineageTag: 228f7bb7-f5e7-4310-b5c2-931e50fc1853

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO: Salvage & Obs_switch_target' = ```
			SWITCH(
			    MIN( Par_Targets[Rank] ),
			    
			    1, [SSSO: Salvage & Obs_APN_Base],
			    2, [SSSO: Salvage & Obs_AFX_Base]
			)
			```
		displayFolder: SSSO Salvage & Obs
		lineageTag: 9c6125fc-f7e1-4d86-9dcd-c63967e1922e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO: Scrap-off_switch_target' = ```
			SWITCH(
			    MIN( Par_Targets[Rank] ),
			    
			    1, [SSSO: Scrap-off APN_Base],
			    2, [SSSO: Scrap-off F66_Base]
			)
			```
		displayFolder: SSSO Scrap-Off
		lineageTag: b9196331-6ada-4670-b13f-552d4102c1a5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure COGS_switch_target = ```
			SWITCH(
			    MIN( Par_Targets[Rank] ),
			    
			    1, [COGS_APN_Base],
			    2, [COGS_AFX_Base]
			)
			```
		displayFolder: COGS
		lineageTag: 1f8ff73e-e844-4252-ade7-b3977c036560

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Logistics on Net Sales_switch_target' = ```
			SWITCH(
			    MIN( Par_Targets[Rank] ),
			    
			    1, [Total Logistics on Net Sales_APN_Base],
			    2, [Total Logistics on Net Sales_AFX_Base]
			)
			```
		displayFolder: Logistic vs Net Sales
		lineageTag: 979c8f28-5b93-4503-bab3-0b3c8d4e9cea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Logistics_switch_target' = ```
			SWITCH(
			    MIN( Par_Targets[Rank] ),
			    
			    1, [Total Logistics Plan],
			    2, [Total Logistics Flex]
			)
			```
		displayFolder: Logistic
		lineageTag: f850e074-344c-4f36-9d30-3cc520a69f60

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Distribution on COGS_switch_target' = ```
			SWITCH(
			    MIN( Par_Targets[Rank] ),
			    
			    1, [Total Distribution on COGS_APN_Base],
			    2, [Total Distribution on COGS_AFX_Base]
			)
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Distribution on COGS
		lineageTag: b5207a45-0c0c-4f06-95b7-3e14f12f7945

	measure 'Gross PPV_switch_target' = ```
			SWITCH(
			    MIN( Par_Targets[Rank] ),
			    
			    1, [Gross PPV APN_base]
			)
			
			```
		displayFolder: Gross PPV
		lineageTag: 98155d7f-f2de-45f0-bca6-aee03b86fe95

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Sales_switch_target' = ```
			SWITCH(
			    MIN( Par_Targets[Rank] ),
			    
			    1, [Net Sales_APN_Base],
			    2, [Net Sales_AFX_Base]
			)
			```
		formatString: 0.0
		displayFolder: Net Sales
		lineageTag: e1e8814e-2cce-4418-a5e1-82a0947a54c6

	measure 'Operating Income_switch_target' = ```
			SWITCH(
			    MIN( Par_Targets[Rank] ),
			    
			    1, [Operating Income APN_Base]
			
			)
			```
		displayFolder: Operating Income
		lineageTag: eebd4e03-12d1-4184-9631-659c968196d0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Switch_Plan_Flex_OI = ```
			SWITCH(
			    VALUES( Operating_Parameter[Operating_Parameter] ),
			    "SSSO: Salvage & Obs", [SSSO: Salvage & Obs_switch_target],
			    "SSSO: Obs linked to Conv", [SSSO: Obso Conv_switch_target],
			    "SSSO: Scrap-Off", [SSSO: Scrap-off_switch_target],
			    "Net Sales", [Net Sales_switch_target],
			    "COGS", [COGS_switch_target],
			    "Distribution to COGS", [Total Distribution on COGS_switch_target],
			    "% Logistics vs Net Sales", [Total Logistics on Net Sales_switch_target],
			    "Customer Fines", [Customer Fines Target],
			    "Operating Income", [Operating Income_switch_target],
			    "Gross PPV", [Gross PPV APN_base],
			    "Net POV", [Net POV APN_base],
			    "ABP Variance", [ABP Variance_APN_Base]
			)
			
			```
		displayFolder: Switch Measures
		lineageTag: 441cc06b-c30b-4e26-9059-e09b9914dbd4

		formatStringDefinition =
				SWITCH(
				    SELECTEDVALUE(Operating_Parameter[Parameter Name]),
				    "SSSO: Salvage & Obs", "#,0",
				    "SSSO: Scrap-Off", "#,0",
				    "COGS", "#,0",
				    "Distribution to COGS", "0.0%",
				    "Operating Income", "#,0",
				    "Net POV", "#,0",
				    "SSSO: Obs linked to Conv","#,0",
				    "Net Sales", "#,0",
				    "% Logistics vs Net Sales", "0.0%",
				    "Customer Fines", "#,0",
				    "Gross PPV","#,0",
				    "ABP Variance","#,0"
				)

	measure 'Good Catch Closure Rate YTD' = TOTALYTD([GOOD Catch Closure Rate],Dim_Date[Date])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: GOOD Catch Closure Rate
		lineageTag: 276a6559-645f-43b0-977b-472a7b6daf01

	measure 'pSIF SIFs Focus YTD' = TOTALYTD([pSIF SIFs Focus],Dim_Date[Date])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: pSIF SIFs Focus
		lineageTag: eb48d3b3-f8c8-4a88-9d4c-16f0429ba44a

	measure 'OEE Focus Lines%' = CALCULATE( [OEE%], KEEPFILTERS( Dim_Locations[Focus Lines] = "Y" ) )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: OEE FOCUS LINES
		lineageTag: 4977f4ef-62ba-4ef9-b68f-6859f2ffb417

	measure 'OEE FOCUS LINES LYTD' =
			VAR LYTD = [Availability LYTD] * [Performance LYTD] * [Quality LYTD]
			
			RETURN
			[OEE FOCUS LINES%] - LYTD
		displayFolder: OEE FOCUS LINES
		lineageTag: f7a88d96-9c8f-46ff-a819-1ce75c5c1432

	measure 'OEE FOCUS LINES% LYTD_Final' =
			VAR kpi_ =  [OEE FOCUS LINES LYTD]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: OEE FOCUS LINES
		lineageTag: f8314130-9af7-463e-9739-55a2f39ef6d5

	measure 'OEE FOCUS LINES% MoM%' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Net_PM = Calculate([OEE FOCUS LINES%],filter_)
			VAR Result = [OEE FOCUS LINES%] - Net_PM
			RETURN
			Result
		displayFolder: OEE FOCUS LINES
		lineageTag: 5b0169dc-e1ea-4e32-a1d0-49c053a19e21

	measure 'OEE FOCUS LINES% MoM_Final' = ```
			VAR kpi_ =  [OEE FOCUS LINES% MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: OEE FOCUS LINES
		lineageTag: 14534fa2-6071-47f8-80e7-071c77d2efb4

	measure 'OEE FOCUS LINES% PP' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([OEE FOCUS LINES%],filter_)
			
			RETURN
			Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: OEE FOCUS LINES
		lineageTag: 7ce98a27-dd8d-4702-89a8-322829538e0e

	measure 'OEE FOCUS LINES% PY' =
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([OEE FOCUS LINES%],filter_)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: OEE FOCUS LINES
		lineageTag: 213a6af3-3b6e-498e-ac0c-ee08093304f2

	measure 'OEE FOCUS LINES% YoY%' = [OEE FOCUS LINES%] - [OEE FOCUS LINES% PY]
		displayFolder: OEE FOCUS LINES
		lineageTag: 0e3b100a-95db-4b9a-96fc-b08b39171dcb

	measure 'OEE FOCUS LINES% YoY_Final' =
			VAR kpi_ =  [OEE FOCUS LINES% YoY%]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
		displayFolder: OEE FOCUS LINES
		lineageTag: 57ce2d91-91d1-4b1d-b081-a4fddb5984fa

	measure 'OEE FOCUS LINES% YTD' = TOTALYTD([OEE FOCUS LINES%],Dim_Date[Date])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: OEE FOCUS LINES
		lineageTag: 3aaadbfc-b805-42f8-93cf-79e25cccbc98

	measure 'OEE FOCUS LINES_Color' =
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [OEE FOCUS LINES% MoM%],
			        "YTD", [OEE FOCUS LINES% YTD],
			        "vs YoY", [OEE FOCUS LINES% YoY%],
			        "vs Plan", [OEE Target diff%],
			        "LYTD", [OEE FOCUS LINES LYTD],
			        BLANK()
			    )
			
			RETURN
			IF(
			        _sel = "YTD",
			        "#000000",  -- Always black for YTD
			    IF(
			        ISBLANK(kpi_value), "#000000",  -- black for blank
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#1A9641"   -- green for ▲ up
			        )
			    )
			)
		displayFolder: OEE FOCUS LINES
		lineageTag: 2f05366d-aace-45ff-963b-9a584c736fb1

	measure 'OEE FOCUS LINES_Color_KPI' =
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [OEE FOCUS LINES% MoM%],
			        "YTD", [OEE FOCUS LINES% YTD],
			        "vs YoY", [OEE FOCUS LINES% YoY%],
			        "vs Plan", [OEE Target diff%],
			        "LYTD", [OEE FOCUS LINES LYTD],
			        BLANK()
			    )
			
			RETURN
			IF(
			        _sel = "YTD",
			        "#000000",  -- Always black for YTD
			    IF(
			        ISBLANK(kpi_value), "#001489",  -- black for blank
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#001489"   -- green for ▲ up
			        )
			    )
			)
		displayFolder: OEE FOCUS LINES
		lineageTag: 0da0daea-8c80-42bc-9762-41b9e81e1a93

	measure 'FA% Lag4 Target' =
			
			Var tar = CALCULATE(MAX(Fact_Target[Target]),KEEPFILTERS(Fact_Target[KPI_Name] = "Forecast Accuracy Lag4 (%)"),
			                KEEPFILTERS(Fact_Target[Area] = "CSCA"))
			RETURN
			DIVIDE(tar,100)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 931c2e10-f6f1-4891-b46f-48e65a9d66a6

	measure 'Cust Fine Validation' = ```
			
			VAR _area = SELECTEDVALUE(Bridge_CSCA_CSCI[Area])   -- Your area field (CSCA / CSCI)
			RETURN
			SWITCH(
			    TRUE(),
			    _area = "CSCA", CALCULATE( SUM(Fact_Customer_Fines[Split Amount]) ),
			    _area = "CSCI", BLANK(),
			    SUM(Fact_Customer_Fines[Split Amount])   -- default if Area not selected
			)
			
			```
		displayFolder: Customer Fines
		lineageTag: b2748f6b-c6b1-432e-afe1-10ba2ce7d4b1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OTCD Validation' = ```
			
			
			VAR _area = SELECTEDVALUE(Bridge_CSCA_CSCI[Area])
			RETURN
			IF(
			    NOT ISBLANK(_area),
			    CALCULATE(
			        DIVIDE(
			            SUM(Fact_Quality[Deviation: Total Closed on Time in Period]),
			            SUM(Fact_Quality[Deviation: Total Closed in Period])
			        ),
			        KEEPFILTERS( FILTER( Bridge_Site_Area, Bridge_Site_Area[Area] = _area ) )
			    ),
			    DIVIDE(
			        SUM(Fact_Quality[Deviation: Total Closed on Time in Period]),
			        SUM(Fact_Quality[Deviation: Total Closed in Period])
			    )
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: On Time Closure of Deviations
		lineageTag: 45f16e4c-e388-4644-8984-e80fb94a3d9c

	measure 'CAPA Validation' = ```
			
			VAR _area = SELECTEDVALUE(Bridge_CSCA_CSCI[Area])
			VAR kpi_ =
			    IF(
			        NOT ISBLANK(_area),
			        CALCULATE(
			            DIVIDE(
			                SUM(Fact_Quality[CAPA: Total Closed on Time in Period]),
			                SUM(Fact_Quality[CAPA: Total Closed In Period])
			            ),
			            KEEPFILTERS( FILTER( Bridge_Site_Area, Bridge_Site_Area[Area] = _area ) )
			        ),
			        DIVIDE(
			            SUM(Fact_Quality[CAPA: Total Closed on Time in Period]),
			            SUM(Fact_Quality[CAPA: Total Closed In Period])
			        )
			    )
			RETURN
			IF(ISBLANK(kpi_), BLANK(), kpi_)
			
			// VAR _area = SELECTEDVALUE(Bridge_CSCA_CSCI[Area])
			// RETURN
			// IF(
			//     NOT ISBLANK(_area),
			//     CALCULATE(
			//         DIVIDE([CAPA Closed on Time],[CAPA Closed]),
			//         KEEPFILTERS( FILTER( Bridge_Site_Area, Bridge_Site_Area[Area] = _area ) )
			//     ),
			//     DIVIDE([CAPA Closed on Time],[CAPA Closed])
			// )
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CAPA Completion Rate
		lineageTag: 5c598059-4405-406e-bd02-34f6ced844ad

	measure 'Critical/Major Obs Validation' = ```
			
			VAR _area = SELECTEDVALUE(Bridge_CSCA_CSCI[Area])
			RETURN
			IF(
			    NOT ISBLANK(_area),
			    CALCULATE(
			        SUM(Fact_Quality[Critical_Major_Obs_Quarter]),
			        KEEPFILTERS( FILTER( Bridge_Site_Area, Bridge_Site_Area[Area] = _area ) )
			    ),
			    SUM(Fact_Quality[Critical_Major_Obs_Quarter])
			)
			
			```
		formatString: 0
		displayFolder: Critical or Major Obs
		lineageTag: d193df14-5324-4660-8f12-1ad7850d7836

	measure 'RFT% Validation' = ```
			
			VAR _area = SELECTEDVALUE(Bridge_CSCA_CSCI[Area])   -- CSCA / CSCI / blank
			VAR kpi_ =
			    IF(
			        NOT ISBLANK(_area),
			        CALCULATE(
			            DIVIDE(
			                SUM(Fact_Quality[RFT: Total # of Batches with Deviations]),
			                SUM(Fact_Quality[RFT: Total # of Finished Goods Batches])
			            ),
			            KEEPFILTERS( FILTER( Bridge_Site_Area, Bridge_Site_Area[Area] = _area ) )
			        ),
			        DIVIDE(
			            SUM(Fact_Quality[RFT: Total # of Batches with Deviations]),
			            SUM(Fact_Quality[RFT: Total # of Finished Goods Batches])
			        )
			    )
			RETURN
			IF(ISBLANK(kpi_), BLANK(), 1 - kpi_)
			
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: RFT
		lineageTag: bbb18c50-b472-4522-8626-5bcfaf761aae

	measure 'Bias Target CSCA L2' =
			
			Var tar = CALCULATE(MAX(Fact_Target[Target]),KEEPFILTERS(Fact_Target[KPI_Name] = "Bias Lag2 (%)"))
			RETURN
			DIVIDE(tar,100)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Bias CSCA
		lineageTag: 1aa03611-558b-42a1-97d1-df5227df1f77

	measure 'Bias Target CSCA L4' =
			
			Var tar = CALCULATE(MAX(Fact_Target[Target]),KEEPFILTERS(Fact_Target[KPI_Name] = "Bias Lag4 (%)"),
			            KEEPFILTERS(Fact_Target[Area] = "CSCA"))
			RETURN
			DIVIDE(tar,100)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Bias CSCA
		lineageTag: 704b57b2-6ed6-413c-aad6-976401d3069c

	measure 'LR FA CSCA' =
			
			MAX(Fact_Forecast_Accuracy[Last Refreshed])
		formatString: dd-mm-yy hh:nn AM/PM
		displayFolder: Refresh Details
		lineageTag: d8e14423-3d26-4883-aa4d-a7c5223f3b3a

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'LR GR' = ```
			
			MAX ( 'Fact_Group_Reporting'[Last Refreshed] )
			
			```
		formatString: dd-mm-yy hh:nn AM/PM
		displayFolder: Refresh Details
		lineageTag: 4ba192a6-9af1-48c5-a573-f85ae7877740

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'LR OEE' = ```
			
			MAX ( 'Fact_OEE'[Refresh DateTime] )
			
			```
		formatString: dd-mm-yy hh:nn AM/PM
		displayFolder: Refresh Details
		lineageTag: 0188ad69-0511-463b-8831-8ba95af04bdc

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'LR Cust Fines' = ```
			
			MAX ( 'Fact_Customer_Fines'[Last Refreshed])
			
			```
		formatString: dd-mm-yy hh:nn AM/PM
		displayFolder: Refresh Details
		lineageTag: c6e21fab-82d7-48b2-99b1-60fd622142a3

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'LR CFR' = MAX('Fact_CFR'[Last Refreshed])
		formatString: General Date
		displayFolder: Refresh Details
		lineageTag: aa9b5a4d-47eb-49fd-a5c0-c7c492c62aba

	measure 'Good Catch Closure Plan_Target' = AVERAGE(Fact_Safety[Target - GOOD Catch Closure Rate %])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: GOOD Catch Closure Rate
		lineageTag: 795b235d-a918-4eb1-a9a8-6007f7300c62

	measure 'pSIF SIFs Focus Plan_Target' = AVERAGE(Fact_Safety[Target - pSIF SIFs Focus at our Sites - Action Past Due Closure Rate])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: pSIF SIFs Focus
		lineageTag: ec66cb95-e0c1-4f6a-bd0a-70d7b3a8491b

	measure 'Customer Fines Target New' = CALCULATE(SUM(Fact_Target[Target_Cust/12]), KEEPFILTERS(Fact_Target[KPI_Name] = "Customer Fines ($)"))
		formatString: #,0
		displayFolder: Customer Fines
		lineageTag: 1271ed04-2aba-47a8-b2fb-e05d836713ff

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'PWS Benefits' = SUM(Fact_PWS[Actual])
		formatString: 0
		displayFolder: PWS
		lineageTag: a422add8-f02f-4677-9dfd-97f06c1bff66

	measure 'PWS Benefits Plan' = SUM(Fact_PWS[Plan])
		formatString: 0
		displayFolder: PWS
		lineageTag: a259e30e-fb21-40ce-a9ab-2c7bebafcc77

	measure 'PWS Benefits PP' =
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -1 )
			VAR Result = Calculate([PWS Benefits],filter_)
			RETURN
			Result
		formatString: 0
		displayFolder: PWS
		lineageTag: 06739195-ab67-492c-b5e9-13eb1be7df98

	measure 'PWS Benefits PY' = ```
			
			VAR alldate_ = all(Dim_Date)
			VAR YearPeriodSeq_ = value( MAX(Dim_Date[YearPeriodSeq]) )
			VAR Filter_ = Filter(alldate_, Dim_Date[YearPeriodSeq] = YearPeriodSeq_ -12 )
			
			RETURN
			Calculate([PWS Benefits],filter_)
			
			```
		formatString: 0
		displayFolder: PWS
		lineageTag: de19efb0-1a84-4a45-b5cc-5b5924d7071c

	measure 'PWS Benefits LYTD' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [PWS Benefits PY])
			VAR Result = Sumx(Table_,[Measure])
			RETURN
			IF(
			    ISBLANK(Result) || Result = 0,
			    BLANK(),
			    DIVIDE([PWS Benefits] - Result,Result)
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: PWS
		lineageTag: a2f1d752-7820-4794-93ce-56d15bbb9e55

	measure 'PWS Benefits MoM%' =
			
			DIVIDE(([PWS Benefits] - [PWS Benefits PP]),[PWS Benefits PP])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: PWS
		lineageTag: 7d49cb26-b2d8-4de2-bf41-d62bf422c2fd

	measure 'PWS Benefits YoY%' =
			
			DIVIDE(([PWS Benefits] - [PWS Benefits PY]),[PWS Benefits PY])
		displayFolder: PWS
		lineageTag: e8865023-fdaa-479a-a96b-b3b673442996

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PWS Benefits YTD' =
			VAR _LastMonth = MAX(Dim_Date[P_YearMonth Number])
			VAR _SelectedYear = MAX(Dim_Date[P_Year])
			RETURN
			    SUMX(
			        FILTER(
			            ALL(Dim_Date),
			            Dim_Date[P_YearMonth Number] <= _LastMonth && Dim_Date[P_Year] = _SelectedYear
			        ),
			        [PWS Benefits]
			    )
		formatString: 0
		displayFolder: PWS
		lineageTag: fb0774ee-c91e-461c-ae2a-c06056cdf3c3

	measure 'PWS Benefits MoM_Final' = ```
			
			VAR kpi_ = [PWS Benefits MoM%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: PWS
		lineageTag: 05554ce2-a647-4311-93c7-79b1c95eb00f

	measure 'PWS Benefits YoY_Final' = ```
			
			VAR kpi_ = [PWS Benefits YoY%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: PWS
		lineageTag: 3f6f3ab7-3ac6-4e9e-a37f-1aac320cefda

	measure 'PWS Benefits LYTD_Final' = ```
			
			VAR kpi_ = [PWS Benefits LYTD]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: PWS
		lineageTag: fcf48894-5096-4a9e-95da-cd943bea4e66

	measure 'PWS Benefits_APN' =
			
			VAR Plan = [PWS Benefits Plan]
			RETURN
			DIVIDE([PWS Benefits] - Plan,Plan)
		displayFolder: PWS
		lineageTag: a5893e91-0607-4263-8136-f19c940a7d73

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PWS Benefits_APN_Final' =
			
			VAR kpi_ = [PWS Benefits_APN]
			RETURN
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			)
		displayFolder: PWS
		lineageTag: d8a22ccd-14c8-4abb-a60c-fec7a43e43d6

	measure 'PWS Benefits Switch' = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [PWS Benefits MoM_Final],
			      "LYTD", [PWS Benefits LYTD_Final],
			      "vs YoY", [PWS Benefits YoY_Final],
			      "vs Plan", [PWS Benefits_APN_Final],
			      "vs 3M avg", [PWS Benefits 3M_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: PWS
		lineageTag: 5010020d-9e6c-4d3d-8917-ae1df6976e25

	measure 'PWS Benefits_Color' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [PWS Benefits MoM%],
			        "LYTD", [PWS Benefits LYTD],
			        "vs YoY", [PWS Benefits YoY%],
			        "vs Plan",[PWS Benefits_APN],
			        "vs 3M avg", [PWS 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value > 0,
			            "#1A9641",  -- green for ▼ down
			            "#D7191C"  -- red for ▲ up
			        )
		displayFolder: PWS
		lineageTag: 153fa370-3a56-4c10-b3cb-da2003d85629

	measure 'PWS Benefits_Color_KPI' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [PWS Benefits MoM%],
			        "LYTD", [PWS Benefits LYTD],
			        "vs YoY", [PWS Benefits YoY%],
			        "vs Plan", [PWS Benefits_APN],
			        "vs 3M avg", [PWS 3M_diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489",
			        IF(
			            kpi_value > 0,
			            "#001489",  -- blue by default
			            "#D7191C"  -- red for ▲ up
			        )
			)
		displayFolder: PWS
		lineageTag: 028fa8d9-0d6c-4195-a13a-0d5773706a44

	measure 'LR Cust Fines Color' = ```
			
			VAR LastRefreshed = [LR Cust Fines]
			RETURN
			IF (
			    DATEVALUE ( LastRefreshed ) >= TODAY () - 2,
			    "#001489",   -- Blue (within 2 days)
			    "#D7191C"    -- Red (older than 2 days)
			)
			
			```
		displayFolder: Refresh Details
		lineageTag: 844b7452-5755-4da8-8ae2-e91558b574ba

	measure 'LR CFR Color' = ```
			
			VAR LastRefreshed = [LR CFR]
			RETURN
			IF (
			    DATEVALUE ( LastRefreshed ) >= TODAY () - 2,
			    "#001489",   -- Blue (within 2 days)
			    "#D7191C"    -- Red (older than 2 days)
			)
			
			```
		displayFolder: Refresh Details
		lineageTag: f21eb78b-91e0-4831-9ca0-62ce4a1098f2

	measure 'LR OEE Color' = ```
			
			VAR LastRefreshed = [LR OEE]
			RETURN
			IF (
			    DATEVALUE ( LastRefreshed ) >= TODAY () - 2,
			    "#001489",   -- Blue (within 2 days)
			    "#D7191C"    -- Red (older than 2 days)
			)
			
			```
		displayFolder: Refresh Details
		lineageTag: 3203e73b-932b-4d6c-9340-89690ddda779

	measure 'LR GR Color' = ```
			
			VAR LastRefreshed = [LR GR]
			RETURN
			IF (
			    DATEVALUE ( LastRefreshed ) >= TODAY () - 2,
			    "#001489",   -- Blue (within 2 days)
			    "#D7191C"    -- Red (older than 2 days)
			)
			
			```
		displayFolder: Refresh Details
		lineageTag: 788d4c25-21a5-4320-8eed-48236be6dee0

	measure 'LR FA CSCA Color' = ```
			
			VAR LastRefreshed = [LR FA CSCA]
			RETURN
			IF (
			    DATEVALUE ( LastRefreshed ) >= TODAY () - 2,
			    "#001489",   -- Blue (within 2 days)
			    "#D7191C"    -- Red (older than 2 days)
			)
			
			```
		displayFolder: Refresh Details
		lineageTag: 989afaaa-0921-4300-93b3-34df8747d57c

	measure 'Last Refresh' = MAX('Last Refresh'[Date Last Refreshed])
		formatString: dd-mm-yyyy hh:nn AM/PM
		displayFolder: Misc
		lineageTag: 9723f24b-a170-4f51-bff8-dd1906d96cd2

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'LR DPO/DSO' = ```
			
			MAX ( 'Fact_DSO_DPO_ABP'[Last Refresh])
			
			```
		formatString: dd-mm-yyyy hh:nn AM/PM
		displayFolder: Refresh Details
		lineageTag: 073ffd35-3733-4e71-8aed-0a160db55aee

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'LR DPO/DSO Color' = ```
			
			VAR LastRefreshed = [LR DPO/DSO]
			RETURN
			IF (
			    DATEVALUE ( LastRefreshed ) >= TODAY () - 2,
			    "#001489",   -- Blue (within 2 days)
			    "#D7191C"    -- Red (older than 2 days)
			)
			
			```
		displayFolder: Refresh Details
		lineageTag: 50e4a805-2151-4aa1-b0a8-ce22a282656d

	measure 'COGS Actual LYTD_base' = ```
			
			VAR Table_ = 
			ADDCOLUMNS(
			Summarize(Dim_Date,Dim_Date[P_YearPeriod]), "Measure", [COGS Actual PY])
			VAR Result = Sumx(Table_,[Measure])
			return
			Result
			```
		displayFolder: Distribution on COGS
		lineageTag: d550c92f-1485-4552-b5cb-dbcc7adf91bc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LR Logistics' = ```
			
			MAX ( 'Fact_Logistics'[Last Refreshed Date])
			
			```
		formatString: dd-mm-yyyy hh:nn AM/PM
		displayFolder: Refresh Details
		lineageTag: 09924365-1b2b-46ce-913c-0f1592808901

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'LR Logistics Color' = ```
			
			VAR LastRefreshed = [LR Logistics]
			RETURN
			IF (
			    DATEVALUE ( LastRefreshed ) >= TODAY () - 2,
			    "#001489",   -- Blue (within 2 days)
			    "#D7191C"    -- Red (older than 2 days)
			)
			
			```
		displayFolder: Refresh Details
		lineageTag: ee1e0cbc-3b08-4b3f-8bb5-c2db2a09852a

	measure 'ABP Variance Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [ABP Variance]
			    )
			RETURN
			    Last3Avg
		displayFolder: ABP Variance
		lineageTag: e373edf5-1297-407c-ad8d-cf57761611f4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ASTM Incidents Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [ASTM Incidents]
			    )
			RETURN
			    Last3Avg
		displayFolder: ASTM Incidents
		lineageTag: 34800e2d-ea6c-49c3-97fb-d77716425333

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ASTM Rate Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq] )
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [ASTM -Rate]
			    )
			
			RETURN
			    Last3Avg
		displayFolder: ASTM Rate
		lineageTag: c7a7a7b2-a6e8-400b-abcc-f32bfe46850a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bias Lag2 Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [Bias% Lag 2]
			    )
			RETURN
			    Last3Avg
		displayFolder: Bias CSCA
		lineageTag: fb6bf12d-89f0-401b-a012-4fd270b55362

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bias Lag4 Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [Bias% Lag 4]
			    )
			RETURN
			    Last3Avg
		displayFolder: Bias CSCA
		lineageTag: 4b72dd0d-602c-4b83-ad04-7a6927f2963e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CAPA Completion Rate Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [CAPA Completion Rate]
			    )
			RETURN
			    Last3Avg
		displayFolder: CAPA Completion Rate
		lineageTag: bbdaf3c3-1960-4fef-b99f-d9265932a67f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CFR Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [CFR]
			    )
			RETURN
			    Last3Avg
		displayFolder: CFR
		lineageTag: 964fe436-5042-4ad1-b395-2273983859a8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'COGS Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [COGS Actual]
			    )
			RETURN
			    Last3Avg
		displayFolder: COGS
		lineageTag: 6846964b-4ab2-4254-adbf-98d522e25338

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Critical or Major Obs Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [Critical or Major Observations]
			    )
			RETURN
			    Last3Avg
		displayFolder: Critical or Major Obs
		lineageTag: b7bea14e-5aa6-4550-8052-43985531eac1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Customer Fines Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [Customer Fines]
			    )
			RETURN
			    Last3Avg
		displayFolder: Customer Fines
		lineageTag: c11bb064-1847-493b-99eb-714383cb3124

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DIO Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [DIO]
			    )
			RETURN
			    Last3Avg
		displayFolder: DIO
		lineageTag: c55cb907-4db6-4170-b48a-47aad6b71f45

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Distribution on COGS Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [Total Distribution on COGS Actual]
			    )
			RETURN
			    Last3Avg
		displayFolder: Distribution on COGS
		lineageTag: 62f96b42-416a-414b-b0ad-f3dd28e6a415

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DPO Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [DPO]
			    )
			RETURN
			    Last3Avg
		displayFolder: DPO
		lineageTag: 683647f1-1c2c-47f4-8b33-86038de4f1ad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DSO Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [DSO]
			    )
			RETURN
			    Last3Avg
		displayFolder: DSO
		lineageTag: 6bd09869-5d68-466e-b085-d6367b150779

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Expired Inventory Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [Expired Inventory]
			    )
			RETURN
			    Last3Avg
		displayFolder: Expired Inventory
		lineageTag: 8b0a2337-d8c5-492d-970f-11353923253a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FA Lag2 Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [FA% Lag2]
			    )
			RETURN
			    Last3Avg
		displayFolder: Forecast Accuracy CSCA
		lineageTag: fdf368ac-bfd7-4fb6-b099-c6fc0b065bca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FA Lag4 Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [FA% Lag4]
			    )
			RETURN
			    Last3Avg
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 8fc4c877-1278-4033-a134-58034e85042d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Good Catch Closure Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [GOOD Catch Closure Rate]
			    )
			RETURN
			    Last3Avg
		displayFolder: GOOD Catch Closure Rate
		lineageTag: 8968d08b-bc2d-463a-9115-c95284856480

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Inventory Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [Gross Inventory]
			    )
			RETURN
			    Last3Avg
		displayFolder: Gross Inventory
		lineageTag: 892a446f-4b47-47a8-a9df-fd886a5a4045

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross PPV Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [Gross PPV Actual]
			    )
			RETURN
			    Last3Avg
		displayFolder: Gross PPV
		lineageTag: 9258e0a1-49f4-49a1-bb64-6a59bde31d52

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Inflated Inventory Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [Inflated Inventory]
			    )
			RETURN
			    Last3Avg
		displayFolder: Inflated Inventory
		lineageTag: 578b7837-1c86-4ca1-b1db-20aed6845856

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Logistics Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [Total Logistics Actual]
			    )
			RETURN
			    Last3Avg
		displayFolder: Logistic
		lineageTag: 2d38f8b4-e4b1-40c9-b16c-11bb0593e920

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Logistics on Net Sales Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [Total Logistics on Net Sales Actual]
			    )
			RETURN
			    Last3Avg
		displayFolder: Logistic vs Net Sales
		lineageTag: 15822e42-e73a-43bc-9431-be5b0f382e46

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Inventory Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [Net Inventory]
			    )
			RETURN
			    Last3Avg
		displayFolder: Net Inventory
		lineageTag: 4f91edee-40ee-4a21-81f9-19c2dde9fc5e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net POV Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [Net POV Actual]
			    )
			RETURN
			    Last3Avg
		displayFolder: Net POV
		lineageTag: 21ce9601-5527-4ee6-880b-b47172532b51

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Sales Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [Net Sales Actual]
			    )
			RETURN
			    Last3Avg
		displayFolder: Net Sales
		lineageTag: 22258b41-ff86-4352-8e9b-66066a3b41fa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OEE% Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [OEE%]
			    )
			RETURN
			    Last3Avg
		displayFolder: OEE
		lineageTag: ac4d6cad-09bf-4fbf-99da-7d85ef609e9a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OEE Focus Lines% Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [OEE Focus Lines%]
			    )
			RETURN
			    Last3Avg
		displayFolder: OEE FOCUS LINES
		lineageTag: ce44c526-c10f-4ce2-ab0f-8e3acfef4924

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'On Time Closure Dev Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [On Time Closure of Deviations%]
			    )
			RETURN
			    Last3Avg
		displayFolder: On Time Closure of Deviations
		lineageTag: 9bc9fa23-bc20-4edf-b478-992ea8bf78b3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'operating Income Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [Operating Income Actual]
			    )
			RETURN
			    Last3Avg
		displayFolder: Operating Income
		lineageTag: 45b8975b-75bb-41f8-bbd1-fb8fcb2b4780

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'pSIF SIFs Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [pSIF SIFs Focus]
			    )
			RETURN
			    Last3Avg
		displayFolder: pSIF SIFs Focus
		lineageTag: 41a10f45-95e0-4e05-8754-27c9d5942afb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PWS Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [PWS Benefits]
			    )
			RETURN
			    Last3Avg
		displayFolder: PWS
		lineageTag: fd993e53-b79b-4382-b78f-c6c5eba5a805

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RFT Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [RFT%]
			    )
			RETURN
			    Last3Avg
		displayFolder: RFT
		lineageTag: 663e1264-6e6a-4ea5-9274-991fd23b1412

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Schedule Attainment Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [Schedule Attn]
			    )
			RETURN
			    Last3Avg
		displayFolder: Schedule Attainment
		lineageTag: da3fb686-5180-4236-b67e-bee951093f3d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Service Rate Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [Service Rate%]
			    )
			RETURN
			    Last3Avg
		displayFolder: Service Rate CSCA
		lineageTag: 7bcaf47b-384d-479a-993b-9ecc032f0a8e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Service Top 11 Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [Service Top 11]
			    )
			RETURN
			    Last3Avg
		displayFolder: Service Top 11
		lineageTag: fd3b0824-2b1b-488b-ac91-3e485a35d690

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO: Obs linked to Conv Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [SSSO: Obsolescenes linked to Conversions]
			    )
			RETURN
			    Last3Avg
		displayFolder: SSSO Obs linked to Conv
		lineageTag: 6ab22bdc-88c7-4d9c-8714-cbc6e4a004a4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO: Salvage & Obs Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [SSSO: Salvage & Obsolescence]
			    )
			RETURN
			    Last3Avg
		displayFolder: SSSO Salvage & Obs
		lineageTag: 6215b501-09f5-4e5f-98c1-93a600e7db96

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO: Scrap-Off Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [SSSO: Scrap-Off]
			    )
			RETURN
			    Last3Avg
		displayFolder: SSSO Scrap-Off
		lineageTag: 6aabbdab-63ca-44cf-8d36-b329e8202619

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ABP Variance 3M_diff%' =
			
			VAR Result = DIVIDE(([ABP Variance] - [ABP Variance Last 3M Avg]), [ABP Variance Last 3M Avg])
			RETURN
			Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: ABP Variance
		lineageTag: 89aab1e2-32ca-4629-9d7e-f4675105b356

	measure 'ABP Variance 3M_Final' = ```
			VAR kpi_ =  [ABP Variance 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: ABP Variance
		lineageTag: 763d5b38-52cc-4a73-b4d9-57e5cf8a36b2

	measure 'ASTM Incidents 3M_diff%' =
			
			VAR Result = DIVIDE(([ASTM Incidents] - [ASTM Incidents Last 3M Avg]), [ASTM Incidents Last 3M Avg])
			RETURN
			Result
		displayFolder: ASTM Incidents
		lineageTag: ad251664-c8cc-4037-9cdb-f07c70e12a40

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ASTM Rate 3M_diff%' =
			
			VAR Result = ([ASTM Rate] - [ASTM Rate Last 3M Avg])
			RETURN
			Result
		displayFolder: ASTM Rate
		lineageTag: 925cc2c1-1fbf-4f58-9016-934d359f9525

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bias Lag2 3M_diff%' =
			
			VAR Result = ([Bias% Lag 2] - [Bias Lag2 Last 3M Avg])
			RETURN
			Result
		displayFolder: Bias CSCA
		lineageTag: 60471356-25d7-4cc1-ab7f-3f793101fa41

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bias Lag4 3M_diff%' =
			
			VAR Result = ([Bias% Lag 4] - [Bias Lag4 Last 3M Avg])
			RETURN
			Result
		displayFolder: Bias CSCA
		lineageTag: 877ec069-1c0c-4b4a-a9d4-9903455063fd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CAPA Completion 3M_diff%' =
			
			VAR Result = ([CAPA Completion Rate] - [CAPA Completion Rate Last 3M Avg])
			RETURN
			Result
		displayFolder: CAPA Completion Rate
		lineageTag: 493f5871-a5ab-4727-9536-4f1c53cb2167

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CFR 3M_diff%' =
			
			VAR Result = ([CFR] - [CFR Last 3M Avg])
			RETURN
			Result
		displayFolder: CFR
		lineageTag: c9c7bd19-451d-4975-89ab-051861837ad2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'COGS 3M_diff%' =
			
			VAR Result = DIVIDE(([COGS Actual] - [COGS Last 3M Avg]), [COGS Last 3M Avg])
			RETURN
			Result
		displayFolder: COGS
		lineageTag: e54314f4-7ad8-4aff-b396-aed203454a3d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Critical Major Obs 3M_diff%' =
			
			VAR Result = DIVIDE(([Critical or Major Observations] - [Critical or Major Obs Last 3M Avg]), [Critical or Major Obs Last 3M Avg])
			RETURN
			Result
		displayFolder: Critical or Major Obs
		lineageTag: 98434e75-1417-45cf-a5e9-4428a5a8dfd8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Customer Fines 3M_diff%' =
			
			VAR Result = DIVIDE(([Customer Fines] - [Customer Fines Last 3M Avg]), [Customer Fines Last 3M Avg])
			RETURN
			Result
		displayFolder: Customer Fines
		lineageTag: 9716f747-cdf5-4bc7-964e-3c4611ee313d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DIO 3M_diff%' =
			
			VAR Result = DIVIDE(([DIO] - [DIO Last 3M Avg]), [DIO Last 3M Avg])
			RETURN
			Result
		displayFolder: DIO
		lineageTag: 56e1866b-777c-48fb-9cd0-efcfae2b5ebe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Distribution on COGS 3M_diff%' =
			
			VAR Result = ([Total Distribution on COGS Actual] - [Distribution on COGS Last 3M Avg])
			RETURN
			Result
		displayFolder: Distribution on COGS
		lineageTag: 4db9b236-f9bc-4274-9d60-e4455c86af3a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DPO 3M_diff%' =
			
			VAR Result = DIVIDE(([DPO] - [DPO Last 3M Avg]), [DPO Last 3M Avg])
			RETURN
			Result
		displayFolder: DPO
		lineageTag: c999df7b-e2f7-4ee9-8b90-064a6b7c5723

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DSO 3M_diff%' =
			
			VAR Result = DIVIDE(([DSO] - [DSO Last 3M Avg]), [DSO Last 3M Avg])
			RETURN
			Result
		displayFolder: DSO
		lineageTag: 9c9a8218-b6dd-4181-b7d5-9e08ced5afc0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Expired Inventory 3M_diff%' =
			
			VAR Result = DIVIDE(([Expired Inventory] - [Expired Inventory Last 3M Avg]), [Expired Inventory Last 3M Avg])
			RETURN
			Result
		displayFolder: Expired Inventory
		lineageTag: 35194e91-b13a-4aaf-92bd-35132c1b66df

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FA Lag2 3M_diff%' =
			
			VAR Result = ([FA% Lag2] - [FA Lag2 Last 3M Avg])
			RETURN
			Result
		displayFolder: Forecast Accuracy CSCA
		lineageTag: c29427b2-af21-4618-9196-8ab20ddbebde

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FA Lag4 3M_diff%' =
			
			VAR Result = ([FA% Lag4] - [FA Lag4 Last 3M Avg])
			RETURN
			Result
		displayFolder: Forecast Accuracy CSCA
		lineageTag: fecfb6c6-5d1a-4ca9-9cbd-7b15e28233fe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Good Catch Closure 3M_diff%' =
			
			VAR Result = ([GOOD Catch Closure Rate] - [Good Catch Closure Last 3M Avg])
			RETURN
			Result
		displayFolder: GOOD Catch Closure Rate
		lineageTag: 677cf36c-d2b6-4906-9304-e825ec407563

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Inventory 3M_diff%' =
			
			VAR Result = DIVIDE(([Gross Inventory] - [Gross Inventory Last 3M Avg]), [Gross Inventory Last 3M Avg])
			RETURN
			Result
		displayFolder: Gross Inventory
		lineageTag: c8b9c5bc-a91a-43ef-b0e8-d02b19c89951

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross PPV 3M_diff%' =
			
			VAR Result = DIVIDE(([Gross PPV Actual] - [Gross PPV Last 3M Avg]), [Gross PPV Last 3M Avg])
			RETURN
			Result
		displayFolder: Gross PPV
		lineageTag: 36ef2371-507b-4b3d-8822-427cb3151bf6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Inflated Inventory 3M_diff%' =
			
			VAR Result = DIVIDE(([Inflated Inventory] - [Inflated Inventory Last 3M Avg]), [Inflated Inventory Last 3M Avg])
			RETURN
			Result
		displayFolder: Inflated Inventory
		lineageTag: 19585e0a-6b19-4e8e-ab05-770ae26cee59

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Logistics 3M_diff%' =
			
			VAR Result = DIVIDE(([Total Logistics Actual] - [Total Logistics Last 3M Avg]), [Total Logistics Last 3M Avg])
			RETURN
			Result
		displayFolder: Logistic
		lineageTag: dc80024e-5e35-4bae-af58-bb8ba295ff40

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Logistics on Net Sales 3M_diff%' =
			
			VAR Result = ([Total Logistics on Net Sales Actual] - [Total Logistics on Net Sales Last 3M Avg])
			RETURN
			Result
		displayFolder: Logistic vs Net Sales
		lineageTag: 39fb09be-ec21-42a6-ad05-e876bb071558

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Inventory 3M_diff%' =
			
			VAR Result = DIVIDE(([Net Inventory] - [Net Inventory Last 3M Avg]), [Net Inventory Last 3M Avg])
			RETURN
			Result
		displayFolder: Net Inventory
		lineageTag: 75fbdb79-4a76-4575-93b5-1c0f030c434f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net POV 3M_diff%' =
			
			VAR Result = DIVIDE(([Net POV Actual] - [Net POV Last 3M Avg]), [Net POV Last 3M Avg])
			RETURN
			Result
		displayFolder: Net POV
		lineageTag: e0deaa94-7e7f-4e23-9856-48f054b615e0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Sales 3M_diff%' =
			
			VAR Result = DIVIDE(([Net Sales Actual] - [Net Sales Last 3M Avg]), [Net Sales Last 3M Avg])
			RETURN
			Result
		displayFolder: Net Sales
		lineageTag: 35b00555-039f-4a7c-a30b-8ea24483d3c7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OEE% 3M_diff%' =
			
			VAR Result = ([OEE%] - [OEE% Last 3M Avg])
			RETURN
			Result
		displayFolder: OEE
		lineageTag: 3f4560d6-c61a-484f-a695-867a49f0d696

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OEE Focus Lines% 3M_diff%' =
			
			VAR Result = ([OEE Focus Lines%] - [OEE Focus Lines% Last 3M Avg])
			RETURN
			Result
		displayFolder: OEE FOCUS LINES
		lineageTag: 55857ef9-c956-439e-b744-a33e54a29cb1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'On Time Closure of Deviations 3M_diff%' =
			
			VAR Result = ([On Time Closure of Deviations%] - [On Time Closure Dev Last 3M Avg])
			RETURN
			Result
		displayFolder: On Time Closure of Deviations
		lineageTag: 1fe0f6aa-cf24-4ebc-bbeb-cf0d45a259f2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Operating Income 3M_diff%' =
			
			VAR Result = DIVIDE(([Operating Income Actual] - [operating Income Last 3M Avg]), [operating Income Last 3M Avg])
			RETURN
			Result
		displayFolder: Operating Income
		lineageTag: 5a6e6957-01b9-4c6f-bfac-d442c66ed1b6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'pSIF SIFs 3M_diff%' =
			
			VAR Result = ([pSIF SIFs Focus] - [pSIF SIFs Last 3M Avg])
			RETURN
			Result
		displayFolder: pSIF SIFs Focus
		lineageTag: 68cc1639-c79b-4168-b6c1-052f94390600

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PWS 3M_diff%' =
			
			VAR Result = DIVIDE(([PWS Benefits] - [PWS Last 3M Avg]), [PWS Last 3M Avg])
			RETURN
			Result
		displayFolder: PWS
		lineageTag: 6aaa11b9-0a1d-4fac-864e-d0638b7fdf43

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RFT 3M_diff%' =
			
			VAR Result = ([RFT%] - [RFT Last 3M Avg])
			RETURN
			Result
		displayFolder: RFT
		lineageTag: 2c8e6887-b548-4edf-b955-5d1f773ab457

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Schedule Attainment 3M_diff%' =
			
			VAR Result = ([Schedule Attn] - [Schedule Attainment Last 3M Avg])
			RETURN
			Result
		displayFolder: Schedule Attainment
		lineageTag: e4862a3c-0973-46c7-80ae-d92e0e6debd1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Service Rate 3M_diff%' =
			
			VAR Result = ([Service Rate%] - [Service Rate Last 3M Avg])
			RETURN
			Result
		displayFolder: Service Rate CSCA
		lineageTag: f23aa261-3aba-4ac8-9cda-bb776a2bd488

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Service Top 11 3M_diff%' =
			
			VAR Result = DIVIDE(([Service Top 11] - [Service Top 11 Last 3M Avg]), [Service Top 11 Last 3M Avg])
			RETURN
			Result
		displayFolder: Service Top 11
		lineageTag: 09748591-0874-4aeb-96a7-a5cbf02533cf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO: Obs linked to Conv 3M_diff%' =
			
			VAR Result = DIVIDE(([SSSO: Obsolescenes linked to Conversions] - [SSSO: Obs linked to Conv Last 3M Avg]), [SSSO: Obs linked to Conv Last 3M Avg])
			RETURN
			Result
		displayFolder: SSSO Obs linked to Conv
		lineageTag: 36fbc3d4-55d9-4329-80e5-5625ee3774c4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO: Salvage & Obs 3M_diff%' =
			
			VAR Result = DIVIDE(([SSSO: Salvage & Obsolescence] - [SSSO: Salvage & Obs Last 3M Avg]), [SSSO: Salvage & Obs Last 3M Avg])
			RETURN
			Result
		displayFolder: SSSO Salvage & Obs
		lineageTag: 25d9ae2b-f4fd-46f9-af9c-9e75b56a2a75

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SSSO: Scrap-Off 3M_diff%' =
			
			VAR Result = DIVIDE(([SSSO: Scrap-Off] - [SSSO: Scrap-Off Last 3M Avg]), [SSSO: Scrap-Off Last 3M Avg])
			RETURN
			Result
		displayFolder: SSSO Scrap-Off
		lineageTag: ee4f95aa-92df-4994-91ce-9fcae47edff0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ASTM Incidents 3M_Final' = ```
			
			VAR kpi_ = [ASTM Incidents 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: ASTM Incidents
		lineageTag: 443ad491-a7c4-4406-82db-4b38842a716d

	measure 'ASTM Rate 3M_Final' = ```
			
			VAR kpi_ = [ASTM Rate 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: ASTM Rate
		lineageTag: 37b793a7-b375-49cb-a4e0-3b407f5ad4e4

	measure 'Bias Lag2 3M_Final' = ```
			
			VAR kpi_ =  [Bias Lag2 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Bias CSCA
		lineageTag: 8763f34c-9e4f-437d-a2ef-22a1cd10a7ae

	measure 'Bias Lag4 3M_Final' = ```
			
			VAR kpi_ =  [Bias Lag4 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Bias CSCA
		lineageTag: cb0674be-0bc0-4995-bdde-2190795b616e

	measure 'CAPA Completion Rate 3M_Final' = ```
			
			VAR kpi_ = [CAPA Completion 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: CAPA Completion Rate
		lineageTag: ced1f5d6-3c9b-4adc-8c55-a7866faab923

	measure 'CFR 3M_Final' = ```
			
			VAR kpi_ =  [CFR 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: CFR
		lineageTag: 67dc60fd-02f8-44d7-87cb-7073cc8195fb

	measure 'COGS Actual 3M_Final' = ```
			VAR kpi_ =  [COGS 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: COGS
		lineageTag: 8b484f9a-a807-4b4a-9436-139d270a5650

	measure 'Critical or Major Observations 3M_Final' = ```
			
			VAR kpi_ = [Critical Major Obs 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: Critical or Major Obs
		lineageTag: 8d8906ee-be93-4bee-99dd-406802d85acc

	measure 'Customer Fines 3M_Final' = ```
			
			VAR kpi_ =  [Customer Fines 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Customer Fines
		lineageTag: 8555a48e-1433-4b5e-becb-09f1b673f08b

	measure 'DIO 3M_Final' = ```
			
			VAR kpi_ =  [DIO 3M_diff%]
			Return 
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
			```
		displayFolder: DIO
		lineageTag: a45a4df3-2988-4760-b700-25f84d1096b6

	measure 'Distribution on COGS 3M_Final' = ```
			
			VAR kpi_ =  [Distribution on COGS 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Distribution on COGS
		lineageTag: f6df1600-5e82-428b-8c58-bb0fe1c29d83

	measure 'DPO 3M_Final' = ```
			
			VAR kpi_ =  [DPO 3M_diff%]
			Return 
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
			```
		displayFolder: DPO
		lineageTag: 6e3f7916-3c61-477a-851a-df15bbb189a7

	measure 'DSO 3M_Final' = ```
			
			VAR kpi_ =  [DSO 3M_diff%]
			Return 
			IF (
			    ISBLANK(kpi_),
			    "--",
			    VAR perc_ = ABS(kpi_)
			    VAR Format_ = FORMAT(perc_, "0.0%")
			    VAR Result_ = IF(kpi_ < 0, "▼ " & Format_, "▲ " & Format_)
			    RETURN Result_ & UNICHAR(160) & UNICHAR(160)
			    )
			```
		displayFolder: DSO
		lineageTag: 772a5644-e27d-458d-9f3c-7b8446dae018

	measure 'Expired Inventory 3M_Final' = ```
			
			VAR kpi_ =  [Expired Inventory 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Expired Inventory
		lineageTag: 0dc6e4ae-6fe0-4d1e-947f-487fc2a32ba5

	measure 'FA% Lag2 3M_Final' = ```
			
			VAR kpi_ =  [FA Lag2 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_
			```
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 69b35359-453e-4567-8220-5441cefaf27a

	measure 'FA% Lag4 3M_Final' = ```
			
			VAR kpi_ =  [FA Lag4 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_
			```
		displayFolder: Forecast Accuracy CSCA
		lineageTag: f23bf00f-ab65-4248-bf3e-d430a5059e96

	measure 'Good Catch Closure 3M_Final' = ```
			
			VAR kpi_ = [Good Catch Closure 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: GOOD Catch Closure Rate
		lineageTag: cc8a595f-9b49-4612-ba37-2d5227b446cf

	measure 'Gross Inventory 3M_Final' = ```
			
			VAR kpi_ =  [Gross Inventory 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Gross Inventory
		lineageTag: f1cd9dba-2fcb-4847-a67b-a835244aa2ef

	measure 'Gross PPV 3M_Final' = ```
			
			VAR kpi_ =  [Gross PPV 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Gross PPV
		lineageTag: 3aadad3c-a7b2-464d-ac9e-8d2201483e3f

	measure 'Inflated Inventory 3M_Final' = ```
			
			VAR kpi_ =  [Inflated Inventory 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Inflated Inventory
		lineageTag: 3f079f46-b819-4ada-8d37-ae5b74ecabc3

	measure 'Total Logistics 3M_Final' = ```
			
			VAR kpi_ =  [Total Logistics 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Logistic
		lineageTag: 2c8d7ca8-0408-4a81-aa56-ce1fa948315f

	measure 'Total Logistics on Net Sales 3M_Final' = ```
			
			VAR kpi_ =  [Total Logistics on Net Sales 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Logistic vs Net Sales
		lineageTag: 01e3bc35-f7b0-4ef0-8afe-01021943c0ac

	measure 'Net Inventory 3M_Final' = ```
			
			VAR kpi_ =  [Net Inventory 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Net Inventory
		lineageTag: fd0ac017-2d1a-4fb2-99d9-f8b3d896acbb

	measure 'Net POV 3M_Final' = ```
			
			VAR kpi_ =  [Net POV 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Net POV
		lineageTag: de65be9d-669d-472e-b7c5-128267b27cb0

	measure 'Net Sales 3M_Final' = ```
			
			VAR kpi_ =  [Net Sales 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Net Sales
		lineageTag: d331d3e3-8098-4506-bc8f-da3d7c9ec7b6

	measure 'OEE% 3M_Final' = ```
			
			VAR kpi_ =  [OEE% 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: OEE
		lineageTag: b699b75a-0869-4df8-81a8-4ed776f1d199

	measure 'OEE Focus Lines% 3M_Final' = ```
			
			VAR kpi_ =  [OEE Focus Lines% 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: OEE FOCUS LINES
		lineageTag: adb6efcb-080b-4b0b-9712-63fb459f86e2

	measure 'On Time Closure of Deviations 3M_Final' = ```
			
			VAR kpi_ = [On Time Closure of Deviations 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: On Time Closure of Deviations
		lineageTag: 8ce1f368-b1f1-4041-b880-fdfb37b758a6

	measure 'Operating Income Actual 3M_Final' = ```
			
			VAR kpi_ =  [Operating Income 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Operating Income
		lineageTag: f3861c26-fd39-403a-bad9-d08fa3b6413b

	measure 'pSIF SIFs Focus 3M_Final' = ```
			
			VAR kpi_ = [pSIF SIFs 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: pSIF SIFs Focus
		lineageTag: f9bdd595-c149-49d1-b969-fc56307a9ce5

	measure 'PWS Benefits 3M_Final' = ```
			
			VAR kpi_ = [PWS 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: PWS
		lineageTag: 28ec4249-4086-4529-8ffc-c01f458aecbb

	measure 'RFT 3M_Final' = ```
			
			VAR kpi_ = [RFT 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			IF(ISBLANK(kpi_),"--",Result_ & UNICHAR(160) & UNICHAR(160))
			```
		displayFolder: RFT
		lineageTag: 39b56821-6b7a-4d63-86e7-ad36ac66c13a

	measure 'Schedule Attainment 3M_Final' = ```
			
			VAR kpi_ =  [Schedule Attainment 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Schedule Attainment
		lineageTag: 49b6a640-8534-4bad-90fc-4c1ac0887803

	measure 'Service Rate% 3M_Final' = ```
			
			VAR kpi_ =  [Service Rate 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Service Rate CSCA
		lineageTag: a2ad8aa8-7593-4bf8-a643-92cd32708a05

	measure 'Service Top 11 3M_Final' = ```
			
			VAR kpi_ =  [Service Top 11 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Service Top 11
		lineageTag: da367c5d-46e4-47ca-b10b-9b683c93adfa

	measure 'SSSO: Obs Linked to Conv 3M_Final' = ```
			
			VAR kpi_ =  [SSSO: Obs linked to Conv 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: SSSO Obs linked to Conv
		lineageTag: f55bf57b-5aa5-4ab1-9bd3-1a15470de3b0

	measure 'SSSO: Salvage 3M_Final' = ```
			
			VAR kpi_ =  [SSSO: Salvage & Obs 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: SSSO Salvage & Obs
		lineageTag: 88b388e4-80fb-4c07-b5fa-38a7bc52d36c

	measure 'SSSO: Scrap-Off 3M_Final' = ```
			
			VAR kpi_ =  [SSSO: Scrap-Off 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: SSSO Scrap-Off
		lineageTag: 97e4b3a4-4c1d-4a2e-89ae-2ff6ef117bf1

	measure 'Bias Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [Bias%]
			    )
			RETURN
			    Last3Avg
		displayFolder: Bias CSCA
		lineageTag: c6188eee-c704-4cee-8b69-351c83b63e31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bias 3M_diff%' =
			
			VAR Result = ([Bias%] - [Bias Last 3M Avg])
			RETURN
			Result
		displayFolder: Bias CSCA
		lineageTag: eaa3e4f8-e2c8-4a8d-a24b-379521c80271

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bias 3M_Final' = ```
			
			VAR kpi_ =  [Bias 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_ & UNICHAR(160) & UNICHAR(160)
			```
		displayFolder: Bias CSCA
		lineageTag: 8b16acf9-6762-4685-acb2-c6c8cd4afc02

	measure 'FA Last 3M Avg' =
			
			VAR CurrentSeq =
			    MAX ( Dim_Date[YearPeriodSeq])
			VAR Last3Avg =
			    AVERAGEX (
			        FILTER (
			            ALL ( Dim_Date ),
			            Dim_Date[YearPeriodSeq] >= CurrentSeq - 3
			                && Dim_Date[YearPeriodSeq] < CurrentSeq
			        ),
			        [FA% CSCA]
			    )
			RETURN
			    Last3Avg
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 63721c5c-42ea-4db1-8d5d-7149a7d40427

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FA 3M_diff%' =
			
			VAR Result = ([FA% CSCA] - [FA Last 3M Avg])
			RETURN
			Result
		displayFolder: Forecast Accuracy CSCA
		lineageTag: f95fe7af-24b0-463d-8f1c-4ca84b451445

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FA% 3M_Final' = ```
			
			VAR kpi_ =  [FA 3M_diff%]
			VAR perc_ = abs(kpi_)
			VAR Format_ = Format( perc_,"0.0%")
			VAR Result_ = if(kpi_ < 0 , "▼ " &Format_,  "▲ " & Format_)
			Return 
			Result_
			```
		displayFolder: Forecast Accuracy CSCA
		lineageTag: 08767dfa-e181-4d29-834d-e3c079fe4958
	measure 'LR CFR ET' = ```
			
			VAR UTC = [LR CFR]  // use the measure from your model directly
			RETURN
			IF(
			    ISBLANK(UTC),
			    BLANK(),
			    VAR Yr = YEAR(UTC)
			    VAR Mar1 = DATE(Yr,3,1)
			    VAR Mar1_Weekday = WEEKDAY(Mar1,1)
			    VAR SecondSunday_March = Mar1 + MOD(8 - Mar1_Weekday,7) + 7
			    VAR DST_Start = SecondSunday_March + TIME(2,0,0)
			
			    VAR Nov1 = DATE(Yr,11,1)
			    VAR Nov1_Weekday = WEEKDAY(Nov1,1)
			    VAR FirstSunday_Nov = Nov1 + MOD(8 - Nov1_Weekday,7)
			    VAR DST_End = FirstSunday_Nov + TIME(2,0,0)
			
			    VAR ET_Offset = IF(UTC >= DST_Start && UTC < DST_End, TIME(4,0,0), TIME(5,0,0))
			
			    RETURN
			        FORMAT(UTC + ET_Offset, "dd-MM-yyyy hh:mm tt") &
			        " " & IF(UTC >= DST_Start && UTC < DST_End, "EDT", "EST")
			)
			
			```
		displayFolder: Refresh Details
		lineageTag: 5ec80487-a03f-4797-8521-697a76660327

	column Measures
		dataType: string
		lineageTag: c1d6289c-8a22-4893-aafb-8e461169c89f
		summarizeBy: none
		sourceColumn: Measures

		annotation SummarizationSetBy = Automatic

	partition Measure = m
		mode: import
		queryGroup: Parameters/Misc
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Measures = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Measures", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

