table MetricSelector
	lineageTag: 06e473f2-bec8-4374-86d7-4e5ff9d350af

	measure 'Selected KPI' = ```
			
			// SELECTEDVALUE('Operating_Parameter'[Parameter Name])
			
			SWITCH(
			    TRUE(),
			    HASONEVALUE('Sales_Parameter'[Parameter Name]), SELECTEDVALUE('Sales_Parameter'[Parameter Name]),
			    HASONEVALUE('Operating_Parameter'[Parameter Name]), SELECTEDVALUE('Operating_Parameter'[Parameter Name]),
			    HASONEVALUE('Working_Capital_Parameter'[Parameter Name]), SELECTEDVALUE('Working_Capital_Parameter'[Parameter Name]),
			    HASONEVALUE('Operations_Parameter'[Parameter Name]), SELECTEDVALUE('Operations_Parameter'[Parameter Name])
			)
			
			```
		displayFolder: Bar Color Measures
		lineageTag: 5c1b1278-8212-431a-9b9d-e78b76a1bb84

	measure 'KPI Target (Unified)' = ```
			
			VAR _kpi = [Selected KPI]
			RETURN
			SWITCH(
			    _kpi,
			    "COGS", [COGS_APN_Base],
			    "Net Sales", [Net Sales_APN_Base],
			    "Operating Income", [Operating Income APN_Base],
			    "Gross PPV", [Gross PPV APN_base],
			    "Net POV", [Net POV APN_base],
			    "Customer Fines", BLANK(),
			    "Distribution to COGS", [Total Distribution on COGS_APN_Base],
			    "% Logistics vs Net Sales", [Total Logistics on Net Sales_APN_Base],
			    "SSSO: Shrinkage", [SSSO: Shrinkage APN_Base],
			    "SSSO: Scrap-Off", [SSSO: Scrap-off APN_Base],
			    "SSSO: Salvage & Obs", [SSSO: Salvage & Obs_APN_Base],
			    "SSSO: Obs linked to Conv", [SSSO: Obso Conv_APN_Base],
			    "Gross Inventory",[Gross Inventory_APN_Base],
			    "Net Inventory",[Net Inventory_APN_Base],
			    "Inflated Inventory",BLANK(),
			    "Expired Inventory", BLANK(),
			    "DSO", [DSO_APN_Base],
			    "DPO", [DPO_APN_Base],
			    "DIO", [DIO_APN_Base],
			    "FA% Lag 2", [FA% Lag2 Target],
			    "FA% Lag 4", [FA% Target],
			    "Bias% Lag 2", [Bias Target],
			    "Bias% Lag 4", [Bias Target],
			    "Service%", [Service Target],
			    "CFR%", [CFR Target],
			    "OEE%", [OEE Target],
			    "Schedule Attainment%", [Schedule Attn Target],
			    "On Time Closure of Deviations%", [Deviations Plan],
			    "CAPA Completion Rate%", [CAPA Plan],
			    "RFT%", [RFT Plan],
			    "ABP Variance", [ABP Variance_APN_Base],
			    "Service Top 11",[Service Top 11 Target],
			    "Critical or Major Observations", BLANK()
			    
			)
			
			```
		displayFolder: Bar Color Measures
		lineageTag: 91b22b24-be4c-447f-a5a2-bff196627517

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BarColor = ```
			
			VAR _kpiName = [Selected KPI] 
			VAR _value = [KPI Value (Unified)]
			VAR _target = [KPI Target (Unified)]
			
			VAR _isBiasKPI = 
			    _kpiName IN { "Bias% Lag 2", "Bias% Lag 4" }
			
			RETURN
			IF(
			    NOT ISBLANK(_value),
			    SWITCH(
			        TRUE(),
			        _isBiasKPI && _value >= -0.03 && _value <= 0.03, "#001489",  // Blue for Bias within ±3%
			        _isBiasKPI, "#D7191C",                                       // Red for Bias outside range
			        NOT ISBLANK(_target) && _value < _target, "#D7191C",         // Red for other KPIs if value < target
			        "#001489"                                                    // Blue otherwise
			    ),
			    "#001489"
			)
			
			```
		displayFolder: Bar Color Measures
		lineageTag: c775bb1c-f729-40c9-84e8-835d01bb0d57

	measure 'KPI Value (Unified)' = ```
			
			VAR _kpi = [Selected KPI]
			RETURN
			SWITCH(
			    _kpi,
			    "COGS", [COGS Actual],
			    "Net Sales", [Net Sales Actual],
			    "Operating Income", [Operating Income Actual],
			    "Gross PPV", [Gross PPV Actual],
			    "Net POV", [Net POV Actual],
			    "Customer Fines", [Customer Fines],
			    "Distribution to COGS", [Total Distribution on COGS Actual],
			    "% Logistics vs Net Sales", [Total Logistics on Net Sales Actual],
			    "SSSO: Shrinkage", [SSSO Shrinkage],
			    "SSSO: Scrap-Off", [SSSO: Scrap-Off],
			    "SSSO: Salvage & Obs", [SSSO: Salvage & Obsolescence],
			    "SSSO: Obs linked to Conv", [SSSO: Obsolescenes linked to Conversions],
			    "Gross Inventory", [Gross Inventory],
			    "Net Inventory", [Net Inventory],
			    "Inflated Inventory", [Inflated Inventory],
			    "Expired Inventory", [Expired Inventory],
			    "DSO", [DSO],
			    "DPO", [DPO],
			    "DIO", [DIO],
			    "OEE%", [OEE%],
			    "Schedule Attainment%", [Schedule Attn],
			    "On Time Closure of Deviations%", [On Time Closure of Deviations%],
			    "CAPA Completion Rate%", [CAPA Completion Rate],
			    "RFT%", [RFT%],
			    "Critical or Major Observations", [Critical or Major Observations],
			    "FA% Lag 2", [FA% Lag2],
			    "FA% Lag 4", [FA% Lag4],
			    "Bias% Lag 2", [Bias% Lag 2],
			    "Bias% Lag 4", [Bias% Lag 4],
			    "Service%", [Service Rate%],
			    "CFR%", [CFR],
			    "ABP Variance",[ABP Variance],
			    "Service Top 11",[Service Top 11],
			    BLANK()
			)
			
			```
		displayFolder: Bar Color Measures
		lineageTag: c94d5e0e-48ec-4f2f-b492-00b03cf88fce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KPI Target (Formatted)' = ```
			
			VAR _rawValue = [KPI Target (Unified)]
			VAR _kpi = [Selected KPI]
			RETURN
			SWITCH(
			    TRUE(),
			    _kpi IN {
			        "OEE%", "Schedule Attainment%", "Service%", "CFR%", 
			        "FA% Lag 2", "FA% Lag 4", "Bias% Lag 2", "Bias% Lag 4", 
			        "On Time Closure of Deviations%", "CAPA Completion Rate%", "RFT%", "Distribution to COGS","% Logistics vs Net Sales"
			    }, FORMAT(_rawValue, "0.0%"),
			    FORMAT(_rawValue, "#,##0")
			)
			    
			```
		displayFolder: Bar Color Measures
		lineageTag: 64957d2f-284d-4bba-890e-ff54ec027cb8

	measure BarColor_WC = ```
			
			VAR _kpiName = [Selected KPI] 
			VAR _value = [KPI Value (Unified)]
			VAR _target = [KPI Target (Unified)]
			
			RETURN
			IF(
			    NOT ISBLANK(_value) && NOT ISBLANK(_target),
			    IF(_value > _target, 
			        "#D7191C",   // Red
			        "#001489"    // Blue
			    ),
			    "#001489"        // Default Blue if value or target is blank
			)
			
			```
		displayFolder: Bar Color Measures
		lineageTag: db2ae7be-0e09-4708-ad30-9cb54cda74d8

	measure BarColor_OI = ```
			
			VAR _kpiName = [Selected KPI] 
			VAR _value = [KPI Value (Unified)]
			VAR _target = [KPI Target (Unified)]
			
			VAR _isSpecialKPI  = 
			    _kpiName IN { "Net Sales", "Operating Income" }
			
			RETURN
			IF(
			    NOT ISBLANK(_value),
			    SWITCH(
			        TRUE(),
			        _isSpecialKPI && _value < _target, "#D7191C",   // Red if value < target for special KPIs
			        NOT _isSpecialKPI && _value > _target, "#D7191C", // Red if value > target for other KPIs
			        "#001489"  // Blue otherwise
			    ),
			    "#001489"
			)
			
			```
		displayFolder: Bar Color Measures
		lineageTag: da89552e-3310-4eb4-ab08-35e88dfd10e8

	column Metric
		lineageTag: b6fb7fae-3803-4e29-b36f-21afd71421fd
		summarizeBy: none
		sourceColumn: [period]
		sortByColumn: SortOrder

		annotation SummarizationSetBy = Automatic

	column SortOrder
		formatString: 0
		lineageTag: 8254b6bf-0377-44ec-b442-6ca89c51ee98
		summarizeBy: none
		isNameInferred
		sourceColumn: [SortOrder]

		annotation SummarizationSetBy = Automatic

	partition MetricSelector = calculated
		mode: import
		source =
				
				DATATABLE(
				    "Period", STRING,
				    "SortOrder", INTEGER,
				    {
				        {"vs YoY", 4},
				        {"vs PP", 3},
				        {"LYTD", 5},
				        {"vs Plan", 1},
				        {"vs Flex", 2}
				    }
				)

	annotation PBI_Id = a03c420cea1b45fa97c91188c7207338

