table MetricSelector
	lineageTag: 06e473f2-bec8-4374-86d7-4e5ff9d350af

	measure Forecast_Accuracy_Lag = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [FA% MoM_Final],
			      "LYTD",               [FA% CSCA LYTD_Final],
			      "vs YoY",               [FA% YoY_Final],
			      "vs Plan", SWITCH(SELECTEDVALUE(Fact_Forecast_Accuracy[LAGs]),"2",[FA% Lag2 Target_Final],"4",[FA% Lag4 Target_Final]),
			      BLANK()
			    )
			
			```
		displayFolder: Switch Measures
		lineageTag: 0df02182-49ea-4ccc-b141-c65ea0001be0

	measure Service_rate = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Service Rate% MoM_Final],
			      "LYTD",               [Service LYTD_Final],
			      "vs YoY",               [Service Rate% YoY_Final],
			      "vs Plan", [Service Target Final],
			      BLANK()
			    )
			```
		displayFolder: Switch Measures
		lineageTag: 62cd4ac5-ee85-432e-a828-97324dfd5c90

	measure 'Bias Switch' = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Bias MoM_Final],
			      "LYTD",               [Bias% LYTD_Final],
			      "vs YoY",               [Bias YoY_Final],
			      "vs Plan", [Bias Target Final],
			      BLANK()
			    )
			
			```
		displayFolder: Switch Measures
		lineageTag: 35cd6896-b861-469f-b15d-3080e543393e

	measure OEE = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [OEE% MoM_Final],
			      "LYTD",               [OEE% LYTD_Final],
			      "vs YOY",               [OEE% YoY_Final],
			      "vs Plan", [OEE Target_Final],
			      BLANK()
			    )
			
			```
		displayFolder: Switch Measures
		lineageTag: 6bf0cc01-ebf7-412a-9cde-0514745abb15

	measure Net_Inventory = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Net Inventory MoM_Final],
			      "LYTD",               [Net Inv LYTD_Final],
			      "vs YoY",               [Net Inventory YoY_Final],
			      "vs Plan", [Net Inventory_APN_Final],
			      "vs Flex", [Net Inventory_AFX_Final],
			      BLANK()
			    )
			
			```
		displayFolder: Switch Measures
		lineageTag: 9641f29e-d5e6-47d5-b11c-7eff043f4732

	measure Gross_Inventory = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Gross Inventory MoM_Final],
			      "LYTD",               [Gross Inv LYTD_Final],
			      "vs YoY",               [Gross Inventory YoY_Final],
			      "vs Plan", [Gross Inventory_APN_Final],
			      "vs Flex", [Gross Inventory_AFX_Final],
			      BLANK()
			    )
			```
		displayFolder: Switch Measures
		lineageTag: ceafa47a-354b-4324-8248-ae2bf82e8e14

	measure Inflated_Inventory = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Inflated Inventory MoM_Final],
			      "LYTD",               [Inflated Inv LYTD_Final],
			      "vs YoY",               [Inflated Inventory YoY_Final],
			      BLANK()
			    )
			
			```
		displayFolder: Switch Measures
		lineageTag: 4142541c-b983-4249-81dc-8c2cd55b1fb4

	measure Expired_Inventory = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Expired Inventory MoM_Final],
			      "LYTD",               [Expired Inv LYTD_Final],
			      "vs YoY",               [Expired Inventory YoY_Final],
			      BLANK()
			    )
			
			```
		displayFolder: Switch Measures
		lineageTag: b78799df-3f7e-4d42-821f-a0626242d7d4

	measure DIO_ = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [DIO MoM_Final],
			      "YTD",               [DIO YTD],
			      "vs YoY",               [DIO YoY_Final],
			      "vs Plan", [DIO_APN_Final],
			      "vs Flex", [DIO_AFX_Final],
			      BLANK()
			    )
			
			```
		formatString: 0.0
		displayFolder: Switch Measures
		lineageTag: 21e1375a-300b-4aad-bd12-18a069b96c6b

	measure SSSO_Salvage&Obs = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP",[SSSO: Salvage MoM_Final],
			      "LYTD",[SSSO: Salvage LYTD_Final],
			      "vs YoY",[SSSO: Salvage YoY_Final],
			      "vs Plan",[SSSO: Salvage & Obs APN_Final],
			      "vs Flex", [SSSO: Salvage & Obs F66_Final],
			      BLANK()
			    )
			```
		displayFolder: Switch Measures
		lineageTag: 4aee5ee6-baab-4f49-a851-5243d4568032

	measure SSSO_Obs_Linked = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [SSSO: Obs Linked to Conv MoM_Final],
			      "LYTD",               [SSSO: Obs LYTD_Final],
			      "vs YoY",               [SSSO: Obs linked to Conv YoY_Final],
			      "vs Plan",[SSSO: Obs linked to conv APN_Final],
			      "vs Flex", [SSSO: Obs linked to conv F66_Final],
			      BLANK()
			    )
			
			```
		displayFolder: Switch Measures
		lineageTag: 64f7d605-77e5-46ad-b7aa-f26bec298bb9

	measure Forecast_Accuracy_Lag_Color = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [FA% MoM%],
			        "LYTD", [FA% CSCA LYTD],
			        "vs YoY", [FA% YoY%],  
			        "vs Plan", Switch(SELECTEDVALUE(Fact_Forecast_Accuracy[LAGs]),"2",[FA% Lag 2 Target Diff%],
			        "4",[FA% Lag 4 Target Diff%]),
			        BLANK()
			    )
			
			RETURN
			IF(
			        _sel = "YTD",
			        "#000000",  -- Always black for YTD
			    IF(
			        ISBLANK(kpi_value), "#000000",  -- black for blank
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#1A9641"   -- green for ▲ up
			        )
			    )
			)
			```
		displayFolder: Cond.format_measure
		lineageTag: cc90c6c1-1a6e-4f64-80a9-d71e27f6a224

	measure 'Service rate_Color' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Service Rate% MoM%],
			        "LYTD", [Service Rate LYTD],
			        "vs YoY", [Service Rate YoY%],  
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#1A9641"   -- green for ▲ up
			        )
			```
		displayFolder: Cond.format_measure
		lineageTag: a1ef24e0-4d13-4f17-973f-4e210e679beb

	measure Bias_Color = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Bias MoM%],
			        "LYTD", [Bias% LYTD],
			        "vs YoY", [Bias YoY%],
			        "vs Plan", [Bias Target Diff%],
			        BLANK()
			    )
			
			RETURN
			    IF(
			        ISBLANK(kpi_value), "#000000",  // black for blank
			        IF(
			            ABS(kpi_value) <= 0.03,     // between -3% and +3%
			            "#1A9641",                  // green
			            "#D7191C"                   // red
			        )
			    )
			
			```
		displayFolder: Cond.format_measure
		lineageTag: d9006fc7-626b-453f-8839-d76881195577

	measure OEE_Color =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [OEE% MoM%],
			        "YTD", [OEE% YTD],
			        "vs YoY", [OEE% YoY%],
			        "vs Plan", [OEE Target diff%],
			        "LYTD", [OEE LYTD],
			        BLANK()
			    )
			
			RETURN
			IF(
			        _sel = "YTD",
			        "#000000",  -- Always black for YTD
			    IF(
			        ISBLANK(kpi_value), "#000000",  -- black for blank
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#1A9641"   -- green for ▲ up
			        )
			    )
			)
		displayFolder: Cond.format_measure
		lineageTag: 980502bb-cbd9-42f8-b167-7100ed8741b6

	measure SSSO_Salvage&Obs_Color = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [SSSO: Salvage & obs MoM%],
			        "LYTD", [SSSO: Salvage LYTD],
			        "vs YoY", [SSSO: Salvage YoY%], 
			        "vs Plan", [SSSO: Salvage & Obsolescence_APN],
			        "vs Flex", [SSSO: Salvage & Obsolescence_F66],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#1A9641",  -- Green for ▼ down
			            "#D7191C"   -- red for ▲ up
			        )
			```
		displayFolder: Cond.format_measure
		lineageTag: f0454bf2-86f2-4625-abb9-b1206d4604c4

	measure SSSO_Obs_Linked_Color =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [SSSO: Obs linked to Conv MoM%],
			        "LYTD", [SSSO: Obs LYTD],
			        "vs YoY", [SSSO: Obs linked to Conv YoY%],
			        "vs Plan", [SSSO: Obsolescenes linked to Conversions_APN],
			        "vs Flex", [SSSO: Obsolescenes linked to Conversions_F66],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#1A9641",  -- Green for ▼ down
			            "#D7191C"   -- Red for ▲ up
			        )
		displayFolder: Cond.format_measure
		lineageTag: 21e5f5e0-6233-4941-999f-0a0e89de6c67

	measure SSSO_Scrap_off_Color = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [SSSO: Scrap-Off MoM%],
			        "LYTD", [SSSO: Scrap-off LYTD],
			        "vs YoY", [SSSO: Scrap-Off YoY%], 
			        "vs Plan", [SSSO: Scrap-Off_APN],
			        "vs Flex", [SSSO: Scrap-Off_F66],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#1A9641",  -- Green for ▼ down
			            "#D7191C"   -- Red for ▲ up
			        )
			```
		displayFolder: Cond.format_measure
		lineageTag: ceecbcf4-8b0d-484e-9d44-1c39040f940a

	measure Expired_Inventory_Color = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Expired Inventory MoM%],
			        "LYTD", [Expired Inventory LYTD],
			        "vs YoY", [Expired Inventory YoY%], 
			        BLANK()
			    )
			
			RETURN
			             IF(
			                kpi_value > 0,
			                "#D7191C",  -- Red for ▲ up
			                "#1A9641"   -- Green for ▼ down
			            )
			```
		displayFolder: Cond.format_measure
		lineageTag: 8fdc36f2-2570-456f-a9ff-1c7abacfa8a9

	measure Net_Inventory_Color =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Net Inventory MoM%],
			        "LYTD", [Net Inventory LYTD],
			        "vs YoY", [Net Inventory YoY%],
			        "vs Plan", [Net Inventory_APN],
			        "vs Flex", [Net Inventory_AFX],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#1A9641",  -- green for ▼ down
			            "#D7191C"   -- red for ▲ up
			        )
		displayFolder: Cond.format_measure
		lineageTag: 2682106c-541b-4134-a970-546eb8033819

	measure Gross_Inventory_Color =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Gross Inventory MoM%],
			        "LYTD", [Gross Inv LYTD],
			        "vs YoY", [Gross Inventory YoY%],
			        "vs Plan", [Gross Inventory_APN],
			        "vs Flex", [Gross Inventory_AFX],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#1A9641",  -- green for ▼ down
			            "#D7191C"   -- red for ▲ up
			        )
		displayFolder: Cond.format_measure
		lineageTag: 01a21988-f77d-49c9-a7cc-a6f087fc4e81

	measure Inflated_Inventory_Color = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Inflated Inventory MoM%],
			        "LYTD", [Inflated Inv LYTD],
			        "vs YoY", [Inflated Inventory YoY%], 
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#1A9641",  -- green for ▼ down
			            "#D7191C"   -- red for ▲ up
			        )
			```
		displayFolder: Cond.format_measure
		lineageTag: 856c2e81-9dbc-41c9-bdac-120fa14755e8

	measure DIO_Color =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [DIO MoM%],
			        "YTD", [DIO YTD],
			        "vs YoY", [DIO YoY%],
			        "vs Plan", [DIO_APN],
			        "vs Flex", [DIO_AFX],
			        BLANK()
			    )
			
			RETURN
			    IF(
			            _sel = "YTD",
			            "#000000",  -- Always black for YTD
			        IF(
			            ISBLANK(kpi_value), "#000000",  -- black for blank
			            IF(
			                kpi_value < 0,
			                "#1A9641",  -- Green for ▼ down
			                "#D7191C"   -- Red for ▲ up
			            )
			        )
			    )
		displayFolder: Cond.format_measure
		lineageTag: 453cac8f-4b98-4d01-b350-016983217915

	measure SSSO_Scrap_Off_ = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [SSSO: Scrap-Off MoM_Final],
			      "LYTD",               [SSSO: Scrap-off LYTD_Final],
			      "vs YoY",               [SSSO: Scrap-Off YoY_Final],
			      "vs Plan", [SSSO: Scrap-Off APN_Final],
			      "vs Flex", [SSSO: Scrap-Off F66_Final],
			      BLANK()
			    )
			
			```
		displayFolder: Switch Measures
		lineageTag: 611d4f8e-c69f-41a1-be89-4bfc6f8e6e5c

	measure 'Total Logistics on Net Sales Actual _Color' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Total Logistics on Net Sales Actual MoM%],
			        "LYTD", [Total Logistics on Net Sales LYTD],
			        "vs YoY", [Total Logistics on Net Sales Actual YoY%],
			        "vs Plan", [Total Logistics on Net Sales_APN],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#1A9641", -- green for ▲ up
			            "#D7191C"  -- red for ▼ down 
			        )
			```
		displayFolder: Cond.format_measure
		lineageTag: e0294879-b309-4989-9fc5-9bed23b9675c

	measure Total_Logistics_on_Net_Sales = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Total Logistics on Net Sales Actual MoM_Final],
			      "LYTD",               [Total Logistics on Net Sales LYTD_Final],
			      "vs YoY",               [Total Logistics on Net Sales Actual YoY_Final],
			      "vs Plan", [Total Logistics on Net Sales_APN_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: Switch Measures
		lineageTag: 10eacfe4-5cad-4ffa-a768-47d7baabe1fc

		annotation PBI_FormatHint = {"isText":true}

	measure 'SA _Color' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [SA MoM%],
			        "LYTD", [Schedule Attn LYTD],
			        "vs YoY", [SA YoY%],
			        "vs Plan", [Schedule Attn Target Diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value >= 0,
			            "#1A9641",  -- green for ▲ up
			            "#D7191C"  -- red for ▼ down
			        )
		displayFolder: Cond.format_measure
		lineageTag: 6a8b82f4-aeff-46ad-8c49-7755b8a36d00

	measure SA = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [SA MoM_Final],
			      "LYTD",               [Schedule Attn LYTD_Final],
			      "vs YoY",               [SA YoY_Final],
			      "vs Plan", [Schedule Attn Target Final],
			      BLANK()
			    )
			```
		displayFolder: Switch Measures
		lineageTag: 5a08dda7-84dd-4620-bb9e-a3079c2313fd

		annotation PBI_FormatHint = {"isText":true}

	measure Reference_lbl_title = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", "vs PP",
			      "LYTD",  "LYTD",
			      "vs YoY", "vs YoY",
			      "vs Plan", "vs Plan",
			      "vs Flex", "vs Flex",
			      BLANK()
			    )
			```
		displayFolder: Switch Measures
		lineageTag: 0f0991da-2fa9-488c-a956-7d8b2c3546ee

	measure Total_Distribution_on_COGS = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Total Distribution on COGS Actual MoM_Final],
			      "LYTD",               [Total Distribution on COGS LYTD_Final],
			      "vs YoY",               [Total Distribution on COGS Actual YoY_Final],
			      "vs Plan", [Total Distribution on COGS_APN_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: Switch Measures
		lineageTag: 836c8524-513b-4a4a-9fd6-67c388c39b7a

		annotation PBI_FormatHint = {"isText":true}

	measure 'Total Distribution on COGS Actual _Color' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Total Distribution on COGS Actual MoM%],
			        "LYTD", [Total Distribution on COGS LYTD],
			        "vs YoY", [Total Distribution on COGS Actual YoY%], 
			        "vs Plan", [Total Logistics on Net Sales_APN],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#1A9641", -- green for ▲ up
			            "#D7191C"  -- red for ▼ down 
			        )
			```
		displayFolder: Cond.format_measure
		lineageTag: c69957fc-fb79-4116-84f9-e51d8533fd37

	measure Net_Sales_Actual = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Net Sales Actual MoM_Final],
			      "LYTD",               [Net Sales Actual LYTD_Final],
			      "vs YoY",               [Net Sales Actual YoY_Final],
			      "vs Plan", [Net Sales_APN_Final],
			      "vs Flex", BLANK(),
			      BLANK()
			    )
			
			
			```
		displayFolder: Switch Measures
		lineageTag: 8aee09ca-7e26-4aa1-a4d4-8fe9827f5614

		annotation PBI_FormatHint = {"isText":true}

	measure Net_Sales_Actual_Color = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Net Sales Actual MoM%],
			        "LYTD", [Net Sales Actual LYTD],
			        "vs YoY", [Net Sales Actual YoY%], 
			        "vs Plan", [Net Sales_APN],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#1A9641"   -- green for ▲ up
			        )
			```
		displayFolder: Cond.format_measure
		lineageTag: def946ce-1480-40c7-8802-3344b832f624

	measure DSO_Color = ```
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [DSO MoM%],
			        "LYTD", BLANK(),
			        "vs YoY", [DSO YoY%], 
			        "vs Plan",[DSO_APN],
			        BLANK()
			    )
			
			RETURN
			         IF(
			            kpi_value < 0,
			                "#1A9641",  -- Green for ▼ down
			                "#D7191C"   -- Red for ▲ up
			        )
			```
		displayFolder: Cond.format_measure
		lineageTag: 314e75e4-2c75-4785-8b19-e9ae5dc36e72

	measure DSO_ =
			VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [DSO MoM_Final],
			      "LYTD",             BLANK(),
			      "vs YoY",               [DSO YoY_Final],
			      "vs Plan", [DSO_APN_Final],
			      BLANK()
			    )
		displayFolder: Switch Measures
		lineageTag: f98738c3-9514-46ea-8165-cdf96cb4bf38

	measure DPO_Color = ```
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [DPO MoM%],
			        "LYTD", BLANK(),
			        "vs YoY", [DPO YoY%], 
			        "vs Plan", [DPO_APN],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			                "#1A9641",  -- Green for ▼ down
			                "#D7191C"   -- Red for ▲ up
			        )
			```
		displayFolder: Cond.format_measure
		lineageTag: 065ebdbd-7356-4922-9657-ae2e162ee6da

	measure DPO_ =
			VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [DPO MoM_Final],
			      "LYTD",             BLANK(),
			      "vs YoY",               [DPO YoY_Final],
			      "vs Plan", [DPO_APN_Final],
			      BLANK()
			    )
		displayFolder: Switch Measures
		lineageTag: 03c321ea-6235-4816-9e0e-d027a8dbd14e

	measure COGS_Actual_Color = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [COGS Actual MoM%],
			        "LYTD", [COGS Actual LYTD],
			        "vs YoY", [COGS Actual YoY%], 
			        "vs Plan", [COGS_APN],
			        BLANK()
			    )
			
			RETURN
			    IF(
			        ISBLANK(kpi_value), "#000000",         // black for blank
			        IF(
			            kpi_value < 0,
			            "#1A9641",  // green → down is good (COGS reduced)
			            "#D7191C"   // red → up is bad (COGS increased)
			        )
			    )
			
			```
		displayFolder: Cond.format_measure
		lineageTag: 64617715-861c-49d7-80aa-96d3fe6cf662

	measure COGS_Actual = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [COGS Actual MoM_Final],
			      "LYTD",               [COGS Actual LYTD_Final],
			      "vs YoY",               [COGS Actual YoY_Final],
			      "vs Plan", [COGS_APN_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: Switch Measures
		lineageTag: 6d9487a3-6008-4ad4-9dd1-62a455d2f02f

		annotation PBI_FormatHint = {"isText":true}

	measure 'Customer Fine Switch' = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Cust Fine MoM_Final],
			      "LYTD",               [Cust fine LYTD_Final],
			      "vs YoY",               [Cust fine YoY_Final],
			      "vs Plan", [Cust fine Target Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: Switch Measures
		lineageTag: 7d24d324-ecca-4e2d-8e7a-a707ebe03941

	measure 'Cust Fine_Color' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Cust Fine MoM%],
			        "LYTD", [Cust Fine LYTD],
			        "vs YoY", [Cust fine YoY%], 
			        "vs Plan", [Cust Fine Target Diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#1A9641",  -- green for ▼ down
			            "#D7191C"   -- red for ▲ up
			        )
			```
		displayFolder: Cond.format_measure
		lineageTag: 567425fd-d2c2-4c4b-8601-b934c144f23b

	measure CFR_switch = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [CFR MoM_Final],
			      "LYTD",               [CFR LYTD_Final],
			      "vs YoY",               [CFR YoY_Final],
			      "vs Plan", [CFR Target Final],
			      BLANK()
			    )
			```
		displayFolder: Switch Measures
		lineageTag: 0f8b1637-a243-466d-b38d-32eaa49bf546

	measure 'CFR _Color' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [CFR MoM%],
			        "LYTD", [CFR LYTD],
			        "vs YoY", [CFR YoY%],
			        "vs Plan", [CFR Target Diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value > 0,
			            "#1A9641",  -- green for ▲ up
			            "#D7191C"  -- red for ▼ down
			        )
		displayFolder: Cond.format_measure
		lineageTag: e4ca5e4c-aaf6-4845-ae38-4787454da709

	measure Bias_CSCA_Color_KPI = ```
			
			/*
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			// Current KPI value (raw % bias)
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Bias MoM%],
			        "LYTD", [Bias% LYTD],
			        "vs YoY", [Bias YoY%],
			        "vs Plan", [Bias Target Diff%],
			        BLANK()
			    )
			
			// Previous period's KPI value
			VAR prev_kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", CALCULATE([Bias MoM%], Dim_Date[YearPeriodSeq] = MAX(Dim_Date[YearPeriodSeq]) - 1),
			        "LYTD", CALCULATE([Bias% LYTD], Dim_Date[YearPeriodSeq] = MAX(Dim_Date[YearPeriodSeq]) - 1),
			        "vs YoY", CALCULATE([Bias YoY%], Dim_Date[YearPeriodSeq] = MAX(Dim_Date[YearPeriodSeq]) - 1),
			        "vs Plan", CALCULATE([Bias Target Diff%], Dim_Date[YearPeriodSeq] = MAX(Dim_Date[YearPeriodSeq]) - 1),
			        BLANK()
			    )
			
			// Is bias within acceptable range of -5% to +5%
			VAR isAcceptable = NOT ISBLANK(kpi_value) && ABS(kpi_value) <= 0.05
			
			// Is bias improving (getting closer to 0 compared to previous)
			VAR isImproving = 
			    NOT isAcceptable &&
			    NOT ISBLANK(kpi_value) &&
			    NOT ISBLANK(prev_kpi_value) &&
			    ABS(kpi_value) < ABS(prev_kpi_value)
			
			RETURN
			    IF(
			        _sel = "YTD", "#000000",  // black for YTD
			        IF(
			            ISBLANK(kpi_value), "#000000",  // black for blank
			            IF(
			                isAcceptable || isImproving,
			                "#1A9641",  // green for acceptable or improving
			                "#D7191C"   // red for bad + not improving
			            )
			        )
			    )
			
			//another calculation
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Bias MoM%],
			        "LYTD", [Bias% LYTD],
			        "vs YoY", [Bias YoY%],
			        "vs Plan", [Bias Target Diff%],
			        BLANK()
			    )
			
			RETURN
			    IF(
			        ISBLANK(kpi_value), "#001489",  
			        IF(
			            ABS(kpi_value) <= 0.03,     // between -3% and +3%
			            "#001489",                  // Blue
			            "#D7191C"                   // red
			        )
			    )
			*/
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			VAR BiasValue = [Bias%] 
			VAR CompValue =
			    SWITCH(
			        _sel,
			        "vs PP", [Bias MoM%],
			        "LYTD", [Bias% LYTD],
			        "vs YoY", [Bias YoY%],
			        "vs Plan", [Bias Target Diff%],
			        BLANK()
			    )
			
			RETURN
			    IF(
			        ISBLANK(CompValue), "#001489",  // fallback for blank
			        IF(
			            ABS(BiasValue) <= 0.03,     // green for bias within ±3%
			            "#001489",                  // green
			            "#D7191C"                   // red
			        )
			    )
			
			```
		displayFolder: KPI Color_Measure
		lineageTag: e07330fb-b52a-4afa-9cb5-8ad0efe057ea

	measure Bias%_CSCI_Color_KPI = ```
			
			/*
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			// Current KPI value (raw % bias)
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Bias MoM%_raw CSCI],
			        "YTD", [Bias_YTD CSCI],
			        "vs YoY", [Bias YoY % Raw CSCI],
			        "vs Plan", [Bias Target Diff%_CSCI],
			        BLANK()
			    )
			
			// Previous period's KPI value
			VAR prev_kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", CALCULATE([Bias MoM%_raw CSCI], Dim_Date[YearPeriodSeq] = MAX(Dim_Date[YearPeriodSeq]) - 1),
			        "vs YoY", CALCULATE([Bias YoY % Raw CSCI], Dim_Date[YearPeriodSeq] = MAX(Dim_Date[YearPeriodSeq]) - 1),
			        "vs Plan", CALCULATE([Bias Target Diff%_CSCI], Dim_Date[YearPeriodSeq] = MAX(Dim_Date[YearPeriodSeq]) - 1),
			        BLANK()
			    )
			
			// Is bias within acceptable range of -5% to +5%
			VAR isAcceptable = NOT ISBLANK(kpi_value) && ABS(kpi_value) <= 0.05
			
			// Is bias improving (getting closer to 0 compared to previous)
			VAR isImproving = 
			    NOT isAcceptable &&
			    NOT ISBLANK(kpi_value) &&
			    NOT ISBLANK(prev_kpi_value) &&
			    ABS(kpi_value) < ABS(prev_kpi_value)
			
			RETURN
			    IF(
			        _sel = "YTD", "#000000",  // black for YTD
			        IF(
			            ISBLANK(kpi_value), "#000000",  // black for blank
			            IF(
			                isAcceptable || isImproving,
			                "#1A9641",  // green for acceptable or improving
			                "#D7191C"   // red for bad + not improving
			            )
			        )
			    )
			 */
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			VAR BiasValue = [Bias % CSCI] 
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Bias MoM%_raw CSCI],
			        "LYTD", [Bias % LYTD CSCI],
			        "vs YoY", [Bias YoY % Raw CSCI],
			        "vs Plan", [Bias Target Diff%_CSCI],
			        BLANK()
			    )
			
			RETURN
			    IF(
			        _sel = "YTD",
			        "#000000",  -- Always black for YTD
			    IF(
			        ISBLANK(kpi_value), "#001489",  
			        IF(
			            ABS(BiasValue) <= 0.10,     // between -10% and +10%
			            "#001489",                  // green
			            "#D7191C"                   // red
			        )
			    )
			    )
			
			```
		displayFolder: KPI Color_Measure
		lineageTag: f2b8f3f4-e505-4b48-a764-7e39bb5a500b

	measure COGS_Color_KPI = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [COGS Actual MoM%],
			        "LYTD", [COGS Actual LYTD],
			        "vs YoY", [COGS Actual YoY%], 
			        "vs Plan", [COGS_APN],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#001489",   -- Blue for ▼ down
			            "#D7191C"    -- red for ▲ up
			        )
			)
			```
		displayFolder: KPI Color_Measure
		lineageTag: 6280ce49-6091-4ed0-95ad-54efeb144211

	measure 'Cust Fine_Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Cust Fine MoM%],
			        "LYTD", [Cust Fine LYTD],
			        "vs YoY", [Cust fine YoY%], 
			        "vs Plan", [Cust Fine Target Diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#001489",  -- green for ▼ down
			            "#D7191C"   -- red for ▲ up
			        )
			)
			```
		displayFolder: KPI Color_Measure
		lineageTag: 8f456d45-80a7-47a0-888a-6a94759b6b3a

	measure DIO_Color_KPI =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [DIO MoM%],
			        "YTD", [DIO YTD],
			        "vs YoY", [DIO YoY%],
			        "vs Plan", [DIO_APN],
			        "vs Flex", [DIO_AFX],
			        BLANK()
			    )
			
			RETURN
			    IF(
			            _sel = "YTD",
			            "#000000",  -- Always black for YTD
			        IF(
			            ISBLANK(kpi_value), "#001489",  -- black for blank
			            IF(
			                kpi_value < 0,
			                "#001489",  -- Green for ▼ down
			                "#D7191C"   -- Red for ▲ up
			            )
			        )
			    )
		displayFolder: KPI Color_Measure
		lineageTag: c924dc8f-d16b-4243-a5a4-07c58f38141f

	measure DPO_Color_KPI = ```
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [DPO MoM%],
			        "LYTD", BLANK(),
			        "vs YoY", [DPO YoY%], 
			        "vs Plan",[DPO_APN],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value > 0,
			                "#D7191C",  -- Red for ▲ up
			                "#001489"   -- Green for ▼ down
			        )
			)
			```
		displayFolder: KPI Color_Measure
		lineageTag: 4faa936f-df86-4205-b4f8-72c30df21673

	measure DSO_Color_KPI = ```
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [DSO MoM%],
			        "LYTD", BLANK(),
			        "vs YoY", [DSO YoY%], 
			        "vs Plan",[DSO_APN],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			                "#001489",  -- Green for ▼ down
			                "#D7191C"   -- Red for ▲ up
			        )
			)
			```
		displayFolder: KPI Color_Measure
		lineageTag: 3c8fc342-ffdd-4485-9ac5-90be41a9847e

	measure Expired_Inventory_Color_KPI = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Expired Inventory MoM%],
			        "LYTD", [Expired Inventory LYTD],
			        "vs YoY", [Expired Inventory YoY%], 
			        BLANK()
			    )
			
			RETURN
			    IF(
			        ISBLANK(kpi_value), "#001489", 
			            IF(
			                kpi_value > 0,
			                "#D7191C",  -- Red for ▲ up
			                "#001489"   -- Green for ▼ down
			            )
			    )
			```
		displayFolder: KPI Color_Measure
		lineageTag: c5c1c3af-1c1c-4b02-80f5-a8031ab38518

	measure FA_CSCA_Color_KPI = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [FA% MoM%],
			        "LYTD", [FA% CSCA LYTD],
			        "vs YoY", [FA% YoY%],  
			        "vs Plan", Switch(SELECTEDVALUE(Fact_Forecast_Accuracy[LAGs]),"2",[FA% Lag 2 Target Diff%], "4", [FA% Lag 4 Target Diff%]),
			        BLANK()
			    )
			
			RETURN
			IF(
			        _sel = "YTD",
			        "#000000",  -- Always black for YTD
			    IF(
			        ISBLANK(kpi_value), "#001489",  -- black for blank
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#001489"   -- green for ▲ up
			        )
			    )
			)
			```
		displayFolder: KPI Color_Measure
		lineageTag: f7814614-4b3d-457c-a6b1-09fcccc76831

	measure FA_CSCI_Color_KPI =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [FA% MoM CSCI],
			        "LYTD", [FA% LYTD CSCI],
			        "vs YoY", [FA% YoY CSCI],
			        "vs Plan", [FA Target Diff%_CSCI],
			        BLANK()
			    )
			
			RETURN
			IF(
			        _sel = "YTD",
			        "#000000",  -- Always black for YTD
			    IF(
			        ISBLANK(kpi_value), "#001489",  -- black for blank
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#001489"   -- green for ▲ up
			        )
			    )
			)
		displayFolder: KPI Color_Measure
		lineageTag: 08b4d419-e8ed-4c8f-8365-592fa1b186ed

	measure 'Gross Inventory _Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Gross Inventory MoM%],
			        "LYTD", [Gross Inv LYTD],
			        "vs YoY", [Gross Inventory YoY%],
			        "vs Plan", [Gross Inventory_APN],
			        "vs Flex", [Gross Inventory_AFX],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value > 0,
			                "#D7191C",  -- Red for ▲ up
			                "#001489"   -- Green for ▼ down
			        )
			)
			```
		displayFolder: KPI Color_Measure
		lineageTag: 93daddeb-ac4c-4805-a0e5-37cff8c957ad

	measure 'Inflated Inventory _Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Inflated Inventory MoM%],
			        "LYTD", [Inflated Inv LYTD],
			        "vs YoY", [Inflated Inventory YoY%], 
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value > 0,
			                "#D7191C",  -- Red for ▲ up
			                "#001489"   -- Green for ▼ down
			        )
			)
			```
		displayFolder: KPI Color_Measure
		lineageTag: ee18417c-4d91-4374-9d7d-b658161639bf

	measure 'Net Inventory _Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Net Inventory MoM%],
			        "LYTD", [Net Inventory LYTD],
			        "vs YoY", [Net Inventory YoY%],
			        "vs Plan", [Net Inventory_APN],
			        "vs Flex", [Net Inventory_AFX],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value > 0,
			                "#D7191C",  -- Red for ▲ up
			                "#001489"   -- Green for ▼ down
			        )
			)
			```
		displayFolder: KPI Color_Measure
		lineageTag: e6e21601-117e-4ef0-a1db-fd0f376470e0

	measure Net_Sales_Color_KPI = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Net Sales Actual MoM%],
			        "LYTD", [Net Sales Actual LYTD],
			        "vs YoY", [Net Sales Actual YoY%], 
			        "vs Plan", [Net Sales_APN],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#001489"   -- green for ▲ up
			        )
			)
			```
		displayFolder: KPI Color_Measure
		lineageTag: 2b4eac49-7816-4d78-a77b-3791ac9194d1

	measure OEE_Color_KPI =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [OEE% MoM%],
			        "YTD", [OEE% YTD],
			        "vs YoY", [OEE% YoY%],
			        "vs Plan", [OEE Target diff%],
			        "LYTD", [OEE LYTD],
			        BLANK()
			    )
			
			RETURN
			IF(
			        _sel = "YTD",
			        "#000000",  -- Always black for YTD
			    IF(
			        ISBLANK(kpi_value), "#001489",  -- black for blank
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#001489"   -- green for ▲ up
			        )
			    )
			)
		displayFolder: KPI Color_Measure
		lineageTag: 8d1da3f5-b9ed-4277-8cd5-4d0f18cbbc9f

	measure 'SA _Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [SA MoM%],
			        "LYTD", [Schedule Attn LYTD],
			        "vs YoY", [SA YoY%],
			        "vs Plan", [Schedule Attn Target Diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value >= 0,
			            "#001489",  -- green for ▲ up
			            "#D7191C"  -- red for ▼ down
			        )
			)
			```
		displayFolder: KPI Color_Measure
		lineageTag: caa01288-2c52-48ff-894e-d1d05f4bb009

	measure 'Service rate_Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Service Rate% MoM%],
			        "LYTD", [Service Rate LYTD],
			        "vs YoY", [Service Rate YoY%],  
			        "vs Plan", [Service Target Diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#001489"   -- green for ▲ up
			        )
			)
			```
		displayFolder: KPI Color_Measure
		lineageTag: 46e78951-5837-4fef-9f51-205ae49cc154

	measure Service_Level_Color_KPI = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Service Level MoM%],
			        "LYTD", [Service Level LYTD],
			        "vs YoY", [Service Level YoY%], 
			        "vs Plan", [Service Target Diff%_CSCI],
			        BLANK()
			    )
			
			RETURN
			IF(
			        _sel = "YTD",
			        "#000000",  -- Always black for YTD
			    IF(
			        ISBLANK(kpi_value), "#001489",  -- black for blank
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- Red for ▼ down
			            "#001489"   -- Green for ▲ up
			        )
			    )
			)
			```
		displayFolder: KPI Color_Measure
		lineageTag: e51617ce-50c7-4a89-b373-f73facdad32a

	measure SSSO_Obs_Linked_Color_KPI = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [SSSO: Obs linked to Conv MoM%],
			        "LYTD", [SSSO: Obs LYTD],
			        "vs YoY", [SSSO: Obs linked to Conv YoY%],
			        "vs Plan", [SSSO: Obsolescenes linked to Conversions_APN],
			        "vs Flex", [SSSO: Obsolescenes linked to Conversions_F66],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#001489",  -- Green for ▼ down
			            "#D7191C"   -- Red for ▲ up
			        )
			)
			```
		displayFolder: KPI Color_Measure
		lineageTag: 75bc24f5-8115-4d15-ab6e-b81b9aafc5ed

	measure SSSO_Salvage&Obs_Color_KPI = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [SSSO: Salvage & obs MoM%],
			        "LYTD", [SSSO: Salvage LYTD],
			        "vs YoY", [SSSO: Salvage YoY%], 
			        "vs Plan", [SSSO: Salvage & Obsolescence_APN],
			        "vs Flex", [SSSO: Salvage & Obsolescence_F66],
			        BLANK()
			    )
			
			RETURN
			    IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#001489",  -- Green for ▼ down
			            "#D7191C"   -- red for ▲ up
			        )
			    )
			```
		displayFolder: KPI Color_Measure
		lineageTag: 410517ff-808b-48ae-ba4d-da03b48e6432

	measure SSSO_Scrap_off_Color_KPI = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [SSSO: Scrap-Off MoM%],
			        "LYTD", [SSSO: Scrap-off LYTD],
			        "vs YoY", [SSSO: Scrap-Off YoY%], 
			        "vs Plan", [SSSO: Scrap-Off_APN],
			        "vs Flex", [SSSO: Scrap-Off_F66],
			        BLANK()
			    )
			
			RETURN
			    IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#001489",  -- Green for ▼ down
			            "#D7191C"   -- Red for ▲ up
			        )
			    )
			```
		displayFolder: KPI Color_Measure
		lineageTag: 878dd288-eec4-4485-b5fd-870f4fdfcd70

	measure SSSO_Shrinkage_Color_KPI = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [SSSO: Shrinkage MoM%],
			        "LYTD", [SSSO: Shrinkage LYTD],
			        "vs YoY", [SSSO: Shrinkage YoY%], 
			        "vs Plan", [SSSO: Shrinkage_APN],
			        "vs Flex", [SSSO: Shrinkage_F66],
			        BLANK()
			    )
			
			RETURN
			    IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#001489",  -- Green for ▼ down
			            "#D7191C"   -- Red for ▲ up
			        )
			    )
			```
		displayFolder: KPI Color_Measure
		lineageTag: 0c69d007-f132-45dd-bc15-643621f42127

	measure 'Total Distribution on COGS_Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Total Distribution on COGS Actual MoM%],
			        "LYTD", [Total Distribution on COGS LYTD],
			        "vs YoY", [Total Distribution on COGS Actual YoY%], 
			        "vs Plan", [Total Logistics on Net Sales_APN],
			        BLANK()
			    )
			
			RETURN
			    IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#001489", -- green for ▲ up
			            "#D7191C"  -- red for ▼ down 
			        )
			    )
			```
		displayFolder: KPI Color_Measure
		lineageTag: 51c879fd-830d-4ec0-920d-4f053f3a1c98

	measure 'Total Logistics on Net Sales_Color' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Total Logistics on Net Sales Actual MoM%],
			        "LYTD", [Total Logistics on Net Sales LYTD],
			        "vs YoY", [Total Logistics on Net Sales Actual YoY%],
			        "vs Plan", [Total Logistics on Net Sales_APN],
			        BLANK()
			    )
			
			RETURN
			    IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#001489", -- green for ▲ up
			            "#D7191C"  -- red for ▼ down 
			        )
			    )
			```
		displayFolder: KPI Color_Measure
		lineageTag: 55eb21b6-62f6-4426-b6f2-921d7afdf911

	measure 'CFR _Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [CFR MoM%],
			        "LYTD", [CFR LYTD],
			        "vs YoY", [CFR YoY%],
			        "vs Plan", [CFR Target Diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value > 0,
			            "#001489",  -- green for ▲ up
			            "#D7191C"  -- red for ▼ down
			        )
			)
			```
		displayFolder: KPI Color_Measure
		lineageTag: b54c830d-13b8-4beb-b276-a7252188ff39

	measure Operating_Income_Actual = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Operating Income Actual MoM_Final],
			      "LYTD",               [Operating Income Actual LYTD_Final],
			      "vs YoY",               [Operating Income Actual YoY_Final],
			      "vs Plan", [Operating Income_APN_Final],
			      "vs Flex", BLANK(),
			      BLANK()
			    )
			
			
			```
		displayFolder: Switch Measures
		lineageTag: 2793fa3d-f884-41c0-9f3c-69edd8de2774

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Operating_Income_Color_KPI = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Operating Income Actual MoM%],
			        "LYTD", [Operating Income Actual LYTD],
			        "vs YoY", [Operating Income Actual YoY%], 
			        "vs Plan", [Operating Income_APN],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#001489"   -- green for ▲ up
			        )
			)
			```
		displayFolder: KPI Color_Measure
		lineageTag: 298cc23d-a900-484d-812d-b4cc7caf9cc2

	measure Net_POV = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Net POV Actual MoM_Final],
			      "LYTD",               [Net POV Actual LYTD_Final],
			      "vs YoY",               [Net POV Actual YoY_Final],
			      "vs Plan", [Net POV_APN_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: Switch Measures
		lineageTag: d76ea9a6-406f-4b8f-8531-8c1d35856890

	measure 'Net POV_Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Net POV Actual MoM%],
			        "LYTD", [Net POV Actual LYTD],
			        "vs YoY", [Net POV Actual YoY%], 
			        "vs Plan", [Net POV_APN],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#001489",  -- green for ▼ down
			            "#D7191C"   -- red for ▲ up
			        )
			)
			```
		displayFolder: KPI Color_Measure
		lineageTag: 8f3d95c8-f2a7-4423-8652-b9e33244f269

	measure Gross_PPV = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Gross PPV Actual MoM_Final],
			      "LYTD",               [Gross PPV Actual LYTD_Final],
			      "vs YoY",               [Gross PPV Actual YoY_Final],
			      "vs Plan", [Gross PPV_APN_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: Switch Measures
		lineageTag: 98e3fa41-abe5-4d5f-9504-0093e42bb23c

	measure 'Gross PPV_Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Gross PPV Actual MoM%],
			        "LYTD", [Gross PPV Actual LYTD],
			        "vs YoY", [Gross PPV Actual YoY%], 
			        "vs Plan", [Gross PPV_APN],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#001489",  -- green for ▼ down
			            "#D7191C"   -- red for ▲ up
			        )
			)
			```
		displayFolder: KPI Color_Measure
		lineageTag: ff3db1d0-0de0-4034-9a40-b86613134aa7

	measure 'Net POV_Color' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Net POV Actual MoM%],
			        "LYTD", [Net POV Actual LYTD],
			        "vs YoY", [Net POV Actual YoY%], 
			        "vs Plan", [Net POV_APN],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#000000", 
			        IF(
			            kpi_value < 0,
			            "#1A9641",  -- green for ▼ down
			            "#D7191C"   -- red for ▲ up
			        )
			)
			```
		displayFolder: Cond.format_measure
		lineageTag: 06476168-c605-4c2b-853c-f9c7f43b6551

	measure 'Gross PPV_Color' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Gross PPV Actual MoM%],
			        "LYTD", [Gross PPV Actual LYTD],
			        "vs YoY", [Gross PPV Actual YoY%], 
			        "vs Plan", [Gross PPV_APN],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#1A9641",  -- Green for ▼ down
			            "#D7191C"   -- red for ▲ up
			        )
			)
			```
		displayFolder: Cond.format_measure
		lineageTag: 467e9056-b60b-48ad-bdb4-6bad800f7a8b

	measure Operating_Income_Color = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Operating Income Actual MoM%],
			        "LYTD", [Operating Income Actual LYTD],
			        "vs YoY", [Operating Income Actual YoY%], 
			        "vs Plan", [Operating Income_APN],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#000000", 
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#1A9641"   -- green for ▲ up
			        )
			)
			```
		displayFolder: Cond.format_measure
		lineageTag: 53ff79f7-8992-4158-bb1d-8f799bd6ca3e

	measure 'Deviations _Color' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [On Time Closure of Deviations MoM%],
			        "LYTD", [On Time Closure of Deviations LYTD],
			        "vs YoY", [On Time Closure of Deviations YoY%],
			        "vs Plan", [On Time Closure of Deviations Target Diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value > 0,
			            "#1A9641",  -- green for ▲ up
			            "#D7191C"  -- red for ▼ down
			        )
		displayFolder: Cond.format_measure
		lineageTag: d417ef57-f4c6-4a2b-8e95-a2e12e2002e0

	measure 'Deviations _Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [On Time Closure of Deviations MoM%],
			        "LYTD", [On Time Closure of Deviations LYTD],
			        "vs YoY", [On Time Closure of Deviations YoY%],
			        "vs Plan", [On Time Closure of Deviations Target Diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value > 0,
			            "#001489",  -- blue by default
			            "#D7191C"  -- red for ▼ down
			        )
			)
			```
		displayFolder: KPI Color_Measure
		lineageTag: 1cac5b71-4aa9-4944-9ecf-1851147a27d8

	measure 'CAPA _Color' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [CAPA Completion Rate MoM%],
			        "LYTD", [CAPA Completion Rate LYTD],
			        "vs YoY", [CAPA Completion Rate YoY%],
			        "vs Plan", [CAPA Completion Rate Target Diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value > 0,
			            "#1A9641",  -- green for ▲ up
			            "#D7191C"  -- red for ▼ down
			        )
		displayFolder: Cond.format_measure
		lineageTag: 19d83f4e-8863-433f-ba49-f0a77c7be310

	measure 'CAPA _Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [CAPA Completion Rate MoM%],
			        "LYTD", [CAPA Completion Rate LYTD],
			        "vs YoY", [CAPA Completion Rate YoY%],
			        "vs Plan", [CAPA Completion Rate Target Diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value > 0,
			            "#001489",  -- blue by default
			            "#D7191C"  -- red for ▼ down
			        )
			)
			```
		displayFolder: KPI Color_Measure
		lineageTag: 712ff5f9-1a54-47fa-93e9-1f7a435b47ea

	measure 'RFT _Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [RFT MoM%],
			        "LYTD", [RFT LYTD],
			        "vs YoY", [RFT YoY%],
			        "vs Plan", [RFT Target Diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value > 0,
			            "#001489",  -- blue by default
			            "#D7191C"  -- red for ▼ down
			        )
			)
			```
		displayFolder: KPI Color_Measure
		lineageTag: a0b8ff3a-6bb4-465b-9af2-1f29f6636561

	measure 'RFT _Color' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [RFT MoM%],
			        "LYTD", [RFT LYTD],
			        "vs YoY", [RFT YTD],
			        "vs Plan", [RFT Target Diff%],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value > 0,
			            "#1A9641",  -- green for ▲ up
			            "#D7191C"  -- red for ▼ down
			        )
		displayFolder: Cond.format_measure
		lineageTag: 42b2e445-ffda-49e5-b252-bdc8d21c0e73

	measure 'CAPA Switch' = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [CAPA Completion Rate MoM_Final],
			      "LYTD", [CAPA Completion Rate LYTD_Final],
			      "vs YoY", [CAPA Completion Rate YoY_Final],
			      "vs Plan", [CAPA Completion Rate Target Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: Switch Measures
		lineageTag: 57b5adf4-217b-479f-847b-5a886f1da021

	measure 'RFT Switch' = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [RFT MoM_Final],
			      "LYTD", [RFT LYTD_Final],
			      "vs YoY", [RFT YoY_Final],
			      "vs Plan", [RFT Target Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: Switch Measures
		lineageTag: 93c1f698-59ac-4d8b-9b41-da39e8f315ec

	measure 'Deviations Switch' = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [On Time Closure of Deviations MoM_Final],
			      "LYTD", [On Time Closure of Deviations LYTD_Final],
			      "vs YoY", [On Time Closure of Deviations YoY_Final],
			      "vs Plan", [On Time Closure of Deviations Target Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: Switch Measures
		lineageTag: ed252ca9-2aa6-4023-971d-d70acef28a88

	measure 'Critical or Major Observations Switch' = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Critical or Major Observations MoM_Final],
			      "LYTD", [Critical or Major Observations LYTD_Final],
			      "vs YoY", [Critical or Major Observations YoY_Final],
			      "vs Plan", "--",
			      BLANK()
			    )
			
			
			```
		displayFolder: Switch Measures
		lineageTag: 0380be26-08ae-45e6-80ed-64eed0bab944

	measure 'Critical or Major Observations _Color' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Critical or Major Observations MoM%],
			        "LYTD", [Critical or Major Observations LYTD],
			        "vs YoY", [Critical or Major Observations YTD],
			        "vs Plan","--",
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#1A9641",  -- green for ▲ up
			            "#D7191C"  -- red for ▼ down
			        )
		displayFolder: Cond.format_measure
		lineageTag: 1d7617d7-9fc4-4d04-97a7-5004c9f8a209

	measure 'Critical or Major Observations _Color_KPI' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Critical or Major Observations MoM%],
			        "LYTD", [Critical or Major Observations LYTD],
			        "vs YoY", [Critical or Major Observations YoY%],
			        "vs Plan", "--",
			        BLANK()
			    )
			
			RETURN
			IF(
			        OR(ISBLANK(kpi_value),kpi_value = "--"), "#001489",
			        IF(
			            kpi_value < 0,
			            "#001489",  -- blue by default
			            "#D7191C"  -- red for ▼ down
			        )
			)
		displayFolder: KPI Color_Measure
		lineageTag: 8cd7b0dd-015f-48f8-9b44-f780b10f0122

	measure 'Selected KPI' = ```
			
			// SELECTEDVALUE('Operating_Parameter'[Parameter Name])
			
			SWITCH(
			    TRUE(),
			    HASONEVALUE('Sales_Parameter'[Parameter Name]), SELECTEDVALUE('Sales_Parameter'[Parameter Name]),
			    HASONEVALUE('Operating_Parameter'[Parameter Name]), SELECTEDVALUE('Operating_Parameter'[Parameter Name]),
			    HASONEVALUE('Working_Capital_Parameter'[Parameter Name]), SELECTEDVALUE('Working_Capital_Parameter'[Parameter Name]),
			    HASONEVALUE('Operations_Parameter'[Parameter Name]), SELECTEDVALUE('Operations_Parameter'[Parameter Name])
			)
			
			```
		displayFolder: Bar Color Measures
		lineageTag: 5c1b1278-8212-431a-9b9d-e78b76a1bb84

	measure 'KPI Target (Unified)' = ```
			
			VAR _kpi = [Selected KPI]
			RETURN
			SWITCH(
			    _kpi,
			    "COGS", [COGS_APN_Base],
			    "Net Sales", [Net Sales_APN_Base],
			    "Operating Income", [Operating Income APN_Base],
			    "Gross PPV", [Gross PPV APN_base],
			    "Net POV", [Net POV APN_base],
			    "Customer Fines", [Customer Fines Target],
			    "Distribution to COGS", [Total Distribution on COGS_APN_Base],
			    "% Logistics vs Net Sales", [Total Logistics on Net Sales_APN_Base],
			    "SSSO: Shrinkage", [SSSO: Shrinkage APN_Base],
			    "SSSO: Scrap-Off", [SSSO: Scrap-off APN_Base],
			    "SSSO: Salvage & Obs", [SSSO: Salvage & Obs_APN_Base],
			    "SSSO: Obs linked to Conv", [SSSO: Obso Conv_APN_Base],
			    "Gross Inventory",[Gross Inventory_APN_Base],
			    "Net Inventory",[Net Inventory_APN_Base],
			    "Inflated Inventory",BLANK(),
			    "Expired Inventory", BLANK(),
			    "DSO", [DSO_APN_Base],
			    "DPO", [DPO_APN_Base],
			    "DIO", [DIO_APN_Base],
			    "FA% Lag 2", [FA% Lag2 Target],
			    "FA% Lag 4", [FA% Target],
			    "Bias% Lag 2", [Bias Target],
			    "Bias% Lag 4", [Bias Target],
			    "Service%", [Service Target],
			    "CFR%", [CFR Target],
			    "OEE%", [OEE Target],
			    "Schedule Attainment%", [Schedule Attn Target],
			    "On Time Closure of Deviations%", [Deviations Plan],
			    "CAPA Completion Rate%", [CAPA Plan],
			    "RFT%", [RFT Plan],
			    "ABP Variance", [ABP Variance_APN_Base],
			    "Service Top 11",[Service Top 11 Target],
			    "Critical or Major Observations", BLANK()
			    
			)
			
			```
		displayFolder: Bar Color Measures
		lineageTag: 91b22b24-be4c-447f-a5a2-bff196627517

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BarColor = ```
			
			VAR _kpiName = [Selected KPI] 
			VAR _value = [KPI Value (Unified)]
			VAR _target = [KPI Target (Unified)]
			
			VAR _isBiasKPI = 
			    _kpiName IN { "Bias% Lag 2", "Bias% Lag 4" }
			
			RETURN
			IF(
			    NOT ISBLANK(_value),
			    SWITCH(
			        TRUE(),
			        _isBiasKPI && _value >= -0.03 && _value <= 0.03, "#001489",  // Blue for Bias within ±3%
			        _isBiasKPI, "#D7191C",                                       // Red for Bias outside range
			        NOT ISBLANK(_target) && _value < _target, "#D7191C",         // Red for other KPIs if value < target
			        "#001489"                                                    // Blue otherwise
			    ),
			    "#001489"
			)
			
			```
		displayFolder: Bar Color Measures
		lineageTag: c775bb1c-f729-40c9-84e8-835d01bb0d57

	measure 'KPI Value (Unified)' = ```
			
			VAR _kpi = [Selected KPI]
			RETURN
			SWITCH(
			    _kpi,
			    "COGS", [COGS Actual],
			    "Net Sales", [Net Sales Actual],
			    "Operating Income", [Operating Income Actual],
			    "Gross PPV", [Gross PPV Actual],
			    "Net POV", [Net POV Actual],
			    "Customer Fines", [Customer Fines],
			    "Distribution to COGS", [Total Distribution on COGS Actual],
			    "% Logistics vs Net Sales", [Total Logistics on Net Sales Actual],
			    "SSSO: Shrinkage", [SSSO Shrinkage],
			    "SSSO: Scrap-Off", [SSSO: Scrap-Off],
			    "SSSO: Salvage & Obs", [SSSO: Salvage & Obsolescence],
			    "SSSO: Obs linked to Conv", [SSSO: Obsolescenes linked to Conversions],
			    "Gross Inventory", [Gross Inventory],
			    "Net Inventory", [Net Inventory],
			    "Inflated Inventory", [Inflated Inventory],
			    "Expired Inventory", [Expired Inventory],
			    "DSO", [DSO],
			    "DPO", [DPO],
			    "DIO", [DIO],
			    "OEE%", [OEE%],
			    "Schedule Attainment%", [Schedule Attn],
			    "On Time Closure of Deviations%", [On Time Closure of Deviations%],
			    "CAPA Completion Rate%", [CAPA Completion Rate],
			    "RFT%", [RFT%],
			    "Critical or Major Observations", [Critical or Major Observations],
			    "FA% Lag 2", [FA% Lag2],
			    "FA% Lag 4", [FA% Lag4],
			    "Bias% Lag 2", [Bias% Lag 2],
			    "Bias% Lag 4", [Bias% Lag 4],
			    "Service%", [Service Rate%],
			    "CFR%", [CFR],
			    "ABP Variance",[ABP Variance],
			    "Service Top 11",[Service Top 11],
			    BLANK()
			)
			
			```
		displayFolder: Bar Color Measures
		lineageTag: c94d5e0e-48ec-4f2f-b492-00b03cf88fce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KPI Target (Formatted)' = ```
			
			VAR _rawValue = [KPI Target (Unified)]
			VAR _kpi = [Selected KPI]
			RETURN
			SWITCH(
			    TRUE(),
			    _kpi IN {
			        "OEE%", "Schedule Attainment%", "Service%", "CFR%", 
			        "FA% Lag 2", "FA% Lag 4", "Bias% Lag 2", "Bias% Lag 4", 
			        "On Time Closure of Deviations%", "CAPA Completion Rate%", "RFT%", "Distribution to COGS","% Logistics vs Net Sales"
			    }, FORMAT(_rawValue, "0.0%"),
			    FORMAT(_rawValue, "#,##0")
			)
			    
			```
		displayFolder: Bar Color Measures
		lineageTag: 64957d2f-284d-4bba-890e-ff54ec027cb8

	measure 'ABP Variance Switch' = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [ABP Variance MoM_Final],
			      "LYTD", [ABP Variance LYTD_Final],
			      "vs YoY", [ABP Variance YoY_Final],
			      "vs Plan", [ABP Variance_APN_Final],
			      BLANK()
			    )
			
			
			```
		displayFolder: Switch Measures
		lineageTag: 1b4f5894-c1e9-45a4-a0ad-2f4c000d0841

	measure 'ABP Variance _Color' =
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [ABP Variance MoM%],
			        "LYTD", [ABP Variance LYTD],
			        "vs YoY", [ABP Variance YoY%],
			        "vs Plan", [ABP Variance_APN],
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value > 0,
			            "#D7191C",  -- red for ▲ up
			            "#1A9641"  -- green for ▼ down
			        )
		displayFolder: Cond.format_measure
		lineageTag: dda3e5b0-c04c-4d94-b3f7-10636779617b

	measure 'ABP Variance _Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [ABP Variance MoM%],
			        "LYTD", [ABP Variance LYTD],
			        "vs YoY", [ABP Variance YoY%],
			        "vs Plan", [ABP Variance_APN],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value > 0,
			            "#D7191C",  -- red
			            "#001489"  -- Blue for ▼ down
			        )
			)
			```
		displayFolder: KPI Color_Measure
		lineageTag: 5a552db2-9736-4306-b944-f7bc3ae29986

	measure 'Service Top 11_Color' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Service Top 11 MoM%],
			        "LYTD", [Service Top 11 LYTD],
			        "vs YoY", [Service Top 11 YoY%],  
			        BLANK()
			    )
			
			RETURN
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#1A9641"   -- green for ▲ up
			        )
			```
		displayFolder: Cond.format_measure
		lineageTag: e8e7e1cc-8b00-4e63-9474-d4cf30fd95a4

	measure 'Service Top 11_Color_KPI' = ```
			
			VAR _sel = SELECTEDVALUE(MetricSelector[Metric], "vs PP")
			
			VAR kpi_value =
			    SWITCH(
			        _sel,
			        "vs PP", [Service Top 11 MoM%],
			        "LYTD", [Service Top 11 LYTD],
			        "vs YoY", [Service Top 11 YoY%],  
			        "vs Plan", [Service Top 11 Target Diff%],
			        BLANK()
			    )
			
			RETURN
			IF(
			        ISBLANK(kpi_value), "#001489", 
			        IF(
			            kpi_value < 0,
			            "#D7191C",  -- red for ▼ down
			            "#001489"   -- green for ▲ up
			        )
			)
			```
		displayFolder: KPI Color_Measure
		lineageTag: 60ff18b0-064d-44b0-8fb3-ac11463b8035

	measure 'Service Top 11_Switch' = ```
			
			  VAR _sel = SELECTEDVALUE( MetricSelector[Metric], "vs PP" )
			  RETURN
			    SWITCH(
			      _sel,
			      "vs PP", [Service Top 11 MoM_Final],
			      "LYTD",               [Service Top 11 LYTD_Final],
			      "vs YoY",               [Service Top 11 YoY_Final],
			      "vs Plan", [Service Top 11 Target Final],
			      BLANK()
			    )
			```
		displayFolder: Switch Measures
		lineageTag: 6d7a320f-1686-4dbc-a8f8-b55b9fc6ac42

	measure BarColor_WC = ```
			
			VAR _kpiName = [Selected KPI] 
			VAR _value = [KPI Value (Unified)]
			VAR _target = [KPI Target (Unified)]
			
			RETURN
			IF(
			    NOT ISBLANK(_value) && NOT ISBLANK(_target),
			    IF(_value > _target, 
			        "#D7191C",   // Red
			        "#001489"    // Blue
			    ),
			    "#001489"        // Default Blue if value or target is blank
			)
			
			```
		displayFolder: Bar Color Measures
		lineageTag: db2ae7be-0e09-4708-ad30-9cb54cda74d8

	measure BarColor_OI = ```
			
			VAR _kpiName = [Selected KPI] 
			VAR _value = [KPI Value (Unified)]
			VAR _target = [KPI Target (Unified)]
			
			VAR _isSpecialKPI  = 
			    _kpiName IN { "Net Sales", "Operating Income" }
			
			RETURN
			IF(
			    NOT ISBLANK(_value),
			    SWITCH(
			        TRUE(),
			        _isSpecialKPI && _value < _target, "#D7191C",   // Red if value < target for special KPIs
			        NOT _isSpecialKPI && _value > _target, "#D7191C", // Red if value > target for other KPIs
			        "#001489"  // Blue otherwise
			    ),
			    "#001489"
			)
			
			```
		displayFolder: Bar Color Measures
		lineageTag: da89552e-3310-4eb4-ab08-35e88dfd10e8

	column Metric
		lineageTag: b6fb7fae-3803-4e29-b36f-21afd71421fd
		summarizeBy: none
		sourceColumn: [period]
		sortByColumn: SortOrder

		annotation SummarizationSetBy = Automatic

	column SortOrder
		formatString: 0
		lineageTag: 8254b6bf-0377-44ec-b442-6ca89c51ee98
		summarizeBy: sum
		isNameInferred
		sourceColumn: [SortOrder]

		annotation SummarizationSetBy = Automatic

	partition MetricSelector = calculated
		mode: import
		source =
				
				DATATABLE(
				    "Period", STRING,
				    "SortOrder", INTEGER,
				    {
				        {"vs YoY", 4},
				        {"vs PP", 3},
				        {"LYTD", 5},
				        {"vs Plan", 1},
				        {"vs Flex", 2}
				    }
				)

	annotation PBI_Id = a03c420cea1b45fa97c91188c7207338

