table Par_Targets
	lineageTag: be87a6a0-b9c3-4f36-bbfa-238b82435ea7

	column Cycle
		dataType: string
		lineageTag: aabda0ae-3f18-4637-9d1a-b1c486e12805
		summarizeBy: none
		sourceColumn: Cycle

		annotation SummarizationSetBy = Automatic

	column Rank
		dataType: int64
		formatString: 0
		lineageTag: e46f9911-0493-42d9-a4cd-6db5047b2288
		summarizeBy: sum
		sourceColumn: Rank

		annotation SummarizationSetBy = Automatic

	partition Par_Targets = m
		mode: import
		queryGroup: Parameters/Misc
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCshJzFPSUTJUitWJVnLLSa1QMNM2AwoYKcXGAgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Cycle = _t, Rank = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Cycle", type text}, {"Rank", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

